package o;

/* JADX INFO: loaded from: classes.dex */
public abstract class AutofillSemanticCallback {
    public static final long ComponentActivity;
    public static final long IconCompatParcelizer;
    public static final long MediaBrowserCompatMediaItem;
    public static final long MediaDescriptionCompat;
    public static final long MediaMetadataCompat;
    public static final long MediaSessionCompatQueueItem;
    public static final long MediaSessionCompatResultReceiverWrapper;
    public static final long MediaSessionCompatToken;
    public static final long ParcelableVolumeInfo;
    public static final long PlaybackStateCompat;
    public static final long PlaybackStateCompatCustomAction;
    public static final long RatingCompat;
    public static final long RemoteActionCompatParcelizer;
    public static final long ResultReceiver;
    public static final long _init_lambda1;
    public static final long _init_lambda2;
    public static final long _init_lambda3;
    public static final long _init_lambda4;
    public static final long accessensureViewModelStore;
    public static final long addObserverForBackInvoker;
    public static final long addObserverForBackInvokerlambda0;
    public static final long createFullyDrawnExecutor;
    public static final long defaultViewModelProviderFactory_delegatelambda0;
    public static final long ensureViewModelStore;
    public static final long fullyDrawnReporter_delegatelambda0;
    public static final long fullyDrawnReporter_delegatelambda00;
    public static final long getOnBackPressedInput;
    public static final long getSavedStateRegistryControllerannotations;
    public static final long menuHostHelperlambda0;
    public static final long onBackPressedDispatcher_delegatelambda0;
    public static final long onBackPressedInput_delegatelambda0;
    public static final long r8lambda54BeH8ZsBru0CXI2CCSP2syNys;
    public static final long r8lambda7IJBVrN0sHyidCAZufWEJFc7yY;
    public static final long r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus;
    public static final long r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss;
    public static final long r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg;
    public static final long r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8;
    public static final long r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4;
    public static final long r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM;
    public static final long r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs;
    public static final long r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28;
    public static final long r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw;
    public static final long r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ;
    public static final long r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0;
    public static final long read;
    public static final long serializer;
    public static final long write;

    static {
        long j = trimToSafeLength.PlaybackStateCompatCustomAction;
        read = j;
        IconCompatParcelizer = trimToSafeLength.serializer;
        write = trimToSafeLength.write;
        serializer = trimToSafeLength.PlaybackStateCompat;
        long j2 = trimToSafeLength.r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg;
        RemoteActionCompatParcelizer = j2;
        RatingCompat = trimToSafeLength.MediaSessionCompatQueueItem;
        long j3 = trimToSafeLength.MediaMetadataCompat;
        MediaSessionCompatQueueItem = j3;
        MediaMetadataCompat = trimToSafeLength.IconCompatParcelizer;
        MediaBrowserCompatMediaItem = trimToSafeLength.RemoteActionCompatParcelizer;
        MediaDescriptionCompat = trimToSafeLength.r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM;
        long j4 = trimToSafeLength.r8lambda7IJBVrN0sHyidCAZufWEJFc7yY;
        MediaSessionCompatToken = j4;
        PlaybackStateCompat = j4;
        ParcelableVolumeInfo = trimToSafeLength.r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4;
        PlaybackStateCompatCustomAction = trimToSafeLength.r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0;
        long j5 = trimToSafeLength.r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ;
        MediaSessionCompatResultReceiverWrapper = j5;
        r8lambda54BeH8ZsBru0CXI2CCSP2syNys = j5;
        r8lambda7IJBVrN0sHyidCAZufWEJFc7yY = trimToSafeLength.r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28;
        ResultReceiver = j3;
        r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus = trimToSafeLength.r8lambda54BeH8ZsBru0CXI2CCSP2syNys;
        ComponentActivity = trimToSafeLength._init_lambda3;
        long j6 = trimToSafeLength._init_lambda2;
        r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8 = j6;
        r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss = j6;
        r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM = trimToSafeLength._init_lambda4;
        r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg = trimToSafeLength.ResultReceiver;
        r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4 = trimToSafeLength.ComponentActivity;
        r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ = trimToSafeLength.r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8;
        long j7 = trimToSafeLength.r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss;
        r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw = j7;
        r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs = j7;
        r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0 = j2;
        r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28 = trimToSafeLength.read;
        _init_lambda1 = trimToSafeLength.r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs;
        long j8 = trimToSafeLength._init_lambda1;
        _init_lambda2 = j8;
        _init_lambda4 = j8;
        _init_lambda3 = trimToSafeLength.r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw;
        accessensureViewModelStore = j;
        createFullyDrawnExecutor = j;
        addObserverForBackInvokerlambda0 = trimToSafeLength.MediaSessionCompatResultReceiverWrapper;
        defaultViewModelProviderFactory_delegatelambda0 = trimToSafeLength.ParcelableVolumeInfo;
        ensureViewModelStore = trimToSafeLength.MediaDescriptionCompat;
        addObserverForBackInvoker = trimToSafeLength.MediaSessionCompatToken;
        getSavedStateRegistryControllerannotations = trimToSafeLength.RatingCompat;
        fullyDrawnReporter_delegatelambda0 = trimToSafeLength.MediaBrowserCompatMediaItem;
        fullyDrawnReporter_delegatelambda00 = trimToSafeLength.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus;
        menuHostHelperlambda0 = trimToSafeLength.accessensureViewModelStore;
        long j9 = trimToSafeLength.addObserverForBackInvoker;
        getOnBackPressedInput = j9;
        onBackPressedDispatcher_delegatelambda0 = j9;
        onBackPressedInput_delegatelambda0 = trimToSafeLength.addObserverForBackInvokerlambda0;
    }
}
