package o;

import java.util.LinkedHashMap;

/* JADX INFO: loaded from: classes4.dex */
public final class getAppropriateImageUrllambda0 {
    public static final getLongEdge Companion;
    public static final LinkedHashMap INSTANCES;
    public static final setMessageIcon ORDER_BY_NAME;
    public static final getAppropriateImageUrllambda0 TLS_AES_128_GCM_SHA256;
    public static final getAppropriateImageUrllambda0 TLS_AES_256_GCM_SHA384;
    public static final getAppropriateImageUrllambda0 TLS_CHACHA20_POLY1305_SHA256;
    public static final getAppropriateImageUrllambda0 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256;
    public static final getAppropriateImageUrllambda0 TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384;
    public static final getAppropriateImageUrllambda0 TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256;
    public static final getAppropriateImageUrllambda0 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA;
    public static final getAppropriateImageUrllambda0 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256;
    public static final getAppropriateImageUrllambda0 TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA;
    public static final getAppropriateImageUrllambda0 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384;
    public static final getAppropriateImageUrllambda0 TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256;
    public static final getAppropriateImageUrllambda0 TLS_RSA_WITH_3DES_EDE_CBC_SHA;
    public static final getAppropriateImageUrllambda0 TLS_RSA_WITH_AES_128_CBC_SHA;
    public static final getAppropriateImageUrllambda0 TLS_RSA_WITH_AES_128_GCM_SHA256;
    public static final getAppropriateImageUrllambda0 TLS_RSA_WITH_AES_256_CBC_SHA;
    public static final getAppropriateImageUrllambda0 TLS_RSA_WITH_AES_256_GCM_SHA384;
    public final String javaName;

    public final String toString() {
        return this.javaName;
    }

    static {
        getLongEdge getlongedge = new getLongEdge();
        Companion = getlongedge;
        ORDER_BY_NAME = new setMessageIcon();
        INSTANCES = new LinkedHashMap();
        getLongEdge.IconCompatParcelizer(getlongedge, "SSL_RSA_WITH_NULL_MD5");
        getLongEdge.IconCompatParcelizer(getlongedge, "SSL_RSA_WITH_NULL_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "SSL_RSA_EXPORT_WITH_RC4_40_MD5");
        getLongEdge.IconCompatParcelizer(getlongedge, "SSL_RSA_WITH_RC4_128_MD5");
        getLongEdge.IconCompatParcelizer(getlongedge, "SSL_RSA_WITH_RC4_128_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "SSL_RSA_EXPORT_WITH_DES40_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "SSL_RSA_WITH_DES_CBC_SHA");
        TLS_RSA_WITH_3DES_EDE_CBC_SHA = getLongEdge.IconCompatParcelizer(getlongedge, "SSL_RSA_WITH_3DES_EDE_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "SSL_DHE_DSS_WITH_DES_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "SSL_DHE_RSA_WITH_DES_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "SSL_DH_anon_EXPORT_WITH_RC4_40_MD5");
        getLongEdge.IconCompatParcelizer(getlongedge, "SSL_DH_anon_WITH_RC4_128_MD5");
        getLongEdge.IconCompatParcelizer(getlongedge, "SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "SSL_DH_anon_WITH_DES_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "SSL_DH_anon_WITH_3DES_EDE_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_KRB5_WITH_DES_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_KRB5_WITH_3DES_EDE_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_KRB5_WITH_RC4_128_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_KRB5_WITH_DES_CBC_MD5");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_KRB5_WITH_3DES_EDE_CBC_MD5");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_KRB5_WITH_RC4_128_MD5");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_KRB5_EXPORT_WITH_DES_CBC_40_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_KRB5_EXPORT_WITH_RC4_40_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_KRB5_EXPORT_WITH_DES_CBC_40_MD5");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_KRB5_EXPORT_WITH_RC4_40_MD5");
        TLS_RSA_WITH_AES_128_CBC_SHA = getLongEdge.IconCompatParcelizer(getlongedge, "TLS_RSA_WITH_AES_128_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DHE_DSS_WITH_AES_128_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DHE_RSA_WITH_AES_128_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DH_anon_WITH_AES_128_CBC_SHA");
        TLS_RSA_WITH_AES_256_CBC_SHA = getLongEdge.IconCompatParcelizer(getlongedge, "TLS_RSA_WITH_AES_256_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DHE_DSS_WITH_AES_256_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DHE_RSA_WITH_AES_256_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DH_anon_WITH_AES_256_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_RSA_WITH_NULL_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_RSA_WITH_AES_128_CBC_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_RSA_WITH_AES_256_CBC_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_RSA_WITH_CAMELLIA_128_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DH_anon_WITH_AES_128_CBC_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DH_anon_WITH_AES_256_CBC_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_RSA_WITH_CAMELLIA_256_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_PSK_WITH_RC4_128_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_PSK_WITH_3DES_EDE_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_PSK_WITH_AES_128_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_PSK_WITH_AES_256_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_RSA_WITH_SEED_CBC_SHA");
        TLS_RSA_WITH_AES_128_GCM_SHA256 = getLongEdge.IconCompatParcelizer(getlongedge, "TLS_RSA_WITH_AES_128_GCM_SHA256");
        TLS_RSA_WITH_AES_256_GCM_SHA384 = getLongEdge.IconCompatParcelizer(getlongedge, "TLS_RSA_WITH_AES_256_GCM_SHA384");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DHE_DSS_WITH_AES_128_GCM_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DHE_DSS_WITH_AES_256_GCM_SHA384");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DH_anon_WITH_AES_128_GCM_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DH_anon_WITH_AES_256_GCM_SHA384");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_EMPTY_RENEGOTIATION_INFO_SCSV");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_FALLBACK_SCSV");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_ECDSA_WITH_NULL_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_ECDSA_WITH_RC4_128_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_ECDSA_WITH_NULL_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_ECDSA_WITH_RC4_128_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_RSA_WITH_NULL_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_RSA_WITH_RC4_128_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_RSA_WITH_NULL_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_RSA_WITH_RC4_128_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA");
        TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA = getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA");
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA = getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_anon_WITH_NULL_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_anon_WITH_RC4_128_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_anon_WITH_AES_128_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_anon_WITH_AES_256_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384");
        TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 = getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256");
        TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 = getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384");
        TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 = getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256");
        TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 = getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA");
        TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 = getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256");
        TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 = getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256");
        TLS_AES_128_GCM_SHA256 = getLongEdge.IconCompatParcelizer(getlongedge, "TLS_AES_128_GCM_SHA256");
        TLS_AES_256_GCM_SHA384 = getLongEdge.IconCompatParcelizer(getlongedge, "TLS_AES_256_GCM_SHA384");
        TLS_CHACHA20_POLY1305_SHA256 = getLongEdge.IconCompatParcelizer(getlongedge, "TLS_CHACHA20_POLY1305_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_AES_128_CCM_SHA256");
        getLongEdge.IconCompatParcelizer(getlongedge, "TLS_AES_128_CCM_8_SHA256");
    }

    public getAppropriateImageUrllambda0(String str) {
        this.javaName = str;
    }
}
