package o;

import com.google.android.gms.dynamite.descriptors.com.google.android.gms.tagmanager.ModuleDescriptor;
import com.huawei.riemann.location.common.utils.Constant;
import java.util.ArrayList;
import java.util.HashMap;

/* JADX INFO: loaded from: classes2.dex */
public abstract class getLocalLifecycleOwnerannotations {
    public static HashMap write() {
        HashMap map = new HashMap(286);
        ArrayList arrayList = new ArrayList(25);
        arrayList.add("US");
        arrayList.add("AG");
        arrayList.add("AI");
        arrayList.add("AS");
        arrayList.add("BB");
        arrayList.add("BM");
        arrayList.add("BS");
        arrayList.add("CA");
        arrayList.add("DM");
        arrayList.add("DO");
        arrayList.add("GD");
        arrayList.add("GU");
        arrayList.add("JM");
        arrayList.add("KN");
        arrayList.add("KY");
        arrayList.add("LC");
        arrayList.add("MP");
        arrayList.add("MS");
        arrayList.add("PR");
        arrayList.add("SX");
        arrayList.add("TC");
        arrayList.add("TT");
        arrayList.add("VC");
        arrayList.add("VG");
        arrayList.add("VI");
        map.put(1, arrayList);
        ArrayList arrayList2 = new ArrayList(2);
        arrayList2.add("RU");
        arrayList2.add("KZ");
        ArrayList arrayList3 = MediaSessionCompatQueueItem.read(36, map, MediaSessionCompatQueueItem.read(34, map, MediaSessionCompatQueueItem.read(33, map, MediaSessionCompatQueueItem.read(32, map, MediaSessionCompatQueueItem.read(31, map, MediaSessionCompatQueueItem.read(30, map, MediaSessionCompatQueueItem.read(27, map, MediaSessionCompatQueueItem.read(20, map, MediaSessionCompatQueueItem.read(7, map, arrayList2, 1, "EG"), 1, "ZA"), 1, "GR"), 1, "NL"), 1, "BE"), 1, "FR"), 1, "ES"), 1, "HU"), 2, "IT");
        arrayList3.add("VA");
        map.put(39, arrayList3);
        ArrayList arrayList4 = new ArrayList(1);
        arrayList4.add("RO");
        ArrayList arrayList5 = MediaSessionCompatQueueItem.read(43, map, MediaSessionCompatQueueItem.read(41, map, MediaSessionCompatQueueItem.read(40, map, arrayList4, 1, "CH"), 1, "AT"), 4, "GB");
        arrayList5.add("GG");
        arrayList5.add("IM");
        arrayList5.add("JE");
        map.put(44, arrayList5);
        ArrayList arrayList6 = new ArrayList(1);
        arrayList6.add("DK");
        ArrayList arrayList7 = MediaSessionCompatQueueItem.read(46, map, MediaSessionCompatQueueItem.read(45, map, arrayList6, 1, "SE"), 2, "NO");
        arrayList7.add("SJ");
        map.put(47, arrayList7);
        ArrayList arrayList8 = new ArrayList(1);
        arrayList8.add("PL");
        ArrayList arrayList9 = MediaSessionCompatQueueItem.read(60, map, MediaSessionCompatQueueItem.read(58, map, MediaSessionCompatQueueItem.read(57, map, MediaSessionCompatQueueItem.read(56, map, MediaSessionCompatQueueItem.read(55, map, MediaSessionCompatQueueItem.read(54, map, MediaSessionCompatQueueItem.read(53, map, MediaSessionCompatQueueItem.read(52, map, MediaSessionCompatQueueItem.read(51, map, MediaSessionCompatQueueItem.read(49, map, MediaSessionCompatQueueItem.read(48, map, arrayList8, 1, "DE"), 1, "PE"), 1, "MX"), 1, "CU"), 1, "AR"), 1, "BR"), 1, "CL"), 1, "CO"), 1, "VE"), 1, "MY"), 3, "AU");
        arrayList9.add("CC");
        arrayList9.add("CX");
        map.put(61, arrayList9);
        ArrayList arrayList10 = new ArrayList(1);
        arrayList10.add("ID");
        ArrayList arrayList11 = MediaSessionCompatQueueItem.read(Constant.ERROR_GYRO_NO_DATA, map, MediaSessionCompatQueueItem.read(98, map, MediaSessionCompatQueueItem.read(95, map, MediaSessionCompatQueueItem.read(94, map, MediaSessionCompatQueueItem.read(93, map, MediaSessionCompatQueueItem.read(92, map, MediaSessionCompatQueueItem.read(91, map, MediaSessionCompatQueueItem.read(90, map, MediaSessionCompatQueueItem.read(86, map, MediaSessionCompatQueueItem.read(84, map, MediaSessionCompatQueueItem.read(82, map, MediaSessionCompatQueueItem.read(81, map, MediaSessionCompatQueueItem.read(66, map, MediaSessionCompatQueueItem.read(65, map, MediaSessionCompatQueueItem.read(64, map, MediaSessionCompatQueueItem.read(63, map, MediaSessionCompatQueueItem.read(62, map, arrayList10, 1, "PH"), 1, "NZ"), 1, "SG"), 1, "TH"), 1, "JP"), 1, "KR"), 1, "VN"), 1, "CN"), 1, "TR"), 1, "IN"), 1, "PK"), 1, "AF"), 1, "LK"), 1, "MM"), 1, "IR"), 1, "SS"), 2, "MA");
        arrayList11.add("EH");
        map.put(Integer.valueOf(Constant.ERROR_GYRO_LOW_FREQ), arrayList11);
        ArrayList arrayList12 = new ArrayList(1);
        arrayList12.add("DZ");
        ArrayList arrayList13 = MediaSessionCompatQueueItem.read(261, map, MediaSessionCompatQueueItem.read(260, map, MediaSessionCompatQueueItem.read(258, map, MediaSessionCompatQueueItem.read(257, map, MediaSessionCompatQueueItem.read(androidx.compose.ui.graphics.Fields.RotationX, map, MediaSessionCompatQueueItem.read(255, map, MediaSessionCompatQueueItem.read(Constant.ERROR_ROAD_AREA_INVALID, map, MediaSessionCompatQueueItem.read(253, map, MediaSessionCompatQueueItem.read(252, map, MediaSessionCompatQueueItem.read(251, map, MediaSessionCompatQueueItem.read(250, map, MediaSessionCompatQueueItem.read(249, map, MediaSessionCompatQueueItem.read(248, map, MediaSessionCompatQueueItem.read(247, map, MediaSessionCompatQueueItem.read(246, map, MediaSessionCompatQueueItem.read(245, map, MediaSessionCompatQueueItem.read(Constant.ERROR_GNSS_STATUS_INVALID, map, MediaSessionCompatQueueItem.read(243, map, MediaSessionCompatQueueItem.read(242, map, MediaSessionCompatQueueItem.read(241, map, MediaSessionCompatQueueItem.read(240, map, MediaSessionCompatQueueItem.read(239, map, MediaSessionCompatQueueItem.read(238, map, MediaSessionCompatQueueItem.read(237, map, MediaSessionCompatQueueItem.read(236, map, MediaSessionCompatQueueItem.read(235, map, MediaSessionCompatQueueItem.read(Constant.ERROR_LOCATION_INVALID, map, MediaSessionCompatQueueItem.read(233, map, MediaSessionCompatQueueItem.read(232, map, MediaSessionCompatQueueItem.read(231, map, MediaSessionCompatQueueItem.read(230, map, MediaSessionCompatQueueItem.read(229, map, MediaSessionCompatQueueItem.read(228, map, MediaSessionCompatQueueItem.read(227, map, MediaSessionCompatQueueItem.read(Constant.ERROR_WSS_SPEED_JUMP, map, MediaSessionCompatQueueItem.read(225, map, MediaSessionCompatQueueItem.read(Constant.ERROR_WSS_INVALID, map, MediaSessionCompatQueueItem.read(Constant.ERROR_WSS_TIME_DIFF_LARGE, map, MediaSessionCompatQueueItem.read(Constant.ERROR_WSS_LOW_FREQ, map, MediaSessionCompatQueueItem.read(Constant.ERROR_WSS_NO_DATA, map, MediaSessionCompatQueueItem.read(220, map, MediaSessionCompatQueueItem.read(ModuleDescriptor.MODULE_VERSION, map, MediaSessionCompatQueueItem.read(Constant.ERROR_GYRO_JUMP, map, MediaSessionCompatQueueItem.read(Constant.ERROR_GYRO_TIME_DIFF_LARGE, map, arrayList12, 1, "TN"), 1, "LY"), 1, "GM"), 1, "SN"), 1, "MR"), 1, "ML"), 1, "GN"), 1, "CI"), 1, "BF"), 1, "NE"), 1, "TG"), 1, "BJ"), 1, "MU"), 1, "LR"), 1, "SL"), 1, "GH"), 1, "NG"), 1, "TD"), 1, "CF"), 1, "CM"), 1, "CV"), 1, "ST"), 1, "GQ"), 1, "GA"), 1, "CG"), 1, "CD"), 1, "AO"), 1, "GW"), 1, "IO"), 1, "AC"), 1, "SC"), 1, "SD"), 1, "RW"), 1, "ET"), 1, "SO"), 1, "DJ"), 1, "KE"), 1, "TZ"), 1, "UG"), 1, "BI"), 1, "MZ"), 1, "ZM"), 1, "MG"), 2, "RE");
        arrayList13.add("YT");
        map.put(262, arrayList13);
        ArrayList arrayList14 = new ArrayList(1);
        arrayList14.add("ZW");
        ArrayList arrayList15 = MediaSessionCompatQueueItem.read(269, map, MediaSessionCompatQueueItem.read(268, map, MediaSessionCompatQueueItem.read(267, map, MediaSessionCompatQueueItem.read(266, map, MediaSessionCompatQueueItem.read(265, map, MediaSessionCompatQueueItem.read(Constant.ERROR_ROTATION_ANGLE_INVALID, map, MediaSessionCompatQueueItem.read(263, map, arrayList14, 1, "NA"), 1, "MW"), 1, "LS"), 1, "BW"), 1, "SZ"), 1, "KM"), 2, "SH");
        arrayList15.add("TA");
        map.put(290, arrayList15);
        ArrayList arrayList16 = new ArrayList(1);
        arrayList16.add("ER");
        ArrayList arrayList17 = MediaSessionCompatQueueItem.read(357, map, MediaSessionCompatQueueItem.read(356, map, MediaSessionCompatQueueItem.read(355, map, MediaSessionCompatQueueItem.read(354, map, MediaSessionCompatQueueItem.read(353, map, MediaSessionCompatQueueItem.read(352, map, MediaSessionCompatQueueItem.read(351, map, MediaSessionCompatQueueItem.read(350, map, MediaSessionCompatQueueItem.read(299, map, MediaSessionCompatQueueItem.read(298, map, MediaSessionCompatQueueItem.read(297, map, MediaSessionCompatQueueItem.read(291, map, arrayList16, 1, "AW"), 1, "FO"), 1, "GL"), 1, "GI"), 1, "PT"), 1, "LU"), 1, "IE"), 1, "IS"), 1, "AL"), 1, "MT"), 1, "CY"), 2, "FI");
        arrayList17.add("AX");
        map.put(358, arrayList17);
        ArrayList arrayList18 = new ArrayList(1);
        arrayList18.add("BG");
        ArrayList arrayList19 = MediaSessionCompatQueueItem.read(509, map, MediaSessionCompatQueueItem.read(508, map, MediaSessionCompatQueueItem.read(507, map, MediaSessionCompatQueueItem.read(506, map, MediaSessionCompatQueueItem.read(505, map, MediaSessionCompatQueueItem.read(504, map, MediaSessionCompatQueueItem.read(503, map, MediaSessionCompatQueueItem.read(502, map, MediaSessionCompatQueueItem.read(501, map, MediaSessionCompatQueueItem.read(Constant.ERROR_UNKNOWN, map, MediaSessionCompatQueueItem.read(423, map, MediaSessionCompatQueueItem.read(421, map, MediaSessionCompatQueueItem.read(420, map, MediaSessionCompatQueueItem.read(389, map, MediaSessionCompatQueueItem.read(387, map, MediaSessionCompatQueueItem.read(386, map, MediaSessionCompatQueueItem.read(385, map, MediaSessionCompatQueueItem.read(383, map, MediaSessionCompatQueueItem.read(382, map, MediaSessionCompatQueueItem.read(381, map, MediaSessionCompatQueueItem.read(380, map, MediaSessionCompatQueueItem.read(378, map, MediaSessionCompatQueueItem.read(377, map, MediaSessionCompatQueueItem.read(376, map, MediaSessionCompatQueueItem.read(375, map, MediaSessionCompatQueueItem.read(374, map, MediaSessionCompatQueueItem.read(373, map, MediaSessionCompatQueueItem.read(372, map, MediaSessionCompatQueueItem.read(371, map, MediaSessionCompatQueueItem.read(370, map, MediaSessionCompatQueueItem.read(359, map, arrayList18, 1, "LT"), 1, "LV"), 1, "EE"), 1, "MD"), 1, "AM"), 1, "BY"), 1, "AD"), 1, "MC"), 1, "SM"), 1, "UA"), 1, "RS"), 1, "ME"), 1, "XK"), 1, "HR"), 1, "SI"), 1, "BA"), 1, "MK"), 1, "CZ"), 1, "SK"), 1, "LI"), 1, "FK"), 1, "BZ"), 1, "GT"), 1, "SV"), 1, "HN"), 1, "NI"), 1, "CR"), 1, "PA"), 1, "PM"), 1, "HT"), 3, "GP");
        arrayList19.add("BL");
        arrayList19.add("MF");
        map.put(590, arrayList19);
        ArrayList arrayList20 = new ArrayList(1);
        arrayList20.add("BO");
        ArrayList arrayList21 = MediaSessionCompatQueueItem.read(598, map, MediaSessionCompatQueueItem.read(597, map, MediaSessionCompatQueueItem.read(596, map, MediaSessionCompatQueueItem.read(595, map, MediaSessionCompatQueueItem.read(594, map, MediaSessionCompatQueueItem.read(593, map, MediaSessionCompatQueueItem.read(592, map, MediaSessionCompatQueueItem.read(591, map, arrayList20, 1, "GY"), 1, "EC"), 1, "GF"), 1, "PY"), 1, "MQ"), 1, "SR"), 1, "UY"), 2, "CW");
        arrayList21.add("BQ");
        map.put(599, arrayList21);
        ArrayList arrayList22 = new ArrayList(1);
        arrayList22.add("TL");
        map.put(998, MediaSessionCompatQueueItem.read(996, map, MediaSessionCompatQueueItem.read(995, map, MediaSessionCompatQueueItem.read(994, map, MediaSessionCompatQueueItem.read(993, map, MediaSessionCompatQueueItem.read(992, map, MediaSessionCompatQueueItem.read(979, map, MediaSessionCompatQueueItem.read(977, map, MediaSessionCompatQueueItem.read(976, map, MediaSessionCompatQueueItem.read(975, map, MediaSessionCompatQueueItem.read(974, map, MediaSessionCompatQueueItem.read(973, map, MediaSessionCompatQueueItem.read(972, map, MediaSessionCompatQueueItem.read(971, map, MediaSessionCompatQueueItem.read(970, map, MediaSessionCompatQueueItem.read(968, map, MediaSessionCompatQueueItem.read(967, map, MediaSessionCompatQueueItem.read(966, map, MediaSessionCompatQueueItem.read(965, map, MediaSessionCompatQueueItem.read(964, map, MediaSessionCompatQueueItem.read(963, map, MediaSessionCompatQueueItem.read(962, map, MediaSessionCompatQueueItem.read(961, map, MediaSessionCompatQueueItem.read(960, map, MediaSessionCompatQueueItem.read(888, map, MediaSessionCompatQueueItem.read(886, map, MediaSessionCompatQueueItem.read(883, map, MediaSessionCompatQueueItem.read(882, map, MediaSessionCompatQueueItem.read(881, map, MediaSessionCompatQueueItem.read(880, map, MediaSessionCompatQueueItem.read(878, map, MediaSessionCompatQueueItem.read(870, map, MediaSessionCompatQueueItem.read(856, map, MediaSessionCompatQueueItem.read(855, map, MediaSessionCompatQueueItem.read(853, map, MediaSessionCompatQueueItem.read(852, map, MediaSessionCompatQueueItem.read(850, map, MediaSessionCompatQueueItem.read(808, map, MediaSessionCompatQueueItem.read(800, map, MediaSessionCompatQueueItem.read(692, map, MediaSessionCompatQueueItem.read(691, map, MediaSessionCompatQueueItem.read(690, map, MediaSessionCompatQueueItem.read(689, map, MediaSessionCompatQueueItem.read(688, map, MediaSessionCompatQueueItem.read(687, map, MediaSessionCompatQueueItem.read(686, map, MediaSessionCompatQueueItem.read(685, map, MediaSessionCompatQueueItem.read(683, map, MediaSessionCompatQueueItem.read(682, map, MediaSessionCompatQueueItem.read(681, map, MediaSessionCompatQueueItem.read(680, map, MediaSessionCompatQueueItem.read(679, map, MediaSessionCompatQueueItem.read(678, map, MediaSessionCompatQueueItem.read(677, map, MediaSessionCompatQueueItem.read(676, map, MediaSessionCompatQueueItem.read(675, map, MediaSessionCompatQueueItem.read(674, map, MediaSessionCompatQueueItem.read(673, map, MediaSessionCompatQueueItem.read(672, map, MediaSessionCompatQueueItem.read(670, map, arrayList22, 1, "NF"), 1, "BN"), 1, "NR"), 1, "PG"), 1, "TO"), 1, "SB"), 1, "VU"), 1, "FJ"), 1, "PW"), 1, "WF"), 1, "CK"), 1, "NU"), 1, "WS"), 1, "KI"), 1, "NC"), 1, "TV"), 1, "PF"), 1, "TK"), 1, "FM"), 1, "MH"), 1, "001"), 1, "001"), 1, "KP"), 1, "HK"), 1, "MO"), 1, "KH"), 1, "LA"), 1, "001"), 1, "001"), 1, "BD"), 1, "001"), 1, "001"), 1, "001"), 1, "TW"), 1, "001"), 1, "MV"), 1, "LB"), 1, "JO"), 1, "SY"), 1, "IQ"), 1, "KW"), 1, "SA"), 1, "YE"), 1, "OM"), 1, "PS"), 1, "AE"), 1, "IL"), 1, "BH"), 1, "QA"), 1, "BT"), 1, "MN"), 1, "NP"), 1, "001"), 1, "TJ"), 1, "TM"), 1, "AZ"), 1, "GE"), 1, "KG"), 1, "UZ"));
        return map;
    }
}
