package o;

import bo.app.m1$$ExternalSyntheticOutline0;

/* JADX INFO: loaded from: classes2.dex */
public final class getLastIndex implements accessdetachAndRemoveNode {
    public static final getLastIndex r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28 = new getLastIndex();
    public static final accessgetAggregateChildKindSet getOnBackPressedDispatcher = new accessgetAggregateChildKindSet("systemInfo", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(1, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet getSavedStateRegistry = new accessgetAggregateChildKindSet("eventName", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(2, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet getNavigationEventDispatcher = new accessgetAggregateChildKindSet("isThickClient", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(37, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet getViewModelStore = new accessgetAggregateChildKindSet("clientType", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(61, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onActivityResult = new accessgetAggregateChildKindSet("modelDownloadLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(3, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onConfigurationChanged = new accessgetAggregateChildKindSet("customModelLoadLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(20, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onBackPressed = new accessgetAggregateChildKindSet("customModelInferenceLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(4, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet invalidateMenu = new accessgetAggregateChildKindSet("customModelCreateLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(29, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet initializeViewTreeOwners = new accessgetAggregateChildKindSet("onDeviceFaceDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(5, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onCreatePanelMenu = new accessgetAggregateChildKindSet("onDeviceFaceLoadLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(59, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onNewIntent = new accessgetAggregateChildKindSet("onDeviceTextDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(6, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onMultiWindowModeChanged = new accessgetAggregateChildKindSet("onDeviceTextDetectionLoadLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(79, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onMenuItemSelected = new accessgetAggregateChildKindSet("onDeviceBarcodeDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(7, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onCreate = new accessgetAggregateChildKindSet("onDeviceBarcodeLoadLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(58, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onPreparePanel = new accessgetAggregateChildKindSet("onDeviceImageLabelCreateLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(48, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onPanelClosed = new accessgetAggregateChildKindSet("onDeviceImageLabelLoadLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(49, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onPictureInPictureModeChanged = new accessgetAggregateChildKindSet("onDeviceImageLabelDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(18, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onRequestPermissionsResult = new accessgetAggregateChildKindSet("onDeviceObjectCreateLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(26, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onPictureInPictureUiStateChanged = new accessgetAggregateChildKindSet("onDeviceObjectLoadLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(27, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onUserLeaveHint = new accessgetAggregateChildKindSet("onDeviceObjectInferenceLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(28, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onRetainCustomNonConfigurationInstance = new accessgetAggregateChildKindSet("onDevicePoseDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(44, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onTrimMemory = new accessgetAggregateChildKindSet("onDeviceSegmentationLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(45, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onRetainNonConfigurationInstance = new accessgetAggregateChildKindSet("onDeviceSmartReplyLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(19, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onSaveInstanceState = new accessgetAggregateChildKindSet("onDeviceLanguageIdentificationLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(21, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet removeOnContextAvailableListener = new accessgetAggregateChildKindSet("onDeviceTranslationLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(22, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet IconCompatParcelizer = new accessgetAggregateChildKindSet("cloudFaceDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(8, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet serializer = new accessgetAggregateChildKindSet("cloudCropHintDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(9, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet read = new accessgetAggregateChildKindSet("cloudDocumentTextDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(10, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet write = new accessgetAggregateChildKindSet("cloudImagePropertiesDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(11, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet RemoteActionCompatParcelizer = new accessgetAggregateChildKindSet("cloudImageLabelDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(12, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet MediaSessionCompatQueueItem = new accessgetAggregateChildKindSet("cloudLandmarkDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(13, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet MediaMetadataCompat = new accessgetAggregateChildKindSet("cloudLogoDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(14, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet MediaBrowserCompatMediaItem = new accessgetAggregateChildKindSet("cloudSafeSearchDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(15, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet RatingCompat = new accessgetAggregateChildKindSet("cloudTextDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(16, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet MediaDescriptionCompat = new accessgetAggregateChildKindSet("cloudWebSearchDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(17, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet PlaybackStateCompat = new accessgetAggregateChildKindSet("automlImageLabelingCreateLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(23, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet ParcelableVolumeInfo = new accessgetAggregateChildKindSet("automlImageLabelingLoadLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(24, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet MediaSessionCompatToken = new accessgetAggregateChildKindSet("automlImageLabelingInferenceLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(25, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet PlaybackStateCompatCustomAction = new accessgetAggregateChildKindSet("isModelDownloadedLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(39, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet MediaSessionCompatResultReceiverWrapper = new accessgetAggregateChildKindSet("deleteModelLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(40, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet r8lambda7IJBVrN0sHyidCAZufWEJFc7yY = new accessgetAggregateChildKindSet("aggregatedAutomlImageLabelingInferenceLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(30, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet ResultReceiver = new accessgetAggregateChildKindSet("aggregatedCustomModelInferenceLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(31, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus = new accessgetAggregateChildKindSet("aggregatedOnDeviceFaceDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(32, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet r8lambda54BeH8ZsBru0CXI2CCSP2syNys = new accessgetAggregateChildKindSet("aggregatedOnDeviceBarcodeDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(33, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet ComponentActivity = new accessgetAggregateChildKindSet("aggregatedOnDeviceImageLabelDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(34, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss = new accessgetAggregateChildKindSet("aggregatedOnDeviceObjectInferenceLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(35, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4 = new accessgetAggregateChildKindSet("aggregatedOnDeviceTextDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(36, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8 = new accessgetAggregateChildKindSet("aggregatedOnDevicePoseDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(46, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM = new accessgetAggregateChildKindSet("aggregatedOnDeviceSegmentationLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(47, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg = new accessgetAggregateChildKindSet("pipelineAccelerationInferenceEvents", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(69, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs = new accessgetAggregateChildKindSet("remoteConfigLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(42, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet getOnBackPressedInput = new accessgetAggregateChildKindSet("inputImageConstructionLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(50, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet getSavedStateRegistryControllerannotations = new accessgetAggregateChildKindSet("leakedHandleEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(51, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet fullyDrawnReporter_delegatelambda00 = new accessgetAggregateChildKindSet("cameraSourceLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(52, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet menuHostHelperlambda0 = new accessgetAggregateChildKindSet("imageLabelOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(53, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet fullyDrawnReporter_delegatelambda0 = new accessgetAggregateChildKindSet("languageIdentificationOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(54, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onBackPressedDispatcher_delegatelambda010 = new accessgetAggregateChildKindSet("faceDetectionOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(60, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet addContentView = new accessgetAggregateChildKindSet("documentDetectionOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(85, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onBackPressedDispatcher_delegatelambda00 = new accessgetAggregateChildKindSet("documentCroppingOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(86, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onBackPressedDispatcher_delegatelambda0 = new accessgetAggregateChildKindSet("documentEnhancementOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(87, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet onBackPressedInput_delegatelambda0 = new accessgetAggregateChildKindSet("nlClassifierOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(55, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet addMenuProvider = new accessgetAggregateChildKindSet("nlClassifierClientLibraryLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(56, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet addOnNewIntentListener = new accessgetAggregateChildKindSet("accelerationAllowlistLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(57, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet addOnContextAvailableListener = new accessgetAggregateChildKindSet("toxicityDetectionCreateEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(62, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet addOnMultiWindowModeChangedListener = new accessgetAggregateChildKindSet("toxicityDetectionLoadEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(63, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet addOnConfigurationChangedListener = new accessgetAggregateChildKindSet("toxicityDetectionInferenceEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(64, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet enterPictureInPictureMode = new accessgetAggregateChildKindSet("barcodeDetectionOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(65, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet addOnPictureInPictureModeChangedListener = new accessgetAggregateChildKindSet("customImageLabelOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(66, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet addOnUserLeaveHintListener = new accessgetAggregateChildKindSet("codeScannerScanApiEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(67, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet addOnTrimMemoryListener = new accessgetAggregateChildKindSet("codeScannerOptionalModuleEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(68, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet addOnPictureInPictureUiStateChangedListener = new accessgetAggregateChildKindSet("onDeviceExplicitContentCreateLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(70, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet getLastCustomNonConfigurationInstance = new accessgetAggregateChildKindSet("onDeviceExplicitContentLoadLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(71, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet getFullyDrawnReporter = new accessgetAggregateChildKindSet("onDeviceExplicitContentInferenceLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(72, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet getActivityResultRegistry = new accessgetAggregateChildKindSet("aggregatedOnDeviceExplicitContentLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(73, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet getDefaultViewModelCreationExtras = new accessgetAggregateChildKindSet("onDeviceFaceMeshCreateLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(74, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet getDefaultViewModelProviderFactory = new accessgetAggregateChildKindSet("onDeviceFaceMeshLoadLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(75, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet getLifecycle = new accessgetAggregateChildKindSet("onDeviceFaceMeshLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(76, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ = new accessgetAggregateChildKindSet("aggregatedOnDeviceFaceMeshLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(77, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw = new accessgetAggregateChildKindSet("smartReplyOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(78, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0 = new accessgetAggregateChildKindSet("textDetectionOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(80, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet _init_lambda1 = new accessgetAggregateChildKindSet("onDeviceImageQualityAnalysisCreateLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(81, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet accessensureViewModelStore = new accessgetAggregateChildKindSet("onDeviceImageQualityAnalysisLoadLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(82, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet _init_lambda4 = new accessgetAggregateChildKindSet("onDeviceImageQualityAnalysisLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(83, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet _init_lambda2 = new accessgetAggregateChildKindSet("aggregatedOnDeviceImageQualityAnalysisLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(84, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet _init_lambda3 = new accessgetAggregateChildKindSet("imageQualityAnalysisOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(88, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet ensureViewModelStore = new accessgetAggregateChildKindSet("imageCaptioningOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(89, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet addObserverForBackInvoker = new accessgetAggregateChildKindSet("onDeviceImageCaptioningCreateLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(90, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet defaultViewModelProviderFactory_delegatelambda0 = new accessgetAggregateChildKindSet("onDeviceImageCaptioningLoadLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(91, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet createFullyDrawnExecutor = new accessgetAggregateChildKindSet("onDeviceImageCaptioningInferenceLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(92, getStylusT8wyACA.DEFAULT))));
    public static final accessgetAggregateChildKindSet addObserverForBackInvokerlambda0 = new accessgetAggregateChildKindSet("aggregatedOnDeviceImageCaptioningInferenceLogEvent", m1$$ExternalSyntheticOutline0.m(MediaSessionCompatQueueItem.serializer(getUnknownT8wyACA.class, new accessgetMousecp(93, getStylusT8wyACA.DEFAULT))));

    @Override // o.accessgetLoggerp
    public final void serializer(Object obj, Object obj2) {
        ApproachLayoutModifierNodeminApproachIntrinsicWidth1 approachLayoutModifierNodeminApproachIntrinsicWidth1 = (ApproachLayoutModifierNodeminApproachIntrinsicWidth1) obj;
        accessupdateNode accessupdatenode = (accessupdateNode) obj2;
        accessupdatenode.write(getOnBackPressedDispatcher, approachLayoutModifierNodeminApproachIntrinsicWidth1.write);
        accessupdatenode.write(getSavedStateRegistry, approachLayoutModifierNodeminApproachIntrinsicWidth1.serializer);
        accessupdatenode.write(getNavigationEventDispatcher, (Object) null);
        accessupdatenode.write(getViewModelStore, (Object) null);
        accessupdatenode.write(onActivityResult, (Object) null);
        accessupdatenode.write(onConfigurationChanged, (Object) null);
        accessupdatenode.write(onBackPressed, (Object) null);
        accessupdatenode.write(invalidateMenu, (Object) null);
        accessupdatenode.write(initializeViewTreeOwners, (Object) null);
        accessupdatenode.write(onCreatePanelMenu, (Object) null);
        accessupdatenode.write(onNewIntent, (Object) null);
        accessupdatenode.write(onMultiWindowModeChanged, (Object) null);
        accessupdatenode.write(onMenuItemSelected, (Object) null);
        accessupdatenode.write(onCreate, (Object) null);
        accessupdatenode.write(onPreparePanel, (Object) null);
        accessupdatenode.write(onPanelClosed, (Object) null);
        accessupdatenode.write(onPictureInPictureModeChanged, (Object) null);
        accessupdatenode.write(onRequestPermissionsResult, (Object) null);
        accessupdatenode.write(onPictureInPictureUiStateChanged, (Object) null);
        accessupdatenode.write(onUserLeaveHint, (Object) null);
        accessupdatenode.write(onRetainCustomNonConfigurationInstance, (Object) null);
        accessupdatenode.write(onTrimMemory, (Object) null);
        accessupdatenode.write(onRetainNonConfigurationInstance, (Object) null);
        accessupdatenode.write(onSaveInstanceState, (Object) null);
        accessupdatenode.write(removeOnContextAvailableListener, (Object) null);
        accessupdatenode.write(IconCompatParcelizer, (Object) null);
        accessupdatenode.write(serializer, (Object) null);
        accessupdatenode.write(read, (Object) null);
        accessupdatenode.write(write, (Object) null);
        accessupdatenode.write(RemoteActionCompatParcelizer, (Object) null);
        accessupdatenode.write(MediaSessionCompatQueueItem, (Object) null);
        accessupdatenode.write(MediaMetadataCompat, (Object) null);
        accessupdatenode.write(MediaBrowserCompatMediaItem, (Object) null);
        accessupdatenode.write(RatingCompat, (Object) null);
        accessupdatenode.write(MediaDescriptionCompat, (Object) null);
        accessupdatenode.write(PlaybackStateCompat, (Object) null);
        accessupdatenode.write(ParcelableVolumeInfo, (Object) null);
        accessupdatenode.write(MediaSessionCompatToken, (Object) null);
        accessupdatenode.write(PlaybackStateCompatCustomAction, (Object) null);
        accessupdatenode.write(MediaSessionCompatResultReceiverWrapper, (Object) null);
        accessupdatenode.write(r8lambda7IJBVrN0sHyidCAZufWEJFc7yY, (Object) null);
        accessupdatenode.write(ResultReceiver, (Object) null);
        accessupdatenode.write(r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus, (Object) null);
        accessupdatenode.write(r8lambda54BeH8ZsBru0CXI2CCSP2syNys, (Object) null);
        accessupdatenode.write(ComponentActivity, (Object) null);
        accessupdatenode.write(r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss, (Object) null);
        accessupdatenode.write(r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4, (Object) null);
        accessupdatenode.write(r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8, (Object) null);
        accessupdatenode.write(r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM, (Object) null);
        accessupdatenode.write(r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg, (Object) null);
        accessupdatenode.write(r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs, (Object) null);
        accessupdatenode.write(getOnBackPressedInput, approachLayoutModifierNodeminApproachIntrinsicWidth1.RemoteActionCompatParcelizer);
        accessupdatenode.write(getSavedStateRegistryControllerannotations, (Object) null);
        accessupdatenode.write(fullyDrawnReporter_delegatelambda00, (Object) null);
        accessupdatenode.write(menuHostHelperlambda0, (Object) null);
        accessupdatenode.write(fullyDrawnReporter_delegatelambda0, (Object) null);
        accessupdatenode.write(onBackPressedDispatcher_delegatelambda010, (Object) null);
        accessupdatenode.write(addContentView, (Object) null);
        accessupdatenode.write(onBackPressedDispatcher_delegatelambda00, (Object) null);
        accessupdatenode.write(onBackPressedDispatcher_delegatelambda0, (Object) null);
        accessupdatenode.write(onBackPressedInput_delegatelambda0, (Object) null);
        accessupdatenode.write(addMenuProvider, (Object) null);
        accessupdatenode.write(addOnNewIntentListener, (Object) null);
        accessupdatenode.write(addOnContextAvailableListener, (Object) null);
        accessupdatenode.write(addOnMultiWindowModeChangedListener, (Object) null);
        accessupdatenode.write(addOnConfigurationChangedListener, (Object) null);
        accessupdatenode.write(enterPictureInPictureMode, (Object) null);
        accessupdatenode.write(addOnPictureInPictureModeChangedListener, (Object) null);
        accessupdatenode.write(addOnUserLeaveHintListener, (Object) null);
        accessupdatenode.write(addOnTrimMemoryListener, (Object) null);
        accessupdatenode.write(addOnPictureInPictureUiStateChangedListener, (Object) null);
        accessupdatenode.write(getLastCustomNonConfigurationInstance, (Object) null);
        accessupdatenode.write(getFullyDrawnReporter, (Object) null);
        accessupdatenode.write(getActivityResultRegistry, (Object) null);
        accessupdatenode.write(getDefaultViewModelCreationExtras, (Object) null);
        accessupdatenode.write(getDefaultViewModelProviderFactory, (Object) null);
        accessupdatenode.write(getLifecycle, (Object) null);
        accessupdatenode.write(r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ, (Object) null);
        accessupdatenode.write(r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw, (Object) null);
        accessupdatenode.write(r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0, (Object) null);
        accessupdatenode.write(_init_lambda1, (Object) null);
        accessupdatenode.write(accessensureViewModelStore, (Object) null);
        accessupdatenode.write(_init_lambda4, (Object) null);
        accessupdatenode.write(_init_lambda2, (Object) null);
        accessupdatenode.write(_init_lambda3, (Object) null);
        accessupdatenode.write(ensureViewModelStore, (Object) null);
        accessupdatenode.write(addObserverForBackInvoker, (Object) null);
        accessupdatenode.write(defaultViewModelProviderFactory_delegatelambda0, (Object) null);
        accessupdatenode.write(createFullyDrawnExecutor, (Object) null);
        accessupdatenode.write(addObserverForBackInvokerlambda0, (Object) null);
    }
}
