package o;

import java.util.List;

/* JADX INFO: loaded from: classes3.dex */
public abstract class getParagraphIntrinsics {
    public static final List IconCompatParcelizer = androidx.sqlite.SQLite.read("HELPCENTER_INIT_WILL_START", "HELPCENTER_INIT_FAILED", "HELPCENTER_INIT_STARTED", "HELPCENTER_INIT_IS_DONE", "HOST_IS_READY", "HOST_ASKS_FOR_BACK_NAVIGATION", "HOST_NOTIFIES_ABOUT_WEBVIEW_VISIBILITY_CHANGE", "HELPCENTER_ASKS_FOR_SHUTDOWN", "HELPCENTER_WILL_HANDLE_BACK_NAVIGATION", "HELPCENTER_WONT_HANDLE_BACK_NAVIGATION", "HELPCENTER_CHAT_STARTED", "HELPCENTER_CHAT_ENDED", "HOST_APP_PROVIDES_CHAT_CONFIG", "CLIENT_ASKS_FOR_CHAT_CONFIG", "CLIENT_CHAT_NOTIFIES_ABOUT_MESSAGE_SENT", "CLIENT_CHAT_NOTIFIES_ABOUT_CHAT_OPEN", "CLIENT_CHAT_NOTIFIES_ABOUT_CHAT_CLOSE", "CLIENT_CHAT_NOTIFIES_ABOUT_QUICK_REPLY_SENT", "CLIENT_CHAT_NOTIFIES_ABOUT_TRANSLATION_TOGGLE_CLICK", "CLIENT_CHAT_NOTIFIES_ABOUT_CALL_BUTTON_CLICK", "CLIENT_CHAT_NOTIFIES_ABOUT_LOCATION_MESSAGE_CLICK", "CLIENT_CRITICAL_CONTENT_RENDERED", "HOST_SENDS_NEW_ACCESS_TOKEN", "HELPCENTER_ASKS_FOR_NEW_ACCESS_TOKEN", "HOST_ENCOUNTERED_ERROR", "HOST_ENCOUNTERED_ERROR_ACK", "HOST_LOADING_PERFORMANCE_MEASUREMENT");
    private static int read = 0;
    private static int serializer = 1;

    static {
        int i = read + 57;
        serializer = i % androidx.compose.ui.graphics.Fields.SpotShadowColor;
        if (i % 2 == 0) {
            throw null;
        }
    }
}
