package o;

import coil3.ImageLoader$Builder;
import com.foodora.courier.app.application.CourierApplication;
import com.google.android.play.core.appupdate.zzz;
import com.roadrunner.appinitialize.InitializeAppStartupItemsImpl;
import com.roadrunner.auth.data.AuthRepository;
import com.roadrunner.auth.domain.token.IsUserAuthenticatedWrapper;
import com.roadrunner.heatmap.domain.ShouldShowHeatmap_Factory;
import com.roadrunner.login.logging.RouterLogger;
import com.roadrunner.push.core.domain.RegisterPushNotificationUseCaseImpl;
import dagger.Lazy;
import io.grpc.internal.SharedResourcePool;
import io.sentry.CombinedScopeView;
import io.sentry.metrics.MetricsBatchProcessor;
import io.sentry.util.network.NetworkBody;

/* JADX INFO: loaded from: classes2.dex */
public final class getSTYLEABLE_VECTOR_DRAWABLE_GROUP_TRANSLATE_X {
    private static int onPanelClosed = 1;
    private static int onRequestPermissionsResult;
    public final subscribeToFeatureFlagsUpdateslambda0 ComponentActivity;
    public final setSyncPolicyOfflineStatuslambda1 IconCompatParcelizer;
    public final mergeJsonObjects MediaBrowserCompatMediaItem;
    public final mergeJsonObjects MediaDescriptionCompat;
    public final mergeJsonObjects MediaMetadataCompat;
    public final mergeJsonObjects MediaSessionCompatQueueItem;
    public final setSyncPolicyOfflineStatuslambda1 MediaSessionCompatResultReceiverWrapper;
    public final SingleProcessDataStore MediaSessionCompatToken;
    public final newTransaction ParcelableVolumeInfo;
    public final r8lambdaZcilDVoiQYR1yQsOxhHduSfdjyw PlaybackStateCompat;
    public final r8lambdazXN1qqQhLYzDDSf7dMTrYE1xu8I PlaybackStateCompatCustomAction;
    public final mergeJsonObjects RatingCompat;
    public final accessgetRelayoutTimep RemoteActionCompatParcelizer;
    public final insertBasedOnParentOffset ResultReceiver;
    public final getDoubleOrNull _init_lambda1;
    public final mergeJsonObjects _init_lambda2;
    public final getDoubleOrNull _init_lambda3;
    public final getDoubleOrNull _init_lambda4;
    public final LayoutCompat accessensureViewModelStore;
    public final FontVariationSettingInt addContentView;
    public final newTransaction addMenuProvider;
    public final invokeqtAw6s addObserverForBackInvoker;
    public final lineEndToVisibleEnd addObserverForBackInvokerlambda0;
    public final mergeJsonObjects addOnConfigurationChangedListener;
    public final FontVariationSettingInt addOnContextAvailableListener;
    public final FontVariationSettingInt addOnMultiWindowModeChangedListener;
    public final insertBasedOnParentOffset addOnNewIntentListener;
    public final setUseTempTrackingTableroom_runtime addOnPictureInPictureModeChangedListener;
    public final r8lambdawMZ4b3qLWvwGdmRM_auBcG267s addOnPictureInPictureUiStateChangedListener;
    public final FontVariationSettingInt addOnTrimMemoryListener;
    public final r8lambdazXN1qqQhLYzDDSf7dMTrYE1xu8I addOnUserLeaveHintListener;
    public final getScrollRange createFullyDrawnExecutor;
    public final setUseTempTrackingTableroom_runtime defaultViewModelProviderFactory_delegatelambda0;
    public final r8lambda6UOvp7lvejigbq5knKoP8A0vEiw ensureViewModelStore;
    public final mergeJsonObjects enterPictureInPictureMode;
    public final transformCanvas fullyDrawnReporter_delegatelambda0;
    public final transformCanvas fullyDrawnReporter_delegatelambda00;
    public final newTransaction getActivityResultRegistry;
    public final mergeJsonObjects getDefaultViewModelCreationExtras;
    public final performPushDeliveryFlushlambda0 getDefaultViewModelProviderFactory;
    public final mergeJsonObjects getFullyDrawnReporter;
    public final invokeqtAw6s getLastCustomNonConfigurationInstance;
    public final r8lambdaqTOOBHcNghE7kA6ntx9WQ9cPAYY getLifecycle;
    public final mergeJsonObjects getNavigationEventDispatcher;
    public final r8lambda31xVc6yTCUqSOPjA0Lc9HsR6ufI getOnBackPressedDispatcher;
    public final onMeasureChild getOnBackPressedInput;
    public final com.data.injection.DataModule_ProvideSchedulerFactory getSavedStateRegistry;
    public final getContentDataType getSavedStateRegistryControllerannotations;
    public final mergeJsonObjects getViewModelStore;
    public final mergeJsonObjects initializeViewTreeOwners;
    public final ShouldShowHeatmap_Factory invalidateMenu;
    public final setVerticalBias menuHostHelperlambda0;
    public final mergeJsonObjects onActivityResult;
    public final setUseTempTrackingTableroom_runtime onBackPressed;
    public final mergeJsonObjects onBackPressedDispatcher_delegatelambda0;
    public final insertBasedOnParentOffset onBackPressedDispatcher_delegatelambda00;
    public final ShouldShowHeatmap_Factory onBackPressedDispatcher_delegatelambda010;
    public final mergeJsonObjects onBackPressedInput_delegatelambda0;
    public final getInvisibleToUserannotations onConfigurationChanged;
    public final fastMergej5T8yCg onCreate;
    public final PreferenceGroupAdapter onCreatePanelMenu;
    public final FontVariationSettingInt onMenuItemSelected;
    public final FontVariationSettingInt onMultiWindowModeChanged;
    public final r8lambdazpHrebeZ5dkHsk62AZggxj52Jpo onNewIntent;
    public final elambda0 onPictureInPictureModeChanged;
    public final mergeJsonObjects r8lambda54BeH8ZsBru0CXI2CCSP2syNys;
    public final insertBasedOnParentOffset r8lambda7IJBVrN0sHyidCAZufWEJFc7yY;
    public final onMeasureChild r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus;
    public final getDoubleOrNull r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss;
    public final getDoubleOrNull r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg;
    public final getDoubleOrNull r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8;
    public final getDoubleOrNull r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4;
    public final getDoubleOrNull r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM;
    public final getDoubleOrNull r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs;
    public final getDoubleOrNull r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28;
    public final getDoubleOrNull r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw;
    public final getDoubleOrNull r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ;
    public final getDoubleOrNull r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0;
    public final mergeJsonObjects read;
    public final mergeJsonObjects serializer;
    public final getSTYLEABLE_VECTOR_DRAWABLE_GROUP_ROTATION write;

    public getSTYLEABLE_VECTOR_DRAWABLE_GROUP_TRANSLATE_X(getSTYLEABLE_VECTOR_DRAWABLE_GROUP_ROTATION getstyleable_vector_drawable_group_rotation) {
        this.write = getstyleable_vector_drawable_group_rotation;
        r8lambdazvX83UIDsL68vmN7rPQXcY0mE r8lambdazvx83uidsl68vmn7rpqxcy0me = new r8lambdazvX83UIDsL68vmN7rPQXcY0mE(10);
        invokeqtAw6s invokeqtaw6s = getstyleable_vector_drawable_group_rotation.ExcludedSupportedSizesQuirk;
        publishErrorlambda1 publisherrorlambda1 = getstyleable_vector_drawable_group_rotation.FocusMeteringControl;
        invokeqtaw6s.getClass();
        publisherrorlambda1.getClass();
        mergeJsonObjects mergejsonobjectsIconCompatParcelizer = getColorIntegerOrNull.IconCompatParcelizer(new requestGeofencesInitializationlambda1(invokeqtaw6s, publisherrorlambda1, r8lambdazvx83uidsl68vmn7rpqxcy0me));
        mergeJsonObjects mergejsonobjects = getstyleable_vector_drawable_group_rotation.applyMeasureResultfoundation;
        lambdaverifyPlayStorePurchase45 lambdaverifyplaystorepurchase45 = getstyleable_vector_drawable_group_rotation.fromId;
        mergeJsonObjects mergejsonobjects2 = getstyleable_vector_drawable_group_rotation.ContentInViewNodelaunchAnimation21;
        mergejsonobjects.getClass();
        lambdaverifyplaystorepurchase45.getClass();
        mergejsonobjects2.getClass();
        mergeJsonObjects mergejsonobjectsIconCompatParcelizer2 = getColorIntegerOrNull.IconCompatParcelizer(new o1(mergejsonobjects, lambdaverifyplaystorepurchase45, mergejsonobjectsIconCompatParcelizer, mergejsonobjects2));
        this.getNavigationEventDispatcher = mergejsonobjectsIconCompatParcelizer2;
        requestSingleLocationUpdatelambda1 requestsinglelocationupdatelambda1 = getstyleable_vector_drawable_group_rotation.NonTouchScrollingLogic;
        postAnimationRunner postanimationrunner = getstyleable_vector_drawable_group_rotation.PagerKt;
        mergeJsonObjects mergejsonobjects3 = getstyleable_vector_drawable_group_rotation.ContentInViewNodelaunchAnimation21;
        requestsinglelocationupdatelambda1.getClass();
        postanimationrunner.getClass();
        mergejsonobjects3.getClass();
        this.onActivityResult = getColorIntegerOrNull.IconCompatParcelizer(new o1(mergejsonobjectsIconCompatParcelizer2, requestsinglelocationupdatelambda1, postanimationrunner, mergejsonobjects3));
        this.enterPictureInPictureMode = getColorIntegerOrNull.IconCompatParcelizer(new insertBasedOnParentOffset(getstyleable_vector_drawable_group_rotation.FocusMeteringControl, getstyleable_vector_drawable_group_rotation.updateWko1d7g, getstyleable_vector_drawable_group_rotation.ContentInViewNodelaunchAnimation21, new newTransaction(getstyleable_vector_drawable_group_rotation.getFeatureGroupUseCaseType, getstyleable_vector_drawable_group_rotation.Contentfoundation, 2), 29));
        hasNestedScrollingParent hasnestedscrollingparent = getstyleable_vector_drawable_group_rotation.AbstractClickableNodeonKeyEvent1;
        mergeJsonObjects mergejsonobjects4 = getstyleable_vector_drawable_group_rotation.setItemInvoker;
        mergeJsonObjects mergejsonobjects5 = getstyleable_vector_drawable_group_rotation.ContentInViewNodelaunchAnimation21;
        hasnestedscrollingparent.getClass();
        mergejsonobjects4.getClass();
        mergejsonobjects5.getClass();
        this.onBackPressedDispatcher_delegatelambda010 = new ShouldShowHeatmap_Factory(hasnestedscrollingparent, mergejsonobjects4, mergejsonobjects5);
        this.r8lambda54BeH8ZsBru0CXI2CCSP2syNys = getColorIntegerOrNull.IconCompatParcelizer(new newTransaction(getstyleable_vector_drawable_group_rotation.calculateApproachOffset, getstyleable_vector_drawable_group_rotation.TextLinkScope, 23));
        com.data.injection.DataModule_ProvideSchedulerFactory dataModule_ProvideSchedulerFactory = getstyleable_vector_drawable_group_rotation.TextLinkScope;
        getScrollRange getscrollrange = getstyleable_vector_drawable_group_rotation.getId;
        r8lambdazXN1qqQhLYzDDSf7dMTrYE1xu8I r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i = getstyleable_vector_drawable_group_rotation.getTabContainer;
        dataModule_ProvideSchedulerFactory.getClass();
        getscrollrange.getClass();
        r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i.getClass();
        this.invalidateMenu = new ShouldShowHeatmap_Factory(dataModule_ProvideSchedulerFactory, getscrollrange, r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i);
        mergeJsonObjects mergejsonobjects6 = getstyleable_vector_drawable_group_rotation.MediaMetadataCompat;
        mergejsonobjects6.getClass();
        this.onMultiWindowModeChanged = new FontVariationSettingInt(mergejsonobjects6, 22);
        FlingCancellationException flingCancellationException = getstyleable_vector_drawable_group_rotation.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus;
        r8lambda31xVc6yTCUqSOPjA0Lc9HsR6ufI r8lambda31xvc6ytcuqsopja0lc9hsr6ufi = getstyleable_vector_drawable_group_rotation.pullBottomk4lQ0M;
        r8lambda31xvc6ytcuqsopja0lc9hsr6ufi.getClass();
        this.getSavedStateRegistry = new com.data.injection.DataModule_ProvideSchedulerFactory(flingCancellationException, r8lambda31xvc6ytcuqsopja0lc9hsr6ufi);
        this.getViewModelStore = getColorIntegerOrNull.IconCompatParcelizer(new invokeqtAw6s(getstyleable_vector_drawable_group_rotation.AbstractClickableNodeonKeyEvent1, getstyleable_vector_drawable_group_rotation.TextLinkScope, 1));
        this.initializeViewTreeOwners = getColorIntegerOrNull.IconCompatParcelizer(accesssetBrushAndDrawyzxVdVo.serializer);
        mergeJsonObjects mergejsonobjectsIconCompatParcelizer3 = getColorIntegerOrNull.IconCompatParcelizer(new copyJdDtMQoui_text());
        this.MediaSessionCompatQueueItem = mergejsonobjectsIconCompatParcelizer3;
        int i = 25;
        this.MediaDescriptionCompat = getColorIntegerOrNull.IconCompatParcelizer(new LayoutCompat(mergejsonobjectsIconCompatParcelizer3, i));
        r8lambdaqTOOBHcNghE7kA6ntx9WQ9cPAYY r8lambdaqtoobhcnghe7ka6ntx9wq9cpayy = new r8lambdaqTOOBHcNghE7kA6ntx9WQ9cPAYY(getstyleable_vector_drawable_group_rotation.ScrollExtensionsKt, getstyleable_vector_drawable_group_rotation.AbstractClickableNodeonKeyEvent1, 7);
        this.getLifecycle = r8lambdaqtoobhcnghe7ka6ntx9wq9cpayy;
        setUseTempTrackingTableroom_runtime setusetemptrackingtableroom_runtime = new setUseTempTrackingTableroom_runtime(r8lambdaqtoobhcnghe7ka6ntx9wq9cpayy, 27);
        this.addOnPictureInPictureModeChangedListener = setusetemptrackingtableroom_runtime;
        mergeJsonObjects mergejsonobjectsIconCompatParcelizer4 = getColorIntegerOrNull.IconCompatParcelizer(isAfterPunctuation.write);
        this.getDefaultViewModelCreationExtras = mergejsonobjectsIconCompatParcelizer4;
        mergeJsonObjects mergejsonobjectsIconCompatParcelizer5 = getColorIntegerOrNull.IconCompatParcelizer(SubcomposeAsyncImageKtExternalSyntheticLambda2.IconCompatParcelizer);
        this.MediaMetadataCompat = mergejsonobjectsIconCompatParcelizer5;
        hasNestedScrollingParent hasnestedscrollingparent2 = getstyleable_vector_drawable_group_rotation.AbstractClickableNodeonKeyEvent1;
        setPresentationView setpresentationview = getstyleable_vector_drawable_group_rotation.createnHHXs2Y;
        mergeJsonObjects mergejsonobjects7 = getstyleable_vector_drawable_group_rotation.ContentInViewNodelaunchAnimation21;
        hasnestedscrollingparent2.getClass();
        setpresentationview.getClass();
        mergejsonobjects7.getClass();
        subscribeToFeatureFlagsUpdateslambda0 subscribetofeatureflagsupdateslambda0 = new subscribeToFeatureFlagsUpdateslambda0(hasnestedscrollingparent2, setpresentationview, mergejsonobjects7, 0);
        this.ComponentActivity = subscribetofeatureflagsupdateslambda0;
        hasNestedScrollingParent hasnestedscrollingparent3 = getstyleable_vector_drawable_group_rotation.AbstractClickableNodeonKeyEvent1;
        setPresentationView setpresentationview2 = getstyleable_vector_drawable_group_rotation.createnHHXs2Y;
        mergeJsonObjects mergejsonobjects8 = getstyleable_vector_drawable_group_rotation.ContentInViewNodelaunchAnimation21;
        hasnestedscrollingparent3.getClass();
        setpresentationview2.getClass();
        mergejsonobjects8.getClass();
        mergeJsonObjects mergejsonobjectsIconCompatParcelizer6 = getColorIntegerOrNull.IconCompatParcelizer(new subscribeToFeatureFlagsUpdateslambda0(hasnestedscrollingparent3, setpresentationview2, mergejsonobjects8, 6));
        mergeJsonObjects mergejsonobjects9 = getstyleable_vector_drawable_group_rotation.Contentfoundation;
        mergejsonobjects9.getClass();
        r8lambda31xVc6yTCUqSOPjA0Lc9HsR6ufI r8lambda31xvc6ytcuqsopja0lc9hsr6ufi2 = new r8lambda31xVc6yTCUqSOPjA0Lc9HsR6ufI((r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ) mergejsonobjects9, subscribetofeatureflagsupdateslambda0, mergejsonobjectsIconCompatParcelizer6);
        this.getOnBackPressedDispatcher = r8lambda31xvc6ytcuqsopja0lc9hsr6ufi2;
        r8lambdazXN1qqQhLYzDDSf7dMTrYE1xu8I r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i2 = new r8lambdazXN1qqQhLYzDDSf7dMTrYE1xu8I(mergejsonobjectsIconCompatParcelizer4, mergejsonobjectsIconCompatParcelizer5, r8lambda31xvc6ytcuqsopja0lc9hsr6ufi2, i);
        this.PlaybackStateCompatCustomAction = r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i2;
        getDoubleOrNull getdoubleornull = getstyleable_vector_drawable_group_rotation.getSupportCheckMarkTintList;
        getdoubleornull.getClass();
        getDoubleOrNull getdoubleornullWrite = getDoubleOrNull.write(new drawTextd8rzKo(new isRound(getdoubleornull, 2)));
        this.r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8 = getdoubleornullWrite;
        getDoubleOrNull getdoubleornull2 = getstyleable_vector_drawable_group_rotation.isEmojiCompatEnabled;
        getdoubleornull2.getClass();
        getDoubleOrNull getdoubleornullWrite2 = getDoubleOrNull.write(new drawTextJFhB2K4(new isRound(getdoubleornull2, 1)));
        this.r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28 = getdoubleornullWrite2;
        r8lambdazpHrebeZ5dkHsk62AZggxj52Jpo r8lambdazphrebez5dkhsk62azggxj52jpo = getstyleable_vector_drawable_group_rotation.AppCompatDialogFragment;
        r8lambdazphrebez5dkhsk62azggxj52jpo.getClass();
        lineEndToVisibleEnd lineendtovisibleend = new lineEndToVisibleEnd(r8lambdazphrebez5dkhsk62azggxj52jpo);
        this.addObserverForBackInvokerlambda0 = lineendtovisibleend;
        getDoubleOrNull getdoubleornull3 = getstyleable_vector_drawable_group_rotation.getShowDividers;
        getDoubleOrNull getdoubleornull4 = getstyleable_vector_drawable_group_rotation.getEmojiTextViewHelper;
        getDoubleOrNull getdoubleornull5 = getstyleable_vector_drawable_group_rotation.getAutoSizeMinTextSize;
        getdoubleornull3.getClass();
        getdoubleornull4.getClass();
        getdoubleornull5.getClass();
        getDoubleOrNull getdoubleornullWrite3 = getDoubleOrNull.write(new TextPainter(new zzz(new r8lambdazpHrebeZ5dkHsk62AZggxj52Jpo(new ShouldShowHeatmap_Factory(getdoubleornull3, getdoubleornull4, getdoubleornull5, 7), 2))));
        this.r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0 = getdoubleornullWrite3;
        r8lambdawMZ4b3qLWvwGdmRM_auBcG267s r8lambdawmz4b3qlwvwgdmrm_aubcg267s = new r8lambdawMZ4b3qLWvwGdmRM_auBcG267s(23);
        this.addOnPictureInPictureUiStateChangedListener = r8lambdawmz4b3qlwvwgdmrm_aubcg267s;
        getDoubleOrNull getdoubleornull6 = getstyleable_vector_drawable_group_rotation.getDividerDrawable;
        getDoubleOrNull getdoubleornull7 = getstyleable_vector_drawable_group_rotation.setBaselineAligned;
        getDoubleOrNull getdoubleornull8 = getstyleable_vector_drawable_group_rotation.getGravity;
        getdoubleornull6.getClass();
        getdoubleornull7.getClass();
        getdoubleornull8.getClass();
        getDoubleOrNull getdoubleornullWrite4 = getDoubleOrNull.write(new drawTextTPWCCtM(new zzz(new r8lambdazpHrebeZ5dkHsk62AZggxj52Jpo(new ShouldShowHeatmap_Factory(getdoubleornull6, getdoubleornull7, getdoubleornull8, 8), 1))));
        r8lambdawMZ4b3qLWvwGdmRM_auBcG267s r8lambdawmz4b3qlwvwgdmrm_aubcg267s2 = new r8lambdawMZ4b3qLWvwGdmRM_auBcG267s(24);
        r8lambdawMZ4b3qLWvwGdmRM_auBcG267s r8lambdawmz4b3qlwvwgdmrm_aubcg267s3 = getstyleable_vector_drawable_group_rotation.setPadding;
        r8lambdawmz4b3qlwvwgdmrm_aubcg267s3.getClass();
        getdoubleornullWrite.getClass();
        getdoubleornullWrite2.getClass();
        getdoubleornullWrite3.getClass();
        setSyncPolicyOfflineStatuslambda1 setsyncpolicyofflinestatuslambda1 = new setSyncPolicyOfflineStatuslambda1(r8lambdawmz4b3qlwvwgdmrm_aubcg267s3, getdoubleornullWrite, getdoubleornullWrite2, lineendtovisibleend, getdoubleornullWrite3, r8lambdawmz4b3qlwvwgdmrm_aubcg267s, getdoubleornullWrite4, r8lambdawmz4b3qlwvwgdmrm_aubcg267s2);
        this.IconCompatParcelizer = setsyncpolicyofflinestatuslambda1;
        SingleProcessDataStore singleProcessDataStore = getstyleable_vector_drawable_group_rotation.removeOnUserLeaveHintListener;
        singleProcessDataStore.getClass();
        FontVariationSettingInt fontVariationSettingInt = new FontVariationSettingInt(singleProcessDataStore, 3);
        this.addOnContextAvailableListener = fontVariationSettingInt;
        ShouldShowHeatmap_Factory shouldShowHeatmap_Factory = getstyleable_vector_drawable_group_rotation.maxIntrinsicWidth;
        AbsSavedState absSavedState = getstyleable_vector_drawable_group_rotation.AndroidPrefetchScheduler;
        o1 o1Var = getstyleable_vector_drawable_group_rotation.addOnPictureInPictureUiStateChangedListener;
        mergeJsonObjects mergejsonobjects10 = getstyleable_vector_drawable_group_rotation.setItemInvoker;
        indexForKey indexforkey = getstyleable_vector_drawable_group_rotation.getAccessibilityClassName;
        com.data.injection.DataModule_ProvideSchedulerFactory dataModule_ProvideSchedulerFactory2 = getstyleable_vector_drawable_group_rotation.reset;
        shouldShowHeatmap_Factory.getClass();
        absSavedState.getClass();
        o1Var.getClass();
        mergejsonobjects10.getClass();
        indexforkey.getClass();
        dataModule_ProvideSchedulerFactory2.getClass();
        getDoubleOrNull getdoubleornullWrite5 = getDoubleOrNull.write(new StaticLayoutFactory35(new plusAH228Gc(shouldShowHeatmap_Factory, absSavedState, o1Var, mergejsonobjects10, indexforkey, dataModule_ProvideSchedulerFactory2)));
        r8lambdazpHrebeZ5dkHsk62AZggxj52Jpo r8lambdazphrebez5dkhsk62azggxj52jpo2 = getstyleable_vector_drawable_group_rotation.getRelatedFixedSize;
        AbsSavedState absSavedState2 = getstyleable_vector_drawable_group_rotation.AndroidPrefetchScheduler;
        r8lambdazphrebez5dkhsk62azggxj52jpo2.getClass();
        absSavedState2.getClass();
        insertBasedOnParentOffset insertbasedonparentoffset = new insertBasedOnParentOffset(fontVariationSettingInt, r8lambdazphrebez5dkhsk62azggxj52jpo2, absSavedState2, getdoubleornullWrite5);
        this.addOnNewIntentListener = insertbasedonparentoffset;
        SingleProcessDataStore singleProcessDataStore2 = getstyleable_vector_drawable_group_rotation.removeOnUserLeaveHintListener;
        singleProcessDataStore2.getClass();
        FontVariationSettingInt fontVariationSettingInt2 = new FontVariationSettingInt(singleProcessDataStore2, 4);
        this.addOnMultiWindowModeChangedListener = fontVariationSettingInt2;
        mergejsonobjectsIconCompatParcelizer4.getClass();
        FontVariationSettingInt fontVariationSettingInt3 = new FontVariationSettingInt(mergejsonobjectsIconCompatParcelizer4, 6);
        this.onMenuItemSelected = fontVariationSettingInt3;
        mergejsonobjectsIconCompatParcelizer4.getClass();
        accessgetRelayoutTimep accessgetrelayouttimep = new accessgetRelayoutTimep(r8lambdaqtoobhcnghe7ka6ntx9wq9cpayy, setsyncpolicyofflinestatuslambda1, insertbasedonparentoffset, fontVariationSettingInt2, fontVariationSettingInt3, new FontVariationSettingInt(mergejsonobjectsIconCompatParcelizer4, 5), new r8lambdazpHrebeZ5dkHsk62AZggxj52Jpo(new getStringBounds(1), 9));
        this.RemoteActionCompatParcelizer = accessgetrelayouttimep;
        performPushDeliveryFlushlambda0 performpushdeliveryflushlambda0 = new performPushDeliveryFlushlambda0(getstyleable_vector_drawable_group_rotation.NonTouchScrollingLogic, new r8lambdaqTOOBHcNghE7kA6ntx9WQ9cPAYY(mergejsonobjectsIconCompatParcelizer5, 6), new r8lambdaqTOOBHcNghE7kA6ntx9WQ9cPAYY(mergejsonobjectsIconCompatParcelizer5, 5), getstyleable_vector_drawable_group_rotation.createnHHXs2Y, 10);
        this.getDefaultViewModelProviderFactory = performpushdeliveryflushlambda0;
        newTransaction newtransaction = new newTransaction(mergejsonobjectsIconCompatParcelizer5, getstyleable_vector_drawable_group_rotation.TapGestureDetectorKtdetectTapAndPress21, 19);
        this.ParcelableVolumeInfo = newtransaction;
        int i2 = 20;
        newTransaction newtransaction2 = new newTransaction(mergejsonobjectsIconCompatParcelizer5, r8lambda31xvc6ytcuqsopja0lc9hsr6ufi2, i2);
        this.getActivityResultRegistry = newtransaction2;
        mergeJsonObjects mergejsonobjectsIconCompatParcelizer7 = getColorIntegerOrNull.IconCompatParcelizer(ImagePainter.read);
        this.read = mergejsonobjectsIconCompatParcelizer7;
        this.RatingCompat = getColorIntegerOrNull.IconCompatParcelizer(new getWriteEnabled(getstyleable_vector_drawable_group_rotation.AbstractClickableNodeonKeyEvent1, getstyleable_vector_drawable_group_rotation.getSensorToViewTransform, setusetemptrackingtableroom_runtime, r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i2, accessgetrelayouttimep, performpushdeliveryflushlambda0, getstyleable_vector_drawable_group_rotation.ScrollingLogicdoFlingAnimation2, getstyleable_vector_drawable_group_rotation.createnHHXs2Y, newtransaction, newtransaction2, getstyleable_vector_drawable_group_rotation.SurfaceProcessingQuirk, getstyleable_vector_drawable_group_rotation.VideoCapture, mergejsonobjectsIconCompatParcelizer7, 0));
        this.getLastCustomNonConfigurationInstance = new invokeqtAw6s(getstyleable_vector_drawable_group_rotation.AbstractClickableNodeonKeyEvent1, getstyleable_vector_drawable_group_rotation.ForEachGestureKtawaitEachGesture2, 7);
        mergeJsonObjects mergejsonobjects11 = getstyleable_vector_drawable_group_rotation.animateScrollToPage;
        mergeJsonObjects mergejsonobjects12 = getstyleable_vector_drawable_group_rotation.toClipEntry;
        mergejsonobjects11.getClass();
        mergejsonobjects12.getClass();
        this.onNewIntent = new r8lambdazpHrebeZ5dkHsk62AZggxj52Jpo(new setVerticalBias(mergejsonobjects11, mergejsonobjects12, 15), i2);
        this.onBackPressedInput_delegatelambda0 = getColorIntegerOrNull.IconCompatParcelizer(r8lambdae0GxSskrhFo5od0nTGVpQDD73Js.read);
        this.r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs = getDoubleOrNull.write(new r8lambdaUofYenlmWtpWX2ga1uehmSCK4A(new RouterLogger(getstyleable_vector_drawable_group_rotation.AnimatedContentTransitionScopeImplSizeModifierNode, 29, new newTransaction(getstyleable_vector_drawable_group_rotation.ImageUtil, getstyleable_vector_drawable_group_rotation.SurfaceUtil, 22))));
        this._init_lambda3 = getDoubleOrNull.write(new UtilsKt(new SharedResourcePool(new r8lambdaqTOOBHcNghE7kA6ntx9WQ9cPAYY(getstyleable_vector_drawable_group_rotation.DefaultLazyKey, 8))));
        setUseTempTrackingTableroom_runtime setusetemptrackingtableroom_runtime2 = getstyleable_vector_drawable_group_rotation.Camera2CameraImpl;
        r8lambdaqTOOBHcNghE7kA6ntx9WQ9cPAYY r8lambdaqtoobhcnghe7ka6ntx9wq9cpayy2 = getstyleable_vector_drawable_group_rotation.ImageUtil;
        setusetemptrackingtableroom_runtime2.getClass();
        r8lambdaqtoobhcnghe7ka6ntx9wq9cpayy2.getClass();
        this._init_lambda4 = getDoubleOrNull.write(new r8lambda5KZolJ_OR7ArWBprLRarbYqZEEA(new r8lambda6cOFqnFCSVnq6uI5jphSUi9HNJU(setusetemptrackingtableroom_runtime2, r8lambdaqtoobhcnghe7ka6ntx9wq9cpayy2)));
        int i3 = 12;
        r8lambdaqTOOBHcNghE7kA6ntx9WQ9cPAYY r8lambdaqtoobhcnghe7ka6ntx9wq9cpayy3 = new r8lambdaqTOOBHcNghE7kA6ntx9WQ9cPAYY(getstyleable_vector_drawable_group_rotation.Contentfoundation, i3);
        setUseTempTrackingTableroom_runtime setusetemptrackingtableroom_runtime3 = getstyleable_vector_drawable_group_rotation.Camera2CameraImpl;
        r8lambdaqTOOBHcNghE7kA6ntx9WQ9cPAYY r8lambdaqtoobhcnghe7ka6ntx9wq9cpayy4 = getstyleable_vector_drawable_group_rotation.ImageUtil;
        setusetemptrackingtableroom_runtime3.getClass();
        r8lambdaqtoobhcnghe7ka6ntx9wq9cpayy4.getClass();
        this._init_lambda1 = getDoubleOrNull.write(new r8lambda80jY8yCJXe50LHel8QKZq07he9s(new CombinedScopeView(setusetemptrackingtableroom_runtime3, r8lambdaqtoobhcnghe7ka6ntx9wq9cpayy4, r8lambdaqtoobhcnghe7ka6ntx9wq9cpayy3)));
        this.defaultViewModelProviderFactory_delegatelambda0 = new setUseTempTrackingTableroom_runtime(new q0(new getSharedElementTargetNames(getstyleable_vector_drawable_group_rotation.play, 19), new getSharedElementTargetNames(getstyleable_vector_drawable_group_rotation.setCollapseContentDescription, i2), 1), i3);
        getInvisibleToUserannotations getinvisibletouserannotations = getInvisibleToUserannotations.read(getstyleable_vector_drawable_group_rotation.AbstractClickableNodeonKeyEvent1);
        this.onConfigurationChanged = getinvisibletouserannotations;
        PreferenceGroupAdapter preferenceGroupAdapterRemoteActionCompatParcelizer = PreferenceGroupAdapter.RemoteActionCompatParcelizer(getstyleable_vector_drawable_group_rotation.getActionBarHideOffset, getstyleable_vector_drawable_group_rotation.Contentfoundation);
        this.onCreatePanelMenu = preferenceGroupAdapterRemoteActionCompatParcelizer;
        isHiddenannotations ishiddenannotationsSerializer = isHiddenannotations.serializer(getinvisibletouserannotations, preferenceGroupAdapterRemoteActionCompatParcelizer, getInvisibleToUserannotations.write(getstyleable_vector_drawable_group_rotation.setItemInvoker), getstyleable_vector_drawable_group_rotation.createnHHXs2Y);
        publishErrorlambda1 publisherrorlambda2 = getstyleable_vector_drawable_group_rotation.FocusMeteringControl;
        publisherrorlambda2.getClass();
        this.r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4 = getDoubleOrNull.write(new getCollectionItemInfo(new InitializeAppStartupItemsImpl(publisherrorlambda2, ishiddenannotationsSerializer)));
        mergeJsonObjects mergejsonobjects13 = getstyleable_vector_drawable_group_rotation.Contentfoundation;
        mergejsonobjects13.getClass();
        getScrollRange getscrollrange2 = new getScrollRange(mergejsonobjects13, 14);
        this.createFullyDrawnExecutor = getscrollrange2;
        mergeJsonObjects mergejsonobjects14 = getstyleable_vector_drawable_group_rotation.setItemInvoker;
        mergejsonobjects14.getClass();
        getScrollRange getscrollrange3 = new getScrollRange(mergejsonobjects14, 15);
        getScrollRange getscrollrange4 = getstyleable_vector_drawable_group_rotation.getId;
        r8lambdazXN1qqQhLYzDDSf7dMTrYE1xu8I r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i3 = getstyleable_vector_drawable_group_rotation.getTabContainer;
        getscrollrange4.getClass();
        r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i3.getClass();
        this.r8lambda7IJBVrN0sHyidCAZufWEJFc7yY = new insertBasedOnParentOffset(getscrollrange4, getscrollrange2, r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i3, getscrollrange3);
        getContentDataType getcontentdatatype = new getContentDataType(getstyleable_vector_drawable_group_rotation.defaultViewModelProviderFactory_delegatelambda0, 22);
        this.getSavedStateRegistryControllerannotations = getcontentdatatype;
        mergeJsonObjects mergejsonobjects15 = getstyleable_vector_drawable_group_rotation.GestureCancellationException;
        setPresentationView setpresentationview3 = getstyleable_vector_drawable_group_rotation.createnHHXs2Y;
        mergejsonobjects15.getClass();
        setpresentationview3.getClass();
        setVerticalBias setverticalbias = new setVerticalBias((r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ) mergejsonobjects15, setpresentationview3, 26);
        this.menuHostHelperlambda0 = setverticalbias;
        mergeJsonObjects mergejsonobjects16 = getstyleable_vector_drawable_group_rotation.GestureCancellationException;
        setPresentationView setpresentationview4 = getstyleable_vector_drawable_group_rotation.createnHHXs2Y;
        mergejsonobjects16.getClass();
        setpresentationview4.getClass();
        setVerticalBias setverticalbias2 = new setVerticalBias((r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ) mergejsonobjects16, setpresentationview4, 28);
        mergeJsonObjects mergejsonobjects17 = getstyleable_vector_drawable_group_rotation.setCompoundDrawablesRelative;
        SimpleExecutableQuery simpleExecutableQuery = getstyleable_vector_drawable_group_rotation.FocusMeteringControl2;
        mergeJsonObjects mergejsonobjects18 = getstyleable_vector_drawable_group_rotation.Contentfoundation;
        mergeJsonObjects mergejsonobjects19 = getstyleable_vector_drawable_group_rotation.toClipEntry;
        mergejsonobjects17.getClass();
        simpleExecutableQuery.getClass();
        mergejsonobjects18.getClass();
        mergejsonobjects19.getClass();
        this.onBackPressed = new setUseTempTrackingTableroom_runtime(new accessgetRelayoutTimep(mergejsonobjects17, simpleExecutableQuery, mergejsonobjects18, getcontentdatatype, mergejsonobjects19, setverticalbias, setverticalbias2), 7);
        this.r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg = getDoubleOrNull.write(new toClickableSpan(new getInitial(getstyleable_vector_drawable_group_rotation.removeOnUserLeaveHintListener, getstyleable_vector_drawable_group_rotation.removeOnContextAvailableListener, getstyleable_vector_drawable_group_rotation.setScreenFlashWindow, getstyleable_vector_drawable_group_rotation.Contentfoundation)));
        r8lambdazXN1qqQhLYzDDSf7dMTrYE1xu8I r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i4 = getstyleable_vector_drawable_group_rotation.BiometricFragmentExternalSyntheticLambda1;
        setPresentationView setpresentationview5 = getstyleable_vector_drawable_group_rotation.createnHHXs2Y;
        newTransaction newtransaction3 = new newTransaction(r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i4, setpresentationview5, 1);
        this.addMenuProvider = newtransaction3;
        this.ResultReceiver = new insertBasedOnParentOffset(getstyleable_vector_drawable_group_rotation.AndroidCursorHandle_androidKt, getstyleable_vector_drawable_group_rotation.setHideOnContentScrollEnabled, newtransaction3, getstyleable_vector_drawable_group_rotation.Contentfoundation, 16);
        mergeJsonObjects mergejsonobjects20 = getstyleable_vector_drawable_group_rotation.isEnabled;
        invokeqtAw6s invokeqtaw6s2 = new invokeqtAw6s(mergejsonobjects20, getstyleable_vector_drawable_group_rotation.sizeVpY3zN4, 29);
        this.addObserverForBackInvoker = invokeqtaw6s2;
        fastMergej5T8yCg fastmergej5t8ycg = new fastMergej5T8yCg(getstyleable_vector_drawable_group_rotation.AbstractClickableNodeonKeyEvent1, 15);
        mergeJsonObjects mergejsonobjects21 = getstyleable_vector_drawable_group_rotation.jumpByPagesOffset;
        r8lambda6UOvp7lvejigbq5knKoP8A0vEiw r8lambda6uovp7lvejigbq5knkop8a0veiw = new r8lambda6UOvp7lvejigbq5knKoP8A0vEiw(mergejsonobjects21, fastmergej5t8ycg, 18);
        insertBasedOnParentOffset insertbasedonparentoffset2 = new insertBasedOnParentOffset(mergejsonobjects21, getstyleable_vector_drawable_group_rotation.PressGestureScopeImpl, new getEditableText(i2, new fastMergej5T8yCg(getstyleable_vector_drawable_group_rotation.TextFieldSizeElement, 6)), getstyleable_vector_drawable_group_rotation.addCloseableactivity, 7);
        int i4 = 17;
        r8lambda6UOvp7lvejigbq5knKoP8A0vEiw r8lambda6uovp7lvejigbq5knkop8a0veiw2 = new r8lambda6UOvp7lvejigbq5knKoP8A0vEiw(r8lambda6uovp7lvejigbq5knkop8a0veiw, insertbasedonparentoffset2, i4);
        this.ensureViewModelStore = r8lambda6uovp7lvejigbq5knkop8a0veiw2;
        fastMergej5T8yCg fastmergej5t8ycg2 = new fastMergej5T8yCg(getstyleable_vector_drawable_group_rotation.tryAwaitRelease, i4);
        this.onCreate = fastmergej5t8ycg2;
        this.r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM = getDoubleOrNull.write(new getTextDirectionmmuk1to(new MetricsBatchProcessor(getstyleable_vector_drawable_group_rotation.draw, getstyleable_vector_drawable_group_rotation.GlowOverscrollNode, mergejsonobjects20, getstyleable_vector_drawable_group_rotation.getTitleMarginEnd, getstyleable_vector_drawable_group_rotation.CameraUpdateException, new setPaddingBottom(invokeqtaw6s2, r8lambda6uovp7lvejigbq5knkop8a0veiw2, fastmergej5t8ycg2, getstyleable_vector_drawable_group_rotation.getOnBackPressedDispatcher, setpresentationview5, 4))));
        mergeJsonObjects mergejsonobjects22 = getstyleable_vector_drawable_group_rotation.TextFieldSelectionManagercontextMenuAreaModifier3;
        mergeJsonObjects mergejsonobjects23 = getstyleable_vector_drawable_group_rotation.Contentfoundation;
        this.onPictureInPictureModeChanged = new elambda0(mergejsonobjects22, mergejsonobjects23, 11);
        getEditableText geteditabletext = getstyleable_vector_drawable_group_rotation.TextFieldSizeElement;
        mergeJsonObjects mergejsonobjects24 = getstyleable_vector_drawable_group_rotation.PressGestureScopeImpl;
        this.MediaSessionCompatResultReceiverWrapper = new setSyncPolicyOfflineStatuslambda1(new r8lambda6UOvp7lvejigbq5knKoP8A0vEiw(new accessgetTextBottomcp(geteditabletext, mergejsonobjects24, 1), r8lambda6uovp7lvejigbq5knkop8a0veiw2, i2), getstyleable_vector_drawable_group_rotation.createnHHXs2Y, getstyleable_vector_drawable_group_rotation.CameraUpdateException, getstyleable_vector_drawable_group_rotation.getTitleMarginEnd, invokeqtaw6s2, fastmergej5t8ycg2, getstyleable_vector_drawable_group_rotation.getOnBackPressedDispatcher, new invokeqtAw6s(mergejsonobjects24, getstyleable_vector_drawable_group_rotation.addCloseableactivity, 28));
        r8lambdaZcilDVoiQYR1yQsOxhHduSfdjyw r8lambdazcildvoiqyr1yqsoxhhdusfdjyw = new r8lambdaZcilDVoiQYR1yQsOxhHduSfdjyw(getstyleable_vector_drawable_group_rotation.setImplementationMode, getstyleable_vector_drawable_group_rotation.setHideOnContentScrollEnabled, getstyleable_vector_drawable_group_rotation.AndroidCursorHandle_androidKt, getstyleable_vector_drawable_group_rotation.setScreenFlashWindow, mergejsonobjects23, 7);
        this.PlaybackStateCompat = r8lambdazcildvoiqyr1yqsoxhhdusfdjyw;
        accessgetTextBottomcp accessgettextbottomcp = getstyleable_vector_drawable_group_rotation.setOnInflateListener;
        accessgettextbottomcp.getClass();
        LocaleListHelperMethods localeListHelperMethods = new LocaleListHelperMethods(accessgettextbottomcp);
        mergeJsonObjects mergejsonobjects25 = getstyleable_vector_drawable_group_rotation.AndroidCursorHandle_androidKt;
        SemanticsPropertiesLinkTestMarker1 semanticsPropertiesLinkTestMarker1 = getstyleable_vector_drawable_group_rotation.ImageCaptureFailedForSpecificCombinationQuirk;
        AbsSavedState absSavedState3 = getstyleable_vector_drawable_group_rotation.ExtraSupportedResolutionQuirk;
        mergeJsonObjects mergejsonobjects26 = getstyleable_vector_drawable_group_rotation.setScreenFlashWindow;
        mergeJsonObjects mergejsonobjects27 = getstyleable_vector_drawable_group_rotation.setImplementationMode;
        ShouldShowHeatmap_Factory shouldShowHeatmap_Factory2 = getstyleable_vector_drawable_group_rotation.getContentInsetStartWithNavigation;
        mergejsonobjects25.getClass();
        semanticsPropertiesLinkTestMarker1.getClass();
        absSavedState3.getClass();
        mergejsonobjects26.getClass();
        mergejsonobjects27.getClass();
        shouldShowHeatmap_Factory2.getClass();
        accessgetRelayoutTimep accessgetrelayouttimep2 = new accessgetRelayoutTimep(mergejsonobjects25, semanticsPropertiesLinkTestMarker1, absSavedState3, mergejsonobjects26, localeListHelperMethods, mergejsonobjects27, shouldShowHeatmap_Factory2);
        mergeJsonObjects mergejsonobjects28 = getstyleable_vector_drawable_group_rotation.setImplementationMode;
        mergejsonobjects28.getClass();
        onMeasureChild onmeasurechild = new onMeasureChild(mergejsonobjects28, accessgetrelayouttimep2);
        this.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus = onmeasurechild;
        mergeJsonObjects mergejsonobjects29 = getstyleable_vector_drawable_group_rotation.AndroidCursorHandle_androidKt;
        mergeJsonObjects mergejsonobjects30 = getstyleable_vector_drawable_group_rotation.setScreenFlashWindow;
        mergejsonobjects29.getClass();
        mergejsonobjects30.getClass();
        setVerticalBias setverticalbias3 = new setVerticalBias(mergejsonobjects29, mergejsonobjects30, 8);
        mergeJsonObjects mergejsonobjects31 = getstyleable_vector_drawable_group_rotation.setScreenFlashWindow;
        AbsSavedState absSavedState4 = getstyleable_vector_drawable_group_rotation.ExtraSupportedResolutionQuirk;
        mergeJsonObjects mergejsonobjects32 = getstyleable_vector_drawable_group_rotation.setImplementationMode;
        mergejsonobjects31.getClass();
        absSavedState4.getClass();
        mergejsonobjects32.getClass();
        insertBasedOnParentOffset insertbasedonparentoffset3 = new insertBasedOnParentOffset(mergejsonobjects31, setverticalbias3, absSavedState4, mergejsonobjects32);
        this.onBackPressedDispatcher_delegatelambda00 = insertbasedonparentoffset3;
        this.r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss = getDoubleOrNull.write(new TypefaceDirtyTrackerLinkedList(new ImageLoader$Builder(r8lambdazcildvoiqyr1yqsoxhhdusfdjyw, onmeasurechild, insertbasedonparentoffset3, getDoubleOrNull.write(new mergelambda0()))));
        this.r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw = getDoubleOrNull.write(new getEnterAnim(new AnnotationRangeListSaverlambda1(getstyleable_vector_drawable_group_rotation.CaptureRequestOptionsBuilderExternalSyntheticLambda0, getstyleable_vector_drawable_group_rotation.CameraClosedException)));
        this.getFullyDrawnReporter = getColorIntegerOrNull.IconCompatParcelizer(new r8lambdaqTOOBHcNghE7kA6ntx9WQ9cPAYY(mergejsonobjectsIconCompatParcelizer7, 4));
        com.data.injection.DataModule_ProvideSchedulerFactory dataModule_ProvideSchedulerFactory3 = getstyleable_vector_drawable_group_rotation.TextMeasurePolicy;
        dataModule_ProvideSchedulerFactory3.getClass();
        lineEndToVisibleEnd lineendtovisibleend2 = new lineEndToVisibleEnd(dataModule_ProvideSchedulerFactory3);
        setPresentationView setpresentationview6 = getstyleable_vector_drawable_group_rotation.MouseWheelScrollingLogicKt;
        setpresentationview6.getClass();
        this._init_lambda2 = getPrettyPrintedString.RemoteActionCompatParcelizer(new r8lambda6UOvp7lvejigbq5knKoP8A0vEiw(lineendtovisibleend2, setpresentationview6));
        this.r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ = getDoubleOrNull.write(new performImeActiondefault(new password(getstyleable_vector_drawable_group_rotation.PreviewBlackScreenQuirk)));
        LayoutCompat layoutCompat = new LayoutCompat(getstyleable_vector_drawable_group_rotation.Contentfoundation, 26);
        this.accessensureViewModelStore = layoutCompat;
        mergeJsonObjects mergejsonobjects33 = getstyleable_vector_drawable_group_rotation.AndroidCursorHandle_androidKt;
        onMeasureChild onmeasurechild2 = new onMeasureChild(layoutCompat, mergejsonobjects33, 13);
        this.getOnBackPressedInput = onmeasurechild2;
        int i5 = 2;
        r8lambdazXN1qqQhLYzDDSf7dMTrYE1xu8I r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i5 = new r8lambdazXN1qqQhLYzDDSf7dMTrYE1xu8I(layoutCompat, new LayoutCompat(mergejsonobjects33, 27), new SimpleExecutableQuery(newtransaction3, i5), i5);
        this.addOnUserLeaveHintListener = r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i5;
        mergeJsonObjects mergejsonobjectsIconCompatParcelizer8 = getColorIntegerOrNull.IconCompatParcelizer(new LayoutCompat(getstyleable_vector_drawable_group_rotation.AbstractClickableNodeonKeyEvent1, 24));
        this.MediaBrowserCompatMediaItem = mergejsonobjectsIconCompatParcelizer8;
        mergeJsonObjects mergejsonobjectsIconCompatParcelizer9 = getColorIntegerOrNull.IconCompatParcelizer(new SharedPreferencesMigration(getstyleable_vector_drawable_group_rotation.AbstractClickableNodeonKeyEvent1, getstyleable_vector_drawable_group_rotation.Preview3AThreadCrashQuirk, getstyleable_vector_drawable_group_rotation.CameraValidatorCameraIdListIncorrectException, 11));
        this.addOnConfigurationChangedListener = mergejsonobjectsIconCompatParcelizer9;
        this.serializer = getColorIntegerOrNull.IconCompatParcelizer(new supportPostponeEnterTransition(getstyleable_vector_drawable_group_rotation.Contentfoundation, onmeasurechild2, r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i5, mergejsonobjectsIconCompatParcelizer8, mergejsonobjectsIconCompatParcelizer3, layoutCompat, mergejsonobjectsIconCompatParcelizer9, getColorIntegerOrNull.IconCompatParcelizer(new accessgetTextBottomcp(getstyleable_vector_drawable_group_rotation.CameraValidatorCameraIdListIncorrectException, getstyleable_vector_drawable_group_rotation.Preview3AThreadCrashQuirk, 9)), getstyleable_vector_drawable_group_rotation.EnterExitTransitionKtshrinkHorizontally2, getstyleable_vector_drawable_group_rotation.getFullyDrawnReporter, getstyleable_vector_drawable_group_rotation.createnHHXs2Y, 4));
        SingleProcessDataStore singleProcessDataStore3 = getstyleable_vector_drawable_group_rotation.removeOnUserLeaveHintListener;
        publishErrorlambda1 publisherrorlambda3 = getstyleable_vector_drawable_group_rotation.FocusMeteringControl;
        singleProcessDataStore3.getClass();
        publisherrorlambda3.getClass();
        transformCanvas transformcanvas = new transformCanvas(singleProcessDataStore3, publisherrorlambda3);
        this.fullyDrawnReporter_delegatelambda0 = transformcanvas;
        r8lambdaqTOOBHcNghE7kA6ntx9WQ9cPAYY r8lambdaqtoobhcnghe7ka6ntx9wq9cpayy5 = getstyleable_vector_drawable_group_rotation.ContextMenuColumn;
        mergeJsonObjects mergejsonobjects34 = getstyleable_vector_drawable_group_rotation.Contentfoundation;
        r8lambdaqtoobhcnghe7ka6ntx9wq9cpayy5.getClass();
        mergejsonobjects34.getClass();
        transformCanvas transformcanvas2 = new transformCanvas(r8lambdaqtoobhcnghe7ka6ntx9wq9cpayy5, mergejsonobjects34);
        this.fullyDrawnReporter_delegatelambda00 = transformcanvas2;
        SingleProcessDataStore singleProcessDataStore4 = new SingleProcessDataStore(getstyleable_vector_drawable_group_rotation.width3ABfNKs, 19);
        this.MediaSessionCompatToken = singleProcessDataStore4;
        mergeJsonObjects mergejsonobjects35 = getstyleable_vector_drawable_group_rotation.setItemInvoker;
        mergejsonobjects35.getClass();
        FontVariationSettingInt fontVariationSettingInt4 = new FontVariationSettingInt(mergejsonobjects35, 18);
        this.addContentView = fontVariationSettingInt4;
        SingleProcessDataStore singleProcessDataStore5 = getstyleable_vector_drawable_group_rotation.removeOnUserLeaveHintListener;
        singleProcessDataStore5.getClass();
        FontVariationSettingInt fontVariationSettingInt5 = new FontVariationSettingInt(singleProcessDataStore5, 19);
        this.addOnTrimMemoryListener = fontVariationSettingInt5;
        mergeJsonObjects mergejsonobjects36 = getstyleable_vector_drawable_group_rotation.TapGestureDetectorKtdetectTapAndPress21;
        mergeJsonObjects mergejsonobjects37 = getstyleable_vector_drawable_group_rotation.toClipEntry;
        mergejsonobjects36.getClass();
        mergejsonobjects37.getClass();
        transformCanvas transformcanvas3 = new transformCanvas(mergejsonobjects36, mergejsonobjects37, 21);
        mergeJsonObjects mergejsonobjects38 = getstyleable_vector_drawable_group_rotation.ImageCaptureException;
        mergejsonobjects38.getClass();
        SemanticsPropertiesLinkTestMarker1 semanticsPropertiesLinkTestMarker2 = new SemanticsPropertiesLinkTestMarker1(fontVariationSettingInt4, transformcanvas3, mergejsonobjects38);
        getDoubleOrNull getdoubleornull9 = getstyleable_vector_drawable_group_rotation.access1101;
        getDoubleOrNull getdoubleornull10 = getstyleable_vector_drawable_group_rotation.AppCompatSpinnerSavedState1;
        mergeJsonObjects mergejsonobjects39 = getstyleable_vector_drawable_group_rotation.ContentInViewNodelaunchAnimation21;
        getdoubleornull9.getClass();
        getdoubleornull10.getClass();
        mergejsonobjects39.getClass();
        this.onBackPressedDispatcher_delegatelambda0 = getColorIntegerOrNull.IconCompatParcelizer(new indexForKey(transformcanvas, getdoubleornull9, getdoubleornull10, transformcanvas2, singleProcessDataStore4, fontVariationSettingInt4, fontVariationSettingInt5, semanticsPropertiesLinkTestMarker2, mergejsonobjects39));
    }

    public final getPreviousUptimeMillis IconCompatParcelizer() {
        int i = 2 % 2;
        getSTYLEABLE_VECTOR_DRAWABLE_GROUP_ROTATION getstyleable_vector_drawable_group_rotation = this.write;
        getPreviousUptimeMillis getpreviousuptimemillis = new getPreviousUptimeMillis((androidx.work.impl.WorkManagerImpl) getstyleable_vector_drawable_group_rotation.tryAwaitRelease.write(), new handleThirdPartySharingCallbackI((decode) getstyleable_vector_drawable_group_rotation.setItemInvoker.write(), new getLiveRegiondelegate((AuthRepository) getstyleable_vector_drawable_group_rotation.defaultViewModelProviderFactory_delegatelambda0.write())), getstyleable_vector_drawable_group_rotation.enterPictureInPictureMode(), (getContentViewGroupParentLayout) getstyleable_vector_drawable_group_rotation.ContentInViewNodelaunchAnimation21.write());
        int i2 = onPanelClosed + 51;
        onRequestPermissionsResult = i2 % androidx.compose.ui.graphics.Fields.SpotShadowColor;
        int i3 = i2 % 2;
        return getpreviousuptimemillis;
    }

    public final colorResource RemoteActionCompatParcelizer() {
        int i = 2 % 2;
        getSTYLEABLE_VECTOR_DRAWABLE_GROUP_ROTATION getstyleable_vector_drawable_group_rotation = this.write;
        getContentViewGroupParentLayout getcontentviewgroupparentlayout = (getContentViewGroupParentLayout) getstyleable_vector_drawable_group_rotation.ContentInViewNodelaunchAnimation21.write();
        access800 access800Var = new access800((decode) getstyleable_vector_drawable_group_rotation.setItemInvoker.write());
        Lazy lazySerializer = getColorIntegerOrNull.serializer((mergeJsonObjects) getstyleable_vector_drawable_group_rotation.getImageFormat);
        IsUserAuthenticatedWrapper isUserAuthenticatedWrapperAddOnUserLeaveHintListener = getstyleable_vector_drawable_group_rotation.addOnUserLeaveHintListener();
        androidx.work.impl.WorkManagerImpl workManagerImpl = (androidx.work.impl.WorkManagerImpl) getstyleable_vector_drawable_group_rotation.tryAwaitRelease.write();
        CourierApplication courierApplication = getstyleable_vector_drawable_group_rotation.r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs;
        colorResource colorresource = new colorResource(getcontentviewgroupparentlayout, new RegisterPushNotificationUseCaseImpl(access800Var, lazySerializer, isUserAuthenticatedWrapperAddOnUserLeaveHintListener, workManagerImpl, new access1200(courierApplication, getColorIntegerOrNull.serializer((mergeJsonObjects) getstyleable_vector_drawable_group_rotation.ScrollableNestedScrollConnection), getColorIntegerOrNull.serializer((mergeJsonObjects) getstyleable_vector_drawable_group_rotation.ScrollableNodeonKeyEvent1)), new NetworkBody(new r8lambdaxXjW7P_AvkpTNfi9yKZ8umnanKU(getColorIntegerOrNull.serializer((mergeJsonObjects) getstyleable_vector_drawable_group_rotation.animateScrollBy), getColorIntegerOrNull.serializer((mergeJsonObjects) getstyleable_vector_drawable_group_rotation.onPostFlingRZ2iAVY), getColorIntegerOrNull.serializer((mergeJsonObjects) getstyleable_vector_drawable_group_rotation.awaitFirstDown)), 2, new access1200(courierApplication, getColorIntegerOrNull.serializer((mergeJsonObjects) getstyleable_vector_drawable_group_rotation.ScrollableNestedScrollConnection), getColorIntegerOrNull.serializer((mergeJsonObjects) getstyleable_vector_drawable_group_rotation.ScrollableNodeonKeyEvent1)))));
        int i2 = onRequestPermissionsResult + 19;
        onPanelClosed = i2 % androidx.compose.ui.graphics.Fields.SpotShadowColor;
        int i3 = i2 % 2;
        return colorresource;
    }
}
