package o;

import java.util.List;

/* JADX INFO: loaded from: classes4.dex */
public abstract class getTargetFragment {
    private static int IconCompatParcelizer = 0;
    public static final List read = androidx.sqlite.SQLite.read("HELPCENTER_INIT_WILL_START", "HELPCENTER_INIT_WILL_START_ACK", "HELPCENTER_INIT_STARTED", "HELPCENTER_INIT_STARTED_ACK", "HELPCENTER_INIT_IS_DONE", "HELPCENTER_INIT_IS_DONE_ACK", "HOST_IS_READY", "HOST_IS_READY_ACK", "HELPCENTER_ASKS_FOR_SHUTDOWN", "HELPCENTER_ASKS_FOR_SHUTDOWN_ACK", "HELPCENTER_ASKS_FOR_AUTO_CHAT_PARAMS", "HELPCENTER_ASKS_FOR_AUTO_CHAT_PARAMS_ACK", "HOST_SENDS_AUTO_CHAT_PARAMS", "HOST_SENDS_AUTO_CHAT_PARAMS_ACK", "HOST_ASKS_FOR_BACK_NAVIGATION", "HELPCENTER_CHAT_STARTED", "HELPCENTER_CHAT_STARTED_ACK", "HELPCENTER_INIT_FAILED", "HELPCENTER_WILL_HANDLE_BACK_NAVIGATION", "HELPCENTER_WILL_NOT_HANDLE_BACK_NAVIGATION", "HELPCENTER_ENCOUNTERED_ERROR", "HOST_ENCOUNTERED_ERROR", "HOST_ENCOUNTERED_ERROR_ACK", "HELPCENTER_CHAT_ENDED", "HELPCENTER_ASKS_FOR_FILE_DOWNLOAD", "HELPCENTER_ASKS_FOR_FILE_DOWNLOAD_ACK", "HOST_FILE_DOWNLOAD_SUCCESS", "HOST_FILE_DOWNLOAD_SUCCESS_ACK", "HOST_FILE_DOWNLOAD_FAIL", "HOST_FILE_DOWNLOAD_FAIL_ACK", "CLIENT_CRITICAL_CONTENT_RENDERED", "HELPCENTER_NOTIFIES_IMAGE_UPLOAD_PERMISSIONS", "HOST_LOADING_PERFORMANCE_MEASUREMENT");
    private static int serializer = 1;

    static {
        int i = serializer + 117;
        IconCompatParcelizer = i % androidx.compose.ui.graphics.Fields.SpotShadowColor;
        int i2 = i % 2;
    }
}
