package o;

import com.huawei.hms.location.ActivityIdentificationData;
import com.huawei.location.gwi.util.GwiErrorCode;
import org.tukaani.xz.delta.DeltaDecoder;

/* JADX INFO: loaded from: classes2.dex */
public final class getTextGeometricTransform {
    public static final getTextGeometricTransform[] read;
    public final DeltaDecoder[] IconCompatParcelizer;
    public final int RemoteActionCompatParcelizer;
    public final int serializer;

    public getTextGeometricTransform(int i, DeltaDecoder... deltaDecoderArr) {
        this.serializer = i;
        this.IconCompatParcelizer = deltaDecoderArr;
        DeltaDecoder deltaDecoder = deltaDecoderArr[0];
        int i2 = deltaDecoder.write;
        int i3 = 0;
        for (InfiniteAnimationPolicyDefaultImpls infiniteAnimationPolicyDefaultImpls : (InfiniteAnimationPolicyDefaultImpls[]) deltaDecoder.serializer) {
            i3 += (infiniteAnimationPolicyDefaultImpls.RemoteActionCompatParcelizer + i2) * infiniteAnimationPolicyDefaultImpls.serializer;
        }
        this.RemoteActionCompatParcelizer = i3;
    }

    public final String toString() {
        return String.valueOf(this.serializer);
    }

    public static getTextGeometricTransform write(int i) {
        if (i >= 1 && i <= 40) {
            return read[i - 1];
        }
        DrawableTransformation.write();
        return null;
    }

    static {
        int i = 1;
        int i2 = 10;
        int i3 = 16;
        int i4 = 13;
        int i5 = 17;
        int i6 = 4;
        int i7 = 2;
        int i8 = 3;
        getTextGeometricTransform gettextgeometrictransform = new getTextGeometricTransform(1, new DeltaDecoder(7, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i, 19)}, i2), new DeltaDecoder(i2, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i, i3)}, i2), new DeltaDecoder(i4, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i, i4)}, i2), new DeltaDecoder(i5, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i, 9)}, i2));
        int i9 = 28;
        int i10 = 22;
        getTextGeometricTransform gettextgeometrictransform2 = new getTextGeometricTransform(2, new DeltaDecoder(i2, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i, 34)}, i2), new DeltaDecoder(i3, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i, i9)}, i2), new DeltaDecoder(i10, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i, i10)}, i2), new DeltaDecoder(i9, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i, i3)}, i2));
        int i11 = 26;
        getTextGeometricTransform gettextgeometrictransform3 = new getTextGeometricTransform(3, new DeltaDecoder(15, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i, 55)}, i2), new DeltaDecoder(i11, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i, 44)}, i2), new DeltaDecoder(18, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, i5)}, i2), new DeltaDecoder(i10, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, i4)}, i2));
        int i12 = 24;
        getTextGeometricTransform gettextgeometrictransform4 = new getTextGeometricTransform(4, new DeltaDecoder(20, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i, 80)}, i2), new DeltaDecoder(18, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, 32)}, i2), new DeltaDecoder(i11, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, i12)}, i2), new DeltaDecoder(16, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 9)}, i2));
        getTextGeometricTransform gettextgeometrictransform5 = new getTextGeometricTransform(5, new DeltaDecoder(i11, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i, ActivityIdentificationData.RUNNING)}, i2), new DeltaDecoder(i12, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, 43)}, i2), new DeltaDecoder(18, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, 15), new InfiniteAnimationPolicyDefaultImpls(i7, 16)}, i2), new DeltaDecoder(22, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, 11), new InfiniteAnimationPolicyDefaultImpls(i7, 12)}, i2));
        getTextGeometricTransform gettextgeometrictransform6 = new getTextGeometricTransform(6, new DeltaDecoder(18, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, 68)}, i2), new DeltaDecoder(16, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 27)}, i2), new DeltaDecoder(i12, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 19)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 15)}, i2));
        int i13 = 14;
        getTextGeometricTransform gettextgeometrictransform7 = new getTextGeometricTransform(7, new DeltaDecoder(20, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, 78)}, i2), new DeltaDecoder(18, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 31)}, i2), new DeltaDecoder(18, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, i13), new InfiniteAnimationPolicyDefaultImpls(i6, 15)}, i2), new DeltaDecoder(i11, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 13), new InfiniteAnimationPolicyDefaultImpls(i, i13)}, i2));
        int i14 = 22;
        getTextGeometricTransform gettextgeometrictransform8 = new getTextGeometricTransform(8, new DeltaDecoder(i12, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, 97)}, i2), new DeltaDecoder(i14, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, 38), new InfiniteAnimationPolicyDefaultImpls(i7, 39)}, i2), new DeltaDecoder(i14, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 18), new InfiniteAnimationPolicyDefaultImpls(i7, 19)}, i2), new DeltaDecoder(i11, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, i13), new InfiniteAnimationPolicyDefaultImpls(i7, 15)}, i2));
        int i15 = 30;
        getTextGeometricTransform gettextgeometrictransform9 = new getTextGeometricTransform(9, new DeltaDecoder(i15, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, 116)}, i2), new DeltaDecoder(22, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i8, 36), new InfiniteAnimationPolicyDefaultImpls(i7, 37)}, i2), new DeltaDecoder(20, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 16), new InfiniteAnimationPolicyDefaultImpls(i6, 17)}, i2), new DeltaDecoder(24, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 12), new InfiniteAnimationPolicyDefaultImpls(i6, 13)}, i2));
        getTextGeometricTransform gettextgeometrictransform10 = new getTextGeometricTransform(10, new DeltaDecoder(18, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, 68), new InfiniteAnimationPolicyDefaultImpls(i7, 69)}, i2), new DeltaDecoder(i11, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 43), new InfiniteAnimationPolicyDefaultImpls(i, 44)}, i2), new DeltaDecoder(24, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(6, 19), new InfiniteAnimationPolicyDefaultImpls(i7, 20)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(6, 15), new InfiniteAnimationPolicyDefaultImpls(i7, 16)}, i2));
        getTextGeometricTransform gettextgeometrictransform11 = new getTextGeometricTransform(11, new DeltaDecoder(20, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 81)}, i2), new DeltaDecoder(i15, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i, 50), new InfiniteAnimationPolicyDefaultImpls(i6, 51)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 22), new InfiniteAnimationPolicyDefaultImpls(i6, 23)}, i2), new DeltaDecoder(24, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i8, 12), new InfiniteAnimationPolicyDefaultImpls(8, 13)}, i2));
        getTextGeometricTransform gettextgeometrictransform12 = new getTextGeometricTransform(12, new DeltaDecoder(24, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, 92), new InfiniteAnimationPolicyDefaultImpls(i7, 93)}, i2), new DeltaDecoder(22, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(6, 36), new InfiniteAnimationPolicyDefaultImpls(i7, 37)}, i2), new DeltaDecoder(i11, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 20), new InfiniteAnimationPolicyDefaultImpls(6, 21)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(7, 14), new InfiniteAnimationPolicyDefaultImpls(i6, 15)}, i2));
        getTextGeometricTransform gettextgeometrictransform13 = new getTextGeometricTransform(13, new DeltaDecoder(i11, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 107)}, i2), new DeltaDecoder(22, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(8, 37), new InfiniteAnimationPolicyDefaultImpls(i, 38)}, i2), new DeltaDecoder(24, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(8, 20), new InfiniteAnimationPolicyDefaultImpls(i6, 21)}, i2), new DeltaDecoder(22, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(12, 11), new InfiniteAnimationPolicyDefaultImpls(i6, 12)}, i2));
        int i16 = 5;
        getTextGeometricTransform gettextgeometrictransform14 = new getTextGeometricTransform(14, new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i8, 115), new InfiniteAnimationPolicyDefaultImpls(i, 116)}, i2), new DeltaDecoder(24, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 40), new InfiniteAnimationPolicyDefaultImpls(i16, 41)}, i2), new DeltaDecoder(20, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(11, 16), new InfiniteAnimationPolicyDefaultImpls(i16, 17)}, i2), new DeltaDecoder(24, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(11, 12), new InfiniteAnimationPolicyDefaultImpls(i16, 13)}, i2));
        int i17 = 5;
        int i18 = 24;
        int i19 = 7;
        getTextGeometricTransform gettextgeometrictransform15 = new getTextGeometricTransform(15, new DeltaDecoder(22, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i17, 87), new InfiniteAnimationPolicyDefaultImpls(i, 88)}, i2), new DeltaDecoder(i18, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i17, 41), new InfiniteAnimationPolicyDefaultImpls(i17, 42)}, i2), new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i17, i18), new InfiniteAnimationPolicyDefaultImpls(i19, 25)}, i2), new DeltaDecoder(24, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(11, 12), new InfiniteAnimationPolicyDefaultImpls(i19, 13)}, i2));
        int i20 = 46;
        int i21 = 15;
        getTextGeometricTransform gettextgeometrictransform16 = new getTextGeometricTransform(16, new DeltaDecoder(24, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(5, 98), new InfiniteAnimationPolicyDefaultImpls(i, 99)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(7, 45), new InfiniteAnimationPolicyDefaultImpls(i8, i20)}, i2), new DeltaDecoder(24, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i21, 19), new InfiniteAnimationPolicyDefaultImpls(i7, 20)}, i2), new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i8, i21), new InfiniteAnimationPolicyDefaultImpls(13, 16)}, i2));
        int i22 = 28;
        int i23 = 15;
        getTextGeometricTransform gettextgeometrictransform17 = new getTextGeometricTransform(17, new DeltaDecoder(i22, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i, 107), new InfiniteAnimationPolicyDefaultImpls(5, ActivityIdentificationData.RUNNING)}, i2), new DeltaDecoder(i22, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i2, i20), new InfiniteAnimationPolicyDefaultImpls(i, 47)}, i2), new DeltaDecoder(i22, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i, 22), new InfiniteAnimationPolicyDefaultImpls(i23, 23)}, i2), new DeltaDecoder(i22, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, 14), new InfiniteAnimationPolicyDefaultImpls(17, i23)}, i2));
        int i24 = 28;
        getTextGeometricTransform gettextgeometrictransform18 = new getTextGeometricTransform(18, new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(5, 120), new InfiniteAnimationPolicyDefaultImpls(i, 121)}, i2), new DeltaDecoder(26, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(9, 43), new InfiniteAnimationPolicyDefaultImpls(i6, 44)}, i2), new DeltaDecoder(i24, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(17, 22), new InfiniteAnimationPolicyDefaultImpls(i, 23)}, i2), new DeltaDecoder(i24, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, 14), new InfiniteAnimationPolicyDefaultImpls(19, 15)}, i2));
        int i25 = 26;
        getTextGeometricTransform gettextgeometrictransform19 = new getTextGeometricTransform(19, new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i8, 113), new InfiniteAnimationPolicyDefaultImpls(i6, 114)}, i2), new DeltaDecoder(i25, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i8, 44), new InfiniteAnimationPolicyDefaultImpls(11, 45)}, i2), new DeltaDecoder(i25, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(17, 21), new InfiniteAnimationPolicyDefaultImpls(i6, 22)}, i2), new DeltaDecoder(i25, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(9, 13), new InfiniteAnimationPolicyDefaultImpls(16, 14)}, i2));
        int i26 = 15;
        getTextGeometricTransform gettextgeometrictransform20 = new getTextGeometricTransform(20, new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i8, 107), new InfiniteAnimationPolicyDefaultImpls(5, ActivityIdentificationData.RUNNING)}, i2), new DeltaDecoder(26, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i8, 41), new InfiniteAnimationPolicyDefaultImpls(13, 42)}, i2), new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i26, 24), new InfiniteAnimationPolicyDefaultImpls(5, 25)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i26, i26), new InfiniteAnimationPolicyDefaultImpls(i2, 16)}, i2));
        int i27 = 17;
        getTextGeometricTransform gettextgeometrictransform21 = new getTextGeometricTransform(21, new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 116), new InfiniteAnimationPolicyDefaultImpls(i6, 117)}, i2), new DeltaDecoder(26, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i27, 42)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i27, 22), new InfiniteAnimationPolicyDefaultImpls(6, 23)}, i2), new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(19, 16), new InfiniteAnimationPolicyDefaultImpls(6, 17)}, i2));
        int i28 = 7;
        int i29 = 28;
        DeltaDecoder deltaDecoder = new DeltaDecoder(i29, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, 111), new InfiniteAnimationPolicyDefaultImpls(i28, 112)}, i2);
        DeltaDecoder deltaDecoder2 = new DeltaDecoder(i29, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(17, 46)}, i2);
        int i30 = 24;
        getTextGeometricTransform gettextgeometrictransform22 = new getTextGeometricTransform(22, deltaDecoder, deltaDecoder2, new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i28, i30), new InfiniteAnimationPolicyDefaultImpls(16, 25)}, i2), new DeltaDecoder(i30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(34, 13)}, i2));
        int i31 = 14;
        int i32 = 30;
        int i33 = 16;
        getTextGeometricTransform gettextgeometrictransform23 = new getTextGeometricTransform(23, new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 121), new InfiniteAnimationPolicyDefaultImpls(5, 122)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 47), new InfiniteAnimationPolicyDefaultImpls(i31, 48)}, i2), new DeltaDecoder(i32, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(11, 24), new InfiniteAnimationPolicyDefaultImpls(i31, 25)}, i2), new DeltaDecoder(i32, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i33, 15), new InfiniteAnimationPolicyDefaultImpls(i31, i33)}, i2));
        int i34 = 16;
        int i35 = 30;
        getTextGeometricTransform gettextgeometrictransform24 = new getTextGeometricTransform(24, new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(6, 117), new InfiniteAnimationPolicyDefaultImpls(i6, 118)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(6, 45), new InfiniteAnimationPolicyDefaultImpls(14, 46)}, i2), new DeltaDecoder(i35, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(11, 24), new InfiniteAnimationPolicyDefaultImpls(i34, 25)}, i2), new DeltaDecoder(i35, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i35, i34), new InfiniteAnimationPolicyDefaultImpls(i7, 17)}, i2));
        int i36 = 22;
        int i37 = 30;
        getTextGeometricTransform gettextgeometrictransform25 = new getTextGeometricTransform(25, new DeltaDecoder(26, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(8, GwiErrorCode.ALG_LIBRARY_NOT_EXIST), new InfiniteAnimationPolicyDefaultImpls(i6, 107)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(8, 47), new InfiniteAnimationPolicyDefaultImpls(13, 48)}, i2), new DeltaDecoder(i37, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(7, 24), new InfiniteAnimationPolicyDefaultImpls(i36, 25)}, i2), new DeltaDecoder(i37, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i36, 15), new InfiniteAnimationPolicyDefaultImpls(13, 16)}, i2));
        int i38 = 28;
        getTextGeometricTransform gettextgeometrictransform26 = new getTextGeometricTransform(26, new DeltaDecoder(i38, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i2, 114), new InfiniteAnimationPolicyDefaultImpls(i7, 115)}, i2), new DeltaDecoder(i38, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(19, 46), new InfiniteAnimationPolicyDefaultImpls(i6, 47)}, i2), new DeltaDecoder(i38, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i38, 22), new InfiniteAnimationPolicyDefaultImpls(6, 23)}, i2), new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(33, 16), new InfiniteAnimationPolicyDefaultImpls(i6, 17)}, i2));
        int i39 = 30;
        getTextGeometricTransform gettextgeometrictransform27 = new getTextGeometricTransform(27, new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(8, 122), new InfiniteAnimationPolicyDefaultImpls(i6, 123)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(22, 45), new InfiniteAnimationPolicyDefaultImpls(i8, 46)}, i2), new DeltaDecoder(i39, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(8, 23), new InfiniteAnimationPolicyDefaultImpls(26, 24)}, i2), new DeltaDecoder(i39, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(12, 15), new InfiniteAnimationPolicyDefaultImpls(28, 16)}, i2));
        int i40 = 30;
        getTextGeometricTransform gettextgeometrictransform28 = new getTextGeometricTransform(28, new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i8, 117), new InfiniteAnimationPolicyDefaultImpls(i2, 118)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i8, 45), new InfiniteAnimationPolicyDefaultImpls(23, 46)}, i2), new DeltaDecoder(i40, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 24), new InfiniteAnimationPolicyDefaultImpls(31, 25)}, i2), new DeltaDecoder(i40, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(11, 15), new InfiniteAnimationPolicyDefaultImpls(31, 16)}, i2));
        int i41 = 7;
        int i42 = 30;
        getTextGeometricTransform gettextgeometrictransform29 = new getTextGeometricTransform(29, new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i41, 116), new InfiniteAnimationPolicyDefaultImpls(i41, 117)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(21, 45), new InfiniteAnimationPolicyDefaultImpls(i41, 46)}, i2), new DeltaDecoder(i42, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i, 23), new InfiniteAnimationPolicyDefaultImpls(37, 24)}, i2), new DeltaDecoder(i42, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(19, 15), new InfiniteAnimationPolicyDefaultImpls(26, 16)}, i2));
        int i43 = 15;
        int i44 = 25;
        int i45 = 30;
        getTextGeometricTransform gettextgeometrictransform30 = new getTextGeometricTransform(30, new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(5, 115), new InfiniteAnimationPolicyDefaultImpls(i2, 116)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(19, 47), new InfiniteAnimationPolicyDefaultImpls(i2, 48)}, i2), new DeltaDecoder(i45, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i43, 24), new InfiniteAnimationPolicyDefaultImpls(i44, i44)}, i2), new DeltaDecoder(i45, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(23, i43), new InfiniteAnimationPolicyDefaultImpls(i44, 16)}, i2));
        int i46 = 30;
        getTextGeometricTransform gettextgeometrictransform31 = new getTextGeometricTransform(31, new DeltaDecoder(i45, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(13, 115), new InfiniteAnimationPolicyDefaultImpls(i8, 116)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, 46), new InfiniteAnimationPolicyDefaultImpls(29, 47)}, i2), new DeltaDecoder(i46, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(42, 24), new InfiniteAnimationPolicyDefaultImpls(i, 25)}, i2), new DeltaDecoder(i46, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(23, 15), new InfiniteAnimationPolicyDefaultImpls(28, 16)}, i2));
        int i47 = 30;
        getTextGeometricTransform gettextgeometrictransform32 = new getTextGeometricTransform(32, new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(17, 115)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i2, 46), new InfiniteAnimationPolicyDefaultImpls(23, 47)}, i2), new DeltaDecoder(i47, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i2, 24), new InfiniteAnimationPolicyDefaultImpls(35, 25)}, i2), new DeltaDecoder(i47, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(19, 15), new InfiniteAnimationPolicyDefaultImpls(35, 16)}, i2));
        int i48 = 30;
        getTextGeometricTransform gettextgeometrictransform33 = new getTextGeometricTransform(33, new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(17, 115), new InfiniteAnimationPolicyDefaultImpls(i, 116)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(14, 46), new InfiniteAnimationPolicyDefaultImpls(21, 47)}, i2), new DeltaDecoder(i48, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(29, 24), new InfiniteAnimationPolicyDefaultImpls(19, 25)}, i2), new DeltaDecoder(i48, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(11, 15), new InfiniteAnimationPolicyDefaultImpls(46, 16)}, i2));
        int i49 = 30;
        getTextGeometricTransform gettextgeometrictransform34 = new getTextGeometricTransform(34, new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(13, 115), new InfiniteAnimationPolicyDefaultImpls(6, 116)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(14, 46), new InfiniteAnimationPolicyDefaultImpls(23, 47)}, i2), new DeltaDecoder(i49, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(44, 24), new InfiniteAnimationPolicyDefaultImpls(7, 25)}, i2), new DeltaDecoder(i49, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(59, 16), new InfiniteAnimationPolicyDefaultImpls(i, 17)}, i2));
        int i50 = 30;
        getTextGeometricTransform gettextgeometrictransform35 = new getTextGeometricTransform(35, new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(12, 121), new InfiniteAnimationPolicyDefaultImpls(7, 122)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(12, 47), new InfiniteAnimationPolicyDefaultImpls(26, 48)}, i2), new DeltaDecoder(i50, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(39, 24), new InfiniteAnimationPolicyDefaultImpls(14, 25)}, i2), new DeltaDecoder(i50, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(22, 15), new InfiniteAnimationPolicyDefaultImpls(41, 16)}, i2));
        int i51 = 30;
        getTextGeometricTransform gettextgeometrictransform36 = new getTextGeometricTransform(36, new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(6, 121), new InfiniteAnimationPolicyDefaultImpls(14, 122)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(6, 47), new InfiniteAnimationPolicyDefaultImpls(34, 48)}, i2), new DeltaDecoder(i51, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(46, 24), new InfiniteAnimationPolicyDefaultImpls(i2, 25)}, i2), new DeltaDecoder(i51, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i7, 15), new InfiniteAnimationPolicyDefaultImpls(64, 16)}, i2));
        int i52 = 24;
        int i53 = 30;
        getTextGeometricTransform gettextgeometrictransform37 = new getTextGeometricTransform(37, new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(17, 122), new InfiniteAnimationPolicyDefaultImpls(i6, 123)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(29, 46), new InfiniteAnimationPolicyDefaultImpls(14, 47)}, i2), new DeltaDecoder(i53, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(49, i52), new InfiniteAnimationPolicyDefaultImpls(i2, 25)}, i2), new DeltaDecoder(i53, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i52, 15), new InfiniteAnimationPolicyDefaultImpls(46, 16)}, i2));
        int i54 = 30;
        getTextGeometricTransform gettextgeometrictransform38 = new getTextGeometricTransform(38, new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i6, 122), new InfiniteAnimationPolicyDefaultImpls(18, 123)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(13, 46), new InfiniteAnimationPolicyDefaultImpls(32, 47)}, i2), new DeltaDecoder(i54, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(48, 24), new InfiniteAnimationPolicyDefaultImpls(14, 25)}, i2), new DeltaDecoder(i54, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(42, 15), new InfiniteAnimationPolicyDefaultImpls(32, 16)}, i2));
        int i55 = 30;
        getTextGeometricTransform gettextgeometrictransform39 = new getTextGeometricTransform(39, new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(20, 117), new InfiniteAnimationPolicyDefaultImpls(i6, 118)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(40, 47), new InfiniteAnimationPolicyDefaultImpls(7, 48)}, i2), new DeltaDecoder(i55, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(43, 24), new InfiniteAnimationPolicyDefaultImpls(22, 25)}, i2), new DeltaDecoder(i55, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(i2, 15), new InfiniteAnimationPolicyDefaultImpls(67, 16)}, i2));
        int i56 = 30;
        read = new getTextGeometricTransform[]{gettextgeometrictransform, gettextgeometrictransform2, gettextgeometrictransform3, gettextgeometrictransform4, gettextgeometrictransform5, gettextgeometrictransform6, gettextgeometrictransform7, gettextgeometrictransform8, gettextgeometrictransform9, gettextgeometrictransform10, gettextgeometrictransform11, gettextgeometrictransform12, gettextgeometrictransform13, gettextgeometrictransform14, gettextgeometrictransform15, gettextgeometrictransform16, gettextgeometrictransform17, gettextgeometrictransform18, gettextgeometrictransform19, gettextgeometrictransform20, gettextgeometrictransform21, gettextgeometrictransform22, gettextgeometrictransform23, gettextgeometrictransform24, gettextgeometrictransform25, gettextgeometrictransform26, gettextgeometrictransform27, gettextgeometrictransform28, gettextgeometrictransform29, gettextgeometrictransform30, gettextgeometrictransform31, gettextgeometrictransform32, gettextgeometrictransform33, gettextgeometrictransform34, gettextgeometrictransform35, gettextgeometrictransform36, gettextgeometrictransform37, gettextgeometrictransform38, gettextgeometrictransform39, new getTextGeometricTransform(40, new DeltaDecoder(30, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(19, 118), new InfiniteAnimationPolicyDefaultImpls(6, 119)}, i2), new DeltaDecoder(28, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(18, 47), new InfiniteAnimationPolicyDefaultImpls(31, 48)}, i2), new DeltaDecoder(i56, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(34, 24), new InfiniteAnimationPolicyDefaultImpls(34, 25)}, i2), new DeltaDecoder(i56, new InfiniteAnimationPolicyDefaultImpls[]{new InfiniteAnimationPolicyDefaultImpls(20, 15), new InfiniteAnimationPolicyDefaultImpls(61, 16)}, i2))};
    }
}
