package o;

/* JADX INFO: loaded from: classes.dex */
public final class getViewingDistancetKroMQ {
    public final long ComponentActivity;
    public final long IconCompatParcelizer;
    public androidx.compose.material3.ButtonColors MediaBrowserCompatMediaItem;
    public final long MediaDescriptionCompat;
    public MediaQuery_androidKtobtainUiMediaScope31invokeinlinedonDispose1 MediaMetadataCompat;
    public androidx.compose.material3.IconButtonColors MediaSessionCompatQueueItem;
    public final long MediaSessionCompatResultReceiverWrapper;
    public final long MediaSessionCompatToken;
    public final long ParcelableVolumeInfo;
    public final long PlaybackStateCompat;
    public final long PlaybackStateCompatCustomAction;
    public androidx.compose.material3.TextFieldColors RatingCompat;
    public SessionMutex RemoteActionCompatParcelizer;
    public final long ResultReceiver;
    public final long _init_lambda1;
    public final long _init_lambda2;
    public final long _init_lambda3;
    public final long _init_lambda4;
    public final long accessensureViewModelStore;
    public final long addContentView;
    public final long addMenuProvider;
    public final long addObserverForBackInvoker;
    public final long addObserverForBackInvokerlambda0;
    public final long addOnConfigurationChangedListener;
    public final long addOnContextAvailableListener;
    public final long addOnMultiWindowModeChangedListener;
    public final long addOnNewIntentListener;
    public final long createFullyDrawnExecutor;
    public final long defaultViewModelProviderFactory_delegatelambda0;
    public final long ensureViewModelStore;
    public final long enterPictureInPictureMode;
    public final long fullyDrawnReporter_delegatelambda0;
    public final long fullyDrawnReporter_delegatelambda00;
    public final long getOnBackPressedInput;
    public final long getSavedStateRegistryControllerannotations;
    public final long menuHostHelperlambda0;
    public final long onBackPressedDispatcher_delegatelambda0;
    public final long onBackPressedDispatcher_delegatelambda00;
    public final long onBackPressedDispatcher_delegatelambda010;
    public final long onBackPressedInput_delegatelambda0;
    public final long r8lambda54BeH8ZsBru0CXI2CCSP2syNys;
    public final long r8lambda7IJBVrN0sHyidCAZufWEJFc7yY;
    public final long r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus;
    public final long r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss;
    public final long r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg;
    public final long r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8;
    public final long r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4;
    public final long r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM;
    public final long r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs;
    public final long r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28;
    public final long r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw;
    public final long r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ;
    public final long r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0;
    public SessionMutexwithSessionCancellingPrevious2 read;
    public androidx.compose.material3.IconButtonColors serializer;
    public androidx.compose.material3.ButtonColors write;

    public getViewingDistancetKroMQ(long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30, long j31, long j32, long j33, long j34, long j35, long j36, long j37, long j38, long j39, long j40, long j41, long j42, long j43, long j44, long j45, long j46, long j47, long j48) {
        this._init_lambda4 = j;
        this.r8lambda7IJBVrN0sHyidCAZufWEJFc7yY = j2;
        this._init_lambda1 = j3;
        this.r8lambda54BeH8ZsBru0CXI2CCSP2syNys = j4;
        this.PlaybackStateCompatCustomAction = j5;
        this.addObserverForBackInvoker = j6;
        this.r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg = j7;
        this.addObserverForBackInvokerlambda0 = j8;
        this.r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM = j9;
        this.addOnContextAvailableListener = j10;
        this.r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ = j11;
        this.addOnMultiWindowModeChangedListener = j12;
        this.r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs = j13;
        this.IconCompatParcelizer = j14;
        this.MediaSessionCompatToken = j15;
        this.menuHostHelperlambda0 = j16;
        this.r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28 = j17;
        this.addMenuProvider = j18;
        this.r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0 = j19;
        this.addOnConfigurationChangedListener = j20;
        this.MediaSessionCompatResultReceiverWrapper = j21;
        this.ParcelableVolumeInfo = j22;
        this.MediaDescriptionCompat = j23;
        this.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus = j24;
        this.PlaybackStateCompat = j25;
        this.ComponentActivity = j26;
        this._init_lambda2 = j27;
        this._init_lambda3 = j28;
        this.defaultViewModelProviderFactory_delegatelambda0 = j29;
        this.getSavedStateRegistryControllerannotations = j30;
        this.onBackPressedInput_delegatelambda0 = j31;
        this.getOnBackPressedInput = j32;
        this.onBackPressedDispatcher_delegatelambda00 = j33;
        this.onBackPressedDispatcher_delegatelambda010 = j34;
        this.addContentView = j35;
        this.onBackPressedDispatcher_delegatelambda0 = j36;
        this.ensureViewModelStore = j37;
        this.createFullyDrawnExecutor = j38;
        this.ResultReceiver = j39;
        this.r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss = j40;
        this.fullyDrawnReporter_delegatelambda0 = j41;
        this.fullyDrawnReporter_delegatelambda00 = j42;
        this.r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8 = j43;
        this.r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4 = j44;
        this.addOnNewIntentListener = j45;
        this.enterPictureInPictureMode = j46;
        this.r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw = j47;
        this.accessensureViewModelStore = j48;
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("ColorScheme(primary=");
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this._init_lambda4, "onPrimary=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.r8lambda7IJBVrN0sHyidCAZufWEJFc7yY, "primaryContainer=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this._init_lambda1, "onPrimaryContainer=", sb);
        long j = this.r8lambda54BeH8ZsBru0CXI2CCSP2syNys;
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(j, "inversePrimary=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.PlaybackStateCompatCustomAction, "secondary=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.addObserverForBackInvoker, "onSecondary=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg, "secondaryContainer=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.addObserverForBackInvokerlambda0, "onSecondaryContainer=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM, "tertiary=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.addOnContextAvailableListener, "onTertiary=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ, "tertiaryContainer=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.addOnMultiWindowModeChangedListener, "onTertiaryContainer=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs, "background=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.IconCompatParcelizer, "onBackground=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.MediaSessionCompatToken, "surface=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.menuHostHelperlambda0, "onSurface=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28, "surfaceVariant=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.addMenuProvider, "onSurfaceVariant=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0, "surfaceTint=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.addOnConfigurationChangedListener, "inverseSurface=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.MediaSessionCompatResultReceiverWrapper, "inverseOnSurface=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.ParcelableVolumeInfo, "error=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.MediaDescriptionCompat, "onError=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus, "errorContainer=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.PlaybackStateCompat, "onErrorContainer=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.ComponentActivity, "outline=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this._init_lambda2, "outlineVariant=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this._init_lambda3, "scrim=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.defaultViewModelProviderFactory_delegatelambda0, "surfaceBright=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.getSavedStateRegistryControllerannotations, "surfaceDim=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.onBackPressedInput_delegatelambda0, "surfaceContainer=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.getOnBackPressedInput, "surfaceContainerHigh=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.onBackPressedDispatcher_delegatelambda00, "surfaceContainerHighest=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.onBackPressedDispatcher_delegatelambda010, "surfaceContainerLow=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.addContentView, "surfaceContainerLowest=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.onBackPressedDispatcher_delegatelambda0, "primaryFixed=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.ensureViewModelStore, "primaryFixedDim=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.createFullyDrawnExecutor, "onPrimaryFixed=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(j, "onPrimaryFixedVariant=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss, "secondaryFixed=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.fullyDrawnReporter_delegatelambda0, "secondaryFixedDim=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.fullyDrawnReporter_delegatelambda00, "onSecondaryFixed=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8, "onSecondaryFixedVariant=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4, "tertiaryFixed=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.addOnNewIntentListener, "tertiaryFixedDim=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.enterPictureInPictureMode, "onTertiaryFixed=", sb);
        r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.read(this.r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw, "onTertiaryFixedVariant=", sb);
        sb.append((Object) androidx.compose.ui.graphics.Color.m730toStringimpl(this.accessensureViewModelStore));
        sb.append(')');
        return sb.toString();
    }
}
