package o;

/* JADX INFO: loaded from: classes2.dex */
public enum incrementSensitiveComponentCount {
    ALL,
    LISTEN_STREAM_IDLE,
    LISTEN_STREAM_CONNECTION_BACKOFF,
    WRITE_STREAM_IDLE,
    WRITE_STREAM_CONNECTION_BACKOFF,
    HEALTH_CHECK_TIMEOUT,
    ONLINE_STATE_TIMEOUT,
    GARBAGE_COLLECTION,
    RETRY_TRANSACTION,
    CONNECTIVITY_ATTEMPT_TIMER,
    INDEX_BACKFILL
}
