package o;

/* JADX INFO: loaded from: classes4.dex */
public abstract class isQuadraticMonotonic {
    public static final int[] BackgroundStyle = {android.R.attr.selectableItemBackground, com.logistics.rider.glovo.R.attr.selectableItemBackground};
    public static final int[] CheckBoxPreference = {android.R.attr.summaryOn, android.R.attr.summaryOff, android.R.attr.disableDependentsState, com.logistics.rider.glovo.R.attr.disableDependentsState, com.logistics.rider.glovo.R.attr.summaryOff, com.logistics.rider.glovo.R.attr.summaryOn};
    public static final int[] DialogPreference = {android.R.attr.dialogTitle, android.R.attr.dialogMessage, android.R.attr.dialogIcon, android.R.attr.positiveButtonText, android.R.attr.negativeButtonText, android.R.attr.dialogLayout, com.logistics.rider.glovo.R.attr.dialogIcon, com.logistics.rider.glovo.R.attr.dialogLayout, com.logistics.rider.glovo.R.attr.dialogMessage, com.logistics.rider.glovo.R.attr.dialogTitle, com.logistics.rider.glovo.R.attr.negativeButtonText, com.logistics.rider.glovo.R.attr.positiveButtonText};
    public static final int[] EditTextPreference = {com.logistics.rider.glovo.R.attr.useSimpleSummaryProvider};
    public static final int[] ListPreference = {android.R.attr.entries, android.R.attr.entryValues, com.logistics.rider.glovo.R.attr.entries, com.logistics.rider.glovo.R.attr.entryValues, com.logistics.rider.glovo.R.attr.useSimpleSummaryProvider};
    public static final int[] MultiSelectListPreference = {android.R.attr.entries, android.R.attr.entryValues, com.logistics.rider.glovo.R.attr.entries, com.logistics.rider.glovo.R.attr.entryValues};
    public static final int[] Preference = {android.R.attr.icon, android.R.attr.persistent, android.R.attr.enabled, android.R.attr.layout, android.R.attr.title, android.R.attr.selectable, android.R.attr.key, android.R.attr.summary, android.R.attr.order, android.R.attr.widgetLayout, android.R.attr.dependency, android.R.attr.defaultValue, android.R.attr.shouldDisableView, android.R.attr.fragment, android.R.attr.singleLineTitle, android.R.attr.iconSpaceReserved, com.logistics.rider.glovo.R.attr.allowDividerAbove, com.logistics.rider.glovo.R.attr.allowDividerBelow, com.logistics.rider.glovo.R.attr.defaultValue, com.logistics.rider.glovo.R.attr.dependency, com.logistics.rider.glovo.R.attr.enableCopying, com.logistics.rider.glovo.R.attr.enabled, com.logistics.rider.glovo.R.attr.fragment, com.logistics.rider.glovo.R.attr.icon, com.logistics.rider.glovo.R.attr.iconSpaceReserved, com.logistics.rider.glovo.R.attr.isPreferenceVisible, com.logistics.rider.glovo.R.attr.key, com.logistics.rider.glovo.R.attr.layout, com.logistics.rider.glovo.R.attr.order, com.logistics.rider.glovo.R.attr.persistent, com.logistics.rider.glovo.R.attr.selectable, com.logistics.rider.glovo.R.attr.shouldDisableView, com.logistics.rider.glovo.R.attr.singleLineTitle, com.logistics.rider.glovo.R.attr.summary, com.logistics.rider.glovo.R.attr.title, com.logistics.rider.glovo.R.attr.widgetLayout};
    public static final int[] PreferenceFragment = {android.R.attr.layout, android.R.attr.divider, android.R.attr.dividerHeight, com.logistics.rider.glovo.R.attr.allowDividerAfterLastItem};
    public static final int[] PreferenceGroup = {android.R.attr.orderingFromXml, com.logistics.rider.glovo.R.attr.initialExpandedChildrenCount, com.logistics.rider.glovo.R.attr.orderingFromXml};
    public static final int[] PreferenceImageView = {android.R.attr.maxWidth, android.R.attr.maxHeight, com.logistics.rider.glovo.R.attr.maxHeight, com.logistics.rider.glovo.R.attr.maxWidth};
    public static final int[] SeekBarPreference = {android.R.attr.layout, android.R.attr.max, com.logistics.rider.glovo.R.attr.adjustable, com.logistics.rider.glovo.R.attr.min, com.logistics.rider.glovo.R.attr.seekBarIncrement, com.logistics.rider.glovo.R.attr.showSeekBarValue, com.logistics.rider.glovo.R.attr.updatesContinuously};
    public static final int[] SwitchPreference = {android.R.attr.summaryOn, android.R.attr.summaryOff, android.R.attr.disableDependentsState, android.R.attr.switchTextOn, android.R.attr.switchTextOff, com.logistics.rider.glovo.R.attr.disableDependentsState, com.logistics.rider.glovo.R.attr.summaryOff, com.logistics.rider.glovo.R.attr.summaryOn, com.logistics.rider.glovo.R.attr.switchTextOff, com.logistics.rider.glovo.R.attr.switchTextOn};
    public static final int[] SwitchPreferenceCompat = {android.R.attr.summaryOn, android.R.attr.summaryOff, android.R.attr.disableDependentsState, android.R.attr.switchTextOn, android.R.attr.switchTextOff, com.logistics.rider.glovo.R.attr.disableDependentsState, com.logistics.rider.glovo.R.attr.summaryOff, com.logistics.rider.glovo.R.attr.summaryOn, com.logistics.rider.glovo.R.attr.switchTextOff, com.logistics.rider.glovo.R.attr.switchTextOn};
}
