package o;

import android.app.Application;
import com.roadrunner.appinitialize.InitializeAppStartupItemsImpl;
import com.roadrunner.heatmap.domain.ShouldShowHeatmap_Factory;
import com.roadrunner.map.integration.mapbox.maneuver.ManeuverApi;
import com.roadrunner.map.integration.mapbox.navigation.MapNavigationImpl;
import com.roadrunner.map.integration.mapbox.route.FetchMapboxRouteUseCase;
import com.roadrunner.map.integration.mapbox.route.RouteArrowApi;
import com.roadrunner.map.integration.mapbox.route.preview.SecondaryRouteApi;
import com.roadrunner.map.integration.mapbox.speedlimit.SpeedLimitApi;
import com.roadrunner.map.integration.mapbox.tripprogress.TripProgressApi;
import okio.Path$Companion;

/* JADX INFO: loaded from: classes3.dex */
public final class l1 implements getColorIntegerOrNulllambda0 {
    private static int r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ = 0;
    private static int r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0 = 1;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ ComponentActivity;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ IconCompatParcelizer;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ MediaBrowserCompatMediaItem;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ MediaDescriptionCompat;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ MediaMetadataCompat;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ MediaSessionCompatQueueItem;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ MediaSessionCompatResultReceiverWrapper;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ MediaSessionCompatToken;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ ParcelableVolumeInfo;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ PlaybackStateCompat;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ PlaybackStateCompatCustomAction;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ RatingCompat;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ RemoteActionCompatParcelizer;
    public final LocaleListHelperMethods ResultReceiver;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambda54BeH8ZsBru0CXI2CCSP2syNys;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambda7IJBVrN0sHyidCAZufWEJFc7yY;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ read;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ serializer;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ write;

    public l1(hasNestedScrollingParent hasnestedscrollingparent, r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdaktwlyipskq3tfa9ey3gatonixfq, buildEventPackage buildeventpackage, getShapedelegate getshapedelegate, onCapabilitiesChanged oncapabilitieschanged, setPaddingBottom setpaddingbottom, r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdaktwlyipskq3tfa9ey3gatonixfq2, performPushDeliveryFlushlambda0 performpushdeliveryflushlambda0, getXmlParser getxmlparser, postAnimationRunner postanimationrunner, performPushDeliveryFlushlambda0 performpushdeliveryflushlambda1, r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdaktwlyipskq3tfa9ey3gatonixfq3, postAnimationRunner postanimationrunner2, SemanticsPropertiesLinkTestMarker1 semanticsPropertiesLinkTestMarker1, r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdaktwlyipskq3tfa9ey3gatonixfq4, setVerticalBias setverticalbias, setVerticalBias setverticalbias2, r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdaktwlyipskq3tfa9ey3gatonixfq5, LocaleListHelperMethods localeListHelperMethods, ShouldShowHeatmap_Factory shouldShowHeatmap_Factory, getSharedElementTargetNames getsharedelementtargetnames, r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdaktwlyipskq3tfa9ey3gatonixfq6, r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdaktwlyipskq3tfa9ey3gatonixfq7, r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdaktwlyipskq3tfa9ey3gatonixfq8, r8lambdazXN1qqQhLYzDDSf7dMTrYE1xu8I r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i, transactionWithResultsuspendImpl transactionwithresultsuspendimpl, SemanticsPropertiesLinkTestMarker1 semanticsPropertiesLinkTestMarker2, LocaleListHelperMethods localeListHelperMethods2) {
        hasnestedscrollingparent.getClass();
        r8lambdaktwlyipskq3tfa9ey3gatonixfq.getClass();
        buildeventpackage.getClass();
        getshapedelegate.getClass();
        oncapabilitieschanged.getClass();
        setpaddingbottom.getClass();
        r8lambdaktwlyipskq3tfa9ey3gatonixfq2.getClass();
        performpushdeliveryflushlambda0.getClass();
        getxmlparser.getClass();
        postanimationrunner.getClass();
        performpushdeliveryflushlambda1.getClass();
        r8lambdaktwlyipskq3tfa9ey3gatonixfq3.getClass();
        postanimationrunner2.getClass();
        semanticsPropertiesLinkTestMarker1.getClass();
        r8lambdaktwlyipskq3tfa9ey3gatonixfq4.getClass();
        setverticalbias.getClass();
        setverticalbias2.getClass();
        r8lambdaktwlyipskq3tfa9ey3gatonixfq5.getClass();
        localeListHelperMethods.getClass();
        shouldShowHeatmap_Factory.getClass();
        getsharedelementtargetnames.getClass();
        r8lambdaktwlyipskq3tfa9ey3gatonixfq6.getClass();
        r8lambdaktwlyipskq3tfa9ey3gatonixfq7.getClass();
        r8lambdaktwlyipskq3tfa9ey3gatonixfq8.getClass();
        r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i.getClass();
        transactionwithresultsuspendimpl.getClass();
        semanticsPropertiesLinkTestMarker2.getClass();
        this.IconCompatParcelizer = hasnestedscrollingparent;
        this.ParcelableVolumeInfo = r8lambdaktwlyipskq3tfa9ey3gatonixfq;
        this.r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8 = buildeventpackage;
        this.r8lambda7IJBVrN0sHyidCAZufWEJFc7yY = getshapedelegate;
        this.ComponentActivity = oncapabilitieschanged;
        this.MediaSessionCompatResultReceiverWrapper = setpaddingbottom;
        this.PlaybackStateCompatCustomAction = r8lambdaktwlyipskq3tfa9ey3gatonixfq2;
        this.r8lambda54BeH8ZsBru0CXI2CCSP2syNys = performpushdeliveryflushlambda0;
        this.r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM = getxmlparser;
        this.r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg = postanimationrunner;
        this.r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4 = performpushdeliveryflushlambda1;
        this.MediaDescriptionCompat = r8lambdaktwlyipskq3tfa9ey3gatonixfq3;
        this.read = postanimationrunner2;
        this.r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss = semanticsPropertiesLinkTestMarker1;
        this.MediaSessionCompatToken = r8lambdaktwlyipskq3tfa9ey3gatonixfq4;
        this.MediaMetadataCompat = setverticalbias;
        this.MediaBrowserCompatMediaItem = setverticalbias2;
        this.r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28 = r8lambdaktwlyipskq3tfa9ey3gatonixfq5;
        this.r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw = localeListHelperMethods;
        this.serializer = shouldShowHeatmap_Factory;
        this.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus = getsharedelementtargetnames;
        this.r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs = r8lambdaktwlyipskq3tfa9ey3gatonixfq6;
        this.MediaSessionCompatQueueItem = r8lambdaktwlyipskq3tfa9ey3gatonixfq7;
        this.RemoteActionCompatParcelizer = r8lambdaktwlyipskq3tfa9ey3gatonixfq8;
        this.write = r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i;
        this.PlaybackStateCompat = transactionwithresultsuspendimpl;
        this.RatingCompat = semanticsPropertiesLinkTestMarker2;
        this.ResultReceiver = localeListHelperMethods2;
    }

    @Override // o.r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ
    public final Object write() {
        int i = 2 % 2;
        Object objWrite = this.IconCompatParcelizer.write();
        objWrite.getClass();
        Application application = (Application) objWrite;
        Object objWrite2 = this.ParcelableVolumeInfo.write();
        objWrite2.getClass();
        j8 j8Var = (j8) objWrite2;
        Object objWrite3 = this.r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8.write();
        objWrite3.getClass();
        TripProgressApi tripProgressApi = (TripProgressApi) objWrite3;
        Object objWrite4 = this.r8lambda7IJBVrN0sHyidCAZufWEJFc7yY.write();
        objWrite4.getClass();
        m7 m7Var = (m7) objWrite4;
        Object objWrite5 = this.ComponentActivity.write();
        objWrite5.getClass();
        RouteArrowApi routeArrowApi = (RouteArrowApi) objWrite5;
        Object objWrite6 = this.MediaSessionCompatResultReceiverWrapper.write();
        objWrite6.getClass();
        ia iaVar = (ia) objWrite6;
        Path$Companion path$Companion = new Path$Companion();
        Object objWrite7 = this.PlaybackStateCompatCustomAction.write();
        objWrite7.getClass();
        ManeuverApi maneuverApi = (ManeuverApi) objWrite7;
        Object objWrite8 = this.r8lambda54BeH8ZsBru0CXI2CCSP2syNys.write();
        objWrite8.getClass();
        SecondaryRouteApi secondaryRouteApi = (SecondaryRouteApi) objWrite8;
        Object objWrite9 = this.r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM.write();
        objWrite9.getClass();
        SpeedLimitApi speedLimitApi = (SpeedLimitApi) objWrite9;
        Object objWrite10 = this.r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg.write();
        objWrite10.getClass();
        n2ExternalSyntheticLambda0 n2externalsyntheticlambda0 = (n2ExternalSyntheticLambda0) objWrite10;
        Object objWrite11 = this.r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4.write();
        objWrite11.getClass();
        mh mhVar = (mh) objWrite11;
        Object objWrite12 = this.MediaDescriptionCompat.write();
        objWrite12.getClass();
        getHeadingrAG3T2k getheadingrag3t2k = (getHeadingrAG3T2k) objWrite12;
        Object objWrite13 = this.read.write();
        objWrite13.getClass();
        k6 k6Var = (k6) objWrite13;
        Object objWrite14 = this.r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss.write();
        objWrite14.getClass();
        getLooseusljTpc getlooseusljtpc = (getLooseusljTpc) objWrite14;
        Object objWrite15 = this.MediaSessionCompatToken.write();
        objWrite15.getClass();
        accessgetParagraphcp accessgetparagraphcp = (accessgetParagraphcp) objWrite15;
        Object objWrite16 = this.MediaMetadataCompat.write();
        objWrite16.getClass();
        lerpjWV1Mfo lerpjwv1mfo = (lerpjWV1Mfo) objWrite16;
        Object objWrite17 = this.MediaBrowserCompatMediaItem.write();
        objWrite17.getClass();
        component10d7_KjU component10d7_kju = (component10d7_KjU) objWrite17;
        Object objWrite18 = this.r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28.write();
        objWrite18.getClass();
        ld ldVar = (ld) objWrite18;
        Object objWrite19 = this.r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw.write();
        objWrite19.getClass();
        LineBreakStrictnessCompanion lineBreakStrictnessCompanion = (LineBreakStrictnessCompanion) objWrite19;
        Object objWrite20 = this.serializer.write();
        objWrite20.getClass();
        i0 i0Var = (i0) objWrite20;
        Object objWrite21 = this.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus.write();
        objWrite21.getClass();
        performCreate performcreate = (performCreate) objWrite21;
        Object objWrite22 = this.r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs.write();
        objWrite22.getClass();
        f2ExternalSyntheticLambda4 f2externalsyntheticlambda4 = (f2ExternalSyntheticLambda4) objWrite22;
        Object objWrite23 = this.MediaSessionCompatQueueItem.write();
        objWrite23.getClass();
        getPresentationContext getpresentationcontext = (getPresentationContext) objWrite23;
        Object objWrite24 = this.RemoteActionCompatParcelizer.write();
        objWrite24.getClass();
        transferSessionPackageI transfersessionpackagei = (transferSessionPackageI) objWrite24;
        Object objWrite25 = this.write.write();
        objWrite25.getClass();
        FetchMapboxRouteUseCase fetchMapboxRouteUseCase = (FetchMapboxRouteUseCase) objWrite25;
        m3 m3Var = new m3();
        ImageHeaderParserImageType imageHeaderParserImageType = new ImageHeaderParserImageType();
        Object objWrite26 = this.PlaybackStateCompat.write();
        objWrite26.getClass();
        k7 k7Var = (k7) objWrite26;
        Object objWrite27 = this.RatingCompat.write();
        objWrite27.getClass();
        MapNavigationImpl mapNavigationImpl = new MapNavigationImpl(application, j8Var, tripProgressApi, m7Var, routeArrowApi, iaVar, path$Companion, maneuverApi, secondaryRouteApi, speedLimitApi, n2externalsyntheticlambda0, mhVar, getheadingrag3t2k, k6Var, getlooseusljtpc, accessgetparagraphcp, lerpjwv1mfo, component10d7_kju, ldVar, lineBreakStrictnessCompanion, i0Var, performcreate, f2externalsyntheticlambda4, getpresentationcontext, transfersessionpackagei, fetchMapboxRouteUseCase, m3Var, imageHeaderParserImageType, k7Var, (resolveBulletTextUnitToPxo2QH7mI) objWrite27, (InitializeAppStartupItemsImpl) this.ResultReceiver.write());
        int i2 = r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ + 15;
        r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0 = i2 % androidx.compose.ui.graphics.Fields.SpotShadowColor;
        if (i2 % 2 != 0) {
            return mapNavigationImpl;
        }
        throw null;
    }
}
