package o;

import com.deliveryhero.fwf_customer_profile.util.ConstantsKt;
import com.google.android.gms.location.DeviceOrientationRequest;
import com.huawei.location.gwi.config.CarGwiSoFileConstant;

/* JADX INFO: loaded from: classes2.dex */
public final class NestedScrollNodeonPreFling1 {
    public static final isAltPressedZmokQxo ComponentActivity;
    public static final isAltPressedZmokQxo IconCompatParcelizer;
    public static final isAltPressedZmokQxo MediaBrowserCompatMediaItem;
    public static final isAltPressedZmokQxo MediaDescriptionCompat;
    public static final isAltPressedZmokQxo MediaMetadataCompat;
    public static final isAltPressedZmokQxo MediaSessionCompatQueueItem;
    public static final isAltPressedZmokQxo MediaSessionCompatResultReceiverWrapper;
    public static final isAltPressedZmokQxo MediaSessionCompatToken;
    public static final isAltPressedZmokQxo ParcelableVolumeInfo;
    public static final isAltPressedZmokQxo PlaybackStateCompat;
    public static final isAltPressedZmokQxo PlaybackStateCompatCustomAction;
    public static final isAltPressedZmokQxo RatingCompat;
    public static final isAltPressedZmokQxo RemoteActionCompatParcelizer;
    public static final isAltPressedZmokQxo ResultReceiver;
    public static final isAltPressedZmokQxo _init_lambda1;
    public static final isAltPressedZmokQxo _init_lambda2;
    public static final isAltPressedZmokQxo _init_lambda3;
    public static final isAltPressedZmokQxo _init_lambda4;
    public static final isAltPressedZmokQxo accessensureViewModelStore;
    public static final isAltPressedZmokQxo addContentView;
    public static final isAltPressedZmokQxo addMenuProvider;
    public static final isAltPressedZmokQxo addObserverForBackInvoker;
    public static final isAltPressedZmokQxo addObserverForBackInvokerlambda0;
    public static final isAltPressedZmokQxo addOnConfigurationChangedListener;
    public static final isAltPressedZmokQxo addOnContextAvailableListener;
    public static final isAltPressedZmokQxo addOnMultiWindowModeChangedListener;
    public static final isAltPressedZmokQxo addOnNewIntentListener;
    public static final isAltPressedZmokQxo addOnPictureInPictureModeChangedListener;
    public static final isAltPressedZmokQxo addOnPictureInPictureUiStateChangedListener;
    public static final isAltPressedZmokQxo addOnTrimMemoryListener;
    public static final isAltPressedZmokQxo addOnUserLeaveHintListener;
    public static final isAltPressedZmokQxo createFullyDrawnExecutor;
    public static final isAltPressedZmokQxo defaultViewModelProviderFactory_delegatelambda0;
    public static final isAltPressedZmokQxo ensureViewModelStore;
    public static final isAltPressedZmokQxo enterPictureInPictureMode;
    public static final isAltPressedZmokQxo fullyDrawnReporter_delegatelambda0;
    public static final isAltPressedZmokQxo fullyDrawnReporter_delegatelambda00;
    public static final isAltPressedZmokQxo getActivityResultRegistry;
    public static final isAltPressedZmokQxo getDefaultViewModelCreationExtras;
    public static final isAltPressedZmokQxo getDefaultViewModelProviderFactory;
    public static final isAltPressedZmokQxo getFullyDrawnReporter;
    public static final isAltPressedZmokQxo getLastCustomNonConfigurationInstance;
    public static final isAltPressedZmokQxo getLifecycle;
    public static final isAltPressedZmokQxo getNavigationEventDispatcher;
    public static final isAltPressedZmokQxo getOnBackPressedDispatcher;
    public static final isAltPressedZmokQxo getOnBackPressedInput;
    public static final isAltPressedZmokQxo getSavedStateRegistry;
    public static final isAltPressedZmokQxo getSavedStateRegistryControllerannotations;
    public static final isAltPressedZmokQxo getViewModelStore;
    public static final isAltPressedZmokQxo initializeViewTreeOwners;
    public static final isAltPressedZmokQxo invalidateMenu;
    public static final isAltPressedZmokQxo menuHostHelperlambda0;
    public static final isAltPressedZmokQxo onActivityResult;
    public static final isAltPressedZmokQxo onBackPressed;
    public static final isAltPressedZmokQxo onBackPressedDispatcher_delegatelambda0;
    public static final isAltPressedZmokQxo onBackPressedDispatcher_delegatelambda00;
    public static final isAltPressedZmokQxo onBackPressedDispatcher_delegatelambda010;
    public static final isAltPressedZmokQxo onBackPressedInput_delegatelambda0;
    public static final isAltPressedZmokQxo onConfigurationChanged;
    public static final isAltPressedZmokQxo r8lambda54BeH8ZsBru0CXI2CCSP2syNys;
    public static final isAltPressedZmokQxo r8lambda7IJBVrN0sHyidCAZufWEJFc7yY;
    public static final isAltPressedZmokQxo r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus;
    public static final isAltPressedZmokQxo r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss;
    public static final isAltPressedZmokQxo r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg;
    public static final isAltPressedZmokQxo r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8;
    public static final isAltPressedZmokQxo r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4;
    public static final isAltPressedZmokQxo r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM;
    public static final isAltPressedZmokQxo r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs;
    public static final isAltPressedZmokQxo r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28;
    public static final isAltPressedZmokQxo r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw;
    public static final isAltPressedZmokQxo r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ;
    public static final isAltPressedZmokQxo r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0;
    public static final isAltPressedZmokQxo read;
    public static final isAltPressedZmokQxo serializer;
    public static final isAltPressedZmokQxo write;

    static {
        truncslo4al4 truncslo4al4Var = new truncslo4al4(getTypeZmokQxo.serializer(), true, true);
        r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0 = truncslo4al4Var.IconCompatParcelizer(DeviceOrientationRequest.OUTPUT_PERIOD_MEDIUM, "measurement.ad_id_cache_time");
        addOnConfigurationChangedListener = truncslo4al4Var.IconCompatParcelizer(3600000L, "measurement.app_uninstalled_additional_ad_id_cache_time");
        addOnMultiWindowModeChangedListener = truncslo4al4Var.serializer("measurement.config.bundle_for_all_apps_on_backgrounded", true);
        addOnNewIntentListener = truncslo4al4Var.IconCompatParcelizer(100L, "measurement.max_bundles_per_iteration");
        addOnContextAvailableListener = truncslo4al4Var.serializer("measurement.gbraid_campaign.campaign_params_triggering_info_update", "gclid,gbraid,gad_campaignid");
        addMenuProvider = truncslo4al4Var.IconCompatParcelizer(CarGwiSoFileConstant.CAR_GWI_SPECIFY_INTERVAL, "measurement.config.cache_time");
        truncslo4al4Var.serializer("measurement.log_tag", "FA");
        addOnPictureInPictureUiStateChangedListener = truncslo4al4Var.serializer("measurement.config.url_authority", "app-measurement.com");
        enterPictureInPictureMode = truncslo4al4Var.serializer("measurement.config.url_scheme", com.adjust.sdk.Constants.SCHEME);
        addOnTrimMemoryListener = truncslo4al4Var.IconCompatParcelizer(1000L, "measurement.upload.debug_upload_interval");
        truncslo4al4Var.serializer("measurement.config.default_flag_values", true);
        addOnUserLeaveHintListener = truncslo4al4Var.IconCompatParcelizer(3600000L, "measurement.session.engagement_interval");
        addOnPictureInPictureModeChangedListener = truncslo4al4Var.serializer("measurement.rb.attribution.event_params", "value|currency");
        getActivityResultRegistry = truncslo4al4Var.serializer("measurement.edpb.events_cached_in_no_data_mode", "_f,_v,_cmp");
        getFullyDrawnReporter = truncslo4al4Var.IconCompatParcelizer(605000L, "measurement.upload.google_signal_max_queue_time");
        getLastCustomNonConfigurationInstance = truncslo4al4Var.serializer("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d");
        truncslo4al4Var.IconCompatParcelizer(0L, "measurement.id.upload.max_conversions_per_day");
        getDefaultViewModelProviderFactory = truncslo4al4Var.IconCompatParcelizer(4L, "measurement.lifetimevalue.max_currency_tracked");
        getDefaultViewModelCreationExtras = truncslo4al4Var.IconCompatParcelizer(1L, "measurement.dma_consent.max_daily_dcu_realtime_events");
        getSavedStateRegistry = truncslo4al4Var.IconCompatParcelizer(500L, "measurement.upload.max_event_parameter_value_length");
        getLifecycle = truncslo4al4Var.IconCompatParcelizer(100000L, "measurement.store.max_stored_events_per_app");
        getViewModelStore = truncslo4al4Var.IconCompatParcelizer(50L, "measurement.experiment.max_ids");
        getOnBackPressedDispatcher = truncslo4al4Var.IconCompatParcelizer(200L, "measurement.audience.filter_result_max_count");
        getNavigationEventDispatcher = truncslo4al4Var.IconCompatParcelizer(27L, "measurement.upload.max_item_scoped_custom_parameters");
        invalidateMenu = truncslo4al4Var.IconCompatParcelizer(1000L, "measurement.rb.max_trigger_registrations_per_day");
        onConfigurationChanged = truncslo4al4Var.IconCompatParcelizer(0L, "measurement.rb.attribution.max_trigger_uris_queried_at_once");
        onActivityResult = truncslo4al4Var.IconCompatParcelizer(7L, "measurement.rb.attribution.client.min_ad_services_version");
        onBackPressed = truncslo4al4Var.IconCompatParcelizer(60000L, "measurement.alarm_manager.minimum_interval");
        initializeViewTreeOwners = truncslo4al4Var.IconCompatParcelizer(500L, "measurement.upload.minimum_delay");
        RemoteActionCompatParcelizer = truncslo4al4Var.IconCompatParcelizer(CarGwiSoFileConstant.CAR_GWI_SPECIFY_INTERVAL, "measurement.monitoring.sample_period_millis");
        serializer = truncslo4al4Var.IconCompatParcelizer(ConstantsKt.DEFAULT_REQUEST_TIMEOUT, "measurement.rb.attribution.notify_app_delay_millis");
        IconCompatParcelizer = truncslo4al4Var.serializer("measurement.config.notify_trigger_uris_on_backgrounded", true);
        read = truncslo4al4Var.serializer("measurement.rb.attribution.app_allowlist", "");
        write = truncslo4al4Var.IconCompatParcelizer(DeviceOrientationRequest.OUTPUT_PERIOD_MEDIUM, "measurement.upload.realtime_upload_interval");
        MediaDescriptionCompat = truncslo4al4Var.IconCompatParcelizer(604800000L, "measurement.upload.refresh_blacklisted_config_interval");
        truncslo4al4Var.IconCompatParcelizer(3600000L, "measurement.config.cache_time.service");
        MediaBrowserCompatMediaItem = truncslo4al4Var.IconCompatParcelizer(DeviceOrientationRequest.OUTPUT_PERIOD_FAST, "measurement.service_client.idle_disconnect_millis");
        truncslo4al4Var.serializer("measurement.log_tag.service", "FA-SVC");
        RatingCompat = truncslo4al4Var.IconCompatParcelizer(1000L, "measurement.service_client.reconnect_millis");
        truncslo4al4Var.serializer("measurement.sgtm.app_allowlist", "*");
        MediaSessionCompatQueueItem = truncslo4al4Var.IconCompatParcelizer(240000L, "measurement.sgtm.batch.long_queuing_threshold");
        MediaMetadataCompat = truncslo4al4Var.IconCompatParcelizer(1800000L, "measurement.sgtm.batch.retry_interval");
        MediaSessionCompatToken = truncslo4al4Var.IconCompatParcelizer(10L, "measurement.sgtm.batch.retry_max_count");
        PlaybackStateCompat = truncslo4al4Var.IconCompatParcelizer(21600000L, "measurement.sgtm.batch.retry_max_wait");
        ParcelableVolumeInfo = truncslo4al4Var.serializer("measurement.sgtm.service_upload_apps_list", "");
        PlaybackStateCompatCustomAction = truncslo4al4Var.serializer("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504");
        MediaSessionCompatResultReceiverWrapper = truncslo4al4Var.IconCompatParcelizer(5L, "measurement.sgtm.upload.batches_retrieval_limit");
        r8lambda7IJBVrN0sHyidCAZufWEJFc7yY = truncslo4al4Var.IconCompatParcelizer(DeviceOrientationRequest.OUTPUT_PERIOD_FAST, "measurement.sgtm.upload.max_queued_batches");
        r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus = truncslo4al4Var.IconCompatParcelizer(600000L, "measurement.sgtm.upload.min_delay_after_background");
        ComponentActivity = truncslo4al4Var.IconCompatParcelizer(1000L, "measurement.sgtm.upload.min_delay_after_broadcast");
        r8lambda54BeH8ZsBru0CXI2CCSP2syNys = truncslo4al4Var.IconCompatParcelizer(DeviceOrientationRequest.OUTPUT_PERIOD_FAST, "measurement.sgtm.upload.min_delay_after_startup");
        ResultReceiver = truncslo4al4Var.IconCompatParcelizer(600000L, "measurement.sgtm.upload.retry_interval");
        r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8 = truncslo4al4Var.IconCompatParcelizer(21600000L, "measurement.sgtm.upload.retry_max_wait");
        r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss = truncslo4al4Var.IconCompatParcelizer(CarGwiSoFileConstant.CAR_GWI_SPECIFY_INTERVAL, "measurement.upload.stale_data_deletion_interval");
        r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg = truncslo4al4Var.IconCompatParcelizer(16L, "measurement.rb.attribution.max_retry_delay_seconds");
        r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM = truncslo4al4Var.IconCompatParcelizer(90L, "measurement.rb.attribution.client.min_time_after_boot_seconds");
        r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4 = truncslo4al4Var.serializer("measurement.rb.attribution.uri_authority", "google-analytics.com");
        r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ = truncslo4al4Var.IconCompatParcelizer(864000000L, "measurement.rb.attribution.max_queue_time");
        r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw = truncslo4al4Var.serializer("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion");
        r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs = truncslo4al4Var.serializer("measurement.rb.attribution.query_parameters_to_remove", "");
        r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28 = truncslo4al4Var.serializer("measurement.rb.attribution.uri_scheme", com.adjust.sdk.Constants.SCHEME);
        accessensureViewModelStore = truncslo4al4Var.IconCompatParcelizer(604800000L, "measurement.sdk.attribution.cache.ttl");
        _init_lambda3 = truncslo4al4Var.IconCompatParcelizer(7200000L, "measurement.redaction.app_instance_id.ttl");
        _init_lambda1 = truncslo4al4Var.IconCompatParcelizer(43200000L, "measurement.upload.backoff_period");
        _init_lambda2 = truncslo4al4Var.IconCompatParcelizer(15000L, "measurement.upload.initial_upload_delay_time");
        _init_lambda4 = truncslo4al4Var.IconCompatParcelizer(3600000L, "measurement.upload.interval");
        defaultViewModelProviderFactory_delegatelambda0 = truncslo4al4Var.IconCompatParcelizer(65536L, "measurement.upload.max_bundle_size");
        addObserverForBackInvoker = truncslo4al4Var.IconCompatParcelizer(100L, "measurement.upload.max_bundles");
        addObserverForBackInvokerlambda0 = truncslo4al4Var.IconCompatParcelizer(500L, "measurement.upload.max_conversions_per_day");
        ensureViewModelStore = truncslo4al4Var.IconCompatParcelizer(1000L, "measurement.upload.max_error_events_per_day");
        createFullyDrawnExecutor = truncslo4al4Var.IconCompatParcelizer(1000L, "measurement.upload.max_events_per_bundle");
        getSavedStateRegistryControllerannotations = truncslo4al4Var.IconCompatParcelizer(100000L, "measurement.upload.max_events_per_day");
        fullyDrawnReporter_delegatelambda00 = truncslo4al4Var.IconCompatParcelizer(50000L, "measurement.upload.max_public_events_per_day");
        getOnBackPressedInput = truncslo4al4Var.IconCompatParcelizer(518400000L, "measurement.upload.max_queue_time");
        menuHostHelperlambda0 = truncslo4al4Var.IconCompatParcelizer(10L, "measurement.upload.max_realtime_events_per_day");
        fullyDrawnReporter_delegatelambda0 = truncslo4al4Var.IconCompatParcelizer(65536L, "measurement.upload.max_batch_size");
        onBackPressedDispatcher_delegatelambda0 = truncslo4al4Var.IconCompatParcelizer(6L, "measurement.upload.retry_count");
        addContentView = truncslo4al4Var.IconCompatParcelizer(1800000L, "measurement.upload.retry_time");
        onBackPressedInput_delegatelambda0 = truncslo4al4Var.serializer("measurement.upload.url", "https://app-measurement.com/a");
        onBackPressedDispatcher_delegatelambda010 = truncslo4al4Var.IconCompatParcelizer(3600000L, "measurement.upload.window_interval");
        onBackPressedDispatcher_delegatelambda00 = truncslo4al4Var.serializer("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot");
    }
}
