package o;

import com.huawei.location.nlp.network.OnlineLocationService;

/* JADX INFO: loaded from: classes4.dex */
public interface PhoneCallTypeNormal {
    public static final getNetworkModule RemoteActionCompatParcelizer;

    static {
        getNetworkModule getnetworkmodule = new getNetworkModule("1.2.840.113549.1.1");
        getnetworkmodule.IconCompatParcelizer("1");
        getnetworkmodule.IconCompatParcelizer("2");
        getnetworkmodule.IconCompatParcelizer("3");
        getnetworkmodule.IconCompatParcelizer(OnlineLocationService.SRC_DEFAULT);
        TranslationsCompanion.write(getnetworkmodule, "5", "6", "7", "8");
        TranslationsCompanion.write(getnetworkmodule, "9", "10", "11", "12");
        getnetworkmodule.IconCompatParcelizer("13");
        getnetworkmodule.IconCompatParcelizer("14");
        getnetworkmodule.IconCompatParcelizer("15");
        getnetworkmodule.IconCompatParcelizer("16");
        new getNetworkModule("1.2.840.113549.1.3").IconCompatParcelizer("1");
        getNetworkModule getnetworkmodule2 = new getNetworkModule("1.2.840.113549.1.5");
        getnetworkmodule2.IconCompatParcelizer("1");
        getnetworkmodule2.IconCompatParcelizer(OnlineLocationService.SRC_DEFAULT);
        TranslationsCompanion.write(getnetworkmodule2, "3", "6", "10", "11");
        getnetworkmodule2.IconCompatParcelizer("12");
        getnetworkmodule2.IconCompatParcelizer("13");
        getnetworkmodule2.IconCompatParcelizer("14");
        getNetworkModule getnetworkmodule3 = new getNetworkModule("1.2.840.113549.3");
        getnetworkmodule3.IconCompatParcelizer("7");
        getnetworkmodule3.IconCompatParcelizer("2");
        getnetworkmodule3.IconCompatParcelizer(OnlineLocationService.SRC_DEFAULT);
        getNetworkModule getnetworkmodule4 = new getNetworkModule("1.2.840.113549.2");
        getnetworkmodule4.IconCompatParcelizer("2");
        getnetworkmodule4.IconCompatParcelizer(OnlineLocationService.SRC_DEFAULT);
        getnetworkmodule4.IconCompatParcelizer("5");
        getnetworkmodule4.IconCompatParcelizer("7").serializer();
        getnetworkmodule4.IconCompatParcelizer("8").serializer();
        getnetworkmodule4.IconCompatParcelizer("9").serializer();
        getnetworkmodule4.IconCompatParcelizer("10").serializer();
        getnetworkmodule4.IconCompatParcelizer("11").serializer();
        getnetworkmodule4.IconCompatParcelizer("12").serializer();
        getnetworkmodule4.IconCompatParcelizer("13").serializer();
        new getNetworkModule("1.2.840.113549.1.7").serializer();
        new getNetworkModule("1.2.840.113549.1.7.1").serializer();
        new getNetworkModule("1.2.840.113549.1.7.2").serializer();
        new getNetworkModule("1.2.840.113549.1.7.3").serializer();
        new getNetworkModule("1.2.840.113549.1.7.4").serializer();
        new getNetworkModule("1.2.840.113549.1.7.5").serializer();
        new getNetworkModule("1.2.840.113549.1.7.6").serializer();
        getNetworkModule getnetworkmodule5 = new getNetworkModule("1.2.840.113549.1.9");
        getnetworkmodule5.IconCompatParcelizer("1").serializer();
        getnetworkmodule5.IconCompatParcelizer("2").serializer();
        getnetworkmodule5.IconCompatParcelizer("3").serializer();
        getnetworkmodule5.IconCompatParcelizer(OnlineLocationService.SRC_DEFAULT).serializer();
        getnetworkmodule5.IconCompatParcelizer("5").serializer();
        getnetworkmodule5.IconCompatParcelizer("6").serializer();
        getnetworkmodule5.IconCompatParcelizer("7").serializer();
        getnetworkmodule5.IconCompatParcelizer("8").serializer();
        getnetworkmodule5.IconCompatParcelizer("9").serializer();
        getnetworkmodule5.IconCompatParcelizer("13").serializer();
        getnetworkmodule5.IconCompatParcelizer("14").serializer();
        getnetworkmodule5.IconCompatParcelizer("15").serializer();
        getNetworkModule getnetworkmoduleSerializer = getnetworkmodule5.IconCompatParcelizer("16").serializer();
        getnetworkmodule5.IconCompatParcelizer("16.2.46").serializer();
        getnetworkmodule5.IconCompatParcelizer("20").serializer();
        getnetworkmodule5.IconCompatParcelizer("21").serializer();
        getnetworkmodule5.IconCompatParcelizer("22.1");
        getNetworkModule getnetworkmoduleIconCompatParcelizer = getnetworkmodule5.IconCompatParcelizer("22");
        getnetworkmoduleIconCompatParcelizer.IconCompatParcelizer("1").serializer();
        getnetworkmoduleIconCompatParcelizer.IconCompatParcelizer("2").serializer();
        getnetworkmodule5.IconCompatParcelizer("23").IconCompatParcelizer("1").serializer();
        getnetworkmodule5.IconCompatParcelizer("52").serializer();
        getnetworkmodule5.IconCompatParcelizer("15.1");
        getnetworkmodule5.IconCompatParcelizer("15.2");
        getnetworkmodule5.IconCompatParcelizer("15.3");
        getNetworkModule getnetworkmodule6 = new getNetworkModule("1.2.840.113549.1.9.16.1");
        getnetworkmodule6.IconCompatParcelizer("2");
        TranslationsCompanion.write(getnetworkmodule6, OnlineLocationService.SRC_DEFAULT, "9", "23", "31");
        getNetworkModule getnetworkmoduleIconCompatParcelizer2 = getnetworkmoduleSerializer.IconCompatParcelizer("3");
        getnetworkmoduleIconCompatParcelizer2.IconCompatParcelizer("5");
        getnetworkmoduleIconCompatParcelizer2.IconCompatParcelizer("6");
        getnetworkmoduleIconCompatParcelizer2.IconCompatParcelizer("7");
        TranslationsCompanion.write(getnetworkmoduleIconCompatParcelizer2, "8", "9", "10", "14");
        RemoteActionCompatParcelizer = getnetworkmoduleIconCompatParcelizer2.IconCompatParcelizer("17");
        getnetworkmoduleIconCompatParcelizer2.IconCompatParcelizer("18");
        getnetworkmoduleIconCompatParcelizer2.IconCompatParcelizer("28");
        getnetworkmoduleIconCompatParcelizer2.IconCompatParcelizer("29");
        getnetworkmoduleIconCompatParcelizer2.IconCompatParcelizer("30");
        getNetworkModule getnetworkmodule7 = new getNetworkModule("1.2.840.113549.1.9.16.6");
        getnetworkmodule7.IconCompatParcelizer("1");
        getnetworkmodule7.IconCompatParcelizer("2");
        getnetworkmodule7.IconCompatParcelizer("3");
        getnetworkmodule7.IconCompatParcelizer(OnlineLocationService.SRC_DEFAULT);
        getnetworkmodule7.IconCompatParcelizer("5");
        getnetworkmodule7.IconCompatParcelizer("6");
        getNetworkModule getnetworkmodule8 = new getNetworkModule("1.2.840.113549.1.9.16.2");
        getnetworkmodule8.IconCompatParcelizer("1");
        TranslationsCompanion.write(getnetworkmodule8, OnlineLocationService.SRC_DEFAULT, "5", "10", "11");
        TranslationsCompanion.write(getnetworkmodule8, "12", "47", "7", "14");
        TranslationsCompanion.write(getnetworkmodule8, "15", "16", "17", "18");
        TranslationsCompanion.write(getnetworkmodule8, "19", "20", "21", "22");
        TranslationsCompanion.write(getnetworkmodule8, "23", "24", "25", "26");
        TranslationsCompanion.write(getnetworkmodule8, "27", "37", "38", "54");
        getnetworkmodule8.IconCompatParcelizer("43");
        getnetworkmodule8.IconCompatParcelizer("40");
        new getNetworkModule("1.2.840.113549.1.9.16.5.1");
        new getNetworkModule("1.2.840.113549.1.9.16.5.2");
        getNetworkModule getnetworkmodule9 = new getNetworkModule("1.2.840.113549.1.12");
        getNetworkModule getnetworkmoduleIconCompatParcelizer3 = getnetworkmodule9.IconCompatParcelizer("10.1");
        getnetworkmoduleIconCompatParcelizer3.IconCompatParcelizer("1");
        getnetworkmoduleIconCompatParcelizer3.IconCompatParcelizer("2");
        getnetworkmoduleIconCompatParcelizer3.IconCompatParcelizer("3");
        getnetworkmoduleIconCompatParcelizer3.IconCompatParcelizer(OnlineLocationService.SRC_DEFAULT);
        getnetworkmoduleIconCompatParcelizer3.IconCompatParcelizer("5");
        getnetworkmoduleIconCompatParcelizer3.IconCompatParcelizer("6");
        getNetworkModule getnetworkmoduleIconCompatParcelizer4 = getnetworkmodule9.IconCompatParcelizer("1");
        getnetworkmoduleIconCompatParcelizer4.IconCompatParcelizer("1");
        getnetworkmoduleIconCompatParcelizer4.IconCompatParcelizer("2");
        getnetworkmoduleIconCompatParcelizer4.IconCompatParcelizer("3");
        TranslationsCompanion.write(getnetworkmoduleIconCompatParcelizer4, OnlineLocationService.SRC_DEFAULT, "5", "6", "6");
    }
}
