package o;

import bo.app.m1$$ExternalSyntheticOutline0;
import com.huawei.hms.location.ActivityIdentificationData;
import com.huawei.location.gwi.util.GwiErrorCode;

/* JADX INFO: loaded from: classes2.dex */
public final class PointerHoverIconModifierElement implements accessdetachAndRemoveNode {
    public static final accessgetAggregateChildKindSet ComponentActivity;
    public static final accessgetAggregateChildKindSet ComponentDialog;
    public static final accessgetAggregateChildKindSet ComponentDialogExternalSyntheticLambda0;
    public static final accessgetAggregateChildKindSet EdgeToEdgeExternalSyntheticLambda0;
    public static final accessgetAggregateChildKindSet IconCompatParcelizer;
    public static final accessgetAggregateChildKindSet MediaBrowserCompatMediaItem;
    public static final accessgetAggregateChildKindSet MediaDescriptionCompat;
    public static final accessgetAggregateChildKindSet MediaMetadataCompat;
    public static final accessgetAggregateChildKindSet MediaSessionCompatQueueItem;
    public static final accessgetAggregateChildKindSet MediaSessionCompatResultReceiverWrapper;
    public static final accessgetAggregateChildKindSet MediaSessionCompatToken;
    public static final accessgetAggregateChildKindSet OnBackPressedCallback;
    public static final accessgetAggregateChildKindSet OnBackPressedDispatcherOnBackPressedEventInputExternalSyntheticLambda0;
    public static final accessgetAggregateChildKindSet ParcelableVolumeInfo;
    public static final accessgetAggregateChildKindSet PlaybackStateCompat;
    public static final accessgetAggregateChildKindSet PlaybackStateCompatCustomAction;
    public static final accessgetAggregateChildKindSet RatingCompat;
    public static final accessgetAggregateChildKindSet RemoteActionCompatParcelizer;
    public static final accessgetAggregateChildKindSet ResultReceiver;
    public static final accessgetAggregateChildKindSet SystemBarStyleCompanion;
    public static final accessgetAggregateChildKindSet _init_lambda1;
    public static final accessgetAggregateChildKindSet _init_lambda2;
    public static final accessgetAggregateChildKindSet _init_lambda3;
    public static final accessgetAggregateChildKindSet _init_lambda4;
    public static final accessgetAggregateChildKindSet accessensureViewModelStore;
    public static final accessgetAggregateChildKindSet addCloseableactivity;
    public static final accessgetAggregateChildKindSet addContentView;
    public static final accessgetAggregateChildKindSet addMenuProvider;
    public static final accessgetAggregateChildKindSet addObserverForBackInvoker;
    public static final accessgetAggregateChildKindSet addObserverForBackInvokerlambda0;
    public static final accessgetAggregateChildKindSet addOnConfigurationChangedListener;
    public static final accessgetAggregateChildKindSet addOnContextAvailableListener;
    public static final accessgetAggregateChildKindSet addOnMultiWindowModeChangedListener;
    public static final accessgetAggregateChildKindSet addOnNewIntentListener;
    public static final accessgetAggregateChildKindSet addOnPictureInPictureModeChangedListener;
    public static final accessgetAggregateChildKindSet addOnPictureInPictureUiStateChangedListener;
    public static final accessgetAggregateChildKindSet addOnTrimMemoryListener;
    public static final accessgetAggregateChildKindSet addOnUserLeaveHintListener;
    public static final accessgetAggregateChildKindSet createFullyDrawnExecutor;
    public static final accessgetAggregateChildKindSet createNavigationEventHandleractivity;
    public static final accessgetAggregateChildKindSet defaultViewModelProviderFactory_delegatelambda0;
    public static final accessgetAggregateChildKindSet ensureViewModelStore;
    public static final accessgetAggregateChildKindSet enterPictureInPictureMode;
    public static final accessgetAggregateChildKindSet fullyDrawnReporter_delegatelambda0;
    public static final accessgetAggregateChildKindSet fullyDrawnReporter_delegatelambda00;
    public static final accessgetAggregateChildKindSet getActivityResultRegistry;
    public static final accessgetAggregateChildKindSet getDefaultViewModelCreationExtras;
    public static final accessgetAggregateChildKindSet getDefaultViewModelProviderFactory;
    public static final accessgetAggregateChildKindSet getFullyDrawnReporter;
    public static final accessgetAggregateChildKindSet getIndexOfFirstFeature;
    public static final accessgetAggregateChildKindSet getLastCustomNonConfigurationInstance;
    public static final accessgetAggregateChildKindSet getLifecycle;
    public static final accessgetAggregateChildKindSet getLifecycleRegistry1;
    public static final accessgetAggregateChildKindSet getNavigationEventDispatcher;
    public static final accessgetAggregateChildKindSet getOnBackPressedDispatcher;
    public static final accessgetAggregateChildKindSet getOnBackPressedDispatcherannotations;
    public static final accessgetAggregateChildKindSet getOnBackPressedInput;
    public static final accessgetAggregateChildKindSet getSavedStateRegistry;
    public static final accessgetAggregateChildKindSet getSavedStateRegistryControllerannotations;
    public static final accessgetAggregateChildKindSet getViewModelStore;
    public static final accessgetAggregateChildKindSet handleOnBackCancelled;
    public static final accessgetAggregateChildKindSet handleOnBackPressed;
    public static final accessgetAggregateChildKindSet handleOnBackProgressed;
    public static final accessgetAggregateChildKindSet handleOnBackStarted;
    public static final accessgetAggregateChildKindSet initializeViewTreeOwners;
    public static final accessgetAggregateChildKindSet invalidateMenu;
    public static final accessgetAggregateChildKindSet invoke;
    public static final accessgetAggregateChildKindSet isEnabled;
    public static final accessgetAggregateChildKindSet menuHostHelperlambda0;
    public static final accessgetAggregateChildKindSet onActivityResult;
    public static final accessgetAggregateChildKindSet onBackPressed;
    public static final accessgetAggregateChildKindSet onBackPressedDispatcher_delegatelambda0;
    public static final accessgetAggregateChildKindSet onBackPressedDispatcher_delegatelambda00;
    public static final accessgetAggregateChildKindSet onBackPressedDispatcher_delegatelambda010;
    public static final accessgetAggregateChildKindSet onBackPressedInput_delegatelambda0;
    public static final accessgetAggregateChildKindSet onConfigurationChanged;
    public static final accessgetAggregateChildKindSet onCreate;
    public static final accessgetAggregateChildKindSet onCreatePanelMenu;
    public static final accessgetAggregateChildKindSet onMenuItemSelected;
    public static final accessgetAggregateChildKindSet onMultiWindowModeChanged;
    public static final accessgetAggregateChildKindSet onNewIntent;
    public static final accessgetAggregateChildKindSet onPanelClosed;
    public static final accessgetAggregateChildKindSet onPictureInPictureModeChanged;
    public static final accessgetAggregateChildKindSet onPictureInPictureUiStateChanged;
    public static final accessgetAggregateChildKindSet onPreparePanel;
    public static final accessgetAggregateChildKindSet onRequestPermissionsResult;
    public static final accessgetAggregateChildKindSet onRetainCustomNonConfigurationInstance;
    public static final accessgetAggregateChildKindSet onRetainNonConfigurationInstance;
    public static final accessgetAggregateChildKindSet onSaveInstanceState;
    public static final accessgetAggregateChildKindSet onStart;
    public static final accessgetAggregateChildKindSet onStop;
    public static final accessgetAggregateChildKindSet onTrimMemory;
    public static final accessgetAggregateChildKindSet onUserLeaveHint;
    public static final accessgetAggregateChildKindSet peekAvailableContext;
    public static final accessgetAggregateChildKindSet r8lambda54BeH8ZsBru0CXI2CCSP2syNys;
    public static final accessgetAggregateChildKindSet r8lambda7IJBVrN0sHyidCAZufWEJFc7yY;
    public static final accessgetAggregateChildKindSet r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus;
    public static final accessgetAggregateChildKindSet r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss;
    public static final accessgetAggregateChildKindSet r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg;
    public static final accessgetAggregateChildKindSet r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8;
    public static final accessgetAggregateChildKindSet r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4;
    public static final accessgetAggregateChildKindSet r8lambdaXxpmZzi8FNPM2sJJA30VCt2mBcQ;
    public static final accessgetAggregateChildKindSet r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM;
    public static final accessgetAggregateChildKindSet r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs;
    public static final accessgetAggregateChildKindSet r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28;
    public static final accessgetAggregateChildKindSet r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw;
    public static final PointerHoverIconModifierElement r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ = new PointerHoverIconModifierElement();
    public static final accessgetAggregateChildKindSet r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0;
    public static final accessgetAggregateChildKindSet read;
    public static final accessgetAggregateChildKindSet registerForActivityResult;
    public static final accessgetAggregateChildKindSet remove;
    public static final accessgetAggregateChildKindSet removeCloseableactivity;
    public static final accessgetAggregateChildKindSet removeMenuProvider;
    public static final accessgetAggregateChildKindSet removeOnConfigurationChangedListener;
    public static final accessgetAggregateChildKindSet removeOnContextAvailableListener;
    public static final accessgetAggregateChildKindSet removeOnMultiWindowModeChangedListener;
    public static final accessgetAggregateChildKindSet removeOnNewIntentListener;
    public static final accessgetAggregateChildKindSet removeOnPictureInPictureModeChangedListener;
    public static final accessgetAggregateChildKindSet removeOnPictureInPictureUiStateChangedListener;
    public static final accessgetAggregateChildKindSet removeOnTrimMemoryListener;
    public static final accessgetAggregateChildKindSet removeOnUserLeaveHintListener;
    public static final accessgetAggregateChildKindSet reportFullyDrawn;
    public static final accessgetAggregateChildKindSet run;
    public static final accessgetAggregateChildKindSet serializer;
    public static final accessgetAggregateChildKindSet setContentView;
    public static final accessgetAggregateChildKindSet setPictureInPictureParams;
    public static final accessgetAggregateChildKindSet startActivityForResult;
    public static final accessgetAggregateChildKindSet startIntentSenderForResult;
    public static final accessgetAggregateChildKindSet write;

    static {
        getComposePointerId_I2yYro getcomposepointerid_i2yyro = getComposePointerId_I2yYro.DEFAULT;
        onMultiWindowModeChanged = new accessgetAggregateChildKindSet("systemInfo", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(1, getcomposepointerid_i2yyro))));
        startIntentSenderForResult = new accessgetAggregateChildKindSet("eventName", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(2, getcomposepointerid_i2yyro))));
        getLifecycleRegistry1 = new accessgetAggregateChildKindSet("isThickClient", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(37, getcomposepointerid_i2yyro))));
        ComponentDialog = new accessgetAggregateChildKindSet("clientType", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(61, getcomposepointerid_i2yyro))));
        r8lambdaXxpmZzi8FNPM2sJJA30VCt2mBcQ = new accessgetAggregateChildKindSet("modelDownloadLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(3, getcomposepointerid_i2yyro))));
        getOnBackPressedDispatcherannotations = new accessgetAggregateChildKindSet("customModelLoadLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(20, getcomposepointerid_i2yyro))));
        EdgeToEdgeExternalSyntheticLambda0 = new accessgetAggregateChildKindSet("customModelInferenceLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(4, getcomposepointerid_i2yyro))));
        onStart = new accessgetAggregateChildKindSet("customModelCreateLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(29, getcomposepointerid_i2yyro))));
        onStop = new accessgetAggregateChildKindSet("onDeviceFaceDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(5, getcomposepointerid_i2yyro))));
        invoke = new accessgetAggregateChildKindSet("onDeviceFaceLoadLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(59, getcomposepointerid_i2yyro))));
        ComponentDialogExternalSyntheticLambda0 = new accessgetAggregateChildKindSet("onDeviceTextDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(6, getcomposepointerid_i2yyro))));
        run = new accessgetAggregateChildKindSet("onDeviceTextDetectionLoadLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(79, getcomposepointerid_i2yyro))));
        createNavigationEventHandleractivity = new accessgetAggregateChildKindSet("onDeviceBarcodeDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(7, getcomposepointerid_i2yyro))));
        OnBackPressedCallback = new accessgetAggregateChildKindSet("onDeviceBarcodeLoadLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(58, getcomposepointerid_i2yyro))));
        addCloseableactivity = new accessgetAggregateChildKindSet("onDeviceImageLabelCreateLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(48, getcomposepointerid_i2yyro))));
        handleOnBackCancelled = new accessgetAggregateChildKindSet("onDeviceImageLabelLoadLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(49, getcomposepointerid_i2yyro))));
        handleOnBackProgressed = new accessgetAggregateChildKindSet("onDeviceImageLabelDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(18, getcomposepointerid_i2yyro))));
        remove = new accessgetAggregateChildKindSet("onDeviceObjectCreateLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(26, getcomposepointerid_i2yyro))));
        handleOnBackStarted = new accessgetAggregateChildKindSet("onDeviceObjectLoadLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(27, getcomposepointerid_i2yyro))));
        handleOnBackPressed = new accessgetAggregateChildKindSet("onDeviceObjectInferenceLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(28, getcomposepointerid_i2yyro))));
        isEnabled = new accessgetAggregateChildKindSet("onDevicePoseDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(44, getcomposepointerid_i2yyro))));
        removeCloseableactivity = new accessgetAggregateChildKindSet("onDeviceSegmentationLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(45, getcomposepointerid_i2yyro))));
        SystemBarStyleCompanion = new accessgetAggregateChildKindSet("onDeviceSmartReplyLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(19, getcomposepointerid_i2yyro))));
        OnBackPressedDispatcherOnBackPressedEventInputExternalSyntheticLambda0 = new accessgetAggregateChildKindSet("onDeviceLanguageIdentificationLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(21, getcomposepointerid_i2yyro))));
        getIndexOfFirstFeature = new accessgetAggregateChildKindSet("onDeviceTranslationLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(22, getcomposepointerid_i2yyro))));
        write = new accessgetAggregateChildKindSet("cloudFaceDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(8, getcomposepointerid_i2yyro))));
        IconCompatParcelizer = new accessgetAggregateChildKindSet("cloudCropHintDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(9, getcomposepointerid_i2yyro))));
        RemoteActionCompatParcelizer = new accessgetAggregateChildKindSet("cloudDocumentTextDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(10, getcomposepointerid_i2yyro))));
        serializer = new accessgetAggregateChildKindSet("cloudImagePropertiesDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(11, getcomposepointerid_i2yyro))));
        read = new accessgetAggregateChildKindSet("cloudImageLabelDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(12, getcomposepointerid_i2yyro))));
        MediaMetadataCompat = new accessgetAggregateChildKindSet("cloudLandmarkDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(13, getcomposepointerid_i2yyro))));
        MediaSessionCompatQueueItem = new accessgetAggregateChildKindSet("cloudLogoDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(14, getcomposepointerid_i2yyro))));
        RatingCompat = new accessgetAggregateChildKindSet("cloudSafeSearchDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(15, getcomposepointerid_i2yyro))));
        MediaBrowserCompatMediaItem = new accessgetAggregateChildKindSet("cloudTextDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(16, getcomposepointerid_i2yyro))));
        MediaDescriptionCompat = new accessgetAggregateChildKindSet("cloudWebSearchDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(17, getcomposepointerid_i2yyro))));
        ParcelableVolumeInfo = new accessgetAggregateChildKindSet("automlImageLabelingCreateLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(23, getcomposepointerid_i2yyro))));
        MediaSessionCompatResultReceiverWrapper = new accessgetAggregateChildKindSet("automlImageLabelingLoadLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(24, getcomposepointerid_i2yyro))));
        PlaybackStateCompatCustomAction = new accessgetAggregateChildKindSet("automlImageLabelingInferenceLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(25, getcomposepointerid_i2yyro))));
        MediaSessionCompatToken = new accessgetAggregateChildKindSet("isModelDownloadedLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(39, getcomposepointerid_i2yyro))));
        PlaybackStateCompat = new accessgetAggregateChildKindSet("deleteModelLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(40, getcomposepointerid_i2yyro))));
        r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus = new accessgetAggregateChildKindSet("aggregatedAutomlImageLabelingInferenceLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(30, getcomposepointerid_i2yyro))));
        ComponentActivity = new accessgetAggregateChildKindSet("aggregatedCustomModelInferenceLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(31, getcomposepointerid_i2yyro))));
        r8lambda7IJBVrN0sHyidCAZufWEJFc7yY = new accessgetAggregateChildKindSet("aggregatedOnDeviceFaceDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(32, getcomposepointerid_i2yyro))));
        r8lambda54BeH8ZsBru0CXI2CCSP2syNys = new accessgetAggregateChildKindSet("aggregatedOnDeviceBarcodeDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(33, getcomposepointerid_i2yyro))));
        ResultReceiver = new accessgetAggregateChildKindSet("aggregatedOnDeviceImageLabelDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(34, getcomposepointerid_i2yyro))));
        r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4 = new accessgetAggregateChildKindSet("aggregatedOnDeviceObjectInferenceLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(35, getcomposepointerid_i2yyro))));
        r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss = new accessgetAggregateChildKindSet("aggregatedOnDeviceTextDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(36, getcomposepointerid_i2yyro))));
        r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8 = new accessgetAggregateChildKindSet("aggregatedOnDevicePoseDetectionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(46, getcomposepointerid_i2yyro))));
        r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg = new accessgetAggregateChildKindSet("aggregatedOnDeviceSegmentationLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(47, getcomposepointerid_i2yyro))));
        r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM = new accessgetAggregateChildKindSet("pipelineAccelerationInferenceEvents", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(69, getcomposepointerid_i2yyro))));
        r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw = new accessgetAggregateChildKindSet("remoteConfigLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(42, getcomposepointerid_i2yyro))));
        addOnConfigurationChangedListener = new accessgetAggregateChildKindSet("inputImageConstructionLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(50, getcomposepointerid_i2yyro))));
        addMenuProvider = new accessgetAggregateChildKindSet("leakedHandleEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(51, getcomposepointerid_i2yyro))));
        enterPictureInPictureMode = new accessgetAggregateChildKindSet("cameraSourceLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(52, getcomposepointerid_i2yyro))));
        addOnTrimMemoryListener = new accessgetAggregateChildKindSet("imageLabelOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(53, getcomposepointerid_i2yyro))));
        addOnPictureInPictureModeChangedListener = new accessgetAggregateChildKindSet("languageIdentificationOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(54, getcomposepointerid_i2yyro))));
        addOnUserLeaveHintListener = new accessgetAggregateChildKindSet("faceDetectionOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(60, getcomposepointerid_i2yyro))));
        addOnPictureInPictureUiStateChangedListener = new accessgetAggregateChildKindSet("documentDetectionOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(85, getcomposepointerid_i2yyro))));
        getDefaultViewModelCreationExtras = new accessgetAggregateChildKindSet("documentCroppingOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(86, getcomposepointerid_i2yyro))));
        getDefaultViewModelProviderFactory = new accessgetAggregateChildKindSet("documentEnhancementOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(87, getcomposepointerid_i2yyro))));
        getFullyDrawnReporter = new accessgetAggregateChildKindSet("nlClassifierOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(55, getcomposepointerid_i2yyro))));
        getLastCustomNonConfigurationInstance = new accessgetAggregateChildKindSet("nlClassifierClientLibraryLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(56, getcomposepointerid_i2yyro))));
        getActivityResultRegistry = new accessgetAggregateChildKindSet("accelerationAllowlistLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(57, getcomposepointerid_i2yyro))));
        getOnBackPressedDispatcher = new accessgetAggregateChildKindSet("toxicityDetectionCreateEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(62, getcomposepointerid_i2yyro))));
        getNavigationEventDispatcher = new accessgetAggregateChildKindSet("toxicityDetectionLoadEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(63, getcomposepointerid_i2yyro))));
        getSavedStateRegistry = new accessgetAggregateChildKindSet("toxicityDetectionInferenceEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(64, getcomposepointerid_i2yyro))));
        getLifecycle = new accessgetAggregateChildKindSet("barcodeDetectionOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(65, getcomposepointerid_i2yyro))));
        getViewModelStore = new accessgetAggregateChildKindSet("customImageLabelOptionalModuleLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(66, getcomposepointerid_i2yyro))));
        onActivityResult = new accessgetAggregateChildKindSet("codeScannerScanApiEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(67, getcomposepointerid_i2yyro))));
        initializeViewTreeOwners = new accessgetAggregateChildKindSet("codeScannerOptionalModuleEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(68, getcomposepointerid_i2yyro))));
        onBackPressed = new accessgetAggregateChildKindSet("onDeviceExplicitContentCreateLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(70, getcomposepointerid_i2yyro))));
        onConfigurationChanged = new accessgetAggregateChildKindSet("onDeviceExplicitContentLoadLogEvent", m1$$ExternalSyntheticOutline0.m(r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.RemoteActionCompatParcelizer(getMotionEventToComposePointerIdMapuiannotations.class, new MotionEventAdapter(71, getcomposepointerid_i2yyro))));
        invalidateMenu = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(72, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceExplicitContentInferenceLogEvent"));
        onCreatePanelMenu = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(73, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("aggregatedOnDeviceExplicitContentLogEvent"));
        onNewIntent = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(74, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceFaceMeshCreateLogEvent"));
        onCreate = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(75, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceFaceMeshLoadLogEvent"));
        onMenuItemSelected = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(76, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceFaceMeshLogEvent"));
        r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0 = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(77, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("aggregatedOnDeviceFaceMeshLogEvent"));
        r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(78, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("smartReplyOptionalModuleLogEvent"));
        r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28 = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(80, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("textDetectionOptionalModuleLogEvent"));
        accessensureViewModelStore = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(81, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceImageQualityAnalysisCreateLogEvent"));
        _init_lambda3 = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(82, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceImageQualityAnalysisLoadLogEvent"));
        _init_lambda2 = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(83, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceImageQualityAnalysisLogEvent"));
        _init_lambda1 = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(84, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("aggregatedOnDeviceImageQualityAnalysisLogEvent"));
        _init_lambda4 = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(88, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("imageQualityAnalysisOptionalModuleLogEvent"));
        addObserverForBackInvokerlambda0 = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(89, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("imageCaptioningOptionalModuleLogEvent"));
        defaultViewModelProviderFactory_delegatelambda0 = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(90, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceImageCaptioningCreateLogEvent"));
        createFullyDrawnExecutor = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(91, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceImageCaptioningLoadLogEvent"));
        addObserverForBackInvoker = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(92, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceImageCaptioningInferenceLogEvent"));
        ensureViewModelStore = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(93, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("aggregatedOnDeviceImageCaptioningInferenceLogEvent"));
        fullyDrawnReporter_delegatelambda0 = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(94, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceDocumentDetectionCreateLogEvent"));
        getOnBackPressedInput = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(95, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceDocumentDetectionLoadLogEvent"));
        fullyDrawnReporter_delegatelambda00 = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(96, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceDocumentDetectionLogEvent"));
        getSavedStateRegistryControllerannotations = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(97, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("aggregatedOnDeviceDocumentDetectionLogEvent"));
        menuHostHelperlambda0 = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(98, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceDocumentCroppingCreateLogEvent"));
        onBackPressedDispatcher_delegatelambda00 = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(99, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceDocumentCroppingLoadLogEvent"));
        onBackPressedInput_delegatelambda0 = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(100, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceDocumentCroppingLogEvent"));
        addContentView = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(101, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("aggregatedOnDeviceDocumentCroppingLogEvent"));
        onBackPressedDispatcher_delegatelambda0 = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(102, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceDocumentEnhancementCreateLogEvent"));
        onBackPressedDispatcher_delegatelambda010 = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(103, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceDocumentEnhancementLoadLogEvent"));
        addOnContextAvailableListener = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(104, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceDocumentEnhancementLogEvent"));
        addOnNewIntentListener = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(105, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("aggregatedOnDeviceDocumentEnhancementLogEvent"));
        addOnMultiWindowModeChangedListener = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(GwiErrorCode.ALG_LIBRARY_NOT_EXIST, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("scannerAutoZoomEvent"));
        onPreparePanel = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(107, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("lowLightAutoExposureComputationEvent"));
        onPictureInPictureUiStateChanged = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(ActivityIdentificationData.RUNNING, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("lowLightFrameProcessEvent"));
        onPanelClosed = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(109, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("lowLightSceneDetectionEvent"));
        onPictureInPictureModeChanged = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(110, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceStainRemovalLogEvent"));
        onRequestPermissionsResult = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(111, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("aggregatedOnDeviceStainRemovalLogEvent"));
        onTrimMemory = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(112, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("stainRemovalOptionalModuleLogEvent"));
        onRetainCustomNonConfigurationInstance = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(113, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceShadowRemovalLogEvent"));
        onUserLeaveHint = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(114, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("aggregatedOnDeviceShadowRemovalLogEvent"));
        onRetainNonConfigurationInstance = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(115, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("shadowRemovalOptionalModuleLogEvent"));
        onSaveInstanceState = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(116, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceDigitalInkSegmentationLogEvent"));
        removeMenuProvider = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(117, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceDocumentScannerStartLogEvent"));
        removeOnConfigurationChangedListener = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(118, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceDocumentScannerFinishLogEvent"));
        registerForActivityResult = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(119, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceDocumentScannerUiStartLogEvent"));
        peekAvailableContext = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(120, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceDocumentScannerUiFinishLogEvent"));
        removeOnContextAvailableListener = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(121, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("documentScannerUiOptionalModuleSessionStartLogEvent"));
        removeOnPictureInPictureUiStateChangedListener = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(122, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("documentScannerUiOptionalModuleSessionFinishLogEvent"));
        removeOnPictureInPictureModeChangedListener = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(123, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceDocumentScannerUiCreateLogEvent"));
        removeOnNewIntentListener = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(124, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceSubjectSegmentationCreateLogEvent"));
        removeOnTrimMemoryListener = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(125, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceSubjectSegmentationLoadLogEvent"));
        removeOnMultiWindowModeChangedListener = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(126, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("onDeviceSubjectSegmentationInferenceLogEvent"));
        removeOnUserLeaveHintListener = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(127, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("aggregatedOnDeviceSubjectSegmentationLogEvent"));
        reportFullyDrawn = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(androidx.compose.ui.graphics.Fields.SpotShadowColor, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("subjectSegmentationOptionalModuleLogEvent"));
        setContentView = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(129, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("documentScannerUiModuleScreenViewEvent"));
        setPictureInPictureParams = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(130, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("documentScannerUiModuleScreenClickEvent"));
        startActivityForResult = r8lambdaLssewuUnwz__zuwPAhaX4NMGewA.serializer(131, getcomposepointerid_i2yyro, accessgetAggregateChildKindSet.write("documentScannerUiModuleScreenErrorEvent"));
    }

    @Override // o.accessgetLoggerp
    public final void serializer(Object obj, Object obj2) {
        dispatchToView dispatchtoview = (dispatchToView) obj;
        accessupdateNode accessupdatenode = (accessupdateNode) obj2;
        accessupdatenode.write(onMultiWindowModeChanged, dispatchtoview.IconCompatParcelizer);
        accessupdatenode.write(startIntentSenderForResult, dispatchtoview.read);
        accessupdatenode.write(getLifecycleRegistry1, (Object) null);
        accessupdatenode.write(ComponentDialog, dispatchtoview.RemoteActionCompatParcelizer);
        accessupdatenode.write(r8lambdaXxpmZzi8FNPM2sJJA30VCt2mBcQ, (Object) null);
        accessupdatenode.write(getOnBackPressedDispatcherannotations, (Object) null);
        accessupdatenode.write(EdgeToEdgeExternalSyntheticLambda0, (Object) null);
        accessupdatenode.write(onStart, (Object) null);
        accessupdatenode.write(onStop, (Object) null);
        accessupdatenode.write(invoke, (Object) null);
        accessupdatenode.write(ComponentDialogExternalSyntheticLambda0, (Object) null);
        accessupdatenode.write(run, (Object) null);
        accessupdatenode.write(createNavigationEventHandleractivity, dispatchtoview.serializer);
        accessupdatenode.write(OnBackPressedCallback, dispatchtoview.write);
        accessupdatenode.write(addCloseableactivity, (Object) null);
        accessupdatenode.write(handleOnBackCancelled, (Object) null);
        accessupdatenode.write(handleOnBackProgressed, (Object) null);
        accessupdatenode.write(remove, (Object) null);
        accessupdatenode.write(handleOnBackStarted, (Object) null);
        accessupdatenode.write(handleOnBackPressed, (Object) null);
        accessupdatenode.write(isEnabled, (Object) null);
        accessupdatenode.write(removeCloseableactivity, (Object) null);
        accessupdatenode.write(SystemBarStyleCompanion, (Object) null);
        accessupdatenode.write(OnBackPressedDispatcherOnBackPressedEventInputExternalSyntheticLambda0, (Object) null);
        accessupdatenode.write(getIndexOfFirstFeature, (Object) null);
        accessupdatenode.write(write, (Object) null);
        accessupdatenode.write(IconCompatParcelizer, (Object) null);
        accessupdatenode.write(RemoteActionCompatParcelizer, (Object) null);
        accessupdatenode.write(serializer, (Object) null);
        accessupdatenode.write(read, (Object) null);
        accessupdatenode.write(MediaMetadataCompat, (Object) null);
        accessupdatenode.write(MediaSessionCompatQueueItem, (Object) null);
        accessupdatenode.write(RatingCompat, (Object) null);
        accessupdatenode.write(MediaBrowserCompatMediaItem, (Object) null);
        accessupdatenode.write(MediaDescriptionCompat, (Object) null);
        accessupdatenode.write(ParcelableVolumeInfo, (Object) null);
        accessupdatenode.write(MediaSessionCompatResultReceiverWrapper, (Object) null);
        accessupdatenode.write(PlaybackStateCompatCustomAction, (Object) null);
        accessupdatenode.write(MediaSessionCompatToken, (Object) null);
        accessupdatenode.write(PlaybackStateCompat, (Object) null);
        accessupdatenode.write(r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus, (Object) null);
        accessupdatenode.write(ComponentActivity, (Object) null);
        accessupdatenode.write(r8lambda7IJBVrN0sHyidCAZufWEJFc7yY, (Object) null);
        accessupdatenode.write(r8lambda54BeH8ZsBru0CXI2CCSP2syNys, dispatchtoview.MediaBrowserCompatMediaItem);
        accessupdatenode.write(ResultReceiver, (Object) null);
        accessupdatenode.write(r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4, (Object) null);
        accessupdatenode.write(r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss, (Object) null);
        accessupdatenode.write(r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8, (Object) null);
        accessupdatenode.write(r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg, (Object) null);
        accessupdatenode.write(r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM, (Object) null);
        accessupdatenode.write(r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw, (Object) null);
        accessupdatenode.write(addOnConfigurationChangedListener, (Object) null);
        accessupdatenode.write(addMenuProvider, (Object) null);
        accessupdatenode.write(enterPictureInPictureMode, (Object) null);
        accessupdatenode.write(addOnTrimMemoryListener, (Object) null);
        accessupdatenode.write(addOnPictureInPictureModeChangedListener, (Object) null);
        accessupdatenode.write(addOnUserLeaveHintListener, (Object) null);
        accessupdatenode.write(addOnPictureInPictureUiStateChangedListener, (Object) null);
        accessupdatenode.write(getDefaultViewModelCreationExtras, (Object) null);
        accessupdatenode.write(getDefaultViewModelProviderFactory, (Object) null);
        accessupdatenode.write(getFullyDrawnReporter, (Object) null);
        accessupdatenode.write(getLastCustomNonConfigurationInstance, (Object) null);
        accessupdatenode.write(getActivityResultRegistry, (Object) null);
        accessupdatenode.write(getOnBackPressedDispatcher, (Object) null);
        accessupdatenode.write(getNavigationEventDispatcher, (Object) null);
        accessupdatenode.write(getSavedStateRegistry, (Object) null);
        accessupdatenode.write(getLifecycle, (Object) null);
        accessupdatenode.write(getViewModelStore, (Object) null);
        accessupdatenode.write(onActivityResult, (Object) null);
        accessupdatenode.write(initializeViewTreeOwners, (Object) null);
        accessupdatenode.write(onBackPressed, (Object) null);
        accessupdatenode.write(onConfigurationChanged, (Object) null);
        accessupdatenode.write(invalidateMenu, (Object) null);
        accessupdatenode.write(onCreatePanelMenu, (Object) null);
        accessupdatenode.write(onNewIntent, (Object) null);
        accessupdatenode.write(onCreate, (Object) null);
        accessupdatenode.write(onMenuItemSelected, (Object) null);
        accessupdatenode.write(r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0, (Object) null);
        accessupdatenode.write(r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs, (Object) null);
        accessupdatenode.write(r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28, (Object) null);
        accessupdatenode.write(accessensureViewModelStore, (Object) null);
        accessupdatenode.write(_init_lambda3, (Object) null);
        accessupdatenode.write(_init_lambda2, (Object) null);
        accessupdatenode.write(_init_lambda1, (Object) null);
        accessupdatenode.write(_init_lambda4, (Object) null);
        accessupdatenode.write(addObserverForBackInvokerlambda0, (Object) null);
        accessupdatenode.write(defaultViewModelProviderFactory_delegatelambda0, (Object) null);
        accessupdatenode.write(createFullyDrawnExecutor, (Object) null);
        accessupdatenode.write(addObserverForBackInvoker, (Object) null);
        accessupdatenode.write(ensureViewModelStore, (Object) null);
        accessupdatenode.write(fullyDrawnReporter_delegatelambda0, (Object) null);
        accessupdatenode.write(getOnBackPressedInput, (Object) null);
        accessupdatenode.write(fullyDrawnReporter_delegatelambda00, (Object) null);
        accessupdatenode.write(getSavedStateRegistryControllerannotations, (Object) null);
        accessupdatenode.write(menuHostHelperlambda0, (Object) null);
        accessupdatenode.write(onBackPressedDispatcher_delegatelambda00, (Object) null);
        accessupdatenode.write(onBackPressedInput_delegatelambda0, (Object) null);
        accessupdatenode.write(addContentView, (Object) null);
        accessupdatenode.write(onBackPressedDispatcher_delegatelambda0, (Object) null);
        accessupdatenode.write(onBackPressedDispatcher_delegatelambda010, (Object) null);
        accessupdatenode.write(addOnContextAvailableListener, (Object) null);
        accessupdatenode.write(addOnNewIntentListener, (Object) null);
        accessupdatenode.write(addOnMultiWindowModeChangedListener, (Object) null);
        accessupdatenode.write(onPreparePanel, (Object) null);
        accessupdatenode.write(onPictureInPictureUiStateChanged, (Object) null);
        accessupdatenode.write(onPanelClosed, (Object) null);
        accessupdatenode.write(onPictureInPictureModeChanged, (Object) null);
        accessupdatenode.write(onRequestPermissionsResult, (Object) null);
        accessupdatenode.write(onTrimMemory, (Object) null);
        accessupdatenode.write(onRetainCustomNonConfigurationInstance, (Object) null);
        accessupdatenode.write(onUserLeaveHint, (Object) null);
        accessupdatenode.write(onRetainNonConfigurationInstance, (Object) null);
        accessupdatenode.write(onSaveInstanceState, (Object) null);
        accessupdatenode.write(removeMenuProvider, (Object) null);
        accessupdatenode.write(removeOnConfigurationChangedListener, (Object) null);
        accessupdatenode.write(registerForActivityResult, (Object) null);
        accessupdatenode.write(peekAvailableContext, (Object) null);
        accessupdatenode.write(removeOnContextAvailableListener, (Object) null);
        accessupdatenode.write(removeOnPictureInPictureUiStateChangedListener, (Object) null);
        accessupdatenode.write(removeOnPictureInPictureModeChangedListener, (Object) null);
        accessupdatenode.write(removeOnNewIntentListener, (Object) null);
        accessupdatenode.write(removeOnTrimMemoryListener, (Object) null);
        accessupdatenode.write(removeOnMultiWindowModeChangedListener, (Object) null);
        accessupdatenode.write(removeOnUserLeaveHintListener, (Object) null);
        accessupdatenode.write(reportFullyDrawn, (Object) null);
        accessupdatenode.write(setContentView, (Object) null);
        accessupdatenode.write(setPictureInPictureParams, (Object) null);
        accessupdatenode.write(startActivityForResult, (Object) null);
    }
}
