package o;

import com.google.android.gms.dynamite.zzj;
import com.google.android.gms.location.DeviceOrientationRequest;
import com.huawei.location.gwi.config.CarGwiSoFileConstant;
import com.huawei.riemann.location.common.utils.Constant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;

/* JADX INFO: loaded from: classes2.dex */
public abstract class premeasure0kLqBqw {
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 ComponentActivity;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 ComponentDialog;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 ComponentDialogExternalSyntheticLambda0;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 EdgeToEdgeExternalSyntheticLambda0;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 IconCompatParcelizer;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 MediaBrowserCompatMediaItem;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 MediaDescriptionCompat;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 MediaMetadataCompat;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 MediaSessionCompatQueueItem;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 MediaSessionCompatResultReceiverWrapper;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 MediaSessionCompatToken;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 ParcelableVolumeInfo;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 PlaybackStateCompat;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 PlaybackStateCompatCustomAction;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 RatingCompat;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 RemoteActionCompatParcelizer;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 ResultReceiver;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 _init_lambda1;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 _init_lambda2;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 _init_lambda3;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 _init_lambda4;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 accessensureViewModelStore;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 addContentView;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 addMenuProvider;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 addObserverForBackInvoker;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 addObserverForBackInvokerlambda0;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 addOnConfigurationChangedListener;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 addOnContextAvailableListener;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 addOnMultiWindowModeChangedListener;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 addOnNewIntentListener;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 addOnPictureInPictureModeChangedListener;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 addOnPictureInPictureUiStateChangedListener;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 addOnTrimMemoryListener;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 addOnUserLeaveHintListener;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 createFullyDrawnExecutor;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 defaultViewModelProviderFactory_delegatelambda0;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 ensureViewModelStore;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 enterPictureInPictureMode;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 fullyDrawnReporter_delegatelambda0;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 fullyDrawnReporter_delegatelambda00;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 getActivityResultRegistry;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 getDefaultViewModelCreationExtras;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 getDefaultViewModelProviderFactory;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 getFullyDrawnReporter;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 getLastCustomNonConfigurationInstance;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 getLifecycle;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 getLifecycleRegistry1;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 getNavigationEventDispatcher;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 getOnBackPressedDispatcher;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 getOnBackPressedDispatcherannotations;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 getOnBackPressedInput;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 getSavedStateRegistry;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 getSavedStateRegistryControllerannotations;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 getViewModelStore;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 initializeViewTreeOwners;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 invalidateMenu;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 invoke;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 menuHostHelperlambda0;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onActivityResult;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onBackPressed;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onBackPressedDispatcher_delegatelambda0;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onBackPressedDispatcher_delegatelambda00;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onBackPressedDispatcher_delegatelambda010;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onBackPressedInput_delegatelambda0;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onConfigurationChanged;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onCreate;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onCreatePanelMenu;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onMenuItemSelected;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onMultiWindowModeChanged;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onNewIntent;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onPanelClosed;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onPictureInPictureModeChanged;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onPictureInPictureUiStateChanged;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onPreparePanel;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onRequestPermissionsResult;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onRetainCustomNonConfigurationInstance;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onRetainNonConfigurationInstance;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onSaveInstanceState;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onStart;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onStop;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onTrimMemory;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 onUserLeaveHint;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 peekAvailableContext;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 r8lambda54BeH8ZsBru0CXI2CCSP2syNys;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 r8lambda7IJBVrN0sHyidCAZufWEJFc7yY;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 r8lambdaXxpmZzi8FNPM2sJJA30VCt2mBcQ;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 read;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 registerForActivityResult;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 removeMenuProvider;
    public static final List removeOnConfigurationChangedListener = Collections.synchronizedList(new ArrayList());
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 removeOnContextAvailableListener;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 removeOnMultiWindowModeChangedListener;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 removeOnNewIntentListener;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 removeOnPictureInPictureModeChangedListener;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 removeOnPictureInPictureUiStateChangedListener;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 removeOnTrimMemoryListener;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 removeOnUserLeaveHintListener;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 reportFullyDrawn;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 serializer;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 setContentView;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 setPictureInPictureParams;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 startActivityForResult;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 startIntentSenderForResult;
    public static final LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 write;

    static {
        Collections.synchronizedSet(new HashSet());
        Long lValueOf = Long.valueOf(DeviceOrientationRequest.OUTPUT_PERIOD_MEDIUM);
        r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28 = RemoteActionCompatParcelizer("measurement.ad_id_cache_time", lValueOf, getIntentArrayWithConfiguredBackStacklambda4.MediaDescriptionCompat, false);
        onCreatePanelMenu = RemoteActionCompatParcelizer("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L, zzj.serializer, false);
        Long lValueOf2 = Long.valueOf(CarGwiSoFileConstant.CAR_GWI_SPECIFY_INTERVAL);
        removeMenuProvider = RemoteActionCompatParcelizer("measurement.monitoring.sample_period_millis", lValueOf2, accessgetWcp.MediaSessionCompatQueueItem, false);
        peekAvailableContext = RemoteActionCompatParcelizer("measurement.config.cache_time", lValueOf2, FlingCancellationException.PlaybackStateCompat, false);
        registerForActivityResult = RemoteActionCompatParcelizer("measurement.config.url_scheme", com.adjust.sdk.Constants.SCHEME, speculativeHit.MediaSessionCompatToken, false);
        removeOnContextAvailableListener = RemoteActionCompatParcelizer("measurement.config.url_authority", "app-measurement.com", getIntentArrayWithConfiguredBackStacklambda4.ParcelableVolumeInfo, false);
        removeOnPictureInPictureUiStateChangedListener = RemoteActionCompatParcelizer("measurement.upload.max_bundles", 100, setRoundRectOutlineTNW_H78default.PlaybackStateCompat, false);
        removeOnPictureInPictureModeChangedListener = RemoteActionCompatParcelizer("measurement.upload.max_batch_size", 65536, zzj.PlaybackStateCompat, false);
        removeOnNewIntentListener = RemoteActionCompatParcelizer("measurement.upload.max_bundle_size", 65536, io.sentry.hints.PlaybackStateCompatCustomAction.write, false);
        removeOnMultiWindowModeChangedListener = RemoteActionCompatParcelizer("measurement.upload.max_events_per_bundle", 1000, accessgetVcp.MediaMetadataCompat, false);
        Integer numValueOf = Integer.valueOf(androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.ParcelSafeTextLength);
        removeOnTrimMemoryListener = RemoteActionCompatParcelizer("measurement.upload.max_events_per_day", numValueOf, accessgetWcp.RatingCompat, false);
        startActivityForResult = RemoteActionCompatParcelizer("measurement.upload.max_error_events_per_day", 1000, speculativeHit.MediaBrowserCompatMediaItem, false);
        setContentView = RemoteActionCompatParcelizer("measurement.upload.max_public_events_per_day", 50000, zzj.write, false);
        reportFullyDrawn = RemoteActionCompatParcelizer("measurement.upload.max_conversions_per_day", 10000, accessgetWcp.write, false);
        setPictureInPictureParams = RemoteActionCompatParcelizer("measurement.upload.max_realtime_events_per_day", 10, getIntentArrayWithConfiguredBackStacklambda4.RatingCompat, false);
        removeOnUserLeaveHintListener = RemoteActionCompatParcelizer("measurement.store.max_stored_events_per_app", numValueOf, io.sentry.hints.PlaybackStateCompatCustomAction.MediaMetadataCompat, false);
        getOnBackPressedDispatcherannotations = RemoteActionCompatParcelizer("measurement.upload.url", "https://app-measurement.com/a", FlingCancellationException.MediaSessionCompatQueueItem, false);
        ComponentDialog = RemoteActionCompatParcelizer("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d", setRoundRectOutlineTNW_H78default.RatingCompat, false);
        startIntentSenderForResult = RemoteActionCompatParcelizer("measurement.sgtm.service_upload_apps_list", "", accessgetVcp.MediaSessionCompatToken, false);
        r8lambdaXxpmZzi8FNPM2sJJA30VCt2mBcQ = RemoteActionCompatParcelizer("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504", speculativeHit.MediaDescriptionCompat, false);
        getLifecycleRegistry1 = RemoteActionCompatParcelizer("measurement.sgtm.upload.retry_interval", 600000L, zzj.MediaSessionCompatQueueItem, false);
        onStop = RemoteActionCompatParcelizer("measurement.sgtm.upload.retry_max_wait", 21600000L, getIntentArrayWithConfiguredBackStacklambda4.MediaMetadataCompat, false);
        onStart = RemoteActionCompatParcelizer("measurement.sgtm.batch.retry_interval", 1800000L, io.sentry.hints.PlaybackStateCompatCustomAction.MediaBrowserCompatMediaItem, false);
        ComponentDialogExternalSyntheticLambda0 = RemoteActionCompatParcelizer("measurement.sgtm.batch.retry_max_wait", 21600000L, FlingCancellationException.MediaMetadataCompat, false);
        EdgeToEdgeExternalSyntheticLambda0 = RemoteActionCompatParcelizer("measurement.sgtm.batch.retry_max_count", 10, setRoundRectOutlineTNW_H78default.MediaDescriptionCompat, false);
        invoke = RemoteActionCompatParcelizer("measurement.sgtm.upload.max_queued_batches", 5000, accessgetVcp.MediaSessionCompatResultReceiverWrapper, false);
        read = RemoteActionCompatParcelizer("measurement.sgtm.upload.batches_retrieval_limit", 5, speculativeHit.MediaMetadataCompat, false);
        Long lValueOf3 = Long.valueOf(DeviceOrientationRequest.OUTPUT_PERIOD_FAST);
        serializer = RemoteActionCompatParcelizer("measurement.sgtm.upload.min_delay_after_startup", lValueOf3, zzj.MediaMetadataCompat, false);
        write = RemoteActionCompatParcelizer("measurement.sgtm.upload.min_delay_after_broadcast", 1000L, accessgetWcp.MediaMetadataCompat, false);
        RemoteActionCompatParcelizer = RemoteActionCompatParcelizer("measurement.sgtm.upload.min_delay_after_background", 600000L, getIntentArrayWithConfiguredBackStacklambda4.MediaSessionCompatToken, false);
        IconCompatParcelizer = RemoteActionCompatParcelizer("measurement.sgtm.batch.long_queuing_threshold", 14400000L, io.sentry.hints.PlaybackStateCompatCustomAction.ParcelableVolumeInfo, false);
        MediaSessionCompatQueueItem = RemoteActionCompatParcelizer("measurement.upload.backoff_period", 43200000L, setRoundRectOutlineTNW_H78default.ParcelableVolumeInfo, false);
        RemoteActionCompatParcelizer("measurement.upload.window_interval", 3600000L, accessgetVcp.PlaybackStateCompat, false);
        MediaMetadataCompat = RemoteActionCompatParcelizer("measurement.upload.interval", 3600000L, speculativeHit.PlaybackStateCompatCustomAction, false);
        RatingCompat = RemoteActionCompatParcelizer("measurement.upload.realtime_upload_interval", lValueOf, zzj.MediaBrowserCompatMediaItem, false);
        MediaDescriptionCompat = RemoteActionCompatParcelizer("measurement.upload.debug_upload_interval", 1000L, accessgetWcp.MediaBrowserCompatMediaItem, false);
        MediaBrowserCompatMediaItem = RemoteActionCompatParcelizer("measurement.upload.minimum_delay", 500L, getIntentArrayWithConfiguredBackStacklambda4.PlaybackStateCompatCustomAction, false);
        MediaSessionCompatToken = RemoteActionCompatParcelizer("measurement.alarm_manager.minimum_interval", 60000L, io.sentry.hints.PlaybackStateCompatCustomAction.MediaSessionCompatResultReceiverWrapper, false);
        ParcelableVolumeInfo = RemoteActionCompatParcelizer("measurement.upload.stale_data_deletion_interval", lValueOf2, FlingCancellationException.ParcelableVolumeInfo, false);
        PlaybackStateCompat = RemoteActionCompatParcelizer("measurement.upload.refresh_blacklisted_config_interval", 604800000L, setRoundRectOutlineTNW_H78default.MediaSessionCompatResultReceiverWrapper, false);
        MediaSessionCompatResultReceiverWrapper = RemoteActionCompatParcelizer("measurement.upload.initial_upload_delay_time", 15000L, accessgetVcp.ParcelableVolumeInfo, false);
        PlaybackStateCompatCustomAction = RemoteActionCompatParcelizer("measurement.upload.retry_time", 1800000L, zzj.RatingCompat, false);
        r8lambda54BeH8ZsBru0CXI2CCSP2syNys = RemoteActionCompatParcelizer("measurement.upload.retry_count", 6, accessgetWcp.MediaSessionCompatResultReceiverWrapper, false);
        r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus = RemoteActionCompatParcelizer("measurement.upload.max_queue_time", 518400000L, getIntentArrayWithConfiguredBackStacklambda4.PlaybackStateCompat, false);
        ResultReceiver = RemoteActionCompatParcelizer("measurement.upload.google_signal_max_queue_time", 300000L, io.sentry.hints.PlaybackStateCompatCustomAction.PlaybackStateCompat, false);
        ComponentActivity = RemoteActionCompatParcelizer("measurement.lifetimevalue.max_currency_tracked", 4, FlingCancellationException.MediaSessionCompatToken, false);
        r8lambda7IJBVrN0sHyidCAZufWEJFc7yY = RemoteActionCompatParcelizer("measurement.audience.filter_result_max_count", 200, setRoundRectOutlineTNW_H78default.MediaSessionCompatToken, false);
        r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss = RemoteActionCompatParcelizer("measurement.upload.max_public_user_properties", 100, null, false);
        r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4 = RemoteActionCompatParcelizer("measurement.upload.max_event_name_cardinality", 2000, null, false);
        r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM = RemoteActionCompatParcelizer("measurement.upload.max_public_event_params", 100, null, false);
        r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8 = RemoteActionCompatParcelizer("measurement.service_client.idle_disconnect_millis", lValueOf3, accessgetVcp.PlaybackStateCompatCustomAction, false);
        r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg = RemoteActionCompatParcelizer("measurement.service_client.reconnect_millis", 1000L, speculativeHit.MediaSessionCompatResultReceiverWrapper, false);
        Boolean bool = Boolean.FALSE;
        addMenuProvider = RemoteActionCompatParcelizer("measurement.test.boolean_flag", bool, zzj.ParcelableVolumeInfo, false);
        addOnContextAvailableListener = RemoteActionCompatParcelizer("measurement.test.string_flag", "---", accessgetWcp.ParcelableVolumeInfo, false);
        addOnNewIntentListener = RemoteActionCompatParcelizer("measurement.test.long_flag", -1L, io.sentry.hints.PlaybackStateCompatCustomAction.MediaSessionCompatToken, false);
        RemoteActionCompatParcelizer("measurement.test.cached_long_flag", -1L, FlingCancellationException.PlaybackStateCompatCustomAction, true);
        addOnTrimMemoryListener = RemoteActionCompatParcelizer("measurement.test.int_flag", -2, setRoundRectOutlineTNW_H78default.PlaybackStateCompatCustomAction, false);
        addOnUserLeaveHintListener = RemoteActionCompatParcelizer("measurement.test.double_flag", Double.valueOf(-3.0d), accessgetVcp.ComponentActivity, false);
        addOnPictureInPictureModeChangedListener = RemoteActionCompatParcelizer("measurement.experiment.max_ids", 50, speculativeHit.PlaybackStateCompat, false);
        enterPictureInPictureMode = RemoteActionCompatParcelizer("measurement.upload.max_item_scoped_custom_parameters", 27, zzj.MediaSessionCompatToken, false);
        addOnPictureInPictureUiStateChangedListener = RemoteActionCompatParcelizer("measurement.upload.max_event_parameter_value_length", Integer.valueOf(Constant.ERROR_UNKNOWN), accessgetWcp.PlaybackStateCompat, true);
        getActivityResultRegistry = RemoteActionCompatParcelizer("measurement.max_bundles_per_iteration", 100, getIntentArrayWithConfiguredBackStacklambda4.MediaSessionCompatResultReceiverWrapper, false);
        getLastCustomNonConfigurationInstance = RemoteActionCompatParcelizer("measurement.sdk.attribution.cache.ttl", 604800000L, io.sentry.hints.PlaybackStateCompatCustomAction.PlaybackStateCompatCustomAction, false);
        getDefaultViewModelProviderFactory = RemoteActionCompatParcelizer("measurement.redaction.app_instance_id.ttl", 7200000L, FlingCancellationException.MediaSessionCompatResultReceiverWrapper, false);
        getFullyDrawnReporter = RemoteActionCompatParcelizer("measurement.rb.attribution.client.min_ad_services_version", 7, accessgetVcp.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus, false);
        getDefaultViewModelCreationExtras = RemoteActionCompatParcelizer("measurement.dma_consent.max_daily_dcu_realtime_events", 1, speculativeHit.ParcelableVolumeInfo, false);
        getLifecycle = RemoteActionCompatParcelizer("measurement.rb.attribution.uri_scheme", com.adjust.sdk.Constants.SCHEME, zzj.PlaybackStateCompatCustomAction, false);
        getOnBackPressedDispatcher = RemoteActionCompatParcelizer("measurement.rb.attribution.uri_authority", "google-analytics.com", accessgetWcp.PlaybackStateCompatCustomAction, false);
        getSavedStateRegistry = RemoteActionCompatParcelizer("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", getIntentArrayWithConfiguredBackStacklambda4.ComponentActivity, false);
        getNavigationEventDispatcher = RemoteActionCompatParcelizer("measurement.session.engagement_interval", 3600000L, io.sentry.hints.PlaybackStateCompatCustomAction.r8lambda54BeH8ZsBru0CXI2CCSP2syNys, false);
        getViewModelStore = RemoteActionCompatParcelizer("measurement.rb.attribution.app_allowlist", "", FlingCancellationException.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus, false);
        initializeViewTreeOwners = RemoteActionCompatParcelizer("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot", setRoundRectOutlineTNW_H78default.ResultReceiver, false);
        invalidateMenu = RemoteActionCompatParcelizer("measurement.rb.attribution.event_params", "value|currency", accessgetVcp.serializer, false);
        onConfigurationChanged = RemoteActionCompatParcelizer("measurement.rb.attribution.query_parameters_to_remove", "", speculativeHit.read, false);
        onBackPressed = RemoteActionCompatParcelizer("measurement.rb.attribution.max_queue_time", 864000000L, accessgetWcp.MediaSessionCompatToken, false);
        onActivityResult = RemoteActionCompatParcelizer("measurement.rb.attribution.max_retry_delay_seconds", 16, getIntentArrayWithConfiguredBackStacklambda4.serializer, false);
        onNewIntent = RemoteActionCompatParcelizer("measurement.rb.attribution.client.min_time_after_boot_seconds", 90, io.sentry.hints.PlaybackStateCompatCustomAction.IconCompatParcelizer, false);
        RemoteActionCompatParcelizer("measurement.rb.attribution.max_trigger_uris_queried_at_once", 0, FlingCancellationException.RemoteActionCompatParcelizer, false);
        onMenuItemSelected = RemoteActionCompatParcelizer("measurement.rb.max_trigger_registrations_per_day", 1000, setRoundRectOutlineTNW_H78default.read, false);
        Boolean bool2 = Boolean.TRUE;
        onMultiWindowModeChanged = RemoteActionCompatParcelizer("measurement.config.bundle_for_all_apps_on_backgrounded", bool2, accessgetVcp.IconCompatParcelizer, false);
        r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw = RemoteActionCompatParcelizer("measurement.config.notify_trigger_uris_on_backgrounded", bool2, speculativeHit.serializer, false);
        r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ = RemoteActionCompatParcelizer("measurement.rb.attribution.notify_app_delay_millis", 3000, zzj.read, false);
        r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs = RemoteActionCompatParcelizer("measurement.quality.checksum", bool, null, false);
        r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0 = RemoteActionCompatParcelizer("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, accessgetWcp.RemoteActionCompatParcelizer, false);
        _init_lambda2 = RemoteActionCompatParcelizer("measurement.audience.refresh_event_count_filters_timestamp", bool, getIntentArrayWithConfiguredBackStacklambda4.read, false);
        accessensureViewModelStore = RemoteActionCompatParcelizer("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, FlingCancellationException.IconCompatParcelizer, true);
        _init_lambda4 = RemoteActionCompatParcelizer("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, setRoundRectOutlineTNW_H78default.write, false);
        _init_lambda1 = RemoteActionCompatParcelizer("measurement.integration.disable_firebase_instance_id", bool, accessgetVcp.MediaDescriptionCompat, false);
        _init_lambda3 = RemoteActionCompatParcelizer("measurement.collection.service.update_with_analytics_fix", bool, speculativeHit.IconCompatParcelizer, false);
        createFullyDrawnExecutor = RemoteActionCompatParcelizer("measurement.service.storage_consent_support_version", 203600, zzj.RemoteActionCompatParcelizer, false);
        addObserverForBackInvokerlambda0 = RemoteActionCompatParcelizer("measurement.service.store_null_safelist", bool2, accessgetWcp.IconCompatParcelizer, false);
        ensureViewModelStore = RemoteActionCompatParcelizer("measurement.service.store_safelist", bool2, getIntentArrayWithConfiguredBackStacklambda4.MediaSessionCompatQueueItem, false);
        defaultViewModelProviderFactory_delegatelambda0 = RemoteActionCompatParcelizer("measurement.session_stitching_token_enabled", bool, io.sentry.hints.PlaybackStateCompatCustomAction.MediaSessionCompatQueueItem, false);
        addObserverForBackInvoker = RemoteActionCompatParcelizer("measurement.sgtm.client.upload_on_backgrounded.dev", bool, FlingCancellationException.read, true);
        fullyDrawnReporter_delegatelambda0 = RemoteActionCompatParcelizer("measurement.gmscore_client_telemetry", bool, FlingCancellationException.MediaBrowserCompatMediaItem, false);
        getSavedStateRegistryControllerannotations = RemoteActionCompatParcelizer("measurement.rb.attribution.service", bool2, setRoundRectOutlineTNW_H78default.serializer, true);
        fullyDrawnReporter_delegatelambda00 = RemoteActionCompatParcelizer("measurement.rb.attribution.client2", bool2, speculativeHit.RatingCompat, true);
        menuHostHelperlambda0 = RemoteActionCompatParcelizer("measurement.rb.attribution.uuid_generation", bool2, zzj.IconCompatParcelizer, false);
        getOnBackPressedInput = RemoteActionCompatParcelizer("measurement.rb.attribution.enable_trigger_redaction", bool2, accessgetWcp.MediaDescriptionCompat, false);
        RemoteActionCompatParcelizer("measurement.rb.attribution.followup1.service", bool, getIntentArrayWithConfiguredBackStacklambda4.MediaBrowserCompatMediaItem, false);
        onBackPressedDispatcher_delegatelambda010 = RemoteActionCompatParcelizer("measurement.rb.attribution.retry_disposition", bool, io.sentry.hints.PlaybackStateCompatCustomAction.MediaDescriptionCompat, false);
        onBackPressedDispatcher_delegatelambda0 = RemoteActionCompatParcelizer("measurement.client.sessions.enable_fix_background_engagement", bool, accessgetVcp.MediaSessionCompatQueueItem, false);
        onBackPressedInput_delegatelambda0 = RemoteActionCompatParcelizer("measurement.set_default_event_parameters_propagate_clear.service.dev", bool2, FlingCancellationException.RatingCompat, false);
        addContentView = RemoteActionCompatParcelizer("measurement.set_default_event_parameters_propagate_clear.client.dev", bool2, setRoundRectOutlineTNW_H78default.MediaMetadataCompat, false);
        onBackPressedDispatcher_delegatelambda00 = RemoteActionCompatParcelizer("measurement.service.ad_impression.convert_value_to_double", bool2, accessgetVcp.RatingCompat, false);
        RemoteActionCompatParcelizer("measurement.rb.attribution.service.enable_max_trigger_uris_queried_at_once", bool2, speculativeHit.MediaSessionCompatQueueItem, false);
        RemoteActionCompatParcelizer("measurement.remove_conflicting_first_party_apis.dev", bool, zzj.MediaDescriptionCompat, false);
        addOnConfigurationChangedListener = RemoteActionCompatParcelizer("measurement.rb.attribution.service.trigger_uris_high_priority", bool2, accessgetWcp.serializer, false);
        addOnMultiWindowModeChangedListener = RemoteActionCompatParcelizer("measurement.tcf.consent_fix", bool2, getIntentArrayWithConfiguredBackStacklambda4.RemoteActionCompatParcelizer, false);
        onCreate = RemoteActionCompatParcelizer("measurement.experiment.enable_phenotype_experiment_reporting", bool2, io.sentry.hints.PlaybackStateCompatCustomAction.read, false);
        onPanelClosed = RemoteActionCompatParcelizer("measurement.set_default_event_parameters.fix_service_request_ordering", bool, FlingCancellationException.write, false);
        onPictureInPictureUiStateChanged = RemoteActionCompatParcelizer("measurement.set_default_event_parameters.fix_app_update_logging", bool2, io.sentry.hints.PlaybackStateCompatCustomAction.serializer, false);
        onRequestPermissionsResult = RemoteActionCompatParcelizer("measurement.service.fix_stop_bundling_bug", bool2, speculativeHit.RemoteActionCompatParcelizer, false);
        onPreparePanel = RemoteActionCompatParcelizer("measurement.fix_params_logcat_spam", bool2, accessgetVcp.RemoteActionCompatParcelizer, false);
        onPictureInPictureModeChanged = RemoteActionCompatParcelizer("measurement.gbraid_campaign.stop_lgclid", bool, io.sentry.hints.PlaybackStateCompatCustomAction.RatingCompat, false);
        onRetainCustomNonConfigurationInstance = RemoteActionCompatParcelizer("measurement.gbraid_compaign.compaign_params_triggering_info_update", "gclid,gbraid,gad_campaignid", FlingCancellationException.serializer, false);
        onSaveInstanceState = RemoteActionCompatParcelizer("measurement.edpb.service", bool, setRoundRectOutlineTNW_H78default.RemoteActionCompatParcelizer, false);
        onTrimMemory = RemoteActionCompatParcelizer("measurement.edpb.events_cached_in_no_data_mode", "_f,_v,_cmp", setRoundRectOutlineTNW_H78default.IconCompatParcelizer, false);
        onRetainNonConfigurationInstance = RemoteActionCompatParcelizer("measurement.add_first_launch_logging_timestamp.service", bool, setRoundRectOutlineTNW_H78default.MediaBrowserCompatMediaItem, false);
        onUserLeaveHint = RemoteActionCompatParcelizer("measurement.overlapping_bundles_fix", bool, accessgetVcp.MediaBrowserCompatMediaItem, false);
    }

    public static LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 RemoteActionCompatParcelizer(String str, Object obj, LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle2 layoutNodeSubcompositionsStatecreatePrecomposedSlotHandle2, boolean z) {
        LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 layoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1 = new LayoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1(str, obj, layoutNodeSubcompositionsStatecreatePrecomposedSlotHandle2);
        if (z) {
            removeOnConfigurationChangedListener.add(layoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1);
        }
        return layoutNodeSubcompositionsStatecreatePrecomposedSlotHandle1;
    }
}
