package o;

import android.app.Application;
import androidx.compose.ui.graphics.Fields;
import com.roadrunner.appperformance.TraceTimeMeasurementWithPerformanceKit;
import io.sentry.SentryTracer$$ExternalSyntheticLambda1;
import io.sentry.okhttp.read;
import java.util.ArrayList;
import java.util.TimeZone;
import o.addFlags;
import o.applyDisplayCutoutMarginsToCloseButtonlambda0;
import o.canTrackThirdPartySharingI;
import o.getClassLogTag;
import o.getShortEdge;
import o.getSpannotations;
import o.qg;
import o.r0;
import o.r2;
import o.r3;
import o.r4;
import o.r5;
import o.r6;
import o.r7;
import o.r8;
import o.r8lambdaA_tBhQGR0_Qo4AfQkBrfTkXVvg0;
import o.r8lambdaChmLGYSNQdplVu9Y_kSRCt5sDig;
import o.r8lambdaUgGAUuJ_lbNZVeF8yYXtWMHrLkQ;
import o.rb;
import o.rc;
import o.rollback;
import o.setHtmlPageFinishedListener;
import o.setVerticalStyle;
import o.setWebViewContent;

/* JADX INFO: loaded from: classes3.dex */
public final class qe implements getColorIntegerOrNulllambda0 {
    private static int r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss = 0;
    private static int r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg = 1;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ ComponentActivity;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ IconCompatParcelizer;
    public final backgroundTimerFiredI MediaBrowserCompatMediaItem;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ MediaDescriptionCompat;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ MediaMetadataCompat;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ MediaSessionCompatQueueItem;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ MediaSessionCompatResultReceiverWrapper;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ MediaSessionCompatToken;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ ParcelableVolumeInfo;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ PlaybackStateCompat;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ PlaybackStateCompatCustomAction;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ RatingCompat;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ RemoteActionCompatParcelizer;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ ResultReceiver;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambda54BeH8ZsBru0CXI2CCSP2syNys;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambda7IJBVrN0sHyidCAZufWEJFc7yY;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ read;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ serializer;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ write;

    public qe(r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdaktwlyipskq3tfa9ey3gatonixfq, hasNestedScrollingParent hasnestedscrollingparent, SimpleExecutableQuery simpleExecutableQuery, setUseTempTrackingTableroom_runtime setusetemptrackingtableroom_runtime, backgroundTimerFiredI backgroundtimerfiredi, backgroundTimerFiredI backgroundtimerfiredi2, setUseTempTrackingTableroom_runtime setusetemptrackingtableroom_runtime2, pasteText pastetext, backgroundTimerFiredI backgroundtimerfiredi3, setUseTempTrackingTableroom_runtime setusetemptrackingtableroom_runtime3, getContentDataType getcontentdatatype, AbsSavedState absSavedState, backgroundTimerFiredI backgroundtimerfiredi4, SingleProcessDataStore singleProcessDataStore, setUseTempTrackingTableroom_runtime setusetemptrackingtableroom_runtime4, r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdaktwlyipskq3tfa9ey3gatonixfq2, postAnimationRunner postanimationrunner, backgroundTimerFiredI backgroundtimerfiredi5, backgroundTimerFiredI backgroundtimerfiredi6, com.data.injection.DataModule_ProvideSchedulerFactory dataModule_ProvideSchedulerFactory) {
        r8lambdaktwlyipskq3tfa9ey3gatonixfq.getClass();
        hasnestedscrollingparent.getClass();
        simpleExecutableQuery.getClass();
        setusetemptrackingtableroom_runtime.getClass();
        backgroundtimerfiredi.getClass();
        backgroundtimerfiredi2.getClass();
        setusetemptrackingtableroom_runtime2.getClass();
        pastetext.getClass();
        backgroundtimerfiredi3.getClass();
        setusetemptrackingtableroom_runtime3.getClass();
        getcontentdatatype.getClass();
        absSavedState.getClass();
        backgroundtimerfiredi4.getClass();
        singleProcessDataStore.getClass();
        setusetemptrackingtableroom_runtime4.getClass();
        r8lambdaktwlyipskq3tfa9ey3gatonixfq2.getClass();
        postanimationrunner.getClass();
        backgroundtimerfiredi5.getClass();
        dataModule_ProvideSchedulerFactory.getClass();
        this.MediaDescriptionCompat = r8lambdaktwlyipskq3tfa9ey3gatonixfq;
        this.write = hasnestedscrollingparent;
        this.MediaMetadataCompat = simpleExecutableQuery;
        this.MediaSessionCompatToken = setusetemptrackingtableroom_runtime;
        this.PlaybackStateCompatCustomAction = backgroundtimerfiredi;
        this.RemoteActionCompatParcelizer = backgroundtimerfiredi2;
        this.r8lambda54BeH8ZsBru0CXI2CCSP2syNys = setusetemptrackingtableroom_runtime2;
        this.r8lambda7IJBVrN0sHyidCAZufWEJFc7yY = pastetext;
        this.read = backgroundtimerfiredi3;
        this.ComponentActivity = setusetemptrackingtableroom_runtime3;
        this.serializer = getcontentdatatype;
        this.MediaSessionCompatQueueItem = absSavedState;
        this.RatingCompat = backgroundtimerfiredi4;
        this.MediaSessionCompatResultReceiverWrapper = singleProcessDataStore;
        this.ParcelableVolumeInfo = setusetemptrackingtableroom_runtime4;
        this.PlaybackStateCompat = r8lambdaktwlyipskq3tfa9ey3gatonixfq2;
        this.ResultReceiver = postanimationrunner;
        this.IconCompatParcelizer = backgroundtimerfiredi5;
        this.MediaBrowserCompatMediaItem = backgroundtimerfiredi6;
        this.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus = dataModule_ProvideSchedulerFactory;
    }

    @Override // o.r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ
    public final Object write() {
        int i = 2 % 2;
        Object objWrite = this.MediaDescriptionCompat.write();
        objWrite.getClass();
        final setVerticalStyle setverticalstyle = (setVerticalStyle) objWrite;
        Object objWrite2 = this.write.write();
        objWrite2.getClass();
        final Application application = (Application) objWrite2;
        Object objWrite3 = this.MediaMetadataCompat.write();
        objWrite3.getClass();
        final r2 r2Var = (r2) objWrite3;
        Object objWrite4 = this.MediaSessionCompatToken.write();
        objWrite4.getClass();
        final r6 r6Var = (r6) objWrite4;
        Object objWrite5 = this.PlaybackStateCompatCustomAction.write();
        objWrite5.getClass();
        final r8 r8Var = (r8) objWrite5;
        Object objWrite6 = this.RemoteActionCompatParcelizer.write();
        objWrite6.getClass();
        final r0 r0Var = (r0) objWrite6;
        Object objWrite7 = this.r8lambda54BeH8ZsBru0CXI2CCSP2syNys.write();
        objWrite7.getClass();
        final r5 r5Var = (r5) objWrite7;
        Object objWrite8 = this.r8lambda7IJBVrN0sHyidCAZufWEJFc7yY.write();
        objWrite8.getClass();
        final rb rbVar = (rb) objWrite8;
        Object objWrite9 = this.read.write();
        objWrite9.getClass();
        final r3 r3Var = (r3) objWrite9;
        Object objWrite10 = this.ComponentActivity.write();
        objWrite10.getClass();
        final r7 r7Var = (r7) objWrite10;
        Object objWrite11 = this.serializer.write();
        objWrite11.getClass();
        final accessgetOldDependencyp accessgetolddependencyp = (accessgetOldDependencyp) objWrite11;
        Object objWrite12 = this.MediaSessionCompatQueueItem.write();
        objWrite12.getClass();
        final canTrackThirdPartySharingI cantrackthirdpartysharingi = (canTrackThirdPartySharingI) objWrite12;
        Object objWrite13 = this.RatingCompat.write();
        objWrite13.getClass();
        final qg qgVar = (qg) objWrite13;
        Object objWrite14 = this.MediaSessionCompatResultReceiverWrapper.write();
        objWrite14.getClass();
        final getSpannotations getspannotations = (getSpannotations) objWrite14;
        Object objWrite15 = this.ParcelableVolumeInfo.write();
        objWrite15.getClass();
        final rc rcVar = (rc) objWrite15;
        Object objWrite16 = this.PlaybackStateCompat.write();
        objWrite16.getClass();
        final addFlags addflags = (addFlags) objWrite16;
        Object objWrite17 = this.ResultReceiver.write();
        objWrite17.getClass();
        final rollback rollbackVar = (rollback) objWrite17;
        Object objWrite18 = this.IconCompatParcelizer.write();
        objWrite18.getClass();
        final getShortEdge getshortedge = (getShortEdge) objWrite18;
        final applyDisplayCutoutMarginsToCloseButtonlambda0 applydisplaycutoutmarginstoclosebuttonlambda0 = (applyDisplayCutoutMarginsToCloseButtonlambda0) this.MediaBrowserCompatMediaItem.write();
        Object objWrite19 = this.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus.write();
        objWrite19.getClass();
        r8lambdaA_tBhQGR0_Qo4AfQkBrfTkXVvg0 r8lambdaa_tbhqgr0_qo4afqkbrftkxvvg0 = (r8lambdaA_tBhQGR0_Qo4AfQkBrfTkXVvg0) ((TraceTimeMeasurementWithPerformanceKit) ((getAllSemanticsNodesToMap) objWrite19)).read("provideOkHttpClient", new r8lambdaRDpfSr94J4iEbcwX_KPqzPM8k0(accessgetolddependencyp, r5Var, rbVar, r3Var, getshortedge, setverticalstyle, r2Var, r8Var, r0Var, r7Var, r6Var, cantrackthirdpartysharingi, qgVar, getspannotations, rcVar, addflags, rollbackVar, application, applydisplaycutoutmarginstoclosebuttonlambda0) { // from class: com.roadrunner.networking.core.NetworkingCoreModule$$ExternalSyntheticLambda5
            private static int r8lambda54BeH8ZsBru0CXI2CCSP2syNys = 1;
            private static int r8lambda7IJBVrN0sHyidCAZufWEJFc7yY;
            public final /* synthetic */ r0 ComponentActivity;
            public final /* synthetic */ r5 IconCompatParcelizer;
            public final /* synthetic */ applyDisplayCutoutMarginsToCloseButtonlambda0 MediaBrowserCompatMediaItem;
            public final /* synthetic */ rc MediaDescriptionCompat;
            public final /* synthetic */ rb MediaMetadataCompat;
            public final /* synthetic */ addFlags MediaSessionCompatQueueItem;
            public final /* synthetic */ setVerticalStyle MediaSessionCompatResultReceiverWrapper;
            public final /* synthetic */ r3 MediaSessionCompatToken;
            public final /* synthetic */ r8 ParcelableVolumeInfo;
            public final /* synthetic */ r2 PlaybackStateCompat;
            public final /* synthetic */ getShortEdge PlaybackStateCompatCustomAction;
            public final /* synthetic */ rollback RatingCompat;
            public final /* synthetic */ r6 RemoteActionCompatParcelizer;
            public final /* synthetic */ r7 r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus;
            public final /* synthetic */ qg read;
            public final /* synthetic */ getSpannotations serializer;
            public final /* synthetic */ canTrackThirdPartySharingI write;

            {
                this.IconCompatParcelizer = r5Var;
                this.MediaMetadataCompat = rbVar;
                this.MediaSessionCompatToken = r3Var;
                this.PlaybackStateCompatCustomAction = getshortedge;
                this.MediaSessionCompatResultReceiverWrapper = setverticalstyle;
                this.PlaybackStateCompat = r2Var;
                this.ParcelableVolumeInfo = r8Var;
                this.ComponentActivity = r0Var;
                this.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus = r7Var;
                this.RemoteActionCompatParcelizer = r6Var;
                this.write = cantrackthirdpartysharingi;
                this.read = qgVar;
                this.serializer = getspannotations;
                this.MediaDescriptionCompat = rcVar;
                this.MediaSessionCompatQueueItem = addflags;
                this.RatingCompat = rollbackVar;
                this.MediaBrowserCompatMediaItem = applydisplaycutoutmarginstoclosebuttonlambda0;
            }

            @Override // o.r8lambdaRDpfSr94J4iEbcwX_KPqzPM8k0
            public final Object invoke() {
                int i2 = 2 % 2;
                getClassLogTag getclasslogtag = new getClassLogTag(0);
                getclasslogtag.write(r8lambdaChmLGYSNQdplVu9Y_kSRCt5sDig.NONE);
                r8lambdaUgGAUuJ_lbNZVeF8yYXtWMHrLkQ r8lambdauggauuj_lbnzvef8yyxtwmhrlkq = new r8lambdaUgGAUuJ_lbNZVeF8yYXtWMHrLkQ();
                ArrayList arrayList = r8lambdauggauuj_lbnzvef8yyxtwmhrlkq.r8lambda7IJBVrN0sHyidCAZufWEJFc7yY;
                arrayList.add(this.IconCompatParcelizer);
                arrayList.add(this.MediaMetadataCompat);
                arrayList.add(this.MediaSessionCompatToken);
                arrayList.add(new r4());
                arrayList.add(this.PlaybackStateCompatCustomAction);
                arrayList.add(new setHtmlPageFinishedListener(3, this.MediaSessionCompatResultReceiverWrapper));
                arrayList.add(this.PlaybackStateCompat);
                arrayList.add(this.ParcelableVolumeInfo);
                arrayList.add(this.ComponentActivity);
                arrayList.add(this.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus);
                arrayList.add(this.RemoteActionCompatParcelizer);
                arrayList.add(this.write);
                arrayList.add(this.read);
                arrayList.add(this.serializer);
                arrayList.add(this.MediaDescriptionCompat);
                arrayList.add(this.MediaSessionCompatQueueItem);
                arrayList.add(this.RatingCompat.IconCompatParcelizer());
                read readVar = new read();
                TimeZone timeZone = setWebViewContent.RemoteActionCompatParcelizer;
                r8lambdauggauuj_lbnzvef8yyxtwmhrlkq.PlaybackStateCompatCustomAction = new SentryTracer$$ExternalSyntheticLambda1(15, readVar);
                arrayList.add(getclasslogtag);
                r8lambdauggauuj_lbnzvef8yyxtwmhrlkq.MediaBrowserCompatMediaItem = this.MediaBrowserCompatMediaItem;
                r8lambdaA_tBhQGR0_Qo4AfQkBrfTkXVvg0 r8lambdaa_tbhqgr0_qo4afqkbrftkxvvg1 = new r8lambdaA_tBhQGR0_Qo4AfQkBrfTkXVvg0(r8lambdauggauuj_lbnzvef8yyxtwmhrlkq);
                int i3 = r8lambda54BeH8ZsBru0CXI2CCSP2syNys + 23;
                r8lambda7IJBVrN0sHyidCAZufWEJFc7yY = i3 % Fields.SpotShadowColor;
                if (i3 % 2 != 0) {
                    int i4 = 31 / 0;
                }
                return r8lambdaa_tbhqgr0_qo4afqkbrftkxvvg1;
            }
        });
        setNativeShader.RemoteActionCompatParcelizer(r8lambdaa_tbhqgr0_qo4afqkbrftkxvvg0, "Cannot return null from a non-@Nullable @Provides method");
        int i2 = r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg + 25;
        r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss = i2 % androidx.compose.ui.graphics.Fields.SpotShadowColor;
        int i3 = i2 % 2;
        return r8lambdaa_tbhqgr0_qo4afqkbrftkxvvg0;
    }
}
