package o;

import bo.app.c8$$ExternalSyntheticOutline0;

/* JADX INFO: loaded from: classes3.dex */
public final class SetTargetFragmentUsageViolation implements getColorIntegerOrNulllambda0 {
    private static int r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28 = 0;
    private static int r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0 = 1;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ ComponentActivity;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ IconCompatParcelizer;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ MediaBrowserCompatMediaItem;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ MediaDescriptionCompat;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ MediaMetadataCompat;
    public final FragmentStrictMode MediaSessionCompatQueueItem;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ MediaSessionCompatResultReceiverWrapper;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ MediaSessionCompatToken;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ ParcelableVolumeInfo;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ PlaybackStateCompat;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ PlaybackStateCompatCustomAction;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ RatingCompat;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ RemoteActionCompatParcelizer;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ ResultReceiver;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambda54BeH8ZsBru0CXI2CCSP2syNys;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambda7IJBVrN0sHyidCAZufWEJFc7yY;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ read;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ serializer;
    public final r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ write;

    public SetTargetFragmentUsageViolation(getDoubleOrNull getdoubleornull, getDoubleOrNull getdoubleornull2, getDoubleOrNull getdoubleornull3, getDoubleOrNull getdoubleornull4, r8lambdazXN1qqQhLYzDDSf7dMTrYE1xu8I r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i, getDoubleOrNull getdoubleornull5, getDoubleOrNull getdoubleornull6, getDoubleOrNull getdoubleornull7, getDoubleOrNull getdoubleornull8, getDoubleOrNull getdoubleornull9, getDoubleOrNull getdoubleornull10, getDoubleOrNull getdoubleornull11, getDoubleOrNull getdoubleornull12, getDoubleOrNull getdoubleornull13, getDoubleOrNull getdoubleornull14, getDoubleOrNull getdoubleornull15, getDoubleOrNull getdoubleornull16, getDoubleOrNull getdoubleornull17, SimpleExecutableQuery simpleExecutableQuery, getDoubleOrNull getdoubleornull18, getDoubleOrNull getdoubleornull19, getDoubleOrNull getdoubleornull20, lambda31 lambda31Var, getDoubleOrNull getdoubleornull21, r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ r8lambdaktwlyipskq3tfa9ey3gatonixfq, FragmentStrictMode fragmentStrictMode) {
        getdoubleornull.getClass();
        getdoubleornull2.getClass();
        getdoubleornull3.getClass();
        getdoubleornull4.getClass();
        r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i.getClass();
        c8$$ExternalSyntheticOutline0.m(getdoubleornull5, getdoubleornull6, getdoubleornull7, getdoubleornull8, getdoubleornull9);
        c8$$ExternalSyntheticOutline0.m(getdoubleornull10, getdoubleornull11, getdoubleornull12, getdoubleornull13, getdoubleornull14);
        getdoubleornull15.getClass();
        getdoubleornull16.getClass();
        getdoubleornull17.getClass();
        simpleExecutableQuery.getClass();
        getdoubleornull18.getClass();
        getdoubleornull19.getClass();
        getdoubleornull20.getClass();
        lambda31Var.getClass();
        getdoubleornull21.getClass();
        r8lambdaktwlyipskq3tfa9ey3gatonixfq.getClass();
        this.ComponentActivity = getdoubleornull;
        this.r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8 = getdoubleornull2;
        this.read = getdoubleornull3;
        this.MediaDescriptionCompat = getdoubleornull4;
        this.RemoteActionCompatParcelizer = r8lambdazxn1qqqhlyzddsf7dmtrye1xu8i;
        this.MediaMetadataCompat = getdoubleornull5;
        this.MediaSessionCompatToken = getdoubleornull6;
        this.MediaBrowserCompatMediaItem = getdoubleornull7;
        this.PlaybackStateCompatCustomAction = getdoubleornull8;
        this.r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg = getdoubleornull9;
        this.r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4 = getdoubleornull10;
        this.r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM = getdoubleornull11;
        this.r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ = getdoubleornull12;
        this.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus = getdoubleornull13;
        this.write = getdoubleornull14;
        this.RatingCompat = getdoubleornull15;
        this.r8lambda7IJBVrN0sHyidCAZufWEJFc7yY = getdoubleornull16;
        this.IconCompatParcelizer = getdoubleornull17;
        this.ParcelableVolumeInfo = simpleExecutableQuery;
        this.MediaSessionCompatResultReceiverWrapper = getdoubleornull18;
        this.PlaybackStateCompat = getdoubleornull19;
        this.r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss = getdoubleornull20;
        this.serializer = lambda31Var;
        this.ResultReceiver = getdoubleornull21;
        this.r8lambda54BeH8ZsBru0CXI2CCSP2syNys = r8lambdaktwlyipskq3tfa9ey3gatonixfq;
        this.MediaSessionCompatQueueItem = fragmentStrictMode;
    }

    @Override // o.r8lambdaktWLyIpskQ3TFA9eY3gatOnIxFQ
    public final Object write() {
        int i = 2 % 2;
        Object objWrite = this.ComponentActivity.write();
        objWrite.getClass();
        r8lambdaozNB94lb3BLPq0xEU9BDU28Zcxw r8lambdaoznb94lb3blpq0xeu9bdu28zcxw = (r8lambdaozNB94lb3BLPq0xEU9BDU28Zcxw) objWrite;
        Object objWrite2 = this.r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8.write();
        objWrite2.getClass();
        sendNextI sendnexti = (sendNextI) objWrite2;
        Object objWrite3 = this.read.write();
        objWrite3.getClass();
        forEachRect foreachrect = (forEachRect) objWrite3;
        Object objWrite4 = this.MediaDescriptionCompat.write();
        objWrite4.getClass();
        getAnimatingAway getanimatingaway = (getAnimatingAway) objWrite4;
        Object objWrite5 = this.RemoteActionCompatParcelizer.write();
        objWrite5.getClass();
        S s = (S) objWrite5;
        Object objWrite6 = this.MediaMetadataCompat.write();
        objWrite6.getClass();
        isSegmentInside issegmentinside = (isSegmentInside) objWrite6;
        Object objWrite7 = this.MediaSessionCompatToken.write();
        objWrite7.getClass();
        getFontCacheManagementDispatcher getfontcachemanagementdispatcher = (getFontCacheManagementDispatcher) objWrite7;
        Object objWrite8 = this.MediaBrowserCompatMediaItem.write();
        objWrite8.getClass();
        getNexteUduSuo getnexteudusuo = (getNexteUduSuo) objWrite8;
        Object objWrite9 = this.PlaybackStateCompatCustomAction.write();
        objWrite9.getClass();
        nb nbVar = (nb) objWrite9;
        Object objWrite10 = this.r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg.write();
        objWrite10.getClass();
        accessgetBothcp accessgetbothcp = (accessgetBothcp) objWrite10;
        Object objWrite11 = this.r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4.write();
        objWrite11.getClass();
        accessgetStartcp accessgetstartcp = (accessgetStartcp) objWrite11;
        Object objWrite12 = this.r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM.write();
        objWrite12.getClass();
        getUnspecifiede0LSkKk getunspecifiede0lskkk = (getUnspecifiede0LSkKk) objWrite12;
        Object objWrite13 = this.r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ.write();
        objWrite13.getClass();
        getUnspecifieds_7Xco getunspecifieds_7xco = (getUnspecifieds_7Xco) objWrite13;
        Object objWrite14 = this.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus.write();
        objWrite14.getClass();
        accessgetFixedcp accessgetfixedcp = (accessgetFixedcp) objWrite14;
        Object objWrite15 = this.write.write();
        objWrite15.getClass();
        accesslayout accesslayoutVar = (accesslayout) objWrite15;
        Object objWrite16 = this.RatingCompat.write();
        objWrite16.getClass();
        getTextDirectionHeuristicui_text gettextdirectionheuristicui_text = (getTextDirectionHeuristicui_text) objWrite16;
        Object objWrite17 = this.r8lambda7IJBVrN0sHyidCAZufWEJFc7yY.write();
        objWrite17.getClass();
        getHasEmojiCompat gethasemojicompat = (getHasEmojiCompat) objWrite17;
        Object objWrite18 = this.IconCompatParcelizer.write();
        objWrite18.getClass();
        buildLicenseVerificationSdkClickPackage buildlicenseverificationsdkclickpackage = (buildLicenseVerificationSdkClickPackage) objWrite18;
        Object objWrite19 = this.ParcelableVolumeInfo.write();
        objWrite19.getClass();
        eg egVar = (eg) objWrite19;
        Object objWrite20 = this.MediaSessionCompatResultReceiverWrapper.write();
        objWrite20.getClass();
        getCharacterLeftBounds getcharacterleftbounds = (getCharacterLeftBounds) objWrite20;
        Object objWrite21 = this.PlaybackStateCompat.write();
        objWrite21.getClass();
        WorkSpecDaoKtdedupinlinedmap12 workSpecDaoKtdedupinlinedmap12 = (WorkSpecDaoKtdedupinlinedmap12) objWrite21;
        Object objWrite22 = this.r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss.write();
        objWrite22.getClass();
        removeSingleSubscriptionlambda1 removesinglesubscriptionlambda1 = (removeSingleSubscriptionlambda1) objWrite22;
        Object objWrite23 = this.serializer.write();
        objWrite23.getClass();
        copyuxg59PAdefault copyuxg59padefault = (copyuxg59PAdefault) objWrite23;
        Object objWrite24 = this.ResultReceiver.write();
        objWrite24.getClass();
        KeyboardCapitalization keyboardCapitalization = (KeyboardCapitalization) objWrite24;
        Object objWrite25 = this.r8lambda54BeH8ZsBru0CXI2CCSP2syNys.write();
        objWrite25.getClass();
        GetRetainInstanceUsageViolation getRetainInstanceUsageViolation = new GetRetainInstanceUsageViolation(r8lambdaoznb94lb3blpq0xeu9bdu28zcxw, sendnexti, foreachrect, getanimatingaway, s, issegmentinside, getfontcachemanagementdispatcher, getnexteudusuo, nbVar, accessgetbothcp, accessgetstartcp, getunspecifiede0lskkk, getunspecifieds_7xco, accessgetfixedcp, accesslayoutVar, gettextdirectionheuristicui_text, gethasemojicompat, buildlicenseverificationsdkclickpackage, egVar, getcharacterleftbounds, workSpecDaoKtdedupinlinedmap12, removesinglesubscriptionlambda1, copyuxg59padefault, keyboardCapitalization, (dispatchChildDetached) objWrite25, (applyState) this.MediaSessionCompatQueueItem.write());
        int i2 = r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28 + 79;
        r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0 = i2 % androidx.compose.ui.graphics.Fields.SpotShadowColor;
        if (i2 % 2 != 0) {
            return getRetainInstanceUsageViolation;
        }
        Object obj = null;
        obj.hashCode();
        throw null;
    }
}
