package o;

import android.view.ViewGroup;
import java.util.Arrays;
import java.util.HashMap;

/* JADX INFO: loaded from: classes.dex */
public final class ShadowScope {
    public final SimpleDropShadowElement IconCompatParcelizer;
    public final SimpleDropShadowNode RatingCompat;
    public final shadowziNgDLEdefault RemoteActionCompatParcelizer;
    public int read;
    public HashMap serializer;
    public final ShadowScopeDefaultImpls write;

    public static void IconCompatParcelizer(ShadowScope shadowScope, int i, shadows4CzXIIdefault shadows4czxiidefault) {
        shadowScope.read = i;
        SimpleDropShadowElement simpleDropShadowElement = shadowScope.IconCompatParcelizer;
        simpleDropShadowElement.ensureViewModelStore = shadows4czxiidefault._init_lambda2;
        simpleDropShadowElement.createFullyDrawnExecutor = shadows4czxiidefault._init_lambda1;
        simpleDropShadowElement.addMenuProvider = shadows4czxiidefault.enterPictureInPictureMode;
        simpleDropShadowElement.addOnContextAvailableListener = shadows4czxiidefault.addOnUserLeaveHintListener;
        simpleDropShadowElement.getFullyDrawnReporter = shadows4czxiidefault.getDefaultViewModelCreationExtras;
        simpleDropShadowElement.addOnUserLeaveHintListener = shadows4czxiidefault.getDefaultViewModelProviderFactory;
        simpleDropShadowElement.RatingCompat = shadows4czxiidefault.MediaDescriptionCompat;
        simpleDropShadowElement.MediaDescriptionCompat = shadows4czxiidefault.RemoteActionCompatParcelizer;
        simpleDropShadowElement.RemoteActionCompatParcelizer = shadows4czxiidefault.read;
        simpleDropShadowElement.serializer = shadows4czxiidefault.IconCompatParcelizer;
        simpleDropShadowElement.write = shadows4czxiidefault.write;
        simpleDropShadowElement.addOnTrimMemoryListener = shadows4czxiidefault.getActivityResultRegistry;
        simpleDropShadowElement.addOnPictureInPictureModeChangedListener = shadows4czxiidefault.getFullyDrawnReporter;
        simpleDropShadowElement.r8lambda54BeH8ZsBru0CXI2CCSP2syNys = shadows4czxiidefault.ResultReceiver;
        simpleDropShadowElement.ComponentActivity = shadows4czxiidefault.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus;
        simpleDropShadowElement._init_lambda3 = shadows4czxiidefault.r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0;
        simpleDropShadowElement.getLastCustomNonConfigurationInstance = shadows4czxiidefault.getLastCustomNonConfigurationInstance;
        simpleDropShadowElement.MediaSessionCompatResultReceiverWrapper = shadows4czxiidefault.MediaSessionCompatResultReceiverWrapper;
        simpleDropShadowElement.MediaSessionCompatQueueItem = shadows4czxiidefault.RatingCompat;
        simpleDropShadowElement.PlaybackStateCompatCustomAction = shadows4czxiidefault.MediaBrowserCompatMediaItem;
        simpleDropShadowElement.MediaBrowserCompatMediaItem = shadows4czxiidefault.MediaMetadataCompat;
        simpleDropShadowElement.PlaybackStateCompat = shadows4czxiidefault.PlaybackStateCompat;
        simpleDropShadowElement.ResultReceiver = shadows4czxiidefault.ParcelableVolumeInfo;
        simpleDropShadowElement.addOnMultiWindowModeChangedListener = shadows4czxiidefault.addOnPictureInPictureModeChangedListener;
        simpleDropShadowElement.r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw = shadows4czxiidefault.r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ;
        simpleDropShadowElement.r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs = shadows4czxiidefault.r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss;
        simpleDropShadowElement.r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ = shadows4czxiidefault.r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs;
        simpleDropShadowElement.onBackPressedInput_delegatelambda0 = ((ViewGroup.MarginLayoutParams) shadows4czxiidefault).width;
        simpleDropShadowElement.getOnBackPressedInput = ((ViewGroup.MarginLayoutParams) shadows4czxiidefault).height;
        simpleDropShadowElement.addObserverForBackInvoker = ((ViewGroup.MarginLayoutParams) shadows4czxiidefault).leftMargin;
        simpleDropShadowElement.addOnNewIntentListener = ((ViewGroup.MarginLayoutParams) shadows4czxiidefault).rightMargin;
        simpleDropShadowElement.addOnPictureInPictureUiStateChangedListener = ((ViewGroup.MarginLayoutParams) shadows4czxiidefault).topMargin;
        simpleDropShadowElement.MediaMetadataCompat = ((ViewGroup.MarginLayoutParams) shadows4czxiidefault).bottomMargin;
        simpleDropShadowElement.IconCompatParcelizer = shadows4czxiidefault.serializer;
        simpleDropShadowElement.getActivityResultRegistry = shadows4czxiidefault.getSavedStateRegistry;
        simpleDropShadowElement.defaultViewModelProviderFactory_delegatelambda0 = shadows4czxiidefault._init_lambda3;
        simpleDropShadowElement.getDefaultViewModelProviderFactory = shadows4czxiidefault.getOnBackPressedDispatcher;
        simpleDropShadowElement.addObserverForBackInvokerlambda0 = shadows4czxiidefault.r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw;
        simpleDropShadowElement.MediaSessionCompatToken = shadows4czxiidefault.MediaSessionCompatToken;
        simpleDropShadowElement.ParcelableVolumeInfo = shadows4czxiidefault.MediaSessionCompatQueueItem;
        simpleDropShadowElement.getDefaultViewModelCreationExtras = shadows4czxiidefault.addOnMultiWindowModeChangedListener;
        simpleDropShadowElement._init_lambda2 = shadows4czxiidefault.onBackPressedDispatcher_delegatelambda010;
        simpleDropShadowElement.getLifecycle = shadows4czxiidefault.addMenuProvider;
        simpleDropShadowElement.accessensureViewModelStore = shadows4czxiidefault.addOnContextAvailableListener;
        simpleDropShadowElement.getNavigationEventDispatcher = shadows4czxiidefault.addOnConfigurationChangedListener;
        simpleDropShadowElement._init_lambda1 = shadows4czxiidefault.addOnNewIntentListener;
        simpleDropShadowElement.getSavedStateRegistry = shadows4czxiidefault.addOnTrimMemoryListener;
        simpleDropShadowElement._init_lambda4 = shadows4czxiidefault.addOnPictureInPictureUiStateChangedListener;
        simpleDropShadowElement.fullyDrawnReporter_delegatelambda00 = shadows4czxiidefault.PlaybackStateCompatCustomAction;
        simpleDropShadowElement.r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28 = shadows4czxiidefault.r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8;
        simpleDropShadowElement.r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss = shadows4czxiidefault.r8lambda7IJBVrN0sHyidCAZufWEJFc7yY;
        simpleDropShadowElement.r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM = shadows4czxiidefault.r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4;
        simpleDropShadowElement.r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4 = shadows4czxiidefault.r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg;
        simpleDropShadowElement.r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg = shadows4czxiidefault.r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM;
        simpleDropShadowElement.r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8 = shadows4czxiidefault.ComponentActivity;
        simpleDropShadowElement.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus = shadows4czxiidefault.r8lambda54BeH8ZsBru0CXI2CCSP2syNys;
        simpleDropShadowElement.addOnConfigurationChangedListener = shadows4czxiidefault.getViewModelStore;
        simpleDropShadowElement.r8lambda7IJBVrN0sHyidCAZufWEJFc7yY = shadows4czxiidefault.getMarginEnd();
        simpleDropShadowElement.enterPictureInPictureMode = shadows4czxiidefault.getMarginStart();
    }

    public final void RemoteActionCompatParcelizer(shadows4CzXIIdefault shadows4czxiidefault) {
        SimpleDropShadowElement simpleDropShadowElement = this.IconCompatParcelizer;
        shadows4czxiidefault._init_lambda2 = simpleDropShadowElement.ensureViewModelStore;
        shadows4czxiidefault._init_lambda1 = simpleDropShadowElement.createFullyDrawnExecutor;
        shadows4czxiidefault.enterPictureInPictureMode = simpleDropShadowElement.addMenuProvider;
        shadows4czxiidefault.addOnUserLeaveHintListener = simpleDropShadowElement.addOnContextAvailableListener;
        shadows4czxiidefault.getDefaultViewModelCreationExtras = simpleDropShadowElement.getFullyDrawnReporter;
        shadows4czxiidefault.getDefaultViewModelProviderFactory = simpleDropShadowElement.addOnUserLeaveHintListener;
        shadows4czxiidefault.MediaDescriptionCompat = simpleDropShadowElement.RatingCompat;
        shadows4czxiidefault.RemoteActionCompatParcelizer = simpleDropShadowElement.MediaDescriptionCompat;
        shadows4czxiidefault.read = simpleDropShadowElement.RemoteActionCompatParcelizer;
        shadows4czxiidefault.IconCompatParcelizer = simpleDropShadowElement.serializer;
        shadows4czxiidefault.write = simpleDropShadowElement.write;
        shadows4czxiidefault.getActivityResultRegistry = simpleDropShadowElement.addOnTrimMemoryListener;
        shadows4czxiidefault.getFullyDrawnReporter = simpleDropShadowElement.addOnPictureInPictureModeChangedListener;
        shadows4czxiidefault.ResultReceiver = simpleDropShadowElement.r8lambda54BeH8ZsBru0CXI2CCSP2syNys;
        shadows4czxiidefault.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus = simpleDropShadowElement.ComponentActivity;
        ((ViewGroup.MarginLayoutParams) shadows4czxiidefault).leftMargin = simpleDropShadowElement.addObserverForBackInvoker;
        ((ViewGroup.MarginLayoutParams) shadows4czxiidefault).rightMargin = simpleDropShadowElement.addOnNewIntentListener;
        ((ViewGroup.MarginLayoutParams) shadows4czxiidefault).topMargin = simpleDropShadowElement.addOnPictureInPictureUiStateChangedListener;
        ((ViewGroup.MarginLayoutParams) shadows4czxiidefault).bottomMargin = simpleDropShadowElement.MediaMetadataCompat;
        shadows4czxiidefault.r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM = simpleDropShadowElement.r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg;
        shadows4czxiidefault.ComponentActivity = simpleDropShadowElement.r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8;
        shadows4czxiidefault.r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8 = simpleDropShadowElement.r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28;
        shadows4czxiidefault.r8lambda7IJBVrN0sHyidCAZufWEJFc7yY = simpleDropShadowElement.r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss;
        shadows4czxiidefault.r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0 = simpleDropShadowElement._init_lambda3;
        shadows4czxiidefault.getLastCustomNonConfigurationInstance = simpleDropShadowElement.getLastCustomNonConfigurationInstance;
        shadows4czxiidefault.RatingCompat = simpleDropShadowElement.MediaSessionCompatQueueItem;
        shadows4czxiidefault.MediaBrowserCompatMediaItem = simpleDropShadowElement.PlaybackStateCompatCustomAction;
        shadows4czxiidefault.MediaMetadataCompat = simpleDropShadowElement.MediaBrowserCompatMediaItem;
        shadows4czxiidefault.MediaSessionCompatResultReceiverWrapper = simpleDropShadowElement.MediaSessionCompatResultReceiverWrapper;
        shadows4czxiidefault.PlaybackStateCompat = simpleDropShadowElement.PlaybackStateCompat;
        shadows4czxiidefault.ParcelableVolumeInfo = simpleDropShadowElement.ResultReceiver;
        shadows4czxiidefault.getSavedStateRegistry = simpleDropShadowElement.getActivityResultRegistry;
        shadows4czxiidefault._init_lambda3 = simpleDropShadowElement.defaultViewModelProviderFactory_delegatelambda0;
        shadows4czxiidefault.getOnBackPressedDispatcher = simpleDropShadowElement.getDefaultViewModelProviderFactory;
        shadows4czxiidefault.r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw = simpleDropShadowElement.addObserverForBackInvokerlambda0;
        shadows4czxiidefault.MediaSessionCompatToken = simpleDropShadowElement.MediaSessionCompatToken;
        shadows4czxiidefault.MediaSessionCompatQueueItem = simpleDropShadowElement.ParcelableVolumeInfo;
        shadows4czxiidefault.addOnMultiWindowModeChangedListener = simpleDropShadowElement.getDefaultViewModelCreationExtras;
        shadows4czxiidefault.onBackPressedDispatcher_delegatelambda010 = simpleDropShadowElement._init_lambda2;
        shadows4czxiidefault.addMenuProvider = simpleDropShadowElement.getLifecycle;
        shadows4czxiidefault.addOnContextAvailableListener = simpleDropShadowElement.accessensureViewModelStore;
        shadows4czxiidefault.addOnConfigurationChangedListener = simpleDropShadowElement.getNavigationEventDispatcher;
        shadows4czxiidefault.addOnNewIntentListener = simpleDropShadowElement._init_lambda1;
        shadows4czxiidefault.addOnTrimMemoryListener = simpleDropShadowElement.getSavedStateRegistry;
        shadows4czxiidefault.addOnPictureInPictureUiStateChangedListener = simpleDropShadowElement._init_lambda4;
        shadows4czxiidefault.addOnPictureInPictureModeChangedListener = simpleDropShadowElement.addOnMultiWindowModeChangedListener;
        shadows4czxiidefault.r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ = simpleDropShadowElement.r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw;
        shadows4czxiidefault.r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss = simpleDropShadowElement.r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs;
        shadows4czxiidefault.r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs = simpleDropShadowElement.r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ;
        ((ViewGroup.MarginLayoutParams) shadows4czxiidefault).width = simpleDropShadowElement.onBackPressedInput_delegatelambda0;
        ((ViewGroup.MarginLayoutParams) shadows4czxiidefault).height = simpleDropShadowElement.getOnBackPressedInput;
        String str = simpleDropShadowElement.fullyDrawnReporter_delegatelambda00;
        if (str != null) {
            shadows4czxiidefault.PlaybackStateCompatCustomAction = str;
        }
        shadows4czxiidefault.getViewModelStore = simpleDropShadowElement.addOnConfigurationChangedListener;
        shadows4czxiidefault.setMarginStart(simpleDropShadowElement.enterPictureInPictureMode);
        shadows4czxiidefault.setMarginEnd(simpleDropShadowElement.r8lambda7IJBVrN0sHyidCAZufWEJFc7yY);
        shadows4czxiidefault.RemoteActionCompatParcelizer();
    }

    public final Object clone() {
        ShadowScope shadowScope = new ShadowScope();
        SimpleDropShadowElement simpleDropShadowElement = shadowScope.IconCompatParcelizer;
        simpleDropShadowElement.getClass();
        SimpleDropShadowElement simpleDropShadowElement2 = this.IconCompatParcelizer;
        simpleDropShadowElement.onBackPressedDispatcher_delegatelambda00 = simpleDropShadowElement2.onBackPressedDispatcher_delegatelambda00;
        simpleDropShadowElement.onBackPressedInput_delegatelambda0 = simpleDropShadowElement2.onBackPressedInput_delegatelambda0;
        simpleDropShadowElement.getOnBackPressedInput = simpleDropShadowElement2.getOnBackPressedInput;
        simpleDropShadowElement.r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs = simpleDropShadowElement2.r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs;
        simpleDropShadowElement.r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ = simpleDropShadowElement2.r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ;
        simpleDropShadowElement.r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw = simpleDropShadowElement2.r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw;
        simpleDropShadowElement.r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0 = simpleDropShadowElement2.r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0;
        simpleDropShadowElement.ensureViewModelStore = simpleDropShadowElement2.ensureViewModelStore;
        simpleDropShadowElement.createFullyDrawnExecutor = simpleDropShadowElement2.createFullyDrawnExecutor;
        simpleDropShadowElement.addMenuProvider = simpleDropShadowElement2.addMenuProvider;
        simpleDropShadowElement.addOnContextAvailableListener = simpleDropShadowElement2.addOnContextAvailableListener;
        simpleDropShadowElement.getFullyDrawnReporter = simpleDropShadowElement2.getFullyDrawnReporter;
        simpleDropShadowElement.addOnUserLeaveHintListener = simpleDropShadowElement2.addOnUserLeaveHintListener;
        simpleDropShadowElement.RatingCompat = simpleDropShadowElement2.RatingCompat;
        simpleDropShadowElement.MediaDescriptionCompat = simpleDropShadowElement2.MediaDescriptionCompat;
        simpleDropShadowElement.RemoteActionCompatParcelizer = simpleDropShadowElement2.RemoteActionCompatParcelizer;
        simpleDropShadowElement.serializer = simpleDropShadowElement2.serializer;
        simpleDropShadowElement.write = simpleDropShadowElement2.write;
        simpleDropShadowElement.addOnTrimMemoryListener = simpleDropShadowElement2.addOnTrimMemoryListener;
        simpleDropShadowElement.addOnPictureInPictureModeChangedListener = simpleDropShadowElement2.addOnPictureInPictureModeChangedListener;
        simpleDropShadowElement.r8lambda54BeH8ZsBru0CXI2CCSP2syNys = simpleDropShadowElement2.r8lambda54BeH8ZsBru0CXI2CCSP2syNys;
        simpleDropShadowElement.ComponentActivity = simpleDropShadowElement2.ComponentActivity;
        simpleDropShadowElement._init_lambda3 = simpleDropShadowElement2._init_lambda3;
        simpleDropShadowElement.getLastCustomNonConfigurationInstance = simpleDropShadowElement2.getLastCustomNonConfigurationInstance;
        simpleDropShadowElement.MediaSessionCompatResultReceiverWrapper = simpleDropShadowElement2.MediaSessionCompatResultReceiverWrapper;
        simpleDropShadowElement.MediaSessionCompatQueueItem = simpleDropShadowElement2.MediaSessionCompatQueueItem;
        simpleDropShadowElement.PlaybackStateCompatCustomAction = simpleDropShadowElement2.PlaybackStateCompatCustomAction;
        simpleDropShadowElement.MediaBrowserCompatMediaItem = simpleDropShadowElement2.MediaBrowserCompatMediaItem;
        simpleDropShadowElement.PlaybackStateCompat = simpleDropShadowElement2.PlaybackStateCompat;
        simpleDropShadowElement.ResultReceiver = simpleDropShadowElement2.ResultReceiver;
        simpleDropShadowElement.addOnMultiWindowModeChangedListener = simpleDropShadowElement2.addOnMultiWindowModeChangedListener;
        simpleDropShadowElement.addObserverForBackInvoker = simpleDropShadowElement2.addObserverForBackInvoker;
        simpleDropShadowElement.addOnNewIntentListener = simpleDropShadowElement2.addOnNewIntentListener;
        simpleDropShadowElement.addOnPictureInPictureUiStateChangedListener = simpleDropShadowElement2.addOnPictureInPictureUiStateChangedListener;
        simpleDropShadowElement.MediaMetadataCompat = simpleDropShadowElement2.MediaMetadataCompat;
        simpleDropShadowElement.r8lambda7IJBVrN0sHyidCAZufWEJFc7yY = simpleDropShadowElement2.r8lambda7IJBVrN0sHyidCAZufWEJFc7yY;
        simpleDropShadowElement.enterPictureInPictureMode = simpleDropShadowElement2.enterPictureInPictureMode;
        simpleDropShadowElement.IconCompatParcelizer = simpleDropShadowElement2.IconCompatParcelizer;
        simpleDropShadowElement.r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM = simpleDropShadowElement2.r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM;
        simpleDropShadowElement.r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28 = simpleDropShadowElement2.r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28;
        simpleDropShadowElement.r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4 = simpleDropShadowElement2.r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4;
        simpleDropShadowElement.r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss = simpleDropShadowElement2.r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss;
        simpleDropShadowElement.r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8 = simpleDropShadowElement2.r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8;
        simpleDropShadowElement.r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg = simpleDropShadowElement2.r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg;
        simpleDropShadowElement.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus = simpleDropShadowElement2.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus;
        simpleDropShadowElement.getActivityResultRegistry = simpleDropShadowElement2.getActivityResultRegistry;
        simpleDropShadowElement.defaultViewModelProviderFactory_delegatelambda0 = simpleDropShadowElement2.defaultViewModelProviderFactory_delegatelambda0;
        simpleDropShadowElement.addObserverForBackInvokerlambda0 = simpleDropShadowElement2.addObserverForBackInvokerlambda0;
        simpleDropShadowElement.getDefaultViewModelProviderFactory = simpleDropShadowElement2.getDefaultViewModelProviderFactory;
        simpleDropShadowElement.getDefaultViewModelCreationExtras = simpleDropShadowElement2.getDefaultViewModelCreationExtras;
        simpleDropShadowElement._init_lambda2 = simpleDropShadowElement2._init_lambda2;
        simpleDropShadowElement.getLifecycle = simpleDropShadowElement2.getLifecycle;
        simpleDropShadowElement.accessensureViewModelStore = simpleDropShadowElement2.accessensureViewModelStore;
        simpleDropShadowElement.getNavigationEventDispatcher = simpleDropShadowElement2.getNavigationEventDispatcher;
        simpleDropShadowElement._init_lambda1 = simpleDropShadowElement2._init_lambda1;
        simpleDropShadowElement.getSavedStateRegistry = simpleDropShadowElement2.getSavedStateRegistry;
        simpleDropShadowElement._init_lambda4 = simpleDropShadowElement2._init_lambda4;
        simpleDropShadowElement.getSavedStateRegistryControllerannotations = simpleDropShadowElement2.getSavedStateRegistryControllerannotations;
        simpleDropShadowElement.menuHostHelperlambda0 = simpleDropShadowElement2.menuHostHelperlambda0;
        simpleDropShadowElement.onBackPressedDispatcher_delegatelambda0 = simpleDropShadowElement2.onBackPressedDispatcher_delegatelambda0;
        simpleDropShadowElement.fullyDrawnReporter_delegatelambda00 = simpleDropShadowElement2.fullyDrawnReporter_delegatelambda00;
        int[] iArr = simpleDropShadowElement2.onBackPressedDispatcher_delegatelambda010;
        if (iArr == null || simpleDropShadowElement2.addContentView != null) {
            simpleDropShadowElement.onBackPressedDispatcher_delegatelambda010 = null;
        } else {
            simpleDropShadowElement.onBackPressedDispatcher_delegatelambda010 = Arrays.copyOf(iArr, iArr.length);
        }
        simpleDropShadowElement.addContentView = simpleDropShadowElement2.addContentView;
        simpleDropShadowElement.MediaSessionCompatToken = simpleDropShadowElement2.MediaSessionCompatToken;
        simpleDropShadowElement.ParcelableVolumeInfo = simpleDropShadowElement2.ParcelableVolumeInfo;
        simpleDropShadowElement.fullyDrawnReporter_delegatelambda0 = simpleDropShadowElement2.fullyDrawnReporter_delegatelambda0;
        simpleDropShadowElement.addOnConfigurationChangedListener = simpleDropShadowElement2.addOnConfigurationChangedListener;
        shadowziNgDLEdefault shadowzingdledefault = shadowScope.RemoteActionCompatParcelizer;
        shadowzingdledefault.getClass();
        shadowziNgDLEdefault shadowzingdledefault2 = this.RemoteActionCompatParcelizer;
        shadowzingdledefault2.getClass();
        shadowzingdledefault.read = shadowzingdledefault2.read;
        shadowzingdledefault.IconCompatParcelizer = shadowzingdledefault2.IconCompatParcelizer;
        shadowzingdledefault.RatingCompat = shadowzingdledefault2.RatingCompat;
        shadowzingdledefault.serializer = shadowzingdledefault2.serializer;
        ShadowScopeDefaultImpls shadowScopeDefaultImpls = this.write;
        int i = shadowScopeDefaultImpls.serializer;
        ShadowScopeDefaultImpls shadowScopeDefaultImpls2 = shadowScope.write;
        shadowScopeDefaultImpls2.serializer = i;
        shadowScopeDefaultImpls2.read = shadowScopeDefaultImpls.read;
        shadowScopeDefaultImpls2.IconCompatParcelizer = shadowScopeDefaultImpls.IconCompatParcelizer;
        shadowScopeDefaultImpls2.write = shadowScopeDefaultImpls.write;
        SimpleDropShadowNode simpleDropShadowNode = shadowScope.RatingCompat;
        simpleDropShadowNode.getClass();
        SimpleDropShadowNode simpleDropShadowNode2 = this.RatingCompat;
        simpleDropShadowNode2.getClass();
        simpleDropShadowNode.RemoteActionCompatParcelizer = simpleDropShadowNode2.RemoteActionCompatParcelizer;
        simpleDropShadowNode.serializer = simpleDropShadowNode2.serializer;
        simpleDropShadowNode.RatingCompat = simpleDropShadowNode2.RatingCompat;
        simpleDropShadowNode.MediaSessionCompatQueueItem = simpleDropShadowNode2.MediaSessionCompatQueueItem;
        simpleDropShadowNode.MediaDescriptionCompat = simpleDropShadowNode2.MediaDescriptionCompat;
        simpleDropShadowNode.MediaMetadataCompat = simpleDropShadowNode2.MediaMetadataCompat;
        simpleDropShadowNode.PlaybackStateCompatCustomAction = simpleDropShadowNode2.PlaybackStateCompatCustomAction;
        simpleDropShadowNode.MediaBrowserCompatMediaItem = simpleDropShadowNode2.MediaBrowserCompatMediaItem;
        simpleDropShadowNode.PlaybackStateCompat = simpleDropShadowNode2.PlaybackStateCompat;
        simpleDropShadowNode.MediaSessionCompatToken = simpleDropShadowNode2.MediaSessionCompatToken;
        simpleDropShadowNode.MediaSessionCompatResultReceiverWrapper = simpleDropShadowNode2.MediaSessionCompatResultReceiverWrapper;
        simpleDropShadowNode.write = simpleDropShadowNode2.write;
        simpleDropShadowNode.IconCompatParcelizer = simpleDropShadowNode2.IconCompatParcelizer;
        shadowScope.read = this.read;
        return shadowScope;
    }

    public ShadowScope() {
        ShadowScopeDefaultImpls shadowScopeDefaultImpls = new ShadowScopeDefaultImpls();
        shadowScopeDefaultImpls.serializer = 0;
        shadowScopeDefaultImpls.write = 0;
        shadowScopeDefaultImpls.read = 1.0f;
        shadowScopeDefaultImpls.IconCompatParcelizer = Float.NaN;
        this.write = shadowScopeDefaultImpls;
        shadowziNgDLEdefault shadowzingdledefault = new shadowziNgDLEdefault();
        shadowzingdledefault.read = -1;
        shadowzingdledefault.write = 0;
        shadowzingdledefault.IconCompatParcelizer = -1;
        shadowzingdledefault.serializer = Float.NaN;
        shadowzingdledefault.RatingCompat = Float.NaN;
        shadowzingdledefault.MediaDescriptionCompat = Float.NaN;
        shadowzingdledefault.MediaBrowserCompatMediaItem = -1;
        shadowzingdledefault.MediaMetadataCompat = null;
        shadowzingdledefault.MediaSessionCompatQueueItem = -1;
        this.RemoteActionCompatParcelizer = shadowzingdledefault;
        SimpleDropShadowElement simpleDropShadowElement = new SimpleDropShadowElement();
        simpleDropShadowElement.onBackPressedDispatcher_delegatelambda00 = false;
        simpleDropShadowElement.r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs = -1;
        simpleDropShadowElement.r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ = -1;
        simpleDropShadowElement.r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw = -1.0f;
        simpleDropShadowElement.r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0 = true;
        simpleDropShadowElement.ensureViewModelStore = -1;
        simpleDropShadowElement.createFullyDrawnExecutor = -1;
        simpleDropShadowElement.addMenuProvider = -1;
        simpleDropShadowElement.addOnContextAvailableListener = -1;
        simpleDropShadowElement.getFullyDrawnReporter = -1;
        simpleDropShadowElement.addOnUserLeaveHintListener = -1;
        simpleDropShadowElement.RatingCompat = -1;
        simpleDropShadowElement.MediaDescriptionCompat = -1;
        simpleDropShadowElement.RemoteActionCompatParcelizer = -1;
        simpleDropShadowElement.serializer = -1;
        simpleDropShadowElement.write = -1;
        simpleDropShadowElement.addOnTrimMemoryListener = -1;
        simpleDropShadowElement.addOnPictureInPictureModeChangedListener = -1;
        simpleDropShadowElement.r8lambda54BeH8ZsBru0CXI2CCSP2syNys = -1;
        simpleDropShadowElement.ComponentActivity = -1;
        simpleDropShadowElement._init_lambda3 = 0.5f;
        simpleDropShadowElement.getLastCustomNonConfigurationInstance = 0.5f;
        simpleDropShadowElement.MediaSessionCompatResultReceiverWrapper = null;
        simpleDropShadowElement.MediaSessionCompatQueueItem = -1;
        simpleDropShadowElement.PlaybackStateCompatCustomAction = 0;
        simpleDropShadowElement.MediaBrowserCompatMediaItem = 0.0f;
        simpleDropShadowElement.PlaybackStateCompat = -1;
        simpleDropShadowElement.ResultReceiver = -1;
        simpleDropShadowElement.addOnMultiWindowModeChangedListener = -1;
        simpleDropShadowElement.addObserverForBackInvoker = 0;
        simpleDropShadowElement.addOnNewIntentListener = 0;
        simpleDropShadowElement.addOnPictureInPictureUiStateChangedListener = 0;
        simpleDropShadowElement.MediaMetadataCompat = 0;
        simpleDropShadowElement.r8lambda7IJBVrN0sHyidCAZufWEJFc7yY = 0;
        simpleDropShadowElement.enterPictureInPictureMode = 0;
        simpleDropShadowElement.IconCompatParcelizer = 0;
        simpleDropShadowElement.r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM = Integer.MIN_VALUE;
        simpleDropShadowElement.r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28 = Integer.MIN_VALUE;
        simpleDropShadowElement.r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4 = Integer.MIN_VALUE;
        simpleDropShadowElement.r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss = Integer.MIN_VALUE;
        simpleDropShadowElement.r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8 = Integer.MIN_VALUE;
        simpleDropShadowElement.r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg = Integer.MIN_VALUE;
        simpleDropShadowElement.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus = Integer.MIN_VALUE;
        simpleDropShadowElement.getActivityResultRegistry = -1.0f;
        simpleDropShadowElement.defaultViewModelProviderFactory_delegatelambda0 = -1.0f;
        simpleDropShadowElement.addObserverForBackInvokerlambda0 = 0;
        simpleDropShadowElement.getDefaultViewModelProviderFactory = 0;
        simpleDropShadowElement.getDefaultViewModelCreationExtras = 0;
        simpleDropShadowElement._init_lambda2 = 0;
        simpleDropShadowElement.getLifecycle = 0;
        simpleDropShadowElement.accessensureViewModelStore = 0;
        simpleDropShadowElement.getNavigationEventDispatcher = 0;
        simpleDropShadowElement._init_lambda1 = 0;
        simpleDropShadowElement.getSavedStateRegistry = 1.0f;
        simpleDropShadowElement._init_lambda4 = 1.0f;
        simpleDropShadowElement.getSavedStateRegistryControllerannotations = -1;
        simpleDropShadowElement.menuHostHelperlambda0 = 0;
        simpleDropShadowElement.onBackPressedDispatcher_delegatelambda0 = -1;
        simpleDropShadowElement.MediaSessionCompatToken = false;
        simpleDropShadowElement.ParcelableVolumeInfo = false;
        simpleDropShadowElement.fullyDrawnReporter_delegatelambda0 = true;
        simpleDropShadowElement.addOnConfigurationChangedListener = 0;
        this.IconCompatParcelizer = simpleDropShadowElement;
        SimpleDropShadowNode simpleDropShadowNode = new SimpleDropShadowNode();
        simpleDropShadowNode.RemoteActionCompatParcelizer = 0.0f;
        simpleDropShadowNode.serializer = 0.0f;
        simpleDropShadowNode.RatingCompat = 0.0f;
        simpleDropShadowNode.MediaSessionCompatQueueItem = 1.0f;
        simpleDropShadowNode.MediaDescriptionCompat = 1.0f;
        simpleDropShadowNode.MediaMetadataCompat = Float.NaN;
        simpleDropShadowNode.PlaybackStateCompatCustomAction = Float.NaN;
        simpleDropShadowNode.MediaBrowserCompatMediaItem = -1;
        simpleDropShadowNode.PlaybackStateCompat = 0.0f;
        simpleDropShadowNode.MediaSessionCompatToken = 0.0f;
        simpleDropShadowNode.MediaSessionCompatResultReceiverWrapper = 0.0f;
        simpleDropShadowNode.write = false;
        simpleDropShadowNode.IconCompatParcelizer = 0.0f;
        this.RatingCompat = simpleDropShadowNode;
        this.serializer = new HashMap();
    }
}
