package o;

/* JADX INFO: loaded from: classes.dex */
public enum toDpGaN1DYA {
    LEFT_TO_LEFT,
    LEFT_TO_RIGHT,
    RIGHT_TO_LEFT,
    RIGHT_TO_RIGHT,
    START_TO_START,
    START_TO_END,
    END_TO_START,
    END_TO_END,
    TOP_TO_TOP,
    TOP_TO_BOTTOM,
    TOP_TO_BASELINE,
    BOTTOM_TO_TOP,
    BOTTOM_TO_BOTTOM,
    BOTTOM_TO_BASELINE,
    BASELINE_TO_BASELINE,
    BASELINE_TO_TOP,
    BASELINE_TO_BOTTOM,
    CENTER_HORIZONTALLY,
    CENTER_VERTICALLY,
    CIRCULAR_CONSTRAINT
}
