package o;

import com.google.android.gms.internal.mlkit_vision_barcode.zzgb;
import com.google.android.gms.internal.mlkit_vision_barcode.zzgh;
import com.google.android.gms.internal.mlkit_vision_barcode.zzgz;
import com.google.android.gms.internal.mlkit_vision_barcode.zzpc;
import com.google.android.gms.internal.mlkit_vision_barcode.zzpd;
import com.google.android.gms.internal.mlkit_vision_barcode.zzpw;
import com.google.android.gms.internal.mlkit_vision_barcode.zzsd;
import com.mapbox.search.ApiTypeKt;
import com.roadrunner.location.util.HmsTasksKt;
import com.roadrunner.push.presentation.NotificationDialogKt;
import com.ui.common.base.BaseRxViewModelKt;
import kotlin.collections.unsigned.UArraysKt;
import kotlinx.datetime.InstantJvmKt;
import kotlinx.datetime.TimeZoneKt;
import okhttp3.Cookie$Companion;
import org.bouncycastle.asn1.ASN1Util;
import org.koin.androidx.viewmodel.GetViewModelKt;

/* JADX INFO: loaded from: classes2.dex */
public final class toMotionEventScopeubNVwUQ implements accessgetBrightnessDowncp {
    public static final toMotionEventScopeubNVwUQ IconCompatParcelizer = new toMotionEventScopeubNVwUQ(1);
    public static toMotionEventScopeubNVwUQ read;
    public final /* synthetic */ int serializer;

    public /* synthetic */ toMotionEventScopeubNVwUQ(int i) {
        this.serializer = i;
    }

    public static void IconCompatParcelizer() {
        synchronized (toMotionEventScopeubNVwUQ.class) {
            if (read == null) {
                read = new toMotionEventScopeubNVwUQ(0);
            }
        }
    }

    public void IconCompatParcelizer(getDiffer getdiffer) {
        getdiffer.serializer(dispatchToView.class, PointerHoverIconModifierElement.r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ);
        getdiffer.serializer(PointerInteropFilter_androidKtpointerInteropFilterinlineddebugInspectorInfo1.class, setInterceptOutOfBoundsChildEvents.serializer);
        getdiffer.serializer(dispatchKeyEventYhN2O0wdefault.class, isTertiaryPressedaHzCxE.IconCompatParcelizer);
        getdiffer.serializer(getEnd.class, PointerHoverIconModifierNode.write);
        getdiffer.serializer(r8lambdaD6k6wXRxTgZJWNsBhjsOrg3Yu9s.class, isShiftPressed5xRPYO0.serializer);
        getdiffer.serializer(downloadFileToPathlambda3.class, PointerIconCompanion.RemoteActionCompatParcelizer);
        getdiffer.serializer(io.sentry.android.replay.ComponentActivity.class, getExit7fucELk.RemoteActionCompatParcelizer);
        getdiffer.serializer(MultiSubscriptionSnapshotFlowManager.class, accessgetScaleChangecp.read);
        getdiffer.serializer(setOnTouchEvent.class, isFunctionPressed5xRPYO0.RemoteActionCompatParcelizer);
        getdiffer.serializer(PointerInteropFilter_androidKtmotionEventSpy11.class, getShareWithSiblings.IconCompatParcelizer);
        getdiffer.serializer(getPointerInputFilterannotations.class, PointerEventTypeCompanion.serializer);
        getdiffer.serializer(setFocusable.class, accessgetScrollcp.read);
        getdiffer.serializer(accessgetDowncp.class, getConsumedDelegateui.write);
        getdiffer.serializer(StrokeJoin.class, getScaleStart7fucELk.IconCompatParcelizer);
        getdiffer.serializer(getOnTouchEvent.class, getAreAnyPressedaHzCxE.write);
        getdiffer.serializer(retryInAppMessagelambda0.class, EmptyPointerKeyboardModifiers.RemoteActionCompatParcelizer);
        getdiffer.serializer(setCustomContentCardsViewBindingHandler.class, getConsumed.read);
        getdiffer.serializer(accessgetResourcep.class, processBIzXfog.write);
        getdiffer.serializer(getWhite0d7_KjUannotations.class, getLayoutCoordinatesui.serializer);
        getdiffer.serializer(evaluateFeaturefwf_client_release.class, clearPreviouslyHitModifierNodes.serializer);
        getdiffer.serializer(PointerInteropFilter_androidKt.class, pointerHoverIcondefault.serializer);
        getdiffer.serializer(emptyCancelMotionEventScopedefault.class, positionChangeInternal.read);
        getdiffer.serializer(motionEventSpy.class, stylusHoverIcon.RemoteActionCompatParcelizer);
        getdiffer.serializer(BaseCardView.class, setConsumedDelegateui.read);
        getdiffer.serializer(fetchCustomExitaToIllAui.class, PointerInputChangeEventProducer.read);
        getdiffer.serializer(io.sentry.util.network.IconCompatParcelizer.class, PointerInputChangeEventProducerPointerInputData.write);
        getdiffer.serializer(getLocalBitmaplambda2.class, setOriginalEventPositionk4lQ0Mui.read);
        getdiffer.serializer(getBlue0d7_KjU.class, component12F1C5BW0.write);
        getdiffer.serializer(r8lambdagkrDDkERifauZUmtkJOYYCCYn0.class, copyhf9UmOkdefault.read);
        getdiffer.serializer(AbstractC0193pointerInteropFilter.class, component1J3iCeTQ.read);
        getdiffer.serializer(displayInAppMessagelambda7.class, PointerInputEventData.RemoteActionCompatParcelizer);
        getdiffer.serializer(io.sentry.rrweb.write.class, PointerIconKt.serializer);
        getdiffer.serializer(isInteropViewHost.class, component4F1C5BW0.read);
        getdiffer.serializer(accessgetTransparentcp.class, copyhf9UmOk.read);
        getdiffer.serializer(getEvaluationsfwf_client_releasedefault.class, component13F1C5BW0.IconCompatParcelizer);
        getdiffer.serializer(fireOnDismissCallback.class, component7T8wyACA.IconCompatParcelizer);
        getdiffer.serializer(createCache.class, getScaleGestureFactor.write);
        getdiffer.serializer(prepareInAppMessageWithBitmapDownloadlambda2.class, PointerInputEventHandler.IconCompatParcelizer);
        getdiffer.serializer(r8lambdaSMZfgeuuAmx3jlwU4oNMm8PFms.class, getUptime.IconCompatParcelizer);
        getdiffer.serializer(FocusManager.class, isNumLockOn5xRPYO0.write);
        getdiffer.serializer(PointerInteropFilterpointerInputFilter1onCancel1.class, PointerInputEvent.RemoteActionCompatParcelizer);
        getdiffer.serializer(UArraysKt.class, getPositionOnScreenF1C5BW0.write);
        getdiffer.serializer(DefaultInAppMessageViewWrapperCompanion.class, component10F1C5BW0.write);
        getdiffer.serializer(TimeZoneKt.class, getInterceptOutOfBoundsChildEvents.read);
        getdiffer.serializer(coil3.network.internal.UtilsKt.class, PointerInputTestUtilKt.serializer);
        getdiffer.serializer(zzpd.class, positionChanged.read);
        getdiffer.serializer(invokeOverPasshUlJWOEdefault.class, positionChangeIgnoreConsumed.serializer);
        getdiffer.serializer(recordGeofenceTransitionlambda0.class, positionChangeConsumed.read);
        getdiffer.serializer(zzpc.class, positionChangedIgnoreConsumed.read);
        getdiffer.serializer(DataStoreUtilsc.class, PointerEventPass.RemoteActionCompatParcelizer);
        getdiffer.serializer(TextFieldImplKtCommonDecorationBox3borderContainerWithId1.class, toInt.serializer);
        getdiffer.serializer(getTopEndannotations.class, PointerEventTimeoutCancellationException.read);
        getdiffer.serializer(androidx.compose.foundation.gestures.ForEachGestureKt.class, accessgetPanEndcp.IconCompatParcelizer);
        getdiffer.serializer(AndroidAutofillManageronFocusChanged21.class, PointerEventType.RemoteActionCompatParcelizer);
        getdiffer.serializer(tryMaxHeightJN0ABg.class, fillInStackTrace.RemoteActionCompatParcelizer);
        getdiffer.serializer(moveBydefault.class, accessgetPanStartcp.write);
        getdiffer.serializer(calculateInSampleSizelambda1.class, isOutOfBoundsO0kMr_c.RemoteActionCompatParcelizer);
        getdiffer.serializer(getUptimeimpl.class, consumeAllChanges.IconCompatParcelizer);
        getdiffer.serializer(MotionEventAdapterIndirectPointerEventData.class, isOutOfBoundsjwHxaWs.write);
        getdiffer.serializer(getRequestDisallowInterceptTouchEvent.class, isBackPressedaHzCxE.RemoteActionCompatParcelizer);
        getdiffer.serializer(com.sentiance.protobuf.j.class, getPanEnd7fucELk.write);
        getdiffer.serializer(getSplitTrack.class, MotionEventAdapterIndirectPointerEventDataCompanion.write);
        getdiffer.serializer(hasPointerId.class, accessunpackShort2.write);
        getdiffer.serializer(PointerInteropFilter.class, PointerEvent_androidKt.serializer);
        getdiffer.serializer(convertToIndirectPointerEventk92h6UUui.class, unpackShort1.read);
        getdiffer.serializer(getCacheKey.class, accessunpackShort1.read);
        getdiffer.serializer(compare.class, dispatchCancel.RemoteActionCompatParcelizer);
        getdiffer.serializer(r8lambdatq6ACLpcPQ5kM_9Qo1nOx0ZDGDM.class, dispatchFinalEventPass.read);
        getdiffer.serializer(convertToPointerInputEventui.class, packShorts.IconCompatParcelizer);
        getdiffer.serializer(resetFakeFingerGesture.class, unpackShort2.serializer);
        getdiffer.serializer(HmsTasksKt.class, markIsIn.write);
        getdiffer.serializer(removeGeofencesRegisteredWithGeofencingClientandroid_sdk_location_release.class, PointerEvent.IconCompatParcelizer);
        getdiffer.serializer(PrematureEndOfStreamVideoQuirk.class, calculatePointerEventType7fucELk.IconCompatParcelizer);
        getdiffer.serializer(com.mapbox.search.base.utils.extension.StringKt.class, getClassification.write);
        getdiffer.serializer(SeekableTransitionState.class, consumePositionChange.serializer);
        getdiffer.serializer(PreviewBlackScreenQuirk.class, consumeDownChange.RemoteActionCompatParcelizer);
        getdiffer.serializer(ArrangementCenter1.class, PointerEventKt.RemoteActionCompatParcelizer);
        getdiffer.serializer(r8lambdajyieMEPHfDZ0H9VbS9ICj8_yOE.class, getKeyboardModifiersk7X9c1A.RemoteActionCompatParcelizer);
        getdiffer.serializer(getDownimpl.class, setTypeEhbLWggui.serializer);
        getdiffer.serializer(PlatformOptimizedCancellationException.class, getInternalPointerEventui.read);
        getdiffer.serializer(GetViewModelKt.class, setLayoutCoordinatesui.serializer);
        getdiffer.serializer(xor.class, getEnter7fucELk.read);
        getdiffer.serializer(Illuminant.class, pointerHoverIcon.RemoteActionCompatParcelizer);
        getdiffer.serializer(accessgetColorcp.class, getHand.RemoteActionCompatParcelizer);
        getdiffer.serializer(composeColorSpace.class, indexOfFirstPressedaHzCxE.RemoteActionCompatParcelizer);
        getdiffer.serializer(markOnScreenCardsAsReadlambda1.class, ProcessResult.write);
        getdiffer.serializer(StampedPathEffectStyle.class, PointerInputFilter.serializer);
        getdiffer.serializer(getCyan0d7_KjU.class, PointerInputModifier.RemoteActionCompatParcelizer);
        getdiffer.serializer(getLightGray0d7_KjUannotations.class, isCtrlPressed5xRPYO0.RemoteActionCompatParcelizer);
        getdiffer.serializer(coil3.util.LifecyclesKt.class, invokeOverPasseshUlJWOEdefault.IconCompatParcelizer);
        getdiffer.serializer(getPlaceholderCanvas.class, moveBy.serializer);
        getdiffer.serializer(getTransparent0d7_KjUannotations.class, invokeOverPasseshUlJWOE.IconCompatParcelizer);
        getdiffer.serializer(getModulateAlphaNrFUSI.class, onCancel.read);
        getdiffer.serializer(PointerInteropFilterDispatchToViewState.class, isForwardPressedaHzCxE.IconCompatParcelizer);
        getdiffer.serializer(fastForEachIndexedWithFilter.class, isPrimaryPressedaHzCxE.serializer);
        getdiffer.serializer(r8lambdaN89jNSW0cXSKUcRoByrTjwCSWzE.class, positionChangeInternaldefault.read);
        getdiffer.serializer(BaseRxViewModelKt.class, isAltGraphPressed5xRPYO0.RemoteActionCompatParcelizer);
        getdiffer.serializer(setNetworkUnavailableJob.class, isPressedbNIWhpI.read);
        getdiffer.serializer(moveTodefault.class, getUnknown7fucELk.RemoteActionCompatParcelizer);
        getdiffer.serializer(onVirtualViewTranslationResponseslambda0.class, getMove7fucELk.IconCompatParcelizer);
        getdiffer.serializer(FontMuC2MFsdefault.class, getRelease7fucELk.write);
        getdiffer.serializer(emitcomroadrunnerdeliveryonthewayobserverBuildingHighlightObserverImplonCreate11invokeSuspendlambda0inlinedmap12.class, getPanMove7fucELk.RemoteActionCompatParcelizer);
        getdiffer.serializer(zzpw.class, getPanStart7fucELk.serializer);
        getdiffer.serializer(restoreFocusedChild.class, getCrosshair.IconCompatParcelizer);
        getdiffer.serializer(r8lambdaNGtmLVJzMfxJG0dVSGRl8fYF5wE.class, PointerIcon.write);
        getdiffer.serializer(removeStaleIds.class, accesspackShorts.serializer);
        getdiffer.serializer(drawInto.class, invokeOverAllPassesH0pRuoYdefault.IconCompatParcelizer);
        getdiffer.serializer(getIntersectb3I0S0c.class, invokeOverPasshUlJWOE.read);
        getdiffer.serializer(androidx.navigation.fragment.FragmentKt.class, downdefault.serializer);
        getdiffer.serializer(ForEachGestureKt.class, positionChange.RemoteActionCompatParcelizer);
        getdiffer.serializer(getSuspendingTransactionContext.class, accessgetScaleEndcp.IconCompatParcelizer);
        getdiffer.serializer(getEventType.class, accessgetScaleStartcp.IconCompatParcelizer);
        getdiffer.serializer(resolvePointerPrecision.class, accessgetPanMovecp.RemoteActionCompatParcelizer);
        getdiffer.serializer(close.class, copyEzrO64.IconCompatParcelizer);
        getdiffer.serializer(component10.class, copylGhnTh8.IconCompatParcelizer);
        getdiffer.serializer(populateFocusOrder.class, copyOHpmEuE.write);
        getdiffer.serializer(runInTransaction.class, hasPositionChanged.RemoteActionCompatParcelizer);
        getdiffer.serializer(ApiTypeKt.class, cleanUpHits.write);
        getdiffer.serializer(setFillTypeoQ8Xj4U.class, getHistorical.serializer);
        getdiffer.serializer(io.sentry.util.RatingCompat.class, getTypeT8wyACA.IconCompatParcelizer);
        getdiffer.serializer(InstantJvmKt.class, getDownChangeui.serializer);
        getdiffer.serializer(dispatchKeyEventYhN2O0w.class, copywbzehF4.write);
        getdiffer.serializer(zzgh.class, NodeParent.serializer);
        getdiffer.serializer(androidx.camera.camera2.internal.CameraIdUtil.class, getPointerIds.IconCompatParcelizer);
        getdiffer.serializer(FeatureInfoJsonAdapter.class, PointerInputResetException.read);
        getdiffer.serializer(DegreesKt.class, getPointerInputFilter.serializer);
        getdiffer.serializer(io.sentry.rrweb.read.class, getInterceptOutOfBoundsChildEventsannotations.IconCompatParcelizer);
        getdiffer.serializer(hsvJlNiLsgdefault.class, invokeOverAllPassesH0pRuoY.RemoteActionCompatParcelizer);
        getdiffer.serializer(createButtonClickListenerslambda0100.class, setPositionChangeui.IconCompatParcelizer);
        getdiffer.serializer(checkForSystemLogLevelPropertylambda0.class, getPointers.write);
        getdiffer.serializer(accessgetDifferencecp.class, produce.read);
        getdiffer.serializer(ThrowableExtensionsKt.class, setMotionEvent.serializer);
        getdiffer.serializer(ContentCardsUpdatedEvent.class, isCapsLockOn5xRPYO0.write);
        getdiffer.serializer(endStream.class, PointerButtons.IconCompatParcelizer);
        getdiffer.serializer(getId.class, getButtonsry648PA.write);
        getdiffer.serializer(disableThirdPartySharingForCoppaEnabledI.class, indexOfLastPressedaHzCxE.write);
        getdiffer.serializer(io.sentry.vendor.IconCompatParcelizer.class, isAltPressed5xRPYO0.read);
        getdiffer.serializer(df.class, getScrollDeltaF1C5BW0.read);
        getdiffer.serializer(getTangenttuRUvjQ.class, getPositionChangeui.write);
        getdiffer.serializer(resetAfterInAppMessageClose.class, setDownChangeui.RemoteActionCompatParcelizer);
        getdiffer.serializer(androidx.camera.core.impl.UseCaseAdditionSimulator.class, getModifierNode.serializer);
        getdiffer.serializer(androidx.camera.core.impl.DeferrableSurfaces.class, dispatchMainEventPass.serializer);
        getdiffer.serializer(FocusOrderModifierKt.class, copy0GkPj7cdefault.write);
        getdiffer.serializer(setDimens.class, copyOHpmEuEdefault.IconCompatParcelizer);
        getdiffer.serializer(io.sentry.android.replay.util.MediaDescriptionCompat.class, copyTn9QgHEdefault.write);
        getdiffer.serializer(setInflatedId.class, MotionEventHelper.RemoteActionCompatParcelizer);
        getdiffer.serializer(r8lambda4MdKbfiHpQQwW57A4NP6ZCybbFA.class, MotionEventClassification.IconCompatParcelizer);
        getdiffer.serializer(getFocusedRect.class, getPointerIconHand.serializer);
        getdiffer.serializer(ContentCardsFragmentonRefresh1.class, copyJKmWfYYdefault.serializer);
        getdiffer.serializer(setServerTargetandroid_sdk_base_release.class, copyEzrO64default.serializer);
        getdiffer.serializer(getMotionEventToComposePointerIdMapui.class, dispatchIfNeeded.read);
        getdiffer.serializer(androidx.biometric.CryptoObjectUtils.class, Node.read);
        getdiffer.serializer(TouchAwareSwipeDismissTouchListenerITouchListener.class, getConsumedannotations.write);
        getdiffer.serializer(isCircle.class, get_consumedannotations.serializer);
        getdiffer.serializer(BrazeSdkAuthenticationErrorEvent.class, copylGhnTh8default.serializer);
        getdiffer.serializer(nearestAncestorIncludingSelf64DMado.class, copywbzehF4default.read);
        getdiffer.serializer(zzgb.class, toRawOffsetdBAh8RU.write);
        getdiffer.serializer(androidx.biometric.AuthenticatorUtils.class, buildCache.read);
        getdiffer.serializer(PointerInteropFilter_androidKtmotionEventSpy1.class, isAttachedui.write);
        getdiffer.serializer(pointerInteropFilterdefault.class, PointerInputModifierDefaultImpls.write);
        getdiffer.serializer(setPublicNotificationExtras.class, isScrollLockOn5xRPYO0.write);
        getdiffer.serializer(setRequestDisallowInterceptTouchEvent.class, isSymPressed5xRPYO0.read);
        getdiffer.serializer(Actual_androidKt.class, isMetaPressed5xRPYO0.RemoteActionCompatParcelizer);
        getdiffer.serializer(r8lambdamYEtK3wDOqF6c3HLWu9wJc3oPw.class, isSecondaryPressedaHzCxE.read);
        getdiffer.serializer(toLongimpl.class, getOriginalEventPositionF1C5BW0.write);
        getdiffer.serializer(asComposePath.class, getActiveHover.write);
        getdiffer.serializer(AwaitFirstLayoutModifier.class, changedToDown.IconCompatParcelizer);
        getdiffer.serializer(r8lambda9zISiqWdkc3dd5mJTZ1F1xGFCGs.class, changedToUp.serializer);
        getdiffer.serializer(androidx.recyclerview.widget.ScrollbarHelper.class, accessgetInterceptOutOfBoundsChildEventsjd.RemoteActionCompatParcelizer);
        getdiffer.serializer(quadraticBezierTo.class, component3F1C5BW0.IconCompatParcelizer);
        getdiffer.serializer(getTolerance.class, getPanGestureOffsetF1C5BW0.write);
        getdiffer.serializer(getOutputTransform.class, getType7fucELk.write);
        getdiffer.serializer(copyWithMergingEnabledui.class, changedToUpIgnoreConsumed.IconCompatParcelizer);
        getdiffer.serializer(PointerInteropFilter_androidKtpointerInteropFilter2.class, PointerInputScope.write);
        getdiffer.serializer(setOnLoggedCallback.class, setStylusHoverIcon.RemoteActionCompatParcelizer);
        getdiffer.serializer(zzsd.class, PointerInputChange.RemoteActionCompatParcelizer);
        getdiffer.serializer(io.sentry.util.serializer.class, getPointerIconDefault.read);
        getdiffer.serializer(BrazeInAppMessageManagerunregisterInAppMessageManager3.class, PointerIconService.read);
        getdiffer.serializer(r8lambdaPetcymL03j3fMaX9gYfmzmaOBPg.class, getPointerIconText.IconCompatParcelizer);
        getdiffer.serializer(getLocalHtmlUrlFromRemoteUrllambda5.class, PointerId.RemoteActionCompatParcelizer);
        getdiffer.serializer(accessgetEntercp.class, getPointerIconCrosshair.IconCompatParcelizer);
        getdiffer.serializer(getLayoutDirection.class, stylusHoverIcondefault.write);
        getdiffer.serializer(PointerInteropFilterpointerInputFilter1stopDispatching1.class, getStylusHoverIcon.RemoteActionCompatParcelizer);
        getdiffer.serializer(FocusModifierKt.class, PointerIcon_androidKt.write);
        getdiffer.serializer(getActiveFocusTargetNode.class, copyTn9QgHE.serializer);
        getdiffer.serializer(getBottom.class, getPress7fucELk.read);
        getdiffer.serializer(DragAndDropNodeKtDragAndDropTargetModifierNode1.class, copy0GkPj7c.serializer);
        getdiffer.serializer(Cookie$Companion.class, copyJKmWfYY.serializer);
        getdiffer.serializer(migrateSealedSessionsMapToJsonlambda3.class, getScaleChange7fucELk.read);
        getdiffer.serializer(getShouldAddStatusBarPaddingToInAppMessages.class, getScroll7fucELk.RemoteActionCompatParcelizer);
        getdiffer.serializer(onCreateWindowlambda2.class, setAttachedui.IconCompatParcelizer);
        getdiffer.serializer(getConicEvaluation.class, processBIzXfogdefault.serializer);
        getdiffer.serializer(getUnionb3I0S0c.class, C0152awaitPointerEventScope.IconCompatParcelizer);
        getdiffer.serializer(RoundRectgG7oq9Y.class, PointerInputEventProcessorKt.read);
        getdiffer.serializer(NotificationDialogKt.class, PointerInputEventProcessor.serializer);
        getdiffer.serializer(ASN1Util.class, PointerInputScopeDefaultImpls.read);
        getdiffer.serializer(zzgz.class, anyChangeConsumed.read);
        getdiffer.serializer(scroll.class, changedToDownIgnoreConsumed.read);
        getdiffer.serializer(androidx.window.core.ValidSpecification.class, accesssetInterceptOutOfBoundsChildEventsjd.RemoteActionCompatParcelizer);
        getdiffer.serializer(getPositionInRoot.class, getScaleEnd7fucELk.read);
    }

    @Override // o.accessgetBrightnessDowncp
    public Object apply(Object obj) {
        return this.serializer != 2 ? (byte[]) obj : (byte[]) obj;
    }
}
