package o;

import com.huawei.riemann.location.common.utils.Constant;

/* JADX INFO: loaded from: classes.dex */
public abstract class trimToSafeLength {
    public static final long ComponentActivity;
    public static final long IconCompatParcelizer;
    public static final long MediaBrowserCompatMediaItem;
    public static final long MediaDescriptionCompat;
    public static final long MediaMetadataCompat;
    public static final long MediaSessionCompatQueueItem;
    public static final long MediaSessionCompatResultReceiverWrapper;
    public static final long MediaSessionCompatToken;
    public static final long ParcelableVolumeInfo;
    public static final long PlaybackStateCompat;
    public static final long PlaybackStateCompatCustomAction;
    public static final long RatingCompat;
    public static final long RemoteActionCompatParcelizer;
    public static final long ResultReceiver;
    public static final long _init_lambda1;
    public static final long _init_lambda2;
    public static final long _init_lambda3;
    public static final long _init_lambda4;
    public static final long accessensureViewModelStore;
    public static final long addObserverForBackInvoker;
    public static final long addObserverForBackInvokerlambda0;
    public static final long r8lambda54BeH8ZsBru0CXI2CCSP2syNys;
    public static final long r8lambda7IJBVrN0sHyidCAZufWEJFc7yY;
    public static final long r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus;
    public static final long r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss;
    public static final long r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg;
    public static final long r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8;
    public static final long r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4;
    public static final long r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM;
    public static final long r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs;
    public static final long r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28;
    public static final long r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw;
    public static final long r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ;
    public static final long r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0;
    public static final long read;
    public static final long serializer;
    public static final long write;

    static {
        androidx.compose.ui.graphics.ColorKt.Color$default(0, 0, 0, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(0, 0, 0, 0, 8, null);
        RemoteActionCompatParcelizer = androidx.compose.ui.graphics.ColorKt.Color$default(65, 14, 11, 0, 8, null);
        IconCompatParcelizer = androidx.compose.ui.graphics.ColorKt.Color$default(255, 255, 255, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(96, 20, 16, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(140, 29, 24, 0, 8, null);
        serializer = androidx.compose.ui.graphics.ColorKt.Color$default(179, 38, 30, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(220, 54, 46, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(228, 105, 98, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(236, 146, 142, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(242, 184, 181, 0, 8, null);
        write = androidx.compose.ui.graphics.ColorKt.Color$default(249, Constant.ERROR_WSS_LOW_FREQ, 220, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(252, 238, 238, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(255, 251, 249, 0, 8, null);
        read = androidx.compose.ui.graphics.ColorKt.Color$default(0, 0, 0, 0, 8, null);
        MediaMetadataCompat = androidx.compose.ui.graphics.ColorKt.Color$default(29, 27, 32, 0, 8, null);
        RatingCompat = androidx.compose.ui.graphics.ColorKt.Color$default(255, 255, 255, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(33, 31, 38, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(43, 41, 48, 0, 8, null);
        MediaSessionCompatQueueItem = androidx.compose.ui.graphics.ColorKt.Color$default(50, 47, 53, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(54, 52, 59, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(59, 56, 62, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(72, 70, 76, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(15, 13, 19, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(96, 93, 100, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(121, 118, 125, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(20, 18, 24, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(147, 143, 150, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(174, 169, 177, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(202, 197, Constant.ERROR_ACC_GRAVITY_INVALID, 0, 8, null);
        MediaBrowserCompatMediaItem = androidx.compose.ui.graphics.ColorKt.Color$default(Constant.ERROR_WSS_LOW_FREQ, Constant.ERROR_GYRO_JUMP, 225, 0, 8, null);
        MediaDescriptionCompat = androidx.compose.ui.graphics.ColorKt.Color$default(230, Constant.ERROR_WSS_INVALID, 233, 0, 8, null);
        ParcelableVolumeInfo = androidx.compose.ui.graphics.ColorKt.Color$default(236, 230, 240, 0, 8, null);
        MediaSessionCompatResultReceiverWrapper = androidx.compose.ui.graphics.ColorKt.Color$default(243, 237, 247, 0, 8, null);
        PlaybackStateCompat = androidx.compose.ui.graphics.ColorKt.Color$default(245, 239, 247, 0, 8, null);
        MediaSessionCompatToken = androidx.compose.ui.graphics.ColorKt.Color$default(247, 242, 250, 0, 8, null);
        PlaybackStateCompatCustomAction = androidx.compose.ui.graphics.ColorKt.Color$default(Constant.ERROR_ROAD_AREA_INVALID, 247, 255, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(255, 251, 255, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(0, 0, 0, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(29, 26, 34, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(255, 255, 255, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(50, 47, 55, 0, 8, null);
        r8lambda54BeH8ZsBru0CXI2CCSP2syNys = androidx.compose.ui.graphics.ColorKt.Color$default(73, 69, 79, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(96, 93, 102, 0, 8, null);
        ResultReceiver = androidx.compose.ui.graphics.ColorKt.Color$default(121, 116, 126, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(147, 143, 153, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(174, 169, 180, 0, 8, null);
        ComponentActivity = androidx.compose.ui.graphics.ColorKt.Color$default(202, 196, 208, 0, 8, null);
        r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus = androidx.compose.ui.graphics.ColorKt.Color$default(231, Constant.ERROR_WSS_INVALID, 236, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(245, 238, 250, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(255, 251, Constant.ERROR_ROAD_AREA_INVALID, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(0, 0, 0, 0, 8, null);
        r8lambda7IJBVrN0sHyidCAZufWEJFc7yY = androidx.compose.ui.graphics.ColorKt.Color$default(33, 0, 93, 0, 8, null);
        r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM = androidx.compose.ui.graphics.ColorKt.Color$default(255, 255, 255, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(56, 30, 114, 0, 8, null);
        r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4 = androidx.compose.ui.graphics.ColorKt.Color$default(79, 55, 139, 0, 8, null);
        r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8 = androidx.compose.ui.graphics.ColorKt.Color$default(103, 80, 164, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(127, 103, 190, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(154, 130, 219, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(182, 157, 248, 0, 8, null);
        r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg = androidx.compose.ui.graphics.ColorKt.Color$default(208, 188, 255, 0, 8, null);
        r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss = androidx.compose.ui.graphics.ColorKt.Color$default(Constant.ERROR_LOCATION_INVALID, Constant.ERROR_WSS_NO_DATA, 255, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(246, 237, 255, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(255, 251, Constant.ERROR_ROAD_AREA_INVALID, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(0, 0, 0, 0, 8, null);
        r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ = androidx.compose.ui.graphics.ColorKt.Color$default(29, 25, 43, 0, 8, null);
        r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0 = androidx.compose.ui.graphics.ColorKt.Color$default(255, 255, 255, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(51, 45, 65, 0, 8, null);
        r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28 = androidx.compose.ui.graphics.ColorKt.Color$default(74, 68, 88, 0, 8, null);
        r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs = androidx.compose.ui.graphics.ColorKt.Color$default(98, 91, 113, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(122, 114, 137, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(149, 141, 165, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(176, 167, 192, 0, 8, null);
        r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw = androidx.compose.ui.graphics.ColorKt.Color$default(Constant.ERROR_ACC_INVALID, 194, 220, 0, 8, null);
        _init_lambda1 = androidx.compose.ui.graphics.ColorKt.Color$default(232, Constant.ERROR_WSS_LOW_FREQ, 248, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(246, 237, 255, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(255, 251, Constant.ERROR_ROAD_AREA_INVALID, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(0, 0, 0, 0, 8, null);
        _init_lambda2 = androidx.compose.ui.graphics.ColorKt.Color$default(49, 17, 29, 0, 8, null);
        _init_lambda3 = androidx.compose.ui.graphics.ColorKt.Color$default(255, 255, 255, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(73, 37, 50, 0, 8, null);
        _init_lambda4 = androidx.compose.ui.graphics.ColorKt.Color$default(99, 59, 72, 0, 8, null);
        accessensureViewModelStore = androidx.compose.ui.graphics.ColorKt.Color$default(125, 82, 96, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(152, 105, 119, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(181, 131, 146, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(210, 157, 172, 0, 8, null);
        addObserverForBackInvokerlambda0 = androidx.compose.ui.graphics.ColorKt.Color$default(239, 184, 200, 0, 8, null);
        addObserverForBackInvoker = androidx.compose.ui.graphics.ColorKt.Color$default(255, Constant.ERROR_GYRO_JUMP, 228, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(255, 236, 241, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(255, 251, 250, 0, 8, null);
        androidx.compose.ui.graphics.ColorKt.Color$default(255, 255, 255, 0, 8, null);
    }
}
