package com.incognia.internal;

import androidx.sqlite.SQLite;
import java.util.ArrayList;

/* JADX INFO: loaded from: classes2.dex */
public final class wg {
    public final NvL BGx;
    public static final String mbG = (String) W4i.NNI.MediaSessionCompatResultReceiverWrapper();
    public static final String HQ = (String) W4i.jN.MediaSessionCompatResultReceiverWrapper();
    public static final String N = (String) W4i.Q.MediaSessionCompatResultReceiverWrapper();
    public static final String x = (String) W4i.KuL.MediaSessionCompatResultReceiverWrapper();
    public static final String hIl = (String) W4i.sl.MediaSessionCompatResultReceiverWrapper();
    public static final String hs = (String) W4i.FkZ.MediaSessionCompatResultReceiverWrapper();
    public static final String VV3 = (String) W4i.rB.MediaSessionCompatResultReceiverWrapper();
    public static final String A1 = (String) W4i.u7.MediaSessionCompatResultReceiverWrapper();
    public static final String q = (String) W4i.Of.MediaSessionCompatResultReceiverWrapper();
    public static final String fZl = (String) W4i.k2.MediaSessionCompatResultReceiverWrapper();
    public static final String S = (String) W4i.I5.MediaSessionCompatResultReceiverWrapper();
    public static final String iaH = (String) W4i.PS.MediaSessionCompatResultReceiverWrapper();
    public static final ArrayList e = SQLite.write((String) W4i.aV.MediaSessionCompatResultReceiverWrapper(), (String) W4i.GN.MediaSessionCompatResultReceiverWrapper(), (String) W4i.NWu.MediaSessionCompatResultReceiverWrapper(), (String) W4i.WUe.MediaSessionCompatResultReceiverWrapper(), (String) W4i.FX.MediaSessionCompatResultReceiverWrapper(), (String) W4i.h5.MediaSessionCompatResultReceiverWrapper(), (String) W4i.tf.MediaSessionCompatResultReceiverWrapper(), (String) W4i.DQu.MediaSessionCompatResultReceiverWrapper(), (String) W4i.dg4.MediaSessionCompatResultReceiverWrapper(), (String) W4i.mbn.MediaSessionCompatResultReceiverWrapper(), (String) W4i.k7I.MediaSessionCompatResultReceiverWrapper(), (String) W4i.ybR.MediaSessionCompatResultReceiverWrapper(), (String) W4i.Fn.MediaSessionCompatResultReceiverWrapper(), (String) W4i.aa.MediaSessionCompatResultReceiverWrapper(), (String) W4i.CcF.MediaSessionCompatResultReceiverWrapper(), (String) W4i.Qgy.MediaSessionCompatResultReceiverWrapper(), (String) W4i.Oq.MediaSessionCompatResultReceiverWrapper(), (String) W4i.qO4.MediaSessionCompatResultReceiverWrapper(), (String) W4i.K3.MediaSessionCompatResultReceiverWrapper(), (String) W4i.RsI.MediaSessionCompatResultReceiverWrapper(), (String) W4i.n1O.MediaSessionCompatResultReceiverWrapper(), (String) W4i.mn4.MediaSessionCompatResultReceiverWrapper(), (String) W4i.r3.MediaSessionCompatResultReceiverWrapper(), (String) W4i.cYD.MediaSessionCompatResultReceiverWrapper(), (String) W4i.yI.MediaSessionCompatResultReceiverWrapper(), (String) W4i.pBX.MediaSessionCompatResultReceiverWrapper(), (String) W4i.FQ2.MediaSessionCompatResultReceiverWrapper(), (String) W4i.eTL.MediaSessionCompatResultReceiverWrapper(), (String) W4i.PU.MediaSessionCompatResultReceiverWrapper(), (String) W4i.Bt.MediaSessionCompatResultReceiverWrapper());
    public static final ArrayList VLD = SQLite.write((String) W4i.nY.MediaSessionCompatResultReceiverWrapper(), (String) W4i.ED.MediaSessionCompatResultReceiverWrapper(), (String) W4i.CT.MediaSessionCompatResultReceiverWrapper(), (String) W4i.GD.MediaSessionCompatResultReceiverWrapper(), (String) W4i.gFd.MediaSessionCompatResultReceiverWrapper(), (String) W4i.f2y.MediaSessionCompatResultReceiverWrapper(), (String) W4i.mZS.MediaSessionCompatResultReceiverWrapper(), (String) W4i.I2.MediaSessionCompatResultReceiverWrapper(), (String) W4i.YHI.MediaSessionCompatResultReceiverWrapper(), (String) W4i.oqZ.MediaSessionCompatResultReceiverWrapper(), (String) W4i.QZ.MediaSessionCompatResultReceiverWrapper(), (String) W4i.c9.MediaSessionCompatResultReceiverWrapper(), (String) W4i.BSe.MediaSessionCompatResultReceiverWrapper(), (String) W4i.SY.MediaSessionCompatResultReceiverWrapper(), (String) W4i.jB.MediaSessionCompatResultReceiverWrapper(), (String) W4i.DJ.MediaSessionCompatResultReceiverWrapper(), (String) W4i.NG.MediaSessionCompatResultReceiverWrapper(), (String) W4i.SaQ.MediaSessionCompatResultReceiverWrapper(), (String) W4i.xyT.MediaSessionCompatResultReceiverWrapper(), (String) W4i.Up.MediaSessionCompatResultReceiverWrapper(), (String) W4i.ZB5.MediaSessionCompatResultReceiverWrapper(), (String) W4i.yQn.MediaSessionCompatResultReceiverWrapper(), (String) W4i.gP7.MediaSessionCompatResultReceiverWrapper(), (String) W4i.RT.MediaSessionCompatResultReceiverWrapper(), (String) W4i.dcz.MediaSessionCompatResultReceiverWrapper(), (String) W4i.x3.MediaSessionCompatResultReceiverWrapper(), (String) W4i.E2.MediaSessionCompatResultReceiverWrapper(), (String) W4i.i9k.MediaSessionCompatResultReceiverWrapper());
    public static final ArrayList TfN = SQLite.write((String) W4i.jg.MediaSessionCompatResultReceiverWrapper(), (String) W4i.kd.MediaSessionCompatResultReceiverWrapper(), (String) W4i.qj.MediaSessionCompatResultReceiverWrapper(), (String) W4i.If.MediaSessionCompatResultReceiverWrapper(), (String) W4i.xG.MediaSessionCompatResultReceiverWrapper(), (String) W4i.kn.MediaSessionCompatResultReceiverWrapper(), (String) W4i.lEm.MediaSessionCompatResultReceiverWrapper(), (String) W4i.tkO.MediaSessionCompatResultReceiverWrapper(), (String) W4i.qi.MediaSessionCompatResultReceiverWrapper(), (String) W4i.Cf.MediaSessionCompatResultReceiverWrapper(), (String) W4i.lXf.MediaSessionCompatResultReceiverWrapper(), (String) W4i.Zw1.MediaSessionCompatResultReceiverWrapper(), (String) W4i.fc.MediaSessionCompatResultReceiverWrapper(), (String) W4i.qf.MediaSessionCompatResultReceiverWrapper(), (String) W4i.Ao.MediaSessionCompatResultReceiverWrapper(), (String) W4i.Cs9.MediaSessionCompatResultReceiverWrapper(), (String) W4i.vF.MediaSessionCompatResultReceiverWrapper(), (String) W4i.Ug.MediaSessionCompatResultReceiverWrapper(), (String) W4i.ts.MediaSessionCompatResultReceiverWrapper(), (String) W4i.TuE.MediaSessionCompatResultReceiverWrapper());
    public static final ArrayList OV7 = SQLite.write((String) W4i.LjS.MediaSessionCompatResultReceiverWrapper(), (String) W4i.RTh.MediaSessionCompatResultReceiverWrapper(), (String) W4i.kpC.MediaSessionCompatResultReceiverWrapper(), (String) W4i.k68.MediaSessionCompatResultReceiverWrapper(), (String) W4i.Mo.MediaSessionCompatResultReceiverWrapper(), (String) W4i.bS4.MediaSessionCompatResultReceiverWrapper(), (String) W4i.dxj.MediaSessionCompatResultReceiverWrapper(), (String) W4i.Ju1.MediaSessionCompatResultReceiverWrapper(), (String) W4i.wOa.MediaSessionCompatResultReceiverWrapper(), (String) W4i.WIS.MediaSessionCompatResultReceiverWrapper(), (String) W4i.al0.MediaSessionCompatResultReceiverWrapper(), (String) W4i.Jvj.MediaSessionCompatResultReceiverWrapper(), (String) W4i.cW.MediaSessionCompatResultReceiverWrapper(), (String) W4i.hkS.MediaSessionCompatResultReceiverWrapper(), (String) W4i.q0.MediaSessionCompatResultReceiverWrapper(), (String) W4i.pq6.MediaSessionCompatResultReceiverWrapper(), (String) W4i.v1a.MediaSessionCompatResultReceiverWrapper(), (String) W4i.ZZt.MediaSessionCompatResultReceiverWrapper(), (String) W4i.Gf.MediaSessionCompatResultReceiverWrapper(), (String) W4i.z1e.MediaSessionCompatResultReceiverWrapper(), (String) W4i.CL.MediaSessionCompatResultReceiverWrapper(), (String) W4i.nj.MediaSessionCompatResultReceiverWrapper());
    public static final ArrayList JR = SQLite.write((String) W4i.CXN.MediaSessionCompatResultReceiverWrapper());
    public static final ArrayList j = SQLite.write((String) W4i.ktY.MediaSessionCompatResultReceiverWrapper(), (String) W4i.R2h.MediaSessionCompatResultReceiverWrapper());
    public static final String n = (String) W4i.Q3.MediaSessionCompatResultReceiverWrapper();
    public static final String vM = (String) W4i.ymi.MediaSessionCompatResultReceiverWrapper();
    public static final String l5 = (String) W4i.ua.MediaSessionCompatResultReceiverWrapper();
    public static final String ss = (String) W4i.la.MediaSessionCompatResultReceiverWrapper();
    public static final String B = (String) W4i.qSS.MediaSessionCompatResultReceiverWrapper();
    public static final String YO = (String) W4i.HJG.MediaSessionCompatResultReceiverWrapper();
    public static final String N6D = (String) W4i.Px.MediaSessionCompatResultReceiverWrapper();
    public static final String v = (String) W4i.j6x.MediaSessionCompatResultReceiverWrapper();

    public wg(NvL nvL) {
        this.BGx = nvL;
    }
}
