package com.mapbox.navigation.core.routerefresh;

import com.mapbox.navigation.base.route.NavigationRoute;
import o.getCieXyz;
import o.getOnFillData;
import o.hideCurrentlyDisplayingInAppMessage;
import o.removeNodeAtDepth;

/* JADX INFO: loaded from: classes2.dex */
public abstract class RouteRefreshValidator {
    public static getOnFillData validateRoute(NavigationRoute navigationRoute) {
        navigationRoute.getClass();
        String str = navigationRoute.origin;
        if (((Boolean) removeNodeAtDepth.RemoteActionCompatParcelizer(getCieXyz.write(), 1803334089, -1803334089, getCieXyz.write(), getCieXyz.write(), new Object[]{str, "CUSTOM_EXTERNAL"}, getCieXyz.write())).booleanValue()) {
            return new RouteRefreshValidator$RouteValidationResult$Invalid("Custom routes can't be refreshed");
        }
        if (((Boolean) removeNodeAtDepth.RemoteActionCompatParcelizer(getCieXyz.write(), 1803334089, -1803334089, getCieXyz.write(), getCieXyz.write(), new Object[]{str, "OFFLINE"}, getCieXyz.write())).booleanValue()) {
            return new RouteRefreshValidator$RouteValidationResult$Invalid("Offline routes can't be refreshed");
        }
        if (!((Boolean) removeNodeAtDepth.RemoteActionCompatParcelizer(getCieXyz.write(), 1803334089, -1803334089, getCieXyz.write(), getCieXyz.write(), new Object[]{navigationRoute.routeOptions.enableRefresh(), Boolean.TRUE}, getCieXyz.write())).booleanValue()) {
            return new RouteRefreshValidator$RouteValidationResult$Invalid("RouteOptions#enableRefresh is false");
        }
        String strRequestUuid = navigationRoute.directionsRoute.requestUuid();
        if (strRequestUuid == null || !(!hideCurrentlyDisplayingInAppMessage.serializer((CharSequence) strRequestUuid))) {
            return new RouteRefreshValidator$RouteValidationResult$Invalid("DirectionsRoute#requestUuid is blank. This can be caused by a route being generated by an Onboard router (in offline mode). Make sure to switch to an Offboard route when possible, only Offboard routes support the refresh feature.");
        }
        return ((Boolean) removeNodeAtDepth.RemoteActionCompatParcelizer(getCieXyz.write(), 1803334089, -1803334089, getCieXyz.write(), getCieXyz.write(), new Object[]{navigationRoute.responseOriginAPI, "MAP_MATCHING_API"}, getCieXyz.write())).booleanValue() ? new RouteRefreshValidator$RouteValidationResult$Invalid("Map matched routes can't be refreshed") : RouteRefreshValidator$RouteValidationResult$Valid.INSTANCE;
    }
}
