package com.roadrunner.settings;

import androidx.compose.ui.text.AnnotatedString;
import androidx.lifecycle.ViewModel;
import androidx.sqlite.SQLite;
import com.logistics.rider.glovo.R;
import com.roadrunner.login.logging.OtpLogger;
import com.roadrunner.settings.data.PreferencesRepository$observeStringPreference$1;
import com.sentiance.core.model.events.C$b;
import com.sentiance.core.model.events.N$b;
import io.grpc.internal.SharedResourcePool;
import java.util.LinkedHashSet;
import kotlinx.coroutines.BuildersKt;
import kotlinx.coroutines.flow.Flow;
import kotlinx.coroutines.flow.FlowKt;
import kotlinx.coroutines.flow.MutableStateFlow;
import kotlinx.coroutines.flow.SharingStarted;
import kotlinx.coroutines.flow.StateFlow;
import kotlinx.coroutines.flow.StateFlowKt;
import o.SemanticsPropertyKey;
import o.ShortNewsContentCardView;
import o.accessgetOldDependencyp;
import o.asComposePaint;
import o.disable;
import o.getInstallBeginTimeInSeconds;
import o.getQueryContext;
import o.instance_delegatelambda0;
import o.isSensitiveData;
import o.mergeJsonObjects;
import o.onContentCardDismissed;
import o.r8lambda4OvXzM2G3U08xdmIsvfVqgmSBTg;
import o.r8lambda5_PQMw30AYpvgDY5yFJI1wIvaeg;
import o.r8lambdaCwU8OzatE7jOuIaQjprNUSKXVA;
import o.r8lambdaFEnLU5alJx2ClfZRg4tE2QEPKfs;
import o.r8lambdaGjDZxd7jQZoBcNzNhpVRngZ6jXY;
import o.r8lambdaH04qYyeOzRXd4CFrSTNkPB99_Ds;
import o.r8lambdaKg12b_kAV6xLHkeltAkZS9jV9c;
import o.r8lambdaNyJ3IxzJGs1Drw4t7O1OG6TKao;
import o.r8lambdaQOx6sXjdIhzywvIPc1cbblE4PLg;
import o.r8lambdaRdO_uN7XDjHQOVIqToN9xCXIqPA;
import o.r8lambdad3KDFaViDQCaterPKviUURECBdQ;
import o.r8lambdadaazyEDDzwnij76sC1FsKvBpnqQ;
import o.r8lambdaeEn0GUG5cGviZ6WG1OS4uJPKt0;
import o.requestSingleLocationUpdatelambda1;
import o.setTransactionSuccessful;
import o.subscribeToBannersDismissedEventandroid_sdk_base_release;
import o.textEntryKey;
import o.toBitmapConfig1JJdX4A;
import o.transferSessionPackageI;
import okhttp3.FormBody;
import retrofit2.OkHttpCall$1;

/* JADX INFO: loaded from: classes3.dex */
public final class SettingsViewModel extends ViewModel {
    public final subscribeToBannersDismissedEventandroid_sdk_base_release ComponentActivity;
    public final accessgetOldDependencyp IconCompatParcelizer;
    public final transferSessionPackageI MediaBrowserCompatMediaItem;
    public final MutableStateFlow MediaDescriptionCompat;
    public final r8lambdadaazyEDDzwnij76sC1FsKvBpnqQ MediaMetadataCompat;
    public final textEntryKey MediaSessionCompatQueueItem;
    public final r8lambdaH04qYyeOzRXd4CFrSTNkPB99_Ds MediaSessionCompatResultReceiverWrapper;
    public final MutableStateFlow MediaSessionCompatToken;
    public final SharedResourcePool ParcelableVolumeInfo;
    public final FormBody.Builder PlaybackStateCompat;
    public final r8lambdad3KDFaViDQCaterPKviUURECBdQ PlaybackStateCompatCustomAction;
    public final C$b RatingCompat;
    public final r8lambda5_PQMw30AYpvgDY5yFJI1wIvaeg RemoteActionCompatParcelizer;
    public final N$b ResultReceiver;
    public final isSensitiveData r8lambda54BeH8ZsBru0CXI2CCSP2syNys;
    public final setTransactionSuccessful r8lambda7IJBVrN0sHyidCAZufWEJFc7yY;
    public final getInstallBeginTimeInSeconds r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus;
    public final SemanticsPropertyKey r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg;
    public final r8lambdaRdO_uN7XDjHQOVIqToN9xCXIqPA r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8;
    public final r8lambdaGjDZxd7jQZoBcNzNhpVRngZ6jXY r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4;
    public final StateFlow r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM;
    public final disable read;
    public final Flow serializer;
    public final MutableStateFlow write;

    public SettingsViewModel(setTransactionSuccessful settransactionsuccessful, subscribeToBannersDismissedEventandroid_sdk_base_release subscribetobannersdismissedeventandroid_sdk_base_release, r8lambdaH04qYyeOzRXd4CFrSTNkPB99_Ds r8lambdah04qyyeozrxd4cfrstnkpb99_ds, r8lambda5_PQMw30AYpvgDY5yFJI1wIvaeg r8lambda5_pqmw30aypvgdy5yfji1wivaeg, N$b n$b, SemanticsPropertyKey semanticsPropertyKey, r8lambdadaazyEDDzwnij76sC1FsKvBpnqQ r8lambdadaazyeddzwnij76sc1fskvbpnqq, SharedResourcePool sharedResourcePool, r8lambdad3KDFaViDQCaterPKviUURECBdQ r8lambdad3kdfavidqcaterpkviuurecbdq, C$b c$b, accessgetOldDependencyp accessgetolddependencyp, disable disableVar, getInstallBeginTimeInSeconds getinstallbegintimeinseconds, isSensitiveData issensitivedata, FormBody.Builder builder, r8lambdaGjDZxd7jQZoBcNzNhpVRngZ6jXY r8lambdagjdzxd7jqzobcnznhpvrngz6jxy, textEntryKey textentrykey, transferSessionPackageI transfersessionpackagei, r8lambdaeEn0GUG5cGviZ6WG1OS4uJPKt0 r8lambdaeen0gug5cgviz6wg1os4ujpkt0, r8lambdaQOx6sXjdIhzywvIPc1cbblE4PLg r8lambdaqox6sxjdihzywvipc1cbble4plg) {
        settransactionsuccessful.getClass();
        subscribetobannersdismissedeventandroid_sdk_base_release.getClass();
        r8lambdah04qyyeozrxd4cfrstnkpb99_ds.getClass();
        r8lambda5_pqmw30aypvgdy5yfji1wivaeg.getClass();
        n$b.getClass();
        semanticsPropertyKey.getClass();
        r8lambdadaazyeddzwnij76sc1fskvbpnqq.getClass();
        sharedResourcePool.getClass();
        r8lambdad3kdfavidqcaterpkviuurecbdq.getClass();
        c$b.getClass();
        accessgetolddependencyp.getClass();
        disableVar.getClass();
        getinstallbegintimeinseconds.getClass();
        issensitivedata.getClass();
        builder.getClass();
        r8lambdagjdzxd7jqzobcnznhpvrngz6jxy.getClass();
        textentrykey.getClass();
        transfersessionpackagei.getClass();
        r8lambdaeen0gug5cgviz6wg1os4ujpkt0.getClass();
        r8lambdaqox6sxjdihzywvipc1cbble4plg.getClass();
        this.r8lambda7IJBVrN0sHyidCAZufWEJFc7yY = settransactionsuccessful;
        this.ComponentActivity = subscribetobannersdismissedeventandroid_sdk_base_release;
        this.MediaSessionCompatResultReceiverWrapper = r8lambdah04qyyeozrxd4cfrstnkpb99_ds;
        this.RemoteActionCompatParcelizer = r8lambda5_pqmw30aypvgdy5yfji1wivaeg;
        this.ResultReceiver = n$b;
        this.r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg = semanticsPropertyKey;
        this.MediaMetadataCompat = r8lambdadaazyeddzwnij76sc1fskvbpnqq;
        this.ParcelableVolumeInfo = sharedResourcePool;
        this.PlaybackStateCompatCustomAction = r8lambdad3kdfavidqcaterpkviuurecbdq;
        this.RatingCompat = c$b;
        this.IconCompatParcelizer = accessgetolddependencyp;
        this.read = disableVar;
        this.r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus = getinstallbegintimeinseconds;
        this.r8lambda54BeH8ZsBru0CXI2CCSP2syNys = issensitivedata;
        this.PlaybackStateCompat = builder;
        this.r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4 = r8lambdagjdzxd7jqzobcnznhpvrngz6jxy;
        this.MediaSessionCompatQueueItem = textentrykey;
        this.MediaBrowserCompatMediaItem = transfersessionpackagei;
        OkHttpCall$1 okHttpCall$1 = r8lambdaqox6sxjdihzywvipc1cbble4plg.IconCompatParcelizer;
        this.r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8 = new r8lambdaRdO_uN7XDjHQOVIqToN9xCXIqPA((setTransactionSuccessful) ((mergeJsonObjects) okHttpCall$1.write).write(), (OtpLogger) ((requestSingleLocationUpdatelambda1) okHttpCall$1.serializer).write(), new getQueryContext());
        ShortNewsContentCardView shortNewsContentCardView = null;
        MutableStateFlow mutableStateFlow = StateFlowKt.read(null);
        this.write = mutableStateFlow;
        int i = 0;
        Flow flowWrite = FlowKt.write(new PreferencesRepository$observeStringPreference$1(r8lambdah04qyyeozrxd4cfrstnkpb99_ds, settransactionsuccessful.IconCompatParcelizer(R.string.preference_chat_language), shortNewsContentCardView, i));
        this.serializer = flowWrite;
        int i2 = 1;
        SettingsViewModel$special$$inlined$map$1 settingsViewModel$special$$inlined$map$1 = new SettingsViewModel$special$$inlined$map$1(FlowKt.write(new PreferencesRepository$observeStringPreference$1(r8lambdah04qyyeozrxd4cfrstnkpb99_ds, settransactionsuccessful.IconCompatParcelizer(R.string.preference_safety_tracking), shortNewsContentCardView, i2)), i, this);
        MutableStateFlow mutableStateFlow2 = StateFlowKt.read(new r8lambdaNyJ3IxzJGs1Drw4t7O1OG6TKao(new r8lambdaKg12b_kAV6xLHkeltAkZS9jV9c()));
        this.MediaDescriptionCompat = mutableStateFlow2;
        MutableStateFlow mutableStateFlow3 = StateFlowKt.read(new LinkedHashSet());
        this.MediaSessionCompatToken = mutableStateFlow3;
        SettingsViewModel$special$$inlined$map$1 settingsViewModel$special$$inlined$map$2 = new SettingsViewModel$special$$inlined$map$1((Flow[]) onContentCardDismissed.PlaybackStateCompat(SQLite.read(flowWrite, mutableStateFlow2, mutableStateFlow, (StateFlow) c$b.IconCompatParcelizer, settingsViewModel$special$$inlined$map$1, mutableStateFlow3, r8lambdaeen0gug5cgviz6wg1os4ujpkt0.read)).toArray(new Flow[0]), 14, this);
        asComposePaint ascomposepaintIconCompatParcelizer = toBitmapConfig1JJdX4A.IconCompatParcelizer(this);
        SharingStarted sharingStarted = SharingStarted.Companion.read(2);
        r8lambdaCwU8OzatE7jOuIaQjprNUSKXVA r8lambdacwu8ozate7jouiaqjprnuskxva = new r8lambdaCwU8OzatE7jOuIaQjprNUSKXVA("", "", "");
        AnnotatedString.Builder builder2 = new AnnotatedString.Builder(0, 1, null);
        builder2.append("");
        r8lambda4OvXzM2G3U08xdmIsvfVqgmSBTg r8lambda4ovxzm2g3u08xdmisvfvqgmsbtg = new r8lambda4OvXzM2G3U08xdmIsvfVqgmSBTg(builder2.toAnnotatedString(), "", "", false);
        instance_delegatelambda0 instance_delegatelambda0Var = instance_delegatelambda0.write;
        this.r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM = FlowKt.write(settingsViewModel$special$$inlined$map$2, ascomposepaintIconCompatParcelizer, sharingStarted, new r8lambdaFEnLU5alJx2ClfZRg4tE2QEPKfs(instance_delegatelambda0Var, null, instance_delegatelambda0Var, r8lambdacwu8ozate7jouiaqjprnuskxva, null, r8lambda4ovxzm2g3u08xdmisvfvqgmsbtg));
        BuildersKt.RemoteActionCompatParcelizer(toBitmapConfig1JJdX4A.IconCompatParcelizer(this), null, null, new SettingsViewModel$load$1(this, shortNewsContentCardView, i2), 3);
    }
}
