package com.roadrunner.designsystem.compose.theme.tokens;

import androidx.compose.ui.graphics.Fields;
import androidx.compose.ui.unit.Dp;
import bo.app.c8$$ExternalSyntheticOutline0;
import bo.app.d$$ExternalSyntheticOutline0;

/* JADX INFO: loaded from: classes3.dex */
public abstract class Dimensions {
    public static final float ActivityResult;
    public static final float ActivityResultRegistry;
    public static final float AlertControllerButtonHandler;
    public static final float AppCompatActivity;
    public static final float AppCompatDialogFragment;
    public static final float AppCompatViewInflater;
    public static final float BackHandlerKtExternalSyntheticLambda1;
    public static final float BaseMenuWrapper;
    public static final float ComponentActivity;
    public static final float ComponentDialog;
    public static final float ComponentDialogExternalSyntheticLambda0;
    public static final float ComposePredictiveBackHandlerlaunchNewGesture11;
    public static final float EdgeToEdgeExternalSyntheticLambda0;
    public static final float IntentSenderRequest;
    public static final float Keep;
    public static final float MediaBrowserCompatMediaItem;
    public static final float MediaDescriptionCompat;
    public static final float MediaMetadataCompat;
    public static final float MediaSessionCompatQueueItem;
    public static final float MediaSessionCompatResultReceiverWrapper;
    public static final float MediaSessionCompatToken;
    public static final float OnBackPressedCallback;
    public static final float OnBackPressedDispatcherOnBackPressedEventInputExternalSyntheticLambda0;
    public static final float ParcelableVolumeInfo;
    public static final float PlaybackStateCompat;
    public static final float PlaybackStateCompatCustomAction;
    public static final float PredictiveBackHandlerKtPredictiveBackHandlerlambda30inlinedonStopOrDispose1;
    public static final float RatingCompat;
    public static final float ResultReceiver;
    public static final float SystemBarStyleCompanion;
    public static final float WindowCallbackWrapper;
    public static final float _init_lambda1;
    public static final float _init_lambda2;
    public static final float _init_lambda3;
    public static final float _init_lambda4;
    public static final float accessensureViewModelStore;
    public static final float accessgetKeyToRcp;
    public static final float accessgetLaunchedKeysp;
    public static final float addCloseableactivity;
    public static final float addContentView;
    public static final float addMenuProvider;
    public static final float addObserverForBackInvoker;
    public static final float addObserverForBackInvokerlambda0;
    public static final float addOnConfigurationChangedListener;
    public static final float addOnContextAvailableListener;
    public static final float addOnMultiWindowModeChangedListener;
    public static final float addOnNewIntentListener;
    public static final float addOnPictureInPictureModeChangedListener;
    public static final float addOnPictureInPictureUiStateChangedListener;
    public static final float addOnTrimMemoryListener;
    public static final float addOnUserLeaveHintListener;
    public static final float attachBaseContext;
    public static final float closeOptionsMenu;
    public static final float createFullyDrawnExecutor;
    public static final float createNavigationEventHandleractivity;
    public static final float defaultViewModelProviderFactory_delegatelambda0;
    public static final float dispatchKeyEvent;
    public static final float dispatchResult;
    public static final float ensureSubDecor;
    public static final float ensureViewModelStore;
    public static final float enterPictureInPictureMode;
    public static final float findViewById;
    public static final float fullyDrawnReporter_delegatelambda0;
    public static final float fullyDrawnReporter_delegatelambda00;
    public static final float generateLayoutParams;
    public static final float getAccessibilityClassName;
    public static final float getActionBarHideOffset;
    public static final float getActionView;
    public static final float getActivityResultRegistry;
    public static final float getAnimatedVisibility;
    public static final float getContentHeight;
    public static final float getDefaultViewModelCreationExtras;
    public static final float getDefaultViewModelProviderFactory;
    public static final float getDelegate;
    public static final float getDrawerToggleDelegate;
    public static final float getFullyDrawnReporter;
    public static final float getIndexOfFirstFeature;
    public static final float getInflater;
    public static final float getItemData;
    public static final float getLastCustomNonConfigurationInstance;
    public static final float getLifecycle;
    public static final float getLifecycleRegistry1;
    public static final float getMenu;
    public static final float getMenuInflater;
    public static final float getNavigationEventDispatcher;
    public static final float getNestedScrollAxes;
    public static final float getOnBackPressedDispatcher;
    public static final float getOnBackPressedDispatcherannotations;
    public static final float getOnBackPressedInput;
    private static int getOverflowIcon = 0;
    public static final float getResources;
    public static final float getSavedStateRegistry;
    public static final float getSavedStateRegistryControllerannotations;
    public static final float getSubtitle;
    public static final float getSupportActionBar;
    public static final float getSupportParentActivityIntent;
    public static final float getTabContainer;
    public static final float getTitle;
    public static final float getViewModelStore;
    public static final float getWindowAnimations;
    public static final float handleMessage;
    public static final float handleOnBackCancelled;
    public static final float handleOnBackPressed;
    public static final float handleOnBackProgressed;
    public static final float handleOnBackStarted;
    public static final float initDelegate;
    public static final float initialize;
    public static final float initializeViewTreeOwners;
    public static final float invalidateMenu;
    public static final float invalidateOptionsMenu;
    public static final float invoke;
    public static final float invokeSuspend;
    public static final float isEnabled;
    public static final float menuHostHelperlambda0;
    public static final float onActivityResult;
    public static final float onBackPressed;
    public static final float onBackPressedDispatcher_delegatelambda0;
    public static final float onBackPressedDispatcher_delegatelambda00;
    public static final float onBackPressedDispatcher_delegatelambda010;
    public static final float onBackPressedInput_delegatelambda0;
    public static final float onConfigurationChanged;
    public static final float onContentChanged;
    public static final float onCreate;
    public static final float onCreatePanelMenu;
    public static final float onCreateSupportNavigateUpTaskStack;
    public static final float onCreateView;
    public static final float onDestroy;
    public static final float onKeyDown;
    public static final float onLaunch;
    public static final float onLocalesChanged;
    public static final float onMenuItemSelected;
    public static final float onMenuOpened;
    public static final float onMultiWindowModeChanged;
    public static final float onNewIntent;
    public static final float onNightModeChanged;
    public static final float onPanelClosed;
    public static final float onPictureInPictureModeChanged;
    public static final float onPictureInPictureUiStateChanged;
    public static final float onPostCreate;
    public static final float onPostResume;
    public static final float onPreparePanel;
    public static final float onPrepareSupportNavigateUpTaskStack;
    public static final float onRequestPermissionsResult;
    public static final float onRestoreInstanceState;
    public static final float onRetainCustomNonConfigurationInstance;
    public static final float onRetainNonConfigurationInstance;
    public static final float onSaveInstanceState;
    public static final float onStart;
    public static final float onStop;
    public static final float onSupportActionModeFinished;
    public static final float onSupportActionModeStarted;
    public static final float onSupportContentChanged;
    public static final float onSupportNavigateUp;
    public static final float onTitleChanged;
    public static final float onTrimMemory;
    public static final float onUserLeaveHint;
    public static final float onWindowStartingSupportActionMode;
    public static final float openOptionsMenu;
    public static final float peekAvailableContext;
    public static final float performMenuItemShortcut;
    public static final float r8lambda54BeH8ZsBru0CXI2CCSP2syNys;
    public static final float r8lambda7IJBVrN0sHyidCAZufWEJFc7yY;
    public static final float r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus;
    public static final float r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss;
    public static final float r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg;
    public static final float r8lambdaTWvtyPFkiHdx0RbtWVLevVLT0;
    public static final float r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8;
    public static final float r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4;
    public static final float r8lambdaXxpmZzi8FNPM2sJJA30VCt2mBcQ;
    public static final float r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM;
    public static final float r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs;
    public static final float r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28;
    public static final float r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw;
    public static final float r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ;
    public static final float r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0;
    public static final float register;
    public static final float registerForActivityResult;
    public static final float registerKey;
    public static final float remove;
    public static final float removeCloseableactivity;
    public static final float removeMenuProvider;
    public static final float removeOnConfigurationChangedListener;
    public static final float removeOnContextAvailableListener;
    public static final float removeOnMultiWindowModeChangedListener;
    public static final float removeOnNewIntentListener;
    public static final float removeOnPictureInPictureModeChangedListener;
    public static final float removeOnPictureInPictureUiStateChangedListener;
    public static final float removeOnTrimMemoryListener;
    public static final float removeOnUserLeaveHintListener;
    public static final float reportFullyDrawn;
    public static final float run;
    public static final float serializer;
    public static final float setActionBarHideOffset;
    public static final float setActionBarVisibilityCallback;
    public static final float setBackgroundResource;
    public static final float setCheckable;
    public static final float setChecked;
    public static final float setContentHeight;
    public static final float setContentView;
    public static final float setCustomView;
    public static final float setEnabled;
    private static int setExpandedActionViewsExclusive = 1;
    public static final float setExpandedFormat;
    public static final float setForceShowIcon;
    public static final float setGroupDividerEnabled;
    public static final float setHasNonEmbeddedTabs;
    public static final float setHideOnContentScrollEnabled;
    public static final float setIcon;
    public static final float setItemInvoker;
    public static final float setLogo;
    public static final float setMenu;
    public static final float setMenuPrepared;
    public static final float setOverlayMode;
    public static final float setPadding;
    public static final float setPictureInPictureParams;
    public static final float setPopupCallback;
    public static final float setPrimaryBackground;
    public static final float setShowingForActionMode;
    public static final float setSplitBackground;
    public static final float setStackedBackground;
    public static final float setSubMenuArrowVisible;
    public static final float setSubtitle;
    public static final float setSupportActionBar;
    public static final float setSupportProgress;
    public static final float setSupportProgressBarIndeterminate;
    public static final float setSupportProgressBarIndeterminateVisibility;
    public static final float setSupportProgressBarVisibility;
    public static final float setTabContainer;
    public static final float setTheme;
    public static final float setTitle;
    public static final float setTitleOptional;
    public static final float setTransitioning;
    public static final float setUiOptions;
    public static final float setVisibility;
    public static final float setWindowCallback;
    public static final float startActivityForResult;
    public static final float startIntentSenderForResult;
    public static final float startSupportActionMode;
    public static final float supportInvalidateOptionsMenu;
    public static final float supportNavigateUpTo;
    public static final float supportRequestWindowFeature;
    public static final float supportShouldUpRecreateTask;
    public static final float unregisteractivity;
    public static final float read = d$$ExternalSyntheticOutline0.m(2.0f, 24.0f, 0.0f, 1.0f);
    public static final float write = Dp.m3673constructorimpl(2.0f);
    public static final float RemoteActionCompatParcelizer = Dp.m3673constructorimpl(3.0f);
    public static final float IconCompatParcelizer = Dp.m3673constructorimpl(6.0f);

    static {
        Dp.m3673constructorimpl(2.0f);
        serializer = Dp.m3673constructorimpl(2.0f);
        MediaSessionCompatQueueItem = d$$ExternalSyntheticOutline0.m(2.0f, 2.0f, 2.0f, 2.0f);
        MediaBrowserCompatMediaItem = Dp.m3673constructorimpl(2.0f);
        Dp.m3673constructorimpl(2.0f);
        Dp.m3673constructorimpl(3.0f);
        MediaDescriptionCompat = Dp.m3673constructorimpl(3.0f);
        MediaMetadataCompat = Dp.m3673constructorimpl(6.0f);
        RatingCompat = Dp.m3673constructorimpl(3.0f);
        MediaSessionCompatResultReceiverWrapper = d$$ExternalSyntheticOutline0.m(1.0f, 0.0f, 2.0f, 2.0f);
        PlaybackStateCompat = Dp.m3673constructorimpl(1.0f);
        c8$$ExternalSyntheticOutline0.m(3.0f, 3.0f, 3.0f, 2.0f, 3.0f);
        Dp.m3673constructorimpl(3.0f);
        Dp.m3673constructorimpl(3.0f);
        Dp.m3673constructorimpl(2.0f);
        Dp.m3673constructorimpl(2.0f);
        ParcelableVolumeInfo = Dp.m3673constructorimpl(2.0f);
        Dp.m3673constructorimpl(2.0f);
        PlaybackStateCompatCustomAction = Dp.m3673constructorimpl(2.0f);
        MediaSessionCompatToken = Dp.m3673constructorimpl(2.0f);
        r8lambda7aWCLmlNPTirEoC8eOYg0rEvmus = Dp.m3673constructorimpl(2.0f);
        ResultReceiver = Dp.m3673constructorimpl(2.0f);
        r8lambda7IJBVrN0sHyidCAZufWEJFc7yY = Dp.m3673constructorimpl(2.0f);
        ComponentActivity = Dp.m3673constructorimpl(2.0f);
        r8lambda54BeH8ZsBru0CXI2CCSP2syNys = Dp.m3673constructorimpl(2.0f);
        r8lambdacI7dwLT0wnPzJ9a3oRpjgUF1USM = Dp.m3673constructorimpl(2.0f);
        c8$$ExternalSyntheticOutline0.m(2.0f, 2.0f, 2.0f, 8.0f, 12.0f);
        Dp.m3673constructorimpl(12.0f);
        r8lambdaXCwb6u5X87zpWrZW4Zmu6tsKQC8 = Dp.m3673constructorimpl(24.0f);
        Dp.m3673constructorimpl(28.0f);
        Dp.m3673constructorimpl(12.0f);
        r8lambdaXj9c8VIP9DfEvaTmZt0ejAuC4a4 = Dp.m3673constructorimpl(12.0f);
        c8$$ExternalSyntheticOutline0.m(24.0f, 24.0f, 24.0f, 24.0f, 24.0f);
        Dp.m3673constructorimpl(24.0f);
        r8lambdaG6Thfp3wAqF9QgDIJrKyBT1uzss = Dp.m3673constructorimpl(28.0f);
        r8lambdaQUUwrpYSdd6n6dD7wrAaa0S4oXg = Dp.m3673constructorimpl(28.0f);
        r8lambdavCwjfXDiSGcirCy4I008VOiJ_lw = Dp.m3673constructorimpl(28.0f);
        Dp.m3673constructorimpl(28.0f);
        r8lambdawJ5MHcSJed_CjC7r4OWD0UxyJsQ = Dp.m3673constructorimpl(24.0f);
        Dp.m3673constructorimpl(24.0f);
        Dp.m3673constructorimpl(28.0f);
        r8lambdag6d1IyBXWIL5aeSAzXsZMVuYCQs = Dp.m3673constructorimpl(28.0f);
        r8lambdayPQlaAoRiYRJ3IY_TqzUUTrVH0 = Dp.m3673constructorimpl(24.0f);
        r8lambdah6vvr6zUWA2U1fE0KsKpOgpr28 = Dp.m3673constructorimpl(32.0f);
        Dp.m3673constructorimpl(28.0f);
        Dp.m3673constructorimpl(8.0f);
        accessensureViewModelStore = Dp.m3673constructorimpl(24.0f);
        _init_lambda2 = Dp.m3673constructorimpl(20.0f);
        _init_lambda3 = Dp.m3673constructorimpl(8.0f);
        Dp.m3673constructorimpl(8.0f);
        Dp.m3673constructorimpl(32.0f);
        _init_lambda4 = Dp.m3673constructorimpl(8.0f);
        _init_lambda1 = d$$ExternalSyntheticOutline0.m(12.0f, 24.0f, 12.0f, 12.0f);
        defaultViewModelProviderFactory_delegatelambda0 = Dp.m3673constructorimpl(24.0f);
        addObserverForBackInvokerlambda0 = Dp.m3673constructorimpl(20.0f);
        Dp.m3673constructorimpl(24.0f);
        addObserverForBackInvoker = Dp.m3673constructorimpl(12.0f);
        createFullyDrawnExecutor = Dp.m3673constructorimpl(8.0f);
        ensureViewModelStore = Dp.m3673constructorimpl(8.0f);
        fullyDrawnReporter_delegatelambda0 = d$$ExternalSyntheticOutline0.m(12.0f, 8.0f, 8.0f, 12.0f);
        Dp.m3673constructorimpl(12.0f);
        getOnBackPressedInput = Dp.m3673constructorimpl(8.0f);
        c8$$ExternalSyntheticOutline0.m(12.0f, 12.0f, 8.0f, 24.0f, 24.0f);
        Dp.m3673constructorimpl(24.0f);
        Dp.m3673constructorimpl(24.0f);
        getSavedStateRegistryControllerannotations = Dp.m3673constructorimpl(24.0f);
        c8$$ExternalSyntheticOutline0.m(24.0f, 24.0f, 24.0f, 24.0f, 24.0f);
        c8$$ExternalSyntheticOutline0.m(24.0f, 24.0f, 24.0f, 24.0f, 24.0f);
        c8$$ExternalSyntheticOutline0.m(24.0f, 12.0f, 24.0f, 12.0f, 50.0f);
        c8$$ExternalSyntheticOutline0.m(47.0f, 5.0f, 8.0f, 12.0f, 12.0f);
        Dp.m3673constructorimpl(12.0f);
        Dp.m3673constructorimpl(8.0f);
        fullyDrawnReporter_delegatelambda00 = Dp.m3673constructorimpl(20.0f);
        menuHostHelperlambda0 = Dp.m3673constructorimpl(12.0f);
        onBackPressedInput_delegatelambda0 = Dp.m3673constructorimpl(8.0f);
        onBackPressedDispatcher_delegatelambda0 = d$$ExternalSyntheticOutline0.m(8.0f, 8.0f, 8.0f, 8.0f);
        Dp.m3673constructorimpl(8.0f);
        onBackPressedDispatcher_delegatelambda00 = Dp.m3673constructorimpl(8.0f);
        addContentView = Dp.m3673constructorimpl(8.0f);
        onBackPressedDispatcher_delegatelambda010 = Dp.m3673constructorimpl(8.0f);
        addOnMultiWindowModeChangedListener = Dp.m3673constructorimpl(8.0f);
        addMenuProvider = Dp.m3673constructorimpl(8.0f);
        addOnConfigurationChangedListener = Dp.m3673constructorimpl(8.0f);
        addOnContextAvailableListener = Dp.m3673constructorimpl(8.0f);
        addOnNewIntentListener = Dp.m3673constructorimpl(8.0f);
        Dp.m3673constructorimpl(24.0f);
        enterPictureInPictureMode = Dp.m3673constructorimpl(12.0f);
        addOnPictureInPictureUiStateChangedListener = Dp.m3673constructorimpl(72.0f);
        addOnTrimMemoryListener = Dp.m3673constructorimpl(100.0f);
        c8$$ExternalSyntheticOutline0.m(16.0f, 16.0f, 16.0f, 16.0f, 24.0f);
        addOnPictureInPictureModeChangedListener = d$$ExternalSyntheticOutline0.m(16.0f, 16.0f, 28.0f, 28.0f);
        c8$$ExternalSyntheticOutline0.m(44.0f, 60.0f, 60.0f, 60.0f, 36.0f);
        addOnUserLeaveHintListener = d$$ExternalSyntheticOutline0.m(36.0f, 24.0f, 48.0f, 56.0f);
        getFullyDrawnReporter = Dp.m3673constructorimpl(56.0f);
        c8$$ExternalSyntheticOutline0.m(48.0f, 36.0f, 24.0f, 36.0f, 36.0f);
        Dp.m3673constructorimpl(20.0f);
        Dp.m3673constructorimpl(36.0f);
        getLastCustomNonConfigurationInstance = Dp.m3673constructorimpl(36.0f);
        getDefaultViewModelProviderFactory = Dp.m3673constructorimpl(36.0f);
        getDefaultViewModelCreationExtras = Dp.m3673constructorimpl(36.0f);
        getActivityResultRegistry = Dp.m3673constructorimpl(36.0f);
        getViewModelStore = Dp.m3673constructorimpl(56.0f);
        getSavedStateRegistry = Dp.m3673constructorimpl(56.0f);
        Dp.m3673constructorimpl(56.0f);
        getOnBackPressedDispatcher = Dp.m3673constructorimpl(48.0f);
        Dp.m3673constructorimpl(48.0f);
        getNavigationEventDispatcher = Dp.m3673constructorimpl(56.0f);
        getLifecycle = Dp.m3673constructorimpl(48.0f);
        initializeViewTreeOwners = Dp.m3673constructorimpl(24.0f);
        onActivityResult = Dp.m3673constructorimpl(60.0f);
        onConfigurationChanged = Dp.m3673constructorimpl(52.0f);
        invalidateMenu = Dp.m3673constructorimpl(60.0f);
        Dp.m3673constructorimpl(44.0f);
        onBackPressed = Dp.m3673constructorimpl(40.0f);
        onMenuItemSelected = d$$ExternalSyntheticOutline0.m(40.0f, 40.0f, 8.0f, 72.0f);
        onCreate = Dp.m3673constructorimpl(72.0f);
        onNewIntent = Dp.m3673constructorimpl(40.0f);
        Dp.m3673constructorimpl(16.0f);
        Dp.m3673constructorimpl(16.0f);
        Dp.m3673constructorimpl(100.0f);
        Dp.m3673constructorimpl(342.0f);
        onCreatePanelMenu = Dp.m3673constructorimpl(35.0f);
        onMultiWindowModeChanged = d$$ExternalSyntheticOutline0.m(24.0f, 2.0f, 3.0f, 1.0f);
        onPictureInPictureModeChanged = d$$ExternalSyntheticOutline0.m(2.0f, 3.0f, 1.0f, 2.0f);
        Dp.m3673constructorimpl(3.0f);
        onRequestPermissionsResult = Dp.m3673constructorimpl(1.0f);
        onPictureInPictureUiStateChanged = Dp.m3673constructorimpl(66.0f);
        c8$$ExternalSyntheticOutline0.m(32.0f, 24.0f, 24.0f, 32.0f, 78.0f);
        onPreparePanel = Dp.m3673constructorimpl(24.0f);
        onPanelClosed = d$$ExternalSyntheticOutline0.m(24.0f, 48.0f, 48.0f, 24.0f);
        Dp.m3673constructorimpl(12.0f);
        Dp.m3673constructorimpl(12.0f);
        Dp.m3673constructorimpl(24.0f);
        Dp.m3673constructorimpl(30.0f);
        onUserLeaveHint = Dp.m3673constructorimpl(24.0f);
        c8$$ExternalSyntheticOutline0.m(24.0f, 52.0f, 120.0f, 60.0f, 32.0f);
        onRetainCustomNonConfigurationInstance = Dp.m3673constructorimpl(64.0f);
        onSaveInstanceState = Dp.m3673constructorimpl(16.0f);
        Dp.m3673constructorimpl(300.0f);
        Dp.m3673constructorimpl(300.0f);
        onTrimMemory = Dp.m3673constructorimpl(160.0f);
        onRetainNonConfigurationInstance = Dp.m3673constructorimpl(160.0f);
        removeOnConfigurationChangedListener = Dp.m3673constructorimpl(100.0f);
        peekAvailableContext = Dp.m3673constructorimpl(100.0f);
        registerForActivityResult = Dp.m3673constructorimpl(60.0f);
        removeMenuProvider = Dp.m3673constructorimpl(24.0f);
        removeOnContextAvailableListener = Dp.m3673constructorimpl(24.0f);
        removeOnPictureInPictureModeChangedListener = d$$ExternalSyntheticOutline0.m(56.0f, 56.0f, 56.0f, 56.0f);
        Dp.m3673constructorimpl(56.0f);
        Dp.m3673constructorimpl(56.0f);
        Dp.m3673constructorimpl(16.0f);
        Dp.m3673constructorimpl(16.0f);
        removeOnMultiWindowModeChangedListener = Dp.m3673constructorimpl(40.0f);
        c8$$ExternalSyntheticOutline0.m(24.0f, 24.0f, 24.0f, 24.0f, 40.0f);
        removeOnNewIntentListener = Dp.m3673constructorimpl(24.0f);
        removeOnPictureInPictureUiStateChangedListener = Dp.m3673constructorimpl(24.0f);
        c8$$ExternalSyntheticOutline0.m(24.0f, 24.0f, 20.0f, 24.0f, 24.0f);
        removeOnTrimMemoryListener = Dp.m3673constructorimpl(24.0f);
        reportFullyDrawn = Dp.m3673constructorimpl(24.0f);
        Dp.m3673constructorimpl(20.0f);
        removeOnUserLeaveHintListener = Dp.m3673constructorimpl(24.0f);
        setPictureInPictureParams = Dp.m3673constructorimpl(24.0f);
        setContentView = Dp.m3673constructorimpl(24.0f);
        c8$$ExternalSyntheticOutline0.m(24.0f, 140.0f, 70.0f, 24.0f, 24.0f);
        Dp.m3673constructorimpl(24.0f);
        Dp.m3673constructorimpl(3.0f);
        Dp.m3673constructorimpl(48.0f);
        Dp.m3673constructorimpl(48.0f);
        startActivityForResult = Dp.m3673constructorimpl(60.0f);
        getOnBackPressedDispatcherannotations = Dp.m3673constructorimpl(189.0f);
        startIntentSenderForResult = Dp.m3673constructorimpl(24.0f);
        r8lambdaXxpmZzi8FNPM2sJJA30VCt2mBcQ = Dp.m3673constructorimpl(120.0f);
        ComponentDialog = Dp.m3673constructorimpl(16.0f);
        getLifecycleRegistry1 = Dp.m3673constructorimpl(60.0f);
        c8$$ExternalSyntheticOutline0.m(60.0f, 189.0f, 24.0f, 120.0f, 16.0f);
        Dp.m3673constructorimpl(60.0f);
        onStart = Dp.m3673constructorimpl(84.0f);
        ComponentDialogExternalSyntheticLambda0 = Dp.m3673constructorimpl(84.0f);
        Dp.m3673constructorimpl(42.0f);
        Dp.m3673constructorimpl(42.0f);
        onStop = Dp.m3673constructorimpl(16.0f);
        invoke = Dp.m3673constructorimpl(16.0f);
        Dp.m3673constructorimpl(84.0f);
        EdgeToEdgeExternalSyntheticLambda0 = Dp.m3673constructorimpl(84.0f);
        Dp.m3673constructorimpl(42.0f);
        Dp.m3673constructorimpl(42.0f);
        Dp.m3673constructorimpl(16.0f);
        Dp.m3673constructorimpl(16.0f);
        run = Dp.m3673constructorimpl(36.0f);
        handleOnBackCancelled = Dp.m3673constructorimpl(36.0f);
        c8$$ExternalSyntheticOutline0.m(4.0f, 72.0f, 72.0f, 16.0f, 200.0f);
        addCloseableactivity = Dp.m3673constructorimpl(100.0f);
        OnBackPressedCallback = Dp.m3673constructorimpl(100.0f);
        Dp.m3673constructorimpl(94.0f);
        Dp.m3673constructorimpl(94.0f);
        createNavigationEventHandleractivity = Dp.m3673constructorimpl(112.0f);
        handleOnBackPressed = Dp.m3673constructorimpl(10.0f);
        handleOnBackProgressed = Dp.m3673constructorimpl(112.0f);
        Dp.m3673constructorimpl(100.0f);
        Dp.m3673constructorimpl(218.0f);
        remove = Dp.m3673constructorimpl(5.0f);
        isEnabled = Dp.m3673constructorimpl(64.0f);
        handleOnBackStarted = Dp.m3673constructorimpl(7.0f);
        OnBackPressedDispatcherOnBackPressedEventInputExternalSyntheticLambda0 = Dp.m3673constructorimpl(64.0f);
        removeCloseableactivity = Dp.m3673constructorimpl(4.0f);
        setEnabled = Dp.m3673constructorimpl(36.0f);
        getIndexOfFirstFeature = Dp.m3673constructorimpl(6.0f);
        SystemBarStyleCompanion = Dp.m3673constructorimpl(36.0f);
        c8$$ExternalSyntheticOutline0.m(48.0f, 24.0f, 24.0f, 4.0f, 4.0f);
        c8$$ExternalSyntheticOutline0.m(12.0f, 12.0f, 24.0f, 8.0f, 48.0f);
        Dp.m3673constructorimpl(78.0f);
        Dp.m3673constructorimpl(32.0f);
        Dp.m3673constructorimpl(32.0f);
        Dp.m3673constructorimpl(28.0f);
        invokeSuspend = Dp.m3673constructorimpl(30.0f);
        Dp.m3673constructorimpl(145.0f);
        BackHandlerKtExternalSyntheticLambda1 = Dp.m3673constructorimpl(48.0f);
        c8$$ExternalSyntheticOutline0.m(40.0f, 0.0f, 0.0f, 0.0f, 0.0f);
        Dp.m3673constructorimpl(8.0f);
        Dp.m3673constructorimpl(0.0f);
        Dp.m3673constructorimpl(0.0f);
        Dp.m3673constructorimpl(8.0f);
        ComposePredictiveBackHandlerlaunchNewGesture11 = Dp.m3673constructorimpl(16.0f);
        ActivityResult = Dp.m3673constructorimpl(16.0f);
        PredictiveBackHandlerKtPredictiveBackHandlerlambda30inlinedonStopOrDispose1 = Dp.m3673constructorimpl(16.0f);
        accessgetKeyToRcp = Dp.m3673constructorimpl(16.0f);
        c8$$ExternalSyntheticOutline0.m(16.0f, 16.0f, 16.0f, 16.0f, 12.0f);
        c8$$ExternalSyntheticOutline0.m(12.0f, 12.0f, 12.0f, 12.0f, 12.0f);
        c8$$ExternalSyntheticOutline0.m(12.0f, 12.0f, 12.0f, 12.0f, 12.0f);
        c8$$ExternalSyntheticOutline0.m(12.0f, 12.0f, 12.0f, 12.0f, 12.0f);
        c8$$ExternalSyntheticOutline0.m(12.0f, 12.0f, 12.0f, 12.0f, 6.0f);
        r8lambdaTWvtyPFkiHdx0RbtWVLevVLT0 = d$$ExternalSyntheticOutline0.m(6.0f, 6.0f, 6.0f, 16.0f);
        accessgetLaunchedKeysp = Dp.m3673constructorimpl(24.0f);
        dispatchResult = Dp.m3673constructorimpl(24.0f);
        ActivityResultRegistry = Dp.m3673constructorimpl(16.0f);
        registerKey = Dp.m3673constructorimpl(16.0f);
        register = Dp.m3673constructorimpl(24.0f);
        onLaunch = Dp.m3673constructorimpl(24.0f);
        unregisteractivity = Dp.m3673constructorimpl(16.0f);
        c8$$ExternalSyntheticOutline0.m(16.0f, 24.0f, 24.0f, 16.0f, 12.0f);
        onRestoreInstanceState = d$$ExternalSyntheticOutline0.m(16.0f, 16.0f, 12.0f, 12.0f);
        IntentSenderRequest = Dp.m3673constructorimpl(16.0f);
        handleMessage = Dp.m3673constructorimpl(16.0f);
        AppCompatActivity = Dp.m3673constructorimpl(12.0f);
        Dp.m3673constructorimpl(12.0f);
        Dp.m3673constructorimpl(16.0f);
        Dp.m3673constructorimpl(16.0f);
        Dp.m3673constructorimpl(12.0f);
        Keep = Dp.m3673constructorimpl(16.0f);
        AlertControllerButtonHandler = Dp.m3673constructorimpl(24.0f);
        closeOptionsMenu = Dp.m3673constructorimpl(24.0f);
        initDelegate = Dp.m3673constructorimpl(16.0f);
        performMenuItemShortcut = Dp.m3673constructorimpl(12.0f);
        attachBaseContext = Dp.m3673constructorimpl(16.0f);
        dispatchKeyEvent = Dp.m3673constructorimpl(16.0f);
        getDrawerToggleDelegate = Dp.m3673constructorimpl(12.0f);
        c8$$ExternalSyntheticOutline0.m(8.0f, 0.0f, 0.0f, 8.0f, 8.0f);
        c8$$ExternalSyntheticOutline0.m(0.0f, 0.0f, 8.0f, 8.0f, 0.0f);
        c8$$ExternalSyntheticOutline0.m(0.0f, 8.0f, 16.0f, 24.0f, 24.0f);
        c8$$ExternalSyntheticOutline0.m(16.0f, 8.0f, 12.0f, 8.0f, 0.0f);
        getResources = d$$ExternalSyntheticOutline0.m(0.0f, 0.0f, 0.0f, 4.0f);
        getDelegate = Dp.m3673constructorimpl(12.0f);
        Dp.m3673constructorimpl(8.0f);
        getMenuInflater = Dp.m3673constructorimpl(12.0f);
        findViewById = Dp.m3673constructorimpl(4.0f);
        invalidateOptionsMenu = Dp.m3673constructorimpl(12.0f);
        c8$$ExternalSyntheticOutline0.m(12.0f, 0.0f, 0.0f, 12.0f, 20.0f);
        getSupportParentActivityIntent = d$$ExternalSyntheticOutline0.m(20.0f, 20.0f, 20.0f, 8.0f);
        onCreateSupportNavigateUpTaskStack = Dp.m3673constructorimpl(16.0f);
        onContentChanged = Dp.m3673constructorimpl(16.0f);
        getSupportActionBar = Dp.m3673constructorimpl(8.0f);
        onMenuOpened = Dp.m3673constructorimpl(4.0f);
        c8$$ExternalSyntheticOutline0.m(12.0f, 24.0f, 24.0f, 12.0f, 4.0f);
        c8$$ExternalSyntheticOutline0.m(24.0f, 24.0f, 8.0f, 4.0f, 24.0f);
        onDestroy = d$$ExternalSyntheticOutline0.m(24.0f, 8.0f, 12.0f, 24.0f);
        c8$$ExternalSyntheticOutline0.m(24.0f, 12.0f, 20.0f, 20.0f, 20.0f);
        c8$$ExternalSyntheticOutline0.m(20.0f, 20.0f, 20.0f, 20.0f, 20.0f);
        c8$$ExternalSyntheticOutline0.m(20.0f, 20.0f, 20.0f, 20.0f, 20.0f);
        onKeyDown = d$$ExternalSyntheticOutline0.m(20.0f, 20.0f, 20.0f, 20.0f);
        onLocalesChanged = Dp.m3673constructorimpl(20.0f);
        onNightModeChanged = Dp.m3673constructorimpl(20.0f);
        onPostCreate = Dp.m3673constructorimpl(20.0f);
        c8$$ExternalSyntheticOutline0.m(20.0f, 20.0f, 20.0f, 20.0f, 20.0f);
        c8$$ExternalSyntheticOutline0.m(20.0f, 20.0f, 20.0f, 20.0f, 20.0f);
        c8$$ExternalSyntheticOutline0.m(20.0f, 20.0f, 16.0f, 16.0f, 16.0f);
        c8$$ExternalSyntheticOutline0.m(16.0f, 16.0f, 16.0f, 16.0f, 16.0f);
        c8$$ExternalSyntheticOutline0.m(16.0f, 16.0f, 16.0f, 16.0f, 16.0f);
        onSupportActionModeStarted = d$$ExternalSyntheticOutline0.m(16.0f, 16.0f, 16.0f, 16.0f);
        onSupportActionModeFinished = Dp.m3673constructorimpl(16.0f);
        onPostResume = Dp.m3673constructorimpl(16.0f);
        onPrepareSupportNavigateUpTaskStack = Dp.m3673constructorimpl(16.0f);
        c8$$ExternalSyntheticOutline0.m(16.0f, 16.0f, 16.0f, 16.0f, 16.0f);
        c8$$ExternalSyntheticOutline0.m(16.0f, 16.0f, 16.0f, 16.0f, 16.0f);
        c8$$ExternalSyntheticOutline0.m(16.0f, 16.0f, 24.0f, 20.0f, 20.0f);
        c8$$ExternalSyntheticOutline0.m(24.0f, 8.0f, 16.0f, 16.0f, 8.0f);
        c8$$ExternalSyntheticOutline0.m(12.0f, 24.0f, 24.0f, 8.0f, 20.0f);
        openOptionsMenu = d$$ExternalSyntheticOutline0.m(20.0f, 20.0f, 20.0f, 24.0f);
        Dp.m3673constructorimpl(0.0f);
        Dp.m3673constructorimpl(12.0f);
        Dp.m3673constructorimpl(4.0f);
        Dp.m3673constructorimpl(4.0f);
        onSupportContentChanged = Dp.m3673constructorimpl(8.0f);
        onTitleChanged = Dp.m3673constructorimpl(12.0f);
        onWindowStartingSupportActionMode = Dp.m3673constructorimpl(12.0f);
        c8$$ExternalSyntheticOutline0.m(0.0f, 16.0f, 16.0f, 8.0f, 0.0f);
        onSupportNavigateUp = d$$ExternalSyntheticOutline0.m(0.0f, 12.0f, 0.0f, 8.0f);
        setSupportProgressBarIndeterminate = Dp.m3673constructorimpl(4.0f);
        setSupportProgressBarVisibility = Dp.m3673constructorimpl(12.0f);
        Dp.m3673constructorimpl(4.0f);
        Dp.m3673constructorimpl(12.0f);
        Dp.m3673constructorimpl(12.0f);
        Dp.m3673constructorimpl(4.0f);
        setSupportProgressBarIndeterminateVisibility = Dp.m3673constructorimpl(12.0f);
        setSupportActionBar = Dp.m3673constructorimpl(4.0f);
        Dp.m3673constructorimpl(4.0f);
        setSupportProgress = Dp.m3673constructorimpl(8.0f);
        supportInvalidateOptionsMenu = Dp.m3673constructorimpl(12.0f);
        startSupportActionMode = Dp.m3673constructorimpl(4.0f);
        c8$$ExternalSyntheticOutline0.m(20.0f, 32.0f, 24.0f, 16.0f, 16.0f);
        c8$$ExternalSyntheticOutline0.m(20.0f, 24.0f, 24.0f, 24.0f, 32.0f);
        c8$$ExternalSyntheticOutline0.m(8.0f, 16.0f, 16.0f, 8.0f, 48.0f);
        c8$$ExternalSyntheticOutline0.m(4.0f, 4.0f, 8.0f, 12.0f, 12.0f);
        setTheme = d$$ExternalSyntheticOutline0.m(24.0f, 24.0f, 24.0f, 8.0f);
        c8$$ExternalSyntheticOutline0.m(8.0f, 4.0f, 16.0f, 16.0f, 8.0f);
        Dp.m3673constructorimpl(16.0f);
        supportRequestWindowFeature = Dp.m3673constructorimpl(16.0f);
        c8$$ExternalSyntheticOutline0.m(16.0f, 4.0f, 4.0f, 4.0f, 16.0f);
        c8$$ExternalSyntheticOutline0.m(12.0f, 12.0f, 8.0f, 8.0f, 4.0f);
        c8$$ExternalSyntheticOutline0.m(4.0f, 4.0f, 16.0f, 20.0f, 8.0f);
        supportNavigateUpTo = Dp.m3673constructorimpl(4.0f);
        supportShouldUpRecreateTask = Dp.m3673constructorimpl(12.0f);
        setBackgroundResource = d$$ExternalSyntheticOutline0.m(4.0f, 4.0f, 4.0f, 8.0f);
        Dp.m3673constructorimpl(8.0f);
        Dp.m3673constructorimpl(16.0f);
        onCreateView = Dp.m3673constructorimpl(4.0f);
        AppCompatDialogFragment = Dp.m3673constructorimpl(8.0f);
        Dp.m3673constructorimpl(36.0f);
        ensureSubDecor = Dp.m3673constructorimpl(20.0f);
        Dp.m3673constructorimpl(20.0f);
        Dp.m3673constructorimpl(16.0f);
        getItemData = Dp.m3673constructorimpl(12.0f);
        c8$$ExternalSyntheticOutline0.m(4.0f, 24.0f, 8.0f, 8.0f, 4.0f);
        c8$$ExternalSyntheticOutline0.m(12.0f, 20.0f, 20.0f, 24.0f, 4.0f);
        c8$$ExternalSyntheticOutline0.m(4.0f, 8.0f, 4.0f, 12.0f, 16.0f);
        c8$$ExternalSyntheticOutline0.m(16.0f, 20.0f, 4.0f, 4.0f, 8.0f);
        c8$$ExternalSyntheticOutline0.m(4.0f, 12.0f, 12.0f, 12.0f, 16.0f);
        c8$$ExternalSyntheticOutline0.m(4.0f, 4.0f, 20.0f, 16.0f, 12.0f);
        c8$$ExternalSyntheticOutline0.m(20.0f, 16.0f, 12.0f, 16.0f, 4.0f);
        c8$$ExternalSyntheticOutline0.m(16.0f, 16.0f, 4.0f, 16.0f, 4.0f);
        c8$$ExternalSyntheticOutline0.m(16.0f, 16.0f, 4.0f, 16.0f, 4.0f);
        c8$$ExternalSyntheticOutline0.m(16.0f, 16.0f, 4.0f, 16.0f, 4.0f);
        AppCompatViewInflater = d$$ExternalSyntheticOutline0.m(16.0f, 16.0f, 4.0f, 4.0f);
        WindowCallbackWrapper = Dp.m3673constructorimpl(12.0f);
        getAccessibilityClassName = Dp.m3673constructorimpl(12.0f);
        getMenu = Dp.m3673constructorimpl(8.0f);
        c8$$ExternalSyntheticOutline0.m(4.0f, 4.0f, 16.0f, 16.0f, 4.0f);
        c8$$ExternalSyntheticOutline0.m(16.0f, 8.0f, 8.0f, 16.0f, 24.0f);
        c8$$ExternalSyntheticOutline0.m(16.0f, 12.0f, 4.0f, 24.0f, 8.0f);
        Dp.m3673constructorimpl(8.0f);
        setExpandedFormat = Dp.m3673constructorimpl(12.0f);
        setCheckable = Dp.m3673constructorimpl(8.0f);
        c8$$ExternalSyntheticOutline0.m(12.0f, 8.0f, 8.0f, 8.0f, 12.0f);
        Dp.m3673constructorimpl(4.0f);
        setIcon = Dp.m3673constructorimpl(12.0f);
        Dp.m3673constructorimpl(24.0f);
        Dp.m3673constructorimpl(8.0f);
        Dp.m3673constructorimpl(16.0f);
        Dp.m3673constructorimpl(16.0f);
        setItemInvoker = Dp.m3673constructorimpl(8.0f);
        setChecked = Dp.m3673constructorimpl(8.0f);
        setPadding = Dp.m3673constructorimpl(12.0f);
        BaseMenuWrapper = Dp.m3673constructorimpl(12.0f);
        setTitle = Dp.m3673constructorimpl(20.0f);
        setPopupCallback = Dp.m3673constructorimpl(24.0f);
        getWindowAnimations = Dp.m3673constructorimpl(24.0f);
        Dp.m3673constructorimpl(24.0f);
        getInflater = Dp.m3673constructorimpl(28.0f);
        initialize = Dp.m3673constructorimpl(32.0f);
        Dp.m3673constructorimpl(47.0f);
        Dp.m3673constructorimpl(50.0f);
        setSubMenuArrowVisible = Dp.m3673constructorimpl(2.0f);
        setForceShowIcon = Dp.m3673constructorimpl(4.0f);
        setGroupDividerEnabled = Dp.m3673constructorimpl(6.0f);
        getTabContainer = Dp.m3673constructorimpl(8.0f);
        getActionView = Dp.m3673constructorimpl(0.0f);
        setPrimaryBackground = Dp.m3673constructorimpl(4.0f);
        setSplitBackground = Dp.m3673constructorimpl(8.0f);
        setStackedBackground = Dp.m3673constructorimpl(12.0f);
        setTabContainer = Dp.m3673constructorimpl(16.0f);
        setTransitioning = Dp.m3673constructorimpl(20.0f);
        getAnimatedVisibility = Dp.m3673constructorimpl(24.0f);
        getContentHeight = Dp.m3673constructorimpl(28.0f);
        setVisibility = Dp.m3673constructorimpl(32.0f);
        setSubtitle = Dp.m3673constructorimpl(36.0f);
        getTitle = Dp.m3673constructorimpl(40.0f);
        setContentHeight = Dp.m3673constructorimpl(44.0f);
        setCustomView = Dp.m3673constructorimpl(48.0f);
        getSubtitle = Dp.m3673constructorimpl(52.0f);
        setActionBarHideOffset = Dp.m3673constructorimpl(56.0f);
        setTitleOptional = Dp.m3673constructorimpl(60.0f);
        generateLayoutParams = Dp.m3673constructorimpl(0.0f);
        getActionBarHideOffset = Dp.m3673constructorimpl(4.0f);
        getNestedScrollAxes = Dp.m3673constructorimpl(8.0f);
        setMenu = Dp.m3673constructorimpl(12.0f);
        setActionBarVisibilityCallback = Dp.m3673constructorimpl(16.0f);
        setHideOnContentScrollEnabled = Dp.m3673constructorimpl(20.0f);
        setLogo = Dp.m3673constructorimpl(24.0f);
        setHasNonEmbeddedTabs = Dp.m3673constructorimpl(28.0f);
        setShowingForActionMode = Dp.m3673constructorimpl(32.0f);
        setMenuPrepared = Dp.m3673constructorimpl(36.0f);
        setWindowCallback = Dp.m3673constructorimpl(40.0f);
        setOverlayMode = Dp.m3673constructorimpl(44.0f);
        setUiOptions = Dp.m3673constructorimpl(48.0f);
        int i = setExpandedActionViewsExclusive + 73;
        getOverflowIcon = i % Fields.SpotShadowColor;
        int i2 = i % 2;
    }
}
